"""Hand-authored remediation status for the 85 checklist items (4.3.0).

Statuses:
  IMPLEMENTED_UNREVIEWED  code/spec + passing tests in this package; still not "done"
                          under the checklist's completion rule because no owner,
                          approver or release-bound independent review exists.
  PARTIAL                 some of the item is real and tested; the named remainder is not.
  BLOCKED                 needs an input that was not supplied (named in `blockers`).
No item is DONE.  Every row lists what it rests on so a reviewer can check it.
"""
OWNER = "no accountable owner/approver assigned (C009)"
PKCORE = "pk_core not available/pinned (A01)"
DAND = "Dandelion not resolved/pinned (A03)"
ADJ = "real PLN-04/INV-26/PLN-05/GAP-09 layers not supplied (A06)"
HW = "no fleet/edge hardware or real deployment to measure"
KMS = "no KMS/IdP supplied"

T = "tests/test_remediation.py::"
ITEMS = [
 ("A01", "pk_core framework", "PARTIAL", ["pkcompat.py", "__init__.py", T+"PkCoreCompatTest"],
  [PKCORE], "import no longer fails without pk_core; absence/incompatibility is a coded error; pin left unset"),
 ("A02", "MASTER.md source artifact", "BLOCKED", ["SOURCE_PROVENANCE.md", "evidence/source_hashes.json",
  T+"RepositoryIntegrityTest"], ["authoritative MASTER.md not supplied"], "absence recorded; not reconstructed"),
 ("A03", "Dandelion pin", "BLOCKED", ["docs/ADR-001-function-execution.md"], [DAND], ""),
 ("A04", "reproducible package manifest", "IMPLEMENTED_UNREVIEWED", ["pyproject.toml", "evidence/ci_run.json"],
  [OWNER], "clean-venv install + test verified in CI script; pk_core extra empty pending A01"),
 ("A05", "production conformance/evidence outputs", "PARTIAL", ["tools/make_evidence.py", "evidence/"],
  [PKCORE, OWNER], "local hash-chained evidence produced; pk_core gate cannot run; no release approver"),
 ("A06", "adjacent-layer adapters/tests", "PARTIAL", ["adapters.py", T+"AdjacentContractTest"], [ADJ],
  "Protocols + reference doubles; no real interop"),
 ("A07", "CI/release automation", "PARTIAL", ["ci.sh", ".github/workflows/ci.yml"], [OWNER],
  "CI runs tests (normal+-O), compile, schemas, bench report, evidence; release gate is NO_GO by design"),
 ("A08", "license/notice metadata", "BLOCKED", ["OWNERSHIP.md"], ["licence choice is the owner's decision"], ""),
 ("A09", "ownership/support metadata", "BLOCKED", ["OWNERSHIP.md"], [OWNER], "template only, UNASSIGNED"),
 ("A10", "performance/fault/security harnesses", "PARTIAL", ["tools/bench.py", T+"FuzzAndPropertyTest",
  T+"ConcurrencyStressTest", T+"DependencyTest"], [HW], "in-process bench/fuzz/stress/fault; no soak/fleet"),
 ("INV-31-C005", "assumptions", "IMPLEMENTED_UNREVIEWED", ["docs/REQUIREMENTS.md#assumptions-c005"], [OWNER], ""),
 ("INV-31-C009", "owner and escalation", "BLOCKED", ["OWNERSHIP.md"], [OWNER], ""),
 ("INV-31-C010", "approved ADR", "BLOCKED", ["docs/ADR-001-function-execution.md"], [OWNER, DAND], "ADR PROPOSED"),
 ("INV-31-C011", "SHALL-level requirements", "PARTIAL", ["docs/REQUIREMENTS.md"], [DAND],
  "reuse/boundary SHALLs mapped to tests; DAG semantics not written (would be invented)"),
 ("INV-31-C012", "functional reqs per context", "PARTIAL", ["docs/REQUIREMENTS.md", "config/*.example.json"], [HW],
  "four context configs, unapproved sizing"),
 ("INV-31-C013", "NFRs", "PARTIAL", ["docs/REQUIREMENTS.md", "docs/SLOS.md"], [OWNER], "thresholds PROPOSED"),
 ("INV-31-C016", "versioning/back-compat", "IMPLEMENTED_UNREVIEWED", ["docs/COMPATIBILITY_MATRIX.md",
  "schemas/PK_INVOKE_REQUEST_1.schema.json", T+"VersioningTest"], [OWNER], ""),
 ("INV-31-C017", "quotas/fairness", "IMPLEMENTED_UNREVIEWED", ["boundary.py::Gateway._admit_quota",
  T+"QuotaFairnessTest"], [OWNER], "per-tenant instance quota + max share of pool"),
 ("INV-31-C018", "network absent/intermittent", "IMPLEMENTED_UNREVIEWED", ["docs/REQUIREMENTS.md",
  T+"DependencyTest"], [OWNER], ""),
 ("INV-31-C019", "precedence rules", "IMPLEMENTED_UNREVIEWED", ["docs/REQUIREMENTS.md"], [OWNER],
  "documented; residency not modelled by INV-31"),
 ("INV-31-C023", "authentication", "IMPLEMENTED_UNREVIEWED", ["boundary.py::HmacAuthenticator",
  T+"AuthenticationTest"], [KMS, OWNER], "keys injected; no IdP integration"),
 ("INV-31-C024", "authorization/capabilities", "IMPLEMENTED_UNREVIEWED", ["boundary.py", T+"AuthorizationTest"],
  [OWNER], ""),
 ("INV-31-C025", "timeout/cancel/retry/idempotency/backpressure", "IMPLEMENTED_UNREVIEWED",
  ["boundary.py", T+"ControlSemanticsTest"], [OWNER],
  "deadline+cancel at admission; work already admitted is not pre-empted (synchronous model)"),
 ("INV-31-C026", "structured failure codes", "IMPLEMENTED_UNREVIEWED", ["errors.py",
  "schemas/PK_INV31_ERROR_1.schema.json", T+"ErrorsTest"], [OWNER], ""),
 ("INV-31-C027", "peer version compatibility", "IMPLEMENTED_UNREVIEWED", [T+"VersioningTest",
  "docs/COMPATIBILITY_MATRIX.md"], [OWNER], "single supported version; refusal behaviour tested"),
 ("INV-31-C029", "examples + conformance fixtures", "PARTIAL", ["fixtures/", "config/"], [OWNER],
  "fixture corpus added for request/error/config; not independently reviewed"),
 ("INV-31-C030", "integration tests with adjacent layers", "PARTIAL", [T+"AdjacentContractTest"], [ADJ], "doubles only"),
 ("INV-31-C031", "pin Dandelion", "BLOCKED", [], [DAND], ""),
 ("INV-31-C033", "declarative config + secure defaults", "IMPLEMENTED_UNREVIEWED", ["config.py",
  "schemas/PK_INV31_CONFIG_1.schema.json", T+"ConfigTest"], [OWNER], "unsigned documents; signing needs KMS"),
 ("INV-31-C036", "config provenance", "IMPLEMENTED_UNREVIEWED", ["config.py::ConfigManager.apply",
  T+"ConfigTest::test_apply_records_provenance"], [OWNER], ""),
 ("INV-31-C037", "atomic config updates", "IMPLEMENTED_UNREVIEWED", ["config.py", T+"ConfigTest"], [OWNER],
  "whole-generation swap under the gateway lock"),
 ("INV-31-C038", "automatic + operator rollback", "IMPLEMENTED_UNREVIEWED", ["config.py", T+"ConfigTest"], [OWNER], ""),
 ("INV-31-C040", "deterministic bootstrap", "PARTIAL", ["docs/RUNBOOKS.md", "ci.sh"], [ADJ],
  "package bootstrap verified in clean venv; node/environment bootstrap belongs to parent platform"),
 ("INV-31-C041", "threat model", "IMPLEMENTED_UNREVIEWED", ["docs/THREAT_MODEL.md"], [OWNER],
  "needs independent security review"),
 ("INV-31-C042", "least privilege", "IMPLEMENTED_UNREVIEWED", ["boundary.py", T+"AuthorizationTest"], [OWNER], ""),
 ("INV-31-C043", "no ambient authority", "IMPLEMENTED_UNREVIEWED",
  [T+"AuthorizationTest::test_no_ambient_authority_in_sources"], [OWNER],
  "source-level check; process-level sandboxing is PLN-04's"),
 ("INV-31-C044", "authenticate peers/actors", "PARTIAL", [T+"AuthenticationTest"], [KMS, ADJ],
  "callers authenticated; nodes/providers/artifacts not"),
 ("INV-31-C045", "verify artifact signatures/provenance", "BLOCKED", [], ["no code-loader or artifact supply chain in scope/supplied"], ""),
 ("INV-31-C047", "encryption in transit/at rest", "BLOCKED", [], [KMS], "INV-31 persists nothing and opens no sockets"),
 ("INV-31-C048", "safe behaviour when trust services down", "IMPLEMENTED_UNREVIEWED",
  [T+"AuthenticationTest::test_empty_keystore_refuses_everyone", T+"DependencyTest"], [OWNER], ""),
 ("INV-31-C049", "tamper-evident audit", "IMPLEMENTED_UNREVIEWED", ["boundary.py::AuditLog",
  T+"ObservabilityTest::test_audit_chain_detects_tampering"], [OWNER], "chain is in-memory; export/anchoring is parent's"),
 ("INV-31-C050", "adversarial tests", "PARTIAL", [T+"AuthenticationTest", T+"AuthorizationTest",
  T+"FuzzAndPropertyTest"], [ADJ], "escape/side channels belong to the isolation tier"),
 ("INV-31-C051", "failure enumeration", "PARTIAL", ["docs/REQUIREMENTS.md", "docs/RUNBOOKS.md"], [ADJ], ""),
 ("INV-31-C052", "health/stall detection thresholds", "PARTIAL", ["boundary.py::Gateway.health"], [OWNER],
  "health/readiness exposed; stall thresholds PROPOSED only"),
 ("INV-31-C053", "bounded retry/backoff/jitter", "IMPLEMENTED_UNREVIEWED", ["boundary.py::bounded_retry",
  T+"ControlSemanticsTest"], [OWNER], ""),
 ("INV-31-C055", "failover without violating isolation", "PARTIAL", ["docs/REQUIREMENTS.md"], [ADJ],
  "pools never migrate; failover = cold start elsewhere"),
 ("INV-31-C056", "degraded operation", "IMPLEMENTED_UNREVIEWED", [T+"DependencyTest"], [OWNER], ""),
 ("INV-31-C058", "split-brain/duplicate execution", "PARTIAL", [T+"ControlSemanticsTest",
  T+"ConcurrencyStressTest"], [ADJ], "idempotency within one gateway; cross-node needs a shared store"),
 ("INV-31-C060", "fault-injection tests", "PARTIAL", [T+"DependencyTest", T+"ConfigTest"], [HW], "in-process only"),
 ("INV-31-C061", "reproducible baselines", "PARTIAL", ["tools/bench.py", "evidence/bench.json"], [HW],
  "seeded workloads; one host only"),
 ("INV-31-C062", "p50/p95/p99 thresholds", "PARTIAL", ["docs/SLOS.md", "evidence/bench_thresholds.json"], [OWNER],
  "PROPOSED"),
 ("INV-31-C063", "steady/burst/overload measurement", "PARTIAL", ["evidence/bench.json"], [HW],
  "no scale-out/in or recovery measurement"),
 ("INV-31-C064", "per-tenant overhead", "PARTIAL", ["evidence/bench.json#gateway_overhead_p50_ns"], [HW], ""),
 ("INV-31-C065", "identify avoidable work", "IMPLEMENTED_UNREVIEWED", ["runtime.py", "evidence/bench.json"],
  [OWNER], "found O(n) identifier revalidation + snapshot dicts per invoke; fixed (burst p50 ~5.7x lower); "
  "remaining linear scan and single admission lock recorded as W-03"),
 ("INV-31-C066", "apply optimisations", "PARTIAL", ["runtime.py"], [OWNER], "two semantics-preserving optimisations"),
 ("INV-31-C067", "bound memory/queues/fan-out", "IMPLEMENTED_UNREVIEWED", ["boundary.py (MAX_* bounds)",
  T+"DependencyTest::test_telemetry_overflow_is_counted_not_silent"], [OWNER], ""),
 ("INV-31-C068", "edge power/thermal", "BLOCKED", [], [HW], ""),
 ("INV-31-C069", "capacity model + saturation", "PARTIAL", ["boundary.py::Gateway.health#saturation"], [HW],
  "saturation signal exposed; no predictive model"),
 ("INV-31-C070", "block regressing releases", "PARTIAL", ["tools/bench.py --check", "ci.sh"], [OWNER],
  "check exists; not a release block while thresholds are unapproved"),
 ("INV-31-C071", "health/readiness/version/config/deps", "IMPLEMENTED_UNREVIEWED", ["boundary.py::Gateway.health",
  T+"ObservabilityTest"], [OWNER], ""),
 ("INV-31-C072", "structured metrics", "IMPLEMENTED_UNREVIEWED", ["boundary.py::Gateway.metrics"], [OWNER], ""),
 ("INV-31-C073", "structured logs", "IMPLEMENTED_UNREVIEWED", ["boundary.py::Telemetry.log"], [OWNER], ""),
 ("INV-31-C074", "trace context", "IMPLEMENTED_UNREVIEWED", ["boundary.py::child_trace",
  T+"ObservabilityTest::test_trace_context_propagates"], [OWNER], "W3C traceparent in; propagation onward is PLN-04's"),
 ("INV-31-C075", "safe high-cardinality detail", "IMPLEMENTED_UNREVIEWED", ["boundary.py::redact_tenant",
  T+"ObservabilityTest"], [OWNER], ""),
 ("INV-31-C077", "explain view", "IMPLEMENTED_UNREVIEWED", ["boundary.py::Gateway.explain",
  T+"ObservabilityTest::test_explain_view_is_tenant_scoped"], [OWNER], ""),
 ("INV-31-C078", "release lineage/infra graph correlation", "BLOCKED", [], [ADJ], ""),
 ("INV-31-C079", "telemetry retention/privacy policy", "PARTIAL", ["docs/TELEMETRY_POLICY.md"], [OWNER], "PROPOSED"),
 ("INV-31-C080", "dashboards + alerts", "PARTIAL", ["docs/TELEMETRY_POLICY.md"], [ADJ], "signal mapping only"),
 ("INV-31-C082", "contract tests for public interfaces", "IMPLEMENTED_UNREVIEWED", [T+"ErrorsTest",
  T+"VersioningTest", "fixtures/"], [OWNER], ""),
 ("INV-31-C083", "integration tests all adjacent layers", "PARTIAL", [T+"AdjacentContractTest"], [ADJ], ""),
 ("INV-31-C084", "compatibility tests across arch/runtimes", "PARTIAL", ["evidence/ci_run.json"], [HW],
  "one interpreter/arch per CI host"),
 ("INV-31-C085", "fuzz untrusted inputs", "IMPLEMENTED_UNREVIEWED", [T+"FuzzAndPropertyTest"], [OWNER],
  "seeded property fuzzing; no coverage-guided fuzzer"),
 ("INV-31-C087", "threat-derived security tests", "IMPLEMENTED_UNREVIEWED", ["docs/THREAT_MODEL.md"], [OWNER], ""),
 ("INV-31-C088", "benchmark/soak/burst/fleet", "PARTIAL", ["tools/bench.py"], [HW], "no soak/fleet"),
 ("INV-31-C089", "disaster/partition/reconnect", "PARTIAL", [T+"DependencyTest"], [ADJ], "sink partition/reconnect only"),
 ("INV-31-C090", "machine-readable acceptance evidence", "PARTIAL", ["evidence/"], [PKCORE, OWNER], ""),
 ("INV-31-C091", "SLOs/error budgets/support", "PARTIAL", ["docs/SLOS.md"], [OWNER], "PROPOSED"),
 ("INV-31-C092", "canary/rollback/emergency disable", "IMPLEMENTED_UNREVIEWED", ["docs/RUNBOOKS.md",
  T+"ObservabilityTest::test_emergency_disable_and_enable"], [OWNER], "canary itself is parent platform's"),
 ("INV-31-C093", "compatibility matrix", "IMPLEMENTED_UNREVIEWED", ["docs/COMPATIBILITY_MATRIX.md"], [OWNER], ""),
 ("INV-31-C094", "patch/vuln/EOL SLAs", "PARTIAL", ["docs/GOVERNANCE.md"], [OWNER], "PROPOSED"),
 ("INV-31-C096", "day-0/1/2 runbooks", "IMPLEMENTED_UNREVIEWED", ["docs/RUNBOOKS.md"], [OWNER], ""),
 ("INV-31-C097", "incident procedures", "PARTIAL", ["docs/RUNBOOKS.md"], [OWNER], "contacts UNASSIGNED"),
 ("INV-31-C098", "recurring reviews", "BLOCKED", ["docs/GOVERNANCE.md"], [OWNER], "cannot be performed by a build"),
 ("INV-31-C099", "exceptions/waivers register", "PARTIAL", ["WAIVERS.json", "docs/GOVERNANCE.md"], [OWNER],
  "owners/expiries unset"),
 ("INV-31-C100", "formal production exit gate", "PARTIAL", ["REMEDIATION_STATUS.json"], [PKCORE, OWNER],
  "gate evaluated mechanically -> NO_GO"),
]
