"""Authoritative source for COMPONENT_STATUS.json (regenerate: python tools/evidence_gate.py --write).

Status vocabulary (no component is marked PASS by this release):
  reference_implemented  - in-process implementation + green automated tests in this package
  port_with_reference    - typed port + in-memory reference implementation; the real external
                           adapter/integration is not in this package
  documented             - governance/process artifact exists; needs named approvers/review
  tooling                - executable release tooling exists; needs to run in the owner's CI
  open                   - nothing executable yet
Gate vocabulary:
  OPEN_REVIEW      - evidence exists; awaiting CI-matrix run + owner sign-off
  OPEN_EXTERNAL    - needs a real external system (API server, cluster, IdP, signer...)
  OPEN_GOVERNANCE  - needs named people/approvals that only the owner can supply
"""
R, P, D, T, OPN = "reference_implemented", "port_with_reference", "documented", "tooling", "open"
RV, EX, GV = "OPEN_REVIEW", "OPEN_EXTERNAL", "OPEN_GOVERNANCE"
TP = "tests/"

C = {
    1: ("Kubernetes API client adapter", P, EX, ["runtime/api.py::ClusterAPI", "runtime/api.py::check_discovery", "runtime/objects.py::from_k8s_pod"],
        [TP + "test_runtime_policy.py::AdapterBoundaryTest", TP + "test_runtime_interface.py::ServiceTest"],
        "Port, discovery fail-closed and wire-object conversion exist; no official-client adapter, kubeconfig/SA auth or server-version matrix run."),
    2: ("Informer/watch cache subsystem", R, EX, ["runtime/store.py::Informer"], [TP + "test_runtime_core.py::InformerTest"],
        "Semantics proven against VersionedStore; needs binding to real list/watch."),
    3: ("Controller work queue", R, RV, ["runtime/workqueue.py::WorkQueue", "runtime/workqueue.py::run_workers"], [TP + "test_runtime_core.py::WorkQueueTest"], ""),
    4: ("ResourceVersion / optimistic-concurrency layer", R, EX, ["runtime/store.py::VersionedStore", "runtime/api.py::InMemoryClusterAPI"],
        [TP + "test_runtime_core.py::StoreTest", TP + "test_properties.py::StoreConcurrencyTest"], "Real API-server conflict path untested."),
    5: ("Leader election / active-controller fencing", R, EX, ["runtime/lease.py::LeaderElector", "runtime/lease.py::FencingGuard"],
        [TP + "test_runtime_core.py::LeaseTest", TP + "test_runtime_drain.py::DrainTest"],
        "Lease lives in VersionedStore; production must use coordination.k8s.io/v1 Lease and enforce the fencing token on the server-side write path."),
    6: ("Durable desired-state adapter", R, EX, ["runtime/store.py::VersionedStore"], [TP + "test_runtime_core.py::StoreTest"],
        "Authoritative desired state in production is the controller objects in the API server."),
    7: ("Crash/restart recovery", R, RV, ["runtime/drain.py::DrainCoordinator"], [TP + "test_runtime_drain.py::CrashRecoveryTest"], ""),
    8: ("Drain transaction coordinator", R, RV, ["runtime/drain.py::DrainCoordinator"], [TP + "test_runtime_drain.py::DrainTest"], ""),
    9: ("Native Kubernetes Eviction API integration", P, EX, ["runtime/api.py::InMemoryClusterAPI", "runtime/policy.py::eviction_allowed"],
        [TP + "test_runtime_drain.py::DrainTest"], "Eviction subresource semantics emulated; real policy/v1 eviction not exercised."),
    10: ("Full PodDisruptionBudget evaluator", R, EX, ["runtime/policy.py::pdb_status", "runtime/policy.py::eviction_allowed"], [TP + "test_runtime_policy.py::PdbTest"],
         "Needs conformance comparison against a real API server's PDB status."),
    11: ("Unmanaged/static/mirror pod policy", R, RV, ["runtime/policy.py::classify_for_drain"], [TP + "test_runtime_policy.py::PodPolicyTest"], ""),
    12: ("Node health/unreachable semantics", R, RV, ["runtime/policy.py::node_state", "runtime/policy.py::may_evict_from"], [TP + "test_runtime_policy.py::NodeHealthTest"], ""),
    13: ("Pod termination lifecycle model", R, EX, ["runtime/policy.py::termination_state"], [TP + "test_runtime_policy.py::PodPolicyTest"],
         "Force-delete intentionally not automated (operator-only per runbook); kubelet behaviour not observed."),
    14: ("Stateful workload semantics", R, EX, ["runtime/policy.py::stateful_order", "runtime/policy.py::quorum_safe"], [TP + "test_runtime_policy.py::PodPolicyTest"],
         "quorum_safe is not yet wired into DrainCoordinator preflight (needs per-set quorum config)."),
    15: ("DaemonSet semantics", R, RV, ["runtime/policy.py::classify_for_drain"], [TP + "test_runtime_drain.py::DrainTest"], ""),
    16: ("Job/CronJob semantics", R, RV, ["runtime/policy.py::job_needs_replacement", "runtime/policy.py::classify_for_drain"], [TP + "test_runtime_policy.py::PodPolicyTest"], ""),
    17: ("Persistent-volume drain constraints", R, EX, ["runtime/policy.py::volume_blockers"], [TP + "test_runtime_policy.py::PodPolicyTest"], "CSI health not modelled."),
    18: ("Preflight capacity engine", R, RV, ["runtime/scheduling.py::plan_drain_capacity", "runtime/scheduling.py::filter_node"],
         [TP + "test_runtime_policy.py::SchedulingTest", TP + "test_runtime_drain.py::DrainTest"], "Hugepages/GPU use generic resource keys; not enumerated."),
    19: ("Scheduling constraint evaluator", R, EX, ["runtime/scheduling.py::filter_node", "runtime/scheduling.py::place"], [TP + "test_runtime_policy.py::SchedulingTest"],
         "Subset of kube-scheduler required predicates; preferred (soft) affinity not scored."),
    20: ("Priority/preemption semantics", R, RV, ["runtime/scheduling.py::preemption_candidates"], [TP + "test_runtime_policy.py::SchedulingTest"], ""),
    21: ("Atomic multi-object operation journal", R, RV, ["runtime/journal.py::Journal"], [TP + "test_runtime_core.py::JournalTest"], ""),
    22: ("Idempotency keys / operation identity", R, RV, ["runtime/journal.py::IdempotencyRegistry"], [TP + "test_runtime_core.py::JournalTest", TP + "test_runtime_interface.py::ServiceTest"], ""),
    23: ("Runtime schema validation", R, RV, ["runtime/validation.py::parse_and_validate"], [TP + "test_runtime_interface.py::SchemaFixtureTest"], ""),
    24: ("Transport/API implementation", P, EX, ["runtime/service.py::Service", "runtime/service.py::serve"], [TP + "test_runtime_interface.py::ServiceTest"], "HTTP/JSON only; gRPC/WIT/event bindings absent."),
    25: ("Protocol compatibility negotiation", R, RV, ["runtime/validation.py::negotiate"], [TP + "test_runtime_interface.py::NegotiationAndMappingTest"], ""),
    26: ("Stable transport error mapping", R, RV, ["runtime/errors.py::TRANSPORT_MAP", "runtime/service.py::problem"], [TP + "test_runtime_interface.py::NegotiationAndMappingTest"], ""),
    27: ("Authentication layer", P, EX, ["runtime/security.py::TokenAuthenticator"], [TP + "test_runtime_interface.py::SecurityTest"], "HS256 only; production IdP (OIDC/JWKS, TokenReview) not integrated."),
    28: ("Authorization/RBAC layer", R, RV, ["runtime/security.py::Authorizer"], [TP + "test_runtime_interface.py::SecurityTest"], ""),
    29: ("mTLS/service identity", OPN, EX, [], [], "Delegated to deployment (mesh/sidecar) by ADR-0001; no in-package implementation."),
    30: ("Admission/policy integration", R, EX, ["runtime/security.py::AdmissionPolicy"], [TP + "test_runtime_interface.py::SecurityTest"], "External policy engine not integrated."),
    31: ("Tenant/environment/site isolation enforcement", R, RV, ["runtime/security.py::scope_filter", "runtime/service.py::Orchestrator"], [TP + "test_runtime_interface.py::SecurityTest", TP + "test_runtime_interface.py::ServiceTest"], ""),
    32: ("Quota and fairness controller", R, RV, ["runtime/security.py::FairQueue"], [TP + "test_runtime_interface.py::SecurityTest"], "Not yet wired into the service dispatch path."),
    33: ("Timeout/deadline/cancellation semantics", R, RV, ["runtime/resilience.py::Context"], [TP + "test_runtime_ops.py::ResilienceTest"], ""),
    34: ("Retry/backoff/jitter policy", R, RV, ["runtime/resilience.py::retry_call", "runtime/resilience.py::Backoff", "runtime/resilience.py::RetryBudget"], [TP + "test_runtime_ops.py::ResilienceTest"], ""),
    35: ("Backpressure/rate limiting", R, RV, ["runtime/resilience.py::TokenBucket", "runtime/workqueue.py::WorkQueue"],
         [TP + "test_runtime_ops.py::ResilienceTest", TP + "test_runtime_core.py::WorkQueueTest", TP + "test_runtime_interface.py::ServiceTest"], ""),
    36: ("Inventory snapshot identity", R, RV, ["runtime/handoff.py::take_snapshot"], [TP + "test_runtime_ops.py::HandoffTest"], ""),
    37: ("Handoff checkpoint/acknowledgement protocol", R, EX, ["runtime/handoff.py::HandoffSession", "runtime/handoff.py::Receiver"], [TP + "test_runtime_ops.py::HandoffTest"], "Needs SCH-01 successor integration."),
    38: ("Handoff diff/change stream", R, EX, ["runtime/handoff.py::ChangeStream"], [TP + "test_runtime_ops.py::HandoffTest"], "Needs SCH-01 successor integration."),
    39: ("Cross-controller ownership resolution", R, EX, ["runtime/handoff.py::OwnershipRegistry"], [TP + "test_runtime_ops.py::HandoffTest"], "Registry is in-process; needs a durable shared authority."),
    40: ("Configuration schema and loader", R, RV, ["runtime/config.py::load_config"], [TP + "test_runtime_ops.py::ConfigTest"], ""),
    41: ("Configuration provenance/activation record", R, RV, ["runtime/config.py::ConfigManager"], [TP + "test_runtime_ops.py::ConfigTest"], ""),
    42: ("Transactional configuration rollback", R, RV, ["runtime/config.py::ConfigManager"], [TP + "test_runtime_ops.py::ConfigTest"], ""),
    43: ("Secret-management integration", P, EX, ["runtime/security.py::SecretResolver", "runtime/journal.py::redact"],
         [TP + "test_runtime_interface.py::SecurityTest", TP + "test_runtime_ops.py::ObservabilityTest"], "Env/file providers only; no external secret manager."),
    44: ("Metrics implementation", R, RV, ["runtime/observability.py::Registry", "runtime/observability.py::standard_metrics"], [TP + "test_runtime_ops.py::ObservabilityTest"], ""),
    45: ("Structured logging", R, RV, ["runtime/observability.py::JsonFormatter", "runtime/observability.py::log_event"], [TP + "test_runtime_ops.py::ObservabilityTest"], ""),
    46: ("Distributed tracing", P, EX, ["runtime/observability.py::Tracer"], [TP + "test_runtime_ops.py::ObservabilityTest"], "No OTLP exporter; W3C traceparent only."),
    47: ("Health/readiness/startup endpoints", R, RV, ["runtime/observability.py::Health", "runtime/service.py::Service"], [TP + "test_runtime_ops.py::ObservabilityTest", TP + "test_runtime_interface.py::ServiceTest"], ""),
    48: ("SLO measurement engine", R, EX, ["runtime/observability.py::ConvergenceSLO"], [TP + "test_runtime_ops.py::ObservabilityTest"], "In-memory window; needs a durable time-series backend."),
    49: ("Alerting and error-budget policy", P, GV, ["runtime/observability.py::evaluate_alerts"], [TP + "test_runtime_ops.py::ObservabilityTest"], "Paging routes/escalation owners unassigned (docs/OWNERS.md)."),
    50: ("Durable audit trail", R, EX, ["runtime/journal.py::AuditTrail"], [TP + "test_runtime_core.py::JournalTest"], "Hash-chained, not externally anchored or signed."),
    51: ("Reconcile-stall detector", R, RV, ["runtime/resilience.py::StallDetector"], [TP + "test_runtime_ops.py::ResilienceTest"], "Not yet wired into the worker loop."),
    52: ("Network-partition behavior", R, EX, ["runtime/store.py::Informer", "runtime/policy.py::node_state"], [TP + "test_runtime_ops.py::ResilienceTest", TP + "test_runtime_policy.py::NodeHealthTest"], "Needs real partition testing."),
    53: ("Dependency circuit breakers", R, RV, ["runtime/resilience.py::CircuitBreaker"], [TP + "test_runtime_ops.py::ResilienceTest"], "Not yet wrapped around every dependency call."),
    54: ("Chaos/fault-injection suite", R, EX, ["runtime/api.py::InMemoryClusterAPI"], [TP + "test_runtime_drain.py::ChaosTest"], "In-memory faults only; no real-cluster chaos."),
    55: ("Property-based/state-machine testing", R, RV, [], [TP + "test_properties.py::ModelStateMachineTest"], ""),
    56: ("Fuzz testing", R, RV, [], [TP + "test_properties.py::FuzzTest"], "Seeded mutation fuzzing; no coverage-guided fuzzer."),
    57: ("Concurrency/race tests", R, RV, [], [TP + "test_properties.py::StoreConcurrencyTest", TP + "test_runtime_core.py::WorkQueueTest"], ""),
    58: ("Real-cluster integration tests", OPN, EX, [], [], "Requires a kind/k3s matrix in owner CI; not runnable in this package."),
    59: ("Migration parity test harness", R, EX, [], [TP + "test_properties.py::ParityHarnessTest"], "Compares v4.2 model vs v4.3 runtime; SCH-01 successor side not available."),
    60: ("Scale/performance benchmarks", T, EX, ["tools/bench.py"], [], "Results are environment-specific; not release evidence until run on target hardware."),
    61: ("Soak/endurance tests", T, EX, ["tests/test_properties.py"], [], "Soak mode = INV04_ITERATIONS long property runs; no long-duration environment run."),
    62: ("Recovery/RTO/RPO tests", R, EX, ["tools/bench.py"], [TP + "test_runtime_drain.py::CrashRecoveryTest"], "Process-level RPO=0 (fsynced journal) shown; node/control-plane recovery untested."),
    63: ("Packaging metadata (pyproject.toml)", T, RV, ["pyproject.toml"], [TP + "test_artifacts.py::ArtifactIntegrityTest"], ""),
    64: ("Pinned dependency manifest/lock strategy", T, RV, ["pyproject.toml", "constraints.txt"], [], "Runtime has zero third-party dependencies; dev tools pinned."),
    65: ("SBOM generation", T, RV, ["tools/sbom.py"], [], ""),
    66: ("Artifact signing and provenance", T, EX, ["tools/release.py"], [], "Provenance statement generated; signing needs the owner's key / cosign identity."),
    67: ("Vulnerability/license scanning gates", T, EX, ["tools/lint_gate.py"], [], "Secret/unsafe-pattern scan in-package; dependency CVE scan needs pip-audit/OSV in CI."),
    68: ("CI matrix", T, RV, [".github/workflows/ci.yml"], [], "Workflow written, never executed in owner CI."),
    69: ("Static type checking", T, RV, ["pyproject.toml"], [], "mypy clean on the runtime in this build."),
    70: ("Lint/security static analysis", T, RV, ["pyproject.toml", "tools/lint_gate.py"], [], "ruff E,F,W,B,S clean in this build."),
    71: ("Release rollback package", D, GV, ["docs/ROLLBACK.md", "tools/release.py"], [], "Rollback to 4.2.0 documented; not rehearsed."),
    72: ("Architecture Decision Record", D, GV, ["docs/ADR-0001-runtime-architecture.md"], [], "Status Proposed; needs approvers."),
    73: ("Threat model", D, GV, ["docs/THREAT_MODEL.md"], [], "Needs review by someone other than the author."),
    74: ("Operator runbook", D, GV, ["docs/RUNBOOK.md"], [], "Needs game-day validation."),
    75: ("Ownership/RACI and escalation path", D, GV, ["docs/OWNERS.md"], [], "All named roles are UNASSIGNED - the owner must fill them."),
    76: ("Evidence traceability matrix", T, RV, ["tools/evidence_gate.py", "docs/TRACEABILITY.md"], [], ""),
    77: ("Evidence-quality gate", T, RV, ["tools/evidence_gate.py"], [TP + "test_artifacts.py::ArtifactIntegrityTest"], ""),
    78: ("pk_core integration pin/test fixture", T, EX, ["tools/pk_core_gate.py"], [], "Gate fails when pk_core is absent; pk_core itself is not in this archive."),
    79: ("Conformance fixtures for all v1 schemas", R, RV, ["fixtures/index.json"], [TP + "test_runtime_interface.py::SchemaFixtureTest"], ""),
    80: ("Master prompt/workflow corpus restoration (conditional)", D, GV, ["docs/ADR-0002-master-corpus.md"], [], "Decision pending owner; no historical text fabricated."),
}
