"""Per-component registry: where each of the 116 checklist components lives in
the code, what "success" means for it, what is explicitly unsupported, which
dependencies/parameters it has, and the operator diagnostics.  The component
documents in docs/components/ are GENERATED from this table, and the
evaluator checks every ``api`` symbol really exists (a missing symbol makes the
interfaces item FAIL, not PASS).

lifecycle: design | implementation | validation | production | deprecated
(no component is 'production': nothing here has passed a production gate).
"""
from __future__ import annotations


def R(api="", success="", unsupported="", deps="", params="", diag="", life="validation", note=""):
    return {"api": [a.strip() for a in api.split(",") if a.strip()], "success": success, "unsupported": unsupported,
            "deps": [d.strip() for d in deps.split(";") if d.strip()], "params": [p.strip() for p in params.split(",") if p.strip()],
            "diag": diag, "lifecycle": life, "note": note}


REG = {
    # ---- A. traversal -------------------------------------------------------------------------------
    "G12-A001": R("wan.stun.binding, wan.stun.discover, wan.stun.transact, wan.stun.decode, wan.stun.StunServer",
                  "a Binding success whose transaction id, source and FINGERPRINT/INTEGRITY (when configured) verify, yielding a server-reflexive address; discovery is OK only when >= 1 server answered and all answering servers agree",
                  "STUN over TCP/TLS/DTLS; ALTERNATE-SERVER redirect is reported, not followed; PASSWORD-ALGORITHMS",
                  "STUN servers (UDP 3478): untrusted network input; DNS resolver: dependency", "rto, rc, rm, deadline_s",
                  "reason NET_UDP_BLOCKED = every server silent; DEP_INCONSISTENT = servers disagree (symmetric NAT); DEP_MALFORMED = parser rejected answers"),
    "G12-A002": R("wan.turn.TurnClient, wan.turn.TurnServer, wan.turn.channel_data, wan.turn.parse_channel_data",
                  "an authenticated allocation whose relayed address carries data both ways under a permission, refreshed before expiry and torn down with lifetime=0",
                  "TURN over TCP/TLS/DTLS (RFC 6062), EVEN-PORT, DONT-FRAGMENT, dual-family allocations, OAuth third-party auth, server failover",
                  "TURN server: authenticated but third-party; secret provider for credentials", "lifetime, rto, rc, rm",
                  "AUTH_FAILED after 401 with valid realm/nonce = bad credential; 438 retried automatically; 486/508 = quota"),
    "G12-A003": R("wan.ice.Agent, wan.ice.Candidate, wan.ice.Pair",
                  "a nominated succeeded pair within MAX_PAIRS checks, with consent refreshed every <= 30 s",
                  "aggressive nomination, ICE-TCP, trickle ICE; the check transport is supplied by the caller",
                  "peer candidates: untrusted input (bounded to 32 per side, 100 pairs)", "MAX_CANDIDATES, MAX_PAIRS, CONSENT_TIMEOUT",
                  "Agent.pruned counts discarded hostile/redundant candidates; consent() false = path must be re-validated"),
    "G12-A004": R("wan.holepunch.punch, wan.holepunch.Rendezvous, wan.holepunch.Ticket, wan.holepunch.verify_ticket",
                  "both peers receive an HMAC-valid punch packet from the ticket's endpoint before the window closes",
                  "port prediction for symmetric NATs (falls to relay by design)",
                  "rendezvous service (trusted, keyed per peer); peer NAT behaviour", "MAX_PROBES, INTERVAL_MIN, INTERVAL_MAX, prime_ttl, window",
                  "PunchResult.cause: coordination | nat_filtering | mapping_change | local_firewall | unreachable"),
    "G12-A005": R("wan.transport.tcp_connect, wan.transport.race, wan.transport.configure_stream, wan.transport.open_sockets",
                  "a connected TCP socket within the hard deadline with keepalive and bounded send buffer",
                  "HTTP CONNECT / SOCKS proxies; VPN-specific routing (uses the OS route)",
                  "remote TCP endpoint; local routing table", "deadline_s, keepalive_idle, keepalive_interval, keepalive_count, sndbuf",
                  "CANCELLED_DEADLINE = SYN black-holed; NET_REFUSED = RST; open_sockets() must return 0 after every attempt"),
    "G12-A006": R("wan.natclass.classify, wan.natclass.Classification, wan.natclass.network_fingerprint",
                  "independent mapping and filtering labels backed by RFC 5780 test evidence, or 'undetermined' with the missing evidence named",
                  "classification without an RFC 5780 (OTHER-ADDRESS / CHANGE-REQUEST) capable server",
                  "RFC 5780 STUN server", "TTL, rto, rc, rm", "Classification.missing lists why a label was not forced"),
    "G12-A007": R("wan.natclass.assess_cgnat, wan.natclass.CgnatAssessment",
                  "a likely/possible/unlikely verdict from >= 2 independent indicators with preserved evidence",
                  "traceroute collection (hops are an input)", "STUN mapping; gateway WAN address (PCP/NAT-PMP/UPnP)", "",
                  "indicators list shows each piece of evidence; never used for identity"),
    "G12-A008": R("wan.portmap.pcp_map_request, wan.portmap.pcp_parse_response, wan.portmap.pcp_validate, wan.portmap.EpochTracker",
                  "a validated MAP response bound to our nonce/protocol/internal port and recorded in the ownership ledger",
                  "the PCP UDP client transaction, PEER opcode, THIRD_PARTY/FILTER options", "local gateway (PCP server)", "lifetime",
                  "PCP result codes mapped to reason codes; epoch regression = gateway lost state", life="implementation"),
    "G12-A009": R("wan.portmap.natpmp_transact, wan.portmap.natpmp_map_request, wan.portmap.natpmp_parse",
                  "a public-address or mapping answer from the selected gateway within 4 bounded attempts",
                  "NAT-PMP epoch reboot handling (PCP EpochTracker is not wired to NAT-PMP)", "local gateway", "attempts, initial",
                  "None = no NAT-PMP gateway; only replies from the chosen gateway are accepted", life="implementation"),
    "G12-A010": R("wan.portmap.validate_igd_url, wan.portmap.soap_add_port_mapping, wan.portmap.MappingLedger",
                  "an IGD control URL on the selected gateway's private address and an escaped SOAP request, recorded in the ledger",
                  "SSDP discovery and the HTTP/SOAP exchange itself (URL and envelope construction only)", "local IGD", "",
                  "ValueError from validate_igd_url = SSRF guard refused the URL", life="implementation"),
    "G12-A011": R("wan.netenv.eligible_ipv6, wan.stun.encode_address",
                  "only global-scope IPv6 addresses become candidates; XOR address coding is family-correct",
                  "live IPv6 traversal: the build host kernel has no IPv6 (EAFNOSUPPORT); temporary-address lifetimes/deprecation",
                  "kernel IPv6 stack", "", "no IPv6 candidates on a host whose kernel lacks IPv6", life="implementation"),
    "G12-A012": R("wan.natclass.discover_nat64_prefixes, wan.natclass.synthesize, wan.natclass.is_synthesized",
                  "Pref64::/n derived per RFC 7050/6052 and synthesized candidates kept apart from native ones",
                  "live DNS64 query of ipv4only.arpa (answers are an input); DNSSEC interaction", "DNS64 resolver", "",
                  "empty prefix list = no NAT64 detected", life="implementation"),
    "G12-A013": R("", "validated CLAT/PLAT behaviour on mobile stacks", "everything: no mobile stacks or 464XLAT lab exist here",
                  "mobile OS CLAT", "", "", life="design"),
    "G12-A014": R("wan.transport.race, wan.transport.interleave",
                  "the first connected family wins, losers are closed, history demotes but never starves a family",
                  "connection reuse across calls; per-family telemetry", "OS resolver output", "attempt_delay, deadline_s, prefer_v6, history",
                  "ConnectResult.attempts shows each racer's start offset and outcome"),
    "G12-A015": R("wan.transport.QuicAdapter", "n/a", "QUIC entirely: no stdlib QUIC; returns UNSUPPORTED", "", "", "UNSUPPORTED reason", life="design"),
    "G12-A016": R("wan.transport.tls_connect, wan.transport.tls_context",
                  "a TLS >= 1.2 AEAD session with verified certificate and hostname within the deadline",
                  "session resumption policy, revocation checking (OCSP/CRL), QUIC", "CA bundle; server certificate", "cafile, min_version, deadline_s",
                  "AUTH_TLS_CERT = certificate/identity failure, distinct from NET_* reasons"),
    # ---- B. network ---------------------------------------------------------------------------------
    "G12-B017": R("wan.netenv.snapshot, wan.netenv.Snapshot, wan.netenv.Interface",
                  "an immutable snapshot with interfaces, addresses, MTU, routes/metrics/gateways, resolvers and a fingerprint",
                  "non-Linux enumeration; Wi-Fi/cellular metering discovery (policy input)", "/sys/class/net, /proc/net/*", "metered",
                  "Snapshot.fingerprint changes when anything path-relevant changes"),
    "G12-B018": R("wan.netenv.RouteWatcher", "a published snapshot within min_stable of a real change, with periodic reconciliation",
                  "rtnetlink event subscription (polling reconcile only)", "snapshot source", "full_interval, min_stable, hold_down",
                  "RouteWatcher.events / reconciles counters"),
    "G12-B019": R("wan.netenv.select_uplink, wan.netenv.Uplink", "a deterministic uplink honouring priority, health, metering, cost and policy",
                  "", "uplink health inputs", "allow_metered, max_cost_per_gb", "reason POLICY_MECHANISM_DISABLED = only metered uplinks healthy"),
    "G12-B020": R("wan.netenv.Debounce", "a change published only after min_stable and outside hold_down", "", "", "min_stable, hold_down",
                  "Debounce.suppressed counts flaps absorbed"),
    "G12-B021": R("wan.netenv.should_migrate", "healthy sessions migrate only for a hysteresis-margin gain; failed paths migrate immediately",
                  "the session transfer itself (transport-specific)", "path scores", "margin", ""),
    "G12-B022": R("wan.netenv.pinned_socket, wan.netenv.verify_pinning", "a socket whose source address is the requested one or an error",
                  "", "local addresses", "", "OSError = source address not local; never silently unpinned"),
    "G12-B023": R("wan.dns.Resolver, wan.dns.DnsServer, wan.dns.decode_response",
                  "an answer with provenance within the overall deadline, or a distinct DNS_* reason",
                  "DNSSEC validation, DoT/DoH, TCP fallback on truncation", "configured resolvers", "query_timeout, overall_timeout, race_delay, max_concurrent, max_stale, negative_cap",
                  "Answer.source fresh|cache|stale|negative-cache; DNS_MISMATCH = spoof attempt"),
    "G12-B024": R("wan.netenv.captive_verdict", "open | captive | blocked | unknown from a connectivity probe", "the probe HTTP client (caller)",
                  "connectivity-check endpoint", "expected_status, expected_body", ""),
    "G12-B025": R("wan.netenv.Plpmtud", "a probed PMTU with black-hole detection that expires to the safe base", "the probe transport (caller)",
                  "", "base, max_size, max_probes, ttl", "Plpmtud.blackhole = large probes vanish silently"),
    "G12-B026": R("wan.netenv.usable_mtu, wan.netenv.mss_for", "usable MTU/MSS after encapsulation overhead, refusing < 576",
                  "clamping packets (policy output only)", "", "", ""),
    "G12-B027": R("wan.netenv.diagnose_firewall", "an explanation with reason codes and an empty mutation list", "active probing (inputs are observations)",
                  "", "", "findings list"),
    # ---- C. quality ----------------------------------------------------------------------------------
    "G12-C028": R("wan.quality.AttemptRunner, wan.quality.bounded_prober", "every attempt ends by its deadline with a record including cleanup status",
                  "killing a non-cooperative thread (it is abandoned and its late result discarded)", "adapters", "timeout, max_workers",
                  "AttemptRecord.late = adapter returned after its deadline"),
    "G12-C029": R("wan.quality.HealthScheduler", "probes scheduled per peer with jitter under a global probe budget", "", "", "interval, jitter, max_probes_per_second", ""),
    "G12-C030": R("wan.quality.bulk_ready", "readiness decided from sustained goodput, not liveness", "", "", "window, min_bytes_per_s", "'unknown' = not enough evidence"),
    "G12-C031": R("wan.quality.QualityWindow", "RTT/loss/jitter summaries only above min_samples, round-trip only", "one-way delay", "", "size, min_samples, max_age", ""),
    "G12-C032": R("wan.quality.BandwidthEstimator", "an estimate that ages to unknown and is disabled on metered links", "the probe train sender (caller)",
                  "", "max_age, max_probe_bytes", ""),
    "G12-C033": R("wan.quality.PathScorer", "a selection that changes only beyond margin and outside hold-down", "", "", "margin, hold_down", "PathScorer.switches"),
    "G12-C034": R("wan.quality.KeepalivePolicy", "keepalives at a fraction of the NAT binding timeout", "binding-timeout discovery", "", "assumed_binding_timeout, fraction, min_interval", ""),
    "G12-C035": R("wan.quality.ResumptionTickets", "single-use, expiring tickets bound to peer and path epoch", "", "ticket key (secret)", "lifetime", ""),
    "G12-C036": R("wan.quality.CandidateCache", "cached candidates only for the same network fingerprint and TTL", "", "", "ttl, max_entries", ""),
    "G12-C037": R("wan.quality.RelayPrewarm", "pre-warm after threshold direct failures within the window, capped", "", "", "threshold, window, max_prewarmed", ""),
    "G12-C038": R("wan.quality.choose_region", "the lowest cost-weighted RTT region inside residency constraints", "live RTT measurement (input)", "region catalogue", "residency, max_cost", ""),
    "G12-C039": R("wan.quality.RelayQuota", "reservations never exceed the hard limit under concurrency", "authoritative provider counters (input)", "", "soft, hard", ""),
    "G12-C040": R("wan.quality.InstrumentedRelay, wan.turn.Counters", "bytes counted at the relay boundary and reconciled with the server", "encryption-overhead accounting",
                  "TURN server usage report", "tolerance", "reconcile().alert = relay_accounting_divergence"),
    "G12-C041": R("wan.quality.MultipathScheduler", "failover by default; striping only for reorder-tolerant payloads", "the multipath transport", "", "", "", life="implementation"),
    "G12-C042": R("wan.quality.TrendPredictor", "a pre-emptive switch recommendation only on a sustained trend", "", "", "alpha, min_points", "", life="implementation"),
    # ---- D. security ---------------------------------------------------------------------------------
    "G12-D043": R("wan.security.TrustGate, wan.security.Attestation", "a peer is trusted only with a fresh, peer-bound attestation", "the GAP-06 verifier itself (injected)",
                  "GAP-06 attestation verifier (sibling subsystem, not bundled)", "max_age", "DEP_UNAVAILABLE = no verifier: fail closed"),
    "G12-D044": R("wan.security.SecureChannel", "AEAD frames that only the bound peer/direction/epoch can open", "channel establishment (key agreement comes from GAP-06/INV-36)",
                  "cryptography==46.0.7 (optional extra)", "window", "AUTH_INTEGRITY / AUTH_REPLAY on open()"),
    "G12-D045": R("wan.security.SecureChannel.rotate", "epoch rotation installs new directional keys and rejects old-epoch frames", "key distribution/revocation service", "", "", ""),
    "G12-D046": R("wan.security.ReplayWindow", "duplicates and out-of-window frames rejected with bounded memory", "", "", "size", ""),
    "G12-D047": R("wan.security.TurnRestCredentials", "time-limited credentials verified across a rotation overlap, revocable", "", "shared TURN secret", "ttl", ""),
    "G12-D048": R("wan.security.RelayAuthorizer", "a tenant uses only its own relays toward its own peers", "", "tenancy map", "", ""),
    "G12-D049": R("wan.security.RateLimiter", "hierarchical buckets with bounded keyspace", "", "", "limits, max_keys", "RateLimiter.denied per level"),
    "G12-D050": R("wan.security.CircuitBreaker, wan.security.RetryBudget", "closed/open/half-open with bounded admission and a shared retry budget", "", "",
                  "failure_threshold, open_for, half_open_max, close_after, ratio, floor, window", "BUDGET_BREAKER_OPEN / OPERATOR_DISABLED"),
    "G12-D051": R("wan.security.EgressPolicy", "deny-by-default with deny precedence", "", "", "allow, deny, allowed_peers", "POLICY_EGRESS_DENIED"),
    "G12-D052": R("wan.security.SecretRef, wan.security.SecretProvider, wan.security.Secret", "secrets by opaque reference, least privilege, never repr'd", "a platform secret manager backend",
                  "platform secret manager", "grants", ""),
    "G12-D053": R("wan.security.redact, wan.security.endpoint_token", "endpoints pseudonymised and secrets removed in all text sinks", "", "", "salt", ""),
    "G12-D054": R("wan.security.AnomalyDetector", "forced-relay, scanning and credential-misuse findings per source", "", "", "window, forced_relay_ratio, scan_distinct_peers, auth_fail_burst", "", life="implementation"),
    "G12-D055": R("wan.security.AuditLog", "a verifiable hash chain; any edit or deletion is located", "external anchoring of the chain head", "", "path", "AuditLog.verify returns the first bad index"),
    # ---- E. state ---------------------------------------------------------------------------------------
    "G12-E056": R("wan.state.PathStore", "no torn reads under concurrent mutation", "", "", "max_peers", ""),
    "G12-E057": R("wan.state.PathStore.transition", "all-or-nothing, generation-ordered transitions", "", "", "", ""),
    "G12-E058": R("wan.state.PathStore.save, wan.state.PathStore.restore", "atomic, digest-verified snapshots; restored paths revalidate", "", "local disk", "", ""),
    "G12-E059": R("wan.state.Clock, wan.state.FakeClock", "monotonic durations, wall only for audit", "", "", "", ""),
    "G12-E060": R("wan.state.ClockWatch", "wall jumps and suspend detected", "", "", "tolerance", ""),
    "G12-E061": R("wan.state.Supervisor, wan.state.RestartPolicy", "restart with backoff, give up after max_restarts in window", "OS-level supervision (systemd)", "", "max_restarts, window, base_backoff, max_backoff", ""),
    "G12-E062": R("wan.state.DependencyHealth", "per-dependency up/down/stale/unknown", "", "stun, turn, dns, identity, keys, observability, control_plane", "stale_after", ""),
    "G12-E063": R("wan.state.degraded_policy", "a defined continue/refuse decision per operation class", "", "", "", ""),
    "G12-E064": R("wan.state.Quarantine", "blocked until release or expiry", "", "", "", ""),
    "G12-E065": R("wan.state.FencedLease", "stale controllers' tokens refused", "a distributed lease store", "", "ttl", ""),
    "G12-E066": R("wan.state.migrate", "v1 snapshots migrated; future schema refused", "", "", "", ""),
    # ---- F. config ----------------------------------------------------------------------------------------
    **{c: R("wan.config.SCHEMA, wan.config.validate, wan.config.ConfigManager", s, "", "", "", "")
       for c, s in {"G12-F067": "a versioned schema that generates docs and fixtures",
                    "G12-F068": "invalid or trust-weakening configs rejected before activation",
                    "G12-F069": "artifact defaults + env + site overlays with a fingerprint",
                    "G12-F070": "preflight, stage, health-check, commit or roll back",
                    "G12-F071": "every activation records source/author/generation/digest/approvals",
                    "G12-F072": "mechanisms enabled per environment/zone",
                    "G12-F073": "regions carry jurisdiction and cost metadata",
                    "G12-F074": "flags carry owner and expiry; expired flags use their safe default"}.items()},
    # ---- G. observability -------------------------------------------------------------------------------
    "G12-G075": R("wan.obs.Metrics, wan.obs.CATALOG", "catalogued metrics within cardinality budget", "a push/scrape agent", "", "cardinality_budget", ""),
    "G12-G076": R("wan.obs.EventLog, wan.obs.EVENTS", "stable event ids, redacted fields, bounded suppression", "", "", "suppress_window, max_field", ""),
    "G12-G077": R("wan.obs.Tracer, wan.obs.Span", "W3C traceparent spans; untrusted ids linked not adopted", "exporting spans (OTLP)", "", "sample_rate", ""),
    "G12-G078": R("wan.obs.HealthServer, wan.obs.readiness_from", "/livez, /readyz with blocking deps, /metrics", "", "dependency health", "bind", ""),
    "G12-G079": R("wan.reasons.REASONS, wan.reasons.reason_class", "every outcome carries a registered, classed reason", "", "", "", ""),
    "G12-G080": R("wan.obs.explain, wan.controller.Controller.explain", "a decision trail with reasons and pseudonymised peer", "a UI", "", "", ""),
    "G12-G081": R("wan.obs.dashboard", "a generated dashboard covering every catalogued metric", "import into Grafana", "", "", "", life="implementation"),
    "G12-G082": R("wan.obs.alert_rules, wan.obs.classify_incident", "multi-window burn-rate and incident-class alerts", "loading into Prometheus/Alertmanager", "", "SLO", "", life="implementation"),
    "G12-G083": R("wan.obs.RETENTION", "a declared retention/sampling/redaction policy", "enforcement in the telemetry backend", "", "", "", life="implementation"),
    "G12-G084": R("wan.obs.lineage", "release/config/topology ids on every event", "a topology graph service", "", "", "", life="implementation"),
    # ---- H. testing --------------------------------------------------------------------------------------
    "G12-H085": R("evidence.run_tests", "every transition/boundary of the path machine is tested", "", "", "", ""),
    "G12-H086": R("wan.contracts.validate, wan.contracts.SCHEMAS", "every reachable document validates; drift is rejected", "", "", "", ""),
    "G12-H087": R("", "interop with independent STUN/TURN implementations", "no independent implementation (coturn etc.) is installable here: PyPI/apt blocked", "coturn or equivalent", "", "", life="design"),
    "G12-H088": R("lab.netlab.Lab, lab.scenarios.SCENARIOS", "kernel-NAT topologies as code with rules, pcaps and teardown evidence", "vendor NAT devices", "root, netns, iptables", "", ""),
    "G12-H089": R("lab.netlab.Lab", "namespace emulation with impairment", "delay/jitter/reorder/dup/corrupt/bandwidth/MTU impairment: no tc/netem on this host", "tc/netem", "", "", life="implementation"),
    "G12-H090": R("tests.test_c_quality", "partition, reconnect and flap scenarios", "", "", "", ""),
    "G12-H091": R("wan.dns.DnsServer", "outage, poison and stale-cache scenarios", "", "", "", ""),
    "G12-H092": R("", "IPv4/IPv6/NAT64 matrix", "IPv6 and NAT64 unavailable on this kernel", "", "", "", life="design"),
    "G12-H093": R("lab.scenarios.SCENARIOS", "firewall, UDP-blocked and captive scenarios", "captive portal only at HTTP level (no lab portal)", "", "", ""),
    "G12-H094": R("tests.test_h_engineering.FuzzTest", "structure-aware fuzzing with corpus and limits", "coverage-guided fuzzing (no atheris)", "", "", ""),
    "G12-H095": R("tests.test_h_engineering.ConcurrencyTest", "race/stress tests without deadlock or torn state", "a thread sanitizer (not available for CPython)", "", "", ""),
    "G12-H096": R("tests.test_h_engineering.SecurityNegativeTest", "spoofing/replay/abuse negatives", "", "", "", ""),
    "G12-H097": R("", "multi-hour soak", "no long-duration run was performed", "", "", "", life="design"),
    "G12-H098": R("tests.test_h_engineering.RetryStormTest", "a 10,000-peer storm never synchronises", "a real fleet", "", "", ""),
    "G12-H099": R("evidence.bench", "budgets met at representative and worst-supported load", "", "", "", ""),
    "G12-H100": R("evidence.evaluate", "per-item machine-readable verdicts tied to the build", "", "", "", ""),
    # ---- I. release ---------------------------------------------------------------------------------------
    "G12-I101": R("pyproject.toml", "a declared matrix; verified cells executed in CI", "Windows/macOS and Python 3.10/3.12/3.13 cells are declared, not executed", "", "", ""),
    "G12-I102": R("ops.build", "two builds byte-identical", "", "", "SOURCE_DATE_EPOCH", ""),
    "G12-I103": R("pyproject.toml", "stdlib-only runtime; the one optional dependency pinned exactly", "hash-pinned lock file", "", "", ""),
    "G12-I104": R("ops.sbom", "SBOM + provenance bound to the artifact digest", "signing (no identity/key)", "", "", ""),
    "G12-I105": R("ops.ci", "lanes on one revision; skipped mandatory lanes fail the gate", "a hosted CI service", "", "", ""),
    "G12-I106": R("", "vulnerability scanning and patch SLA", "no scanner reachable offline; SLA needs owner commitment", "", "", "", life="design"),
    "G12-I107": R("wan.rollout.Rollout", "canary stages with evidence holds and auto-rollback", "fleet deployment tooling", "", "soak_s, criteria", ""),
    "G12-I108": R("wan.rollout.KillSwitch", "signed, scoped, versioned, expiring, audited disables with a safe default", "control-plane distribution", "", "", ""),
    "G12-I109": R("docs.RUNBOOK_DAY0", "a day-0 runbook", "named contacts", "", "", ""),
    "G12-I110": R("docs.RUNBOOK_DAY1", "a day-1 runbook", "named contacts", "", "", ""),
    "G12-I111": R("docs.RUNBOOK_DAY2", "a day-2 runbook", "named contacts", "", "", ""),
    "G12-I112": R("docs.INCIDENT_MATRIX", "severity/paging/escalation by role", "paging integrations and named people", "", "", ""),
    "G12-I113": R("docs.BACKUP_RECONSTRUCTION", "durable/reconstructable/discarded split with integrity", "", "", "", ""),
    "G12-I114": R("docs.COMPATIBILITY_EOL", "contract compatibility table and proposed EOL", "an approved EOL policy", "", "", ""),
    "G12-I115": R("evidence.waivers, ops/waivers.json", "signed, expiring waivers only", "an approver registry (empty)", "", "", ""),
    "G12-I116": R("evidence.evaluate, evidence.ci_gate", "an aggregate gate over every item", "", "", "", ""),
}
