"""Render TRACEABILITY.md and MISSING_COMPONENTS.md from SELF_AUDIT.json and
REMEDIATION_STATUS.json so human- and machine-readable status always agree."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]


def main() -> None:
    sa = json.loads((HERE / "SELF_AUDIT.json").read_text())
    rs = {i["check_id"]: i for i in json.loads((HERE / "REMEDIATION_STATUS.json").read_text())["items"]}
    c = Counter(r["status"] for r in sa["requirements"])
    t = ["# Traceability matrix — INV-37 v4.3.0", "",
         f"Generated by `tools/render_status.py` from `SELF_AUDIT.json` (gate **{sa['gate']}**). "
         f"Totals: {', '.join(f'{k} {v}' for k, v in sorted(c.items()))}.", "",
         "`IMPLEMENTED_PENDING_REVIEW` = repository obligations implemented and tested; the checklist forbids PASS until the accountable role reviews it.", "",
         "| ID | Dimension | Requirement | Status (prior) | Evidence |", "|---|---|---|---|---|"]
    for r in sa["requirements"]:
        prior = f" ({r['prior_status']})" if "prior_status" in r else ""
        t.append(f"| {r['check_id']} | {r['dimension']} | {r['requirement']} | **{r['status']}**{prior} | {r['evidence']} |")
    (HERE / "TRACEABILITY.md").write_text("\n".join(t) + "\n")
    m = ["# Remaining gaps — INV-37 v4.3.0", "",
         "Generated from `REMEDIATION_STATUS.json`. Lists every checklist requirement that is not yet PASS and what is still open.", ""]
    for st in ("MISSING", "PARTIAL", "IMPLEMENTED_PENDING_REVIEW"):
        rows = [r for r in rs.values() if r["status"] == st]
        m += [f"## {st} ({len(rows)})", "", "| ID | Requirement | Done in 4.3.0 | Still open |", "|---|---|---|---|"]
        m += [f"| {r['check_id']} | {r['requirement']} | {r['done']} | {r['open']} |" for r in rows]
        m.append("")
    (HERE / "MISSING_COMPONENTS.md").write_text("\n".join(m))


if __name__ == "__main__":
    main()
