apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
resources:
  - "../../base"
patches:
  - target:
      kind: "Deployment"
      name: "inv67-controller"
    patch: "- op: replace\n  path: /spec/replicas\n  value: 3\n"
