"""Single source for the 4.3.0 remediation status of the 50 previously MISSING items.

Drives requirements/RTM.yaml, AUDIT_MATRIX_4.3.0.json and the report tables.
Status vocabulary:
  VERIFIED - implementation + passing automated tests + evidence in RELEASE_EVIDENCE.json
  PARTIAL  - implemented/specified, but part of the requirement needs an external
             environment or a named human decision that this repository cannot supply
  BLOCKED  - cannot be completed here; the blocking dependency is named
No item is WAIVED; waivers would have to be registered in EXCEPTIONS.yaml (C099).
"""

OWNER = "David Paul Russell (accountable owner, OWNERS.md)"

S = {
 "INV-70-C009": ("PARTIAL", ["OWNERS.md"], ["tests/test_governance.py::Docs"],
   "Accountable owner named. On-call alias, security reviewer and reliability reviewer are UNASSIGNED placeholders - the owner must name them."),
 "INV-70-C010": ("PARTIAL", ["docs/adr/ADR-0001-execution-technology.md"], ["tests/test_governance.py::Docs"],
   "ADR drafted with options, decision and consequences; status PROPOSED until the owner and security reviewer sign the approval block."),
 "INV-70-C012": ("VERIFIED", ["docs/DEPLOYMENT_MATRIX.md", "config.py::ENVIRONMENTS"],
   ["tests/test_config.py::Overlays.test_every_environment_resolves", "tests/test_integration.py::DevAndEdgeTiers"], ""),
 "INV-70-C015": ("VERIFIED", ["semantics.py::Lifecycle", "RUNTIME_SPEC.md#lifecycle"],
   ["tests/test_semantics.py::LifecycleTests"], ""),
 "INV-70-C019": ("VERIFIED", ["semantics.py::resolve_conflict", "docs/PRECEDENCE.md", "service.py (capability intersection, fuel tightening)"],
   ["tests/test_semantics.py::Precedence", "tests/test_integration.py::ProdPath.test_capability_requires_token_grant"], ""),
 "INV-70-C020": ("VERIFIED", ["requirements/RTM.yaml", "tools/remediation_status.py"],
   ["tests/test_governance.py::RTM"], ""),
 "INV-70-C023": ("VERIFIED", ["security.py::Authenticator", "docs/INTERFACES.md#authentication"],
   ["tests/test_security.py::AuthTests", "tests/test_integration.py::ProdPath.test_unauthenticated_rejected_before_execution"],
   "Residual: HMAC key-id verifier; ADR-0001 records the move to asymmetric keys via the Verifier seam."),
 "INV-70-C025": ("VERIFIED", ["resilience.py::Deadline/CancelToken/IdempotencyCache", "executor.py::ProcessExecutor", "docs/INTERFACES.md#timeouts"],
   ["tests/test_resilience.py", "tests/test_integration.py::Faults.test_wall_clock_preemption", "tests/test_integration.py::ProdPath.test_idempotency"], ""),
 "INV-70-C027": ("VERIFIED", ["semantics.py::negotiate/downgrade_result"],
   ["tests/test_semantics.py::Versions", "tests/test_integration.py::ProdPath.test_ok_v2_and_v1"], ""),
 "INV-70-C030": ("PARTIAL", ["tests/test_integration.py"], ["tests/test_integration.py"],
   "All adjacent seams (caller tokens, host pipe, observability, control plane) are exercised in-process; the real INV-69 / GAP-09 / INV-71 components are not in this repository."),
 "INV-70-C031": ("BLOCKED", ["executor.py::WasmBackend", "requirements/wasm.lock", "docs/WASM_RUNTIME.md", "tests/test_wasm.py"],
   ["tests/test_wasm.py"],
   "Engine seam, exact pin, fail-closed behaviour and malicious-module tests are in place; the pinned wasmtime wheel could not be installed in the remediation environment, so 5 engine tests SKIP (and FAIL under INV70_REQUIRE_WASM=1). Wheel hash in wasm.lock is UNSET."),
 "INV-70-C035": ("VERIFIED", ["config.py::resolve", "docs/CONFIGURATION.md"], ["tests/test_config.py::Overlays"], ""),
 "INV-70-C036": ("VERIFIED", ["config.py::ConfigStore._record"], ["tests/test_config.py::Activation.test_provenance_and_atomicity"], ""),
 "INV-70-C037": ("VERIFIED", ["config.py::ConfigStore.activate/rollback"],
   ["tests/test_config.py::Activation"], ""),
 "INV-70-C044": ("PARTIAL", ["security.py::make_attestation/verify_attestation"], ["tests/test_security.py::AttestationTests"],
   "Verification mechanism for all four roles is implemented and tested; there is no live node/peer/control-plane handshake in this repository to wire it into."),
 "INV-70-C045": ("VERIFIED", ["security.py::verify_artifact", "service.py (wasm path)"],
   ["tests/test_security.py::ArtifactTests", "tests/test_integration.py::WasmProfile"], ""),
 "INV-70-C048": ("VERIFIED", ["security.py::TrustStore.available/Clock.healthy", "resilience.py::derive_mode"],
   ["tests/test_security.py::AuthTests.test_c048_fail_closed", "tests/test_integration.py::Faults.test_trust_time_audit_outage_halts_then_recovers"], ""),
 "INV-70-C049": ("VERIFIED", ["security.py::AuditLog"], ["tests/test_security.py::AuditTests", "tests/test_integration.py::Faults.test_audit_sink_failure_is_fail_closed"], ""),
 "INV-70-C053": ("VERIFIED", ["resilience.py::RetryPolicy"], ["tests/test_resilience.py::Retry"],
   "Retry is a caller-side policy by design; the sandbox never retries a guest internally."),
 "INV-70-C054": ("VERIFIED", ["resilience.py::Admission/CircuitBreaker"],
   ["tests/test_resilience.py::AdmissionBreaker", "tests/test_integration.py::Faults.test_worker_crash_opens_breaker_then_recovers"], ""),
 "INV-70-C055": ("PARTIAL", ["resilience.py::select_failover"], ["tests/test_resilience.py::Failover"],
   "Failover selection policy is implemented and tested; there is no multi-site deployment to exercise it end to end."),
 "INV-70-C056": ("VERIFIED", ["resilience.py::Mode/DEGRADED_RULES", "service.py::mode", "RUNBOOK.md#degraded-modes"],
   ["tests/test_resilience.py::Degraded", "tests/test_integration.py::Faults"], ""),
 "INV-70-C058": ("VERIFIED", ["resilience.py::IdempotencyCache/FencedLease"],
   ["tests/test_resilience.py::Idempotency", "tests/test_resilience.py::Fencing"], ""),
 "INV-70-C060": ("PARTIAL", ["tests/test_integration.py::Faults"], ["tests/test_integration.py::Faults"],
   "Eight in-process fault-injection scenarios with recovery assertions; certification in a staging environment is still required."),
 "INV-70-C061": ("VERIFIED", ["tools/bench.py", "perf/baseline.json"], ["tests/test_governance.py::Perf"], "Baseline is for one machine class (recorded in the file)."),
 "INV-70-C063": ("PARTIAL", ["tools/bench.py::bench_service/bench_burst"], ["perf/baseline.json"],
   "Steady, burst, overload and recovery measured; multi-node scale not measurable here."),
 "INV-70-C064": ("VERIFIED", ["tools/bench.py::bench_tenants"], ["perf/baseline.json"], ""),
 "INV-70-C065": ("VERIFIED", ["docs/PERFORMANCE.md#overhead-analysis"], ["perf/baseline.json"], ""),
 "INV-70-C066": ("VERIFIED", ["executor.py::ProcessExecutor(warm)", "docs/PERFORMANCE.md#optimizations"], ["perf/baseline.json#warm_vs_cold"], ""),
 "INV-70-C068": ("BLOCKED", ["docs/PERFORMANCE.md#edge-power"], [],
   "Needs physical edge hardware with power instrumentation; procedure is written, no measurements exist."),
 "INV-70-C070": ("VERIFIED", ["tools/bench.py::gate", ".github/workflows/ci.yml"], ["tests/test_governance.py::Perf"], ""),
 "INV-70-C072": ("VERIFIED", ["telemetry.py::Metrics"], ["tests/test_telemetry.py::MetricsTests"], ""),
 "INV-70-C073": ("VERIFIED", ["telemetry.py::StructuredLog"], ["tests/test_telemetry.py::LogTests"], ""),
 "INV-70-C074": ("VERIFIED", ["telemetry.py::TraceContext"], ["tests/test_telemetry.py::TraceTests", "tests/test_integration.py::Observability.test_trace_propagates"], ""),
 "INV-70-C075": ("VERIFIED", ["telemetry.py::DiagnosticChannel"], ["tests/test_telemetry.py::DiagTests"], ""),
 "INV-70-C077": ("VERIFIED", ["service.py::Sandbox.explain"], ["tests/test_integration.py::Observability"], ""),
 "INV-70-C078": ("PARTIAL", ["service.py::RELEASE_LINEAGE"], ["tests/test_integration.py::Observability"],
   "Every run links to release version, source revision and config digest; no live infrastructure graph exists to correlate against."),
 "INV-70-C079": ("PARTIAL", ["telemetry.py::TELEMETRY_POLICY/redact"], ["tests/test_telemetry.py"],
   "Policy as code with in-process redaction, sampling and bounds; retention-day enforcement belongs to the collector (GAP-09)."),
 "INV-70-C080": ("PARTIAL", ["ops/alerts.yaml", "ops/dashboard.json", "service.py::REASON_CODES"], ["tests/test_governance.py::Ops"],
   "Alert rules, dashboard and diagnostic classes are shipped as code; not deployed to a monitoring stack."),
 "INV-70-C083": ("PARTIAL", ["tests/test_integration.py"], ["tests/test_integration.py"],
   "dev / prod / edge tiers certified in-process; real multi-layer environment not available."),
 "INV-70-C084": ("PARTIAL", ["docs/COMPATIBILITY.md", ".github/workflows/ci.yml"], ["tests/test_semantics.py::Versions"],
   "Matrix defined; only CPython 3.11 / Linux x86_64 was actually exercised."),
 "INV-70-C085": ("VERIFIED", ["tests/test_fuzz.py"], ["tests/test_fuzz.py"], ""),
 "INV-70-C088": ("PARTIAL", ["tools/bench.py"], ["perf/baseline.json"], "Benchmark and burst done locally; soak and fleet-scale not run."),
 "INV-70-C089": ("PARTIAL", ["tests/test_integration.py::Faults"], ["tests/test_integration.py::Faults"],
   "Trust/time/audit outage, control-plane partition, drain and reconnect simulated in-process; no real network partition test."),
 "INV-70-C090": ("VERIFIED", ["tools/release_evidence.py", "RELEASE_EVIDENCE.json"], ["tests/test_governance.py::Evidence"], ""),
 "INV-70-C093": ("VERIFIED", ["semantics.py::SUPPORTED_PEER_RELEASES/check_peer_release", "docs/COMPATIBILITY.md"],
   ["tests/test_semantics.py::Versions.test_peer_window"], ""),
 "INV-70-C094": ("PARTIAL", ["ops/VULNERABILITY_AND_EOL.md"], ["tests/test_governance.py::Docs"], "Policy written; owner adoption and a scanner feed are pending."),
 "INV-70-C097": ("PARTIAL", ["RUNBOOK.md"], ["tests/test_governance.py::Docs"], "Severity, containment and recovery defined; paging target is UNASSIGNED."),
 "INV-70-C098": ("PARTIAL", ["ops/REVIEWS.md"], ["tests/test_governance.py::Docs"], "Review schedule defined; no review has been held yet."),
 "INV-70-C099": ("VERIFIED", ["EXCEPTIONS.yaml"], ["tests/test_governance.py::Exceptions"], ""),
}
