"""Regenerate docs/ERRORS.md from errors.ERROR_CODES (CI checks it is current)."""
from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent))
from pln04_execution_plane.errors import ERROR_CODES, ERROR_TAXONOMY_VERSION  # noqa: E402


def render() -> str:
    lines = [f"# PLN-04 error taxonomy — `{ERROR_TAXONOMY_VERSION}`", "",
             "Generated by `tools/gen_error_doc.py` from `errors.py`; do not edit by hand.", "",
             "Codes are append-only. A code is never renamed or re-purposed; deprecated codes stay listed. "
             "Retryability belongs to the code, not to an exception class. `Retry-After` is sent only where the "
             "Retry-After column says yes. Public error bodies carry only allow-listed detail keys; causes are kept "
             "internally (`__cause__`) and never serialised.", "",
             "| Code | Category | Retryable | HTTP | Retry-After | Meaning |", "|---|---|---|---|---|---|"]
    for code, s in ERROR_CODES.items():
        lines.append(f"| `{code}` | {s.category} | {'yes' if s.retryable else 'no'} | {s.http_status} | "
                     f"{'yes' if s.retry_after_allowed else 'no'} | {s.summary}{' (deprecated)' if s.deprecated else ''} |")
    lines += ["", "Legacy mapping: `NoSufficientTier`→POL-001, `AdmissionConflict`→CONF-001, `CapacityExceeded`→CAP-001, "
              "`ResidentTierUnattested`→ATT-001, `PermissionError`→AUTHZ-002, `ValueError`/`TypeError`→VAL-001, "
              "anything else→INT-001.", "",
              "gRPC/WIT equivalents are not shipped; any future binding must carry `error_code` unchanged."]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = ROOT / "docs" / "ERRORS.md"
    if "--check" in sys.argv:
        sys.exit(0 if out.read_text(encoding="utf-8") == render() else 1)
    out.write_text(render(), encoding="utf-8")
