"""Render the data-derived reference documents from the code that enforces them.

Generated documents cannot drift from behavior: tests/test_governance.py
re-renders them and fails if the committed copy differs.

  docs/generated/LIFECYCLE.md        lifecycle.TRANSITIONS
  docs/generated/ERROR_CODES.md      errors.REGISTRY
  docs/generated/CONFIGURATION.md    config.FIELDS / LOCKED / LAYER_ALLOW / SECURE_DEFAULTS
  docs/generated/OPERATIONS.md       resilience.OPERATIONS, DEPENDENCIES, STALE_TRUST_GRACE_S
  docs/generated/PROFILES.md         qualify.PROFILES
  docs/generated/COMPATIBILITY.md    compat.SURFACES / FEATURES / MATRIX / DEPRECATIONS
  docs/generated/METRICS.md          telemetry.CATALOG
  docs/generated/FAILURE_MATRIX.md   governance/failure_matrix.json
  docs/generated/AUTHZ.md            auth.ROLES / TWO_PERSON / HOST_ACTIONS
  docs/generated/REQUIREMENTS.md     governance/requirements.json
"""
from __future__ import annotations

import json
import pathlib
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG.parent))

HDR = "<!-- GENERATED by tools/render_docs.py - do not edit by hand -->\n\n"


def table(headers, rows) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ") for c in r) + " |")
    return "\n".join(out) + "\n"


def render() -> dict[str, str]:
    from inv71_heavy_agent_sandbox.control import auth, compat, config, errors, lifecycle, qualify, resilience, telemetry
    docs: dict[str, str] = {}
    t = lifecycle.TRANSITIONS
    docs["LIFECYCLE.md"] = HDR + "# Lifecycle state machine (C015)\n\nEvery legal transition. Anything else is rejected with `LIFECYCLE.ILLEGAL_TRANSITION`. `CLOSED` is reachable only from `VERIFYING_TEARDOWN` with a verified, leak-free teardown proof; a failed teardown goes to `QUARANTINED`.\n\n" + table(
        ["From", "To", "Initiator", "Guard", "Deadline in target (s)", "Event", "Crash/restart reconciliation"],
        [(x.src.value, x.dst.value, x.initiator, x.guard, x.timeout_s if x.timeout_s is not None else "-", x.event, x.crash_recovery) for x in t])
    docs["ERROR_CODES.md"] = HDR + "# Stable error codes (C026, C014)\n\nRecord shape: `schemas/PK_HEAVYBOX_ERROR_v1.schema.json`. Unknown internal failures map to `INTERNAL.UNCLASSIFIED`; the original exception type is kept only in the privileged diagnostic field.\n\n" + table(
        ["Code", "Outcome", "Retry class", "HTTP", "gRPC", "Operator action", "User-safe message"],
        [(e.code, e.outcome.value, e.retry.value, e.http_status, e.grpc_status, e.operator_action, e.user_message) for e in errors.REGISTRY.values()])
    docs["CONFIGURATION.md"] = HDR + "# Configuration schema (C033-C036)\n\nLayers, lowest to highest precedence: " + " < ".join(config.LAYERS) + ". Tenant and session layers may only lower numeric ceilings. `LOCKED` fields cannot be changed by any layer. Unknown fields are rejected. Duplicate JSON keys, NaN/Infinity and documents over " + str(config.MAX_CONFIG_BYTES) + " bytes are rejected before use.\n\n" + table(
        ["Field", "Type", "Min", "Max", "Privileged-change only", "Secure default", "Locked", "Overridable at"],
        [(k, v[0].__name__, v[1] if v[1] is not None else "-", v[2] if v[2] is not None else "-", v[3], json.dumps(config.SECURE_DEFAULTS[k]),
          "yes" if k in config.LOCKED else "", ", ".join(l for l in config.LAYERS[1:] if k in config.LAYER_ALLOW[l]) or "-")
         for k, v in config.FIELDS.items()])
    docs["OPERATIONS.md"] = HDR + "# Deadlines, retry classes, dependency criticality (C025, C053, C048, C056)\n\n" + table(
        ["Operation", "Deadline (s)", "Retry class", "Cancellable"], [(k, *v) for k, v in resilience.OPERATIONS.items()]) + "\n## Dependencies\n\n" + table(
        ["Dependency", "Criticality", "Stale-trust grace for new decisions (s)"],
        [(k, v.value, resilience.STALE_TRUST_GRACE_S.get(k, "n/a (degraded only)")) for k, v in resilience.DEPENDENCIES.items()]) + \
        "\nRetry policy defaults: full jitter, base 50 ms, cap 2 s, max 5 attempts, max 10 s elapsed, caller deadline propagated. `never` and `with_compensation` codes are never retried by the library.\n"
    docs["PROFILES.md"] = HDR + "# Deployment profiles (C012)\n\n" + table(
        ["Profile", "Min kernel", "Min memory MiB", "KVM", "cgroup v2", "Nested virt allowed", "Offline grace (s)", "Telemetry buffer MiB"],
        [(k, "%d.%d" % v["min_kernel"], v["min_mem_mib"], v["kvm"], v["cgroup2"], v["nested_ok"], v["offline_grace_s"], v["telemetry_buffer_mib"]) for k, v in qualify.PROFILES.items()]) + \
        "\nUnsupported: nested virtualization on every profile; any host without usable `/dev/kvm`, unified cgroup v2, virtualization CPU flags or time sync; far-edge sessions above 8192 MiB.\n"
    docs["COMPATIBILITY.md"] = HDR + "# Versioning and compatibility (C016, C027, C084, C093)\n\nSupport window: current major N and N-1 for every surface. Maximum skew: " + json.dumps(compat.MAX_SKEW) + ".\n\n" + table(
        ["Surface", "Current"], [(k, "%d.%d" % v) for k, v in compat.SURFACES.items()]) + "\n## Features\n\n" + table(
        ["Feature", "Minimum control_api"], compat.FEATURES.items()) + "\n## Deprecations\n\n" + table(
        ["Contract", "Notice", "Enforced after", "Migration"], [(k, v["notice"], v["enforce_after"], v["migration"]) for k, v in compat.DEPRECATIONS.items()]) + "\n## Runtime matrix\n\nEvery real-runtime row is `untested`: no Firecracker host run exists. `deployable()` returns true only for `supported` rows, so nothing is deployable yet.\n\n" + table(
        ["arch", "cpu", "host_kernel", "firecracker", "guest_kernel", "status"], [(r.get("arch"), r.get("cpu"), r.get("host_kernel"), r.get("firecracker"), r.get("guest_kernel"), r["status"]) for r in compat.MATRIX])
    docs["METRICS.md"] = HDR + "# Metric catalog (C072)\n\nLabel values come from bounded vocabularies; raw session ids, hostnames, URLs and tenant ids are refused. Histogram buckets (s): " + ", ".join(map(str, telemetry.BUCKETS_S)) + ".\n\n" + table(
        ["Metric", "Type", "Unit", "Labels", "Meaning"], [(k, v[0], v[1], ", ".join(v[2]) or "-", v[3]) for k, v in telemetry.CATALOG.items()])
    fm = json.loads((PKG / "governance" / "failure_matrix.json").read_text())
    docs["FAILURE_MATRIX.md"] = HDR + "# Failure matrix (C051) - " + fm["status"] + "\n\n" + table(
        ["ID", "Component", "Failure", "Detection", "Blast radius", "Retry", "Automatic recovery", "Isolation risk", "Correlated", "Scenario"],
        [(r["id"], r["component"], r["failure"], r["detection"], r["blast_radius"], r["retry_safety"], r["automatic_recovery"], r["isolation_risk"], r["correlated_with"], r["scenario"]) for r in fm["rows"]])
    docs["AUTHZ.md"] = HDR + "# Roles and capabilities (C024, C042, C009-IMP-02)\n\nDefault deny. No wildcard, no inherited administrator. Host capabilities belong only to `node-helper`. Two-person actions: " + ", ".join(sorted(auth.TWO_PERSON)) + ".\n\n" + table(
        ["Role", "Actions"], [(k, ", ".join(sorted(v))) for k, v in auth.ROLES.items()])
    req = json.loads((PKG / "governance" / "requirements.json").read_text())
    rows = [(r["id"], r["level"], r["text"], r.get("pre", "-"), r.get("post", "-"), r["acceptance"], ", ".join(r["controls"]), ", ".join(r["tests"])) for r in req["requirements"]]
    docs["REQUIREMENTS.md"] = HDR + "# Normative requirements (C011) - " + req["status"] + "\n\n" + table(
        ["ID", "Level", "Requirement", "Precondition", "Postcondition", "Acceptance", "Controls", "Tests"], rows)
    return docs


def write() -> None:
    out = PKG / "docs" / "generated"
    out.mkdir(parents=True, exist_ok=True)
    for name, text in render().items():
        (out / name).write_text(text, encoding="utf-8")


if __name__ == "__main__":
    write()
    print("rendered", len(render()), "documents")
