"""Per-component execution status for the v4.3.0 pass over the MC-001..MC-032 checklists.

x = implemented AND objectively evidenced by an automated test/artifact in this package (reference scope)
~ = partially implemented / evidenced (gap stated in the component's 'gaps')
(unlisted) = not evidenced; stays [ ]
Exit-evidence boxes are keyed 'EX:<first words>'. Per the checklist's own rule, no P0/P1 component is
declared production-closed here: human security review, org ownership and fleet/CI evidence are external.
"""
T = "tests/"
STATUS = {
 "MC-001": dict(status="PARTIAL", evidence=["wit/inv13-system-interface.wit", "WIT.lock", "APPROVED_SURFACE.json", "host/wit_surface.py", T+"test_wit_wasm.py::WitSurface"],
   x=["Target selection", "Package namespace", "World decomposition", "Capability mapping", "Error surface", "Compatibility policy", "Locking/pinning", "Surface-diff gate", "Negative contract tests", "Release tagging"],
   p=["Type design", "Resource ownership", "String/byte semantics", "Schema fuzzing", "Deprecation tests", "Review ownership", "EX:Immutable WIT source", "EX:Contract/conformance tests"],
   gaps="No wit-bindgen generated bindings, canonical-ABI validation, cross-language conformance or generated docs (toolchain absent); security approval of the world set pending named reviewers."),
 "MC-002": dict(status="PARTIAL", evidence=["host/runtime_adapter.py", "host/adapter_v8.mjs", "host/wasm_loader.py", T+"test_wit_wasm.py::V8Adapter"],
   x=["Adapter boundary", "Component loading", "Instantiation sequence", "World enforcement", "Trap classification", "Panic containment", "Security defaults", "Provider injection"],
   p=["Runtime selection", "Lifecycle", "Fuel/epoch limits", "Store/isolate design", "Integration tests", "Operational diagnostics", "Version negotiation", "EX:Denied capabilities are demonstrab", "EX:Failure injection proves guest fau"],
   gaps="Engine is V8 via Node for core Wasm only (process-per-run, wall-time limit, no fuel/memory caps inside the engine); Component-model binaries refused; no Wasmtime binding, canonical ABI, multi-runtime tests; fs/net/http providers not yet bound into the engine import table."),
 "MC-003": dict(status="IMPLEMENTED (POSIX host provider)", evidence=["host/fs.py", T+"test_fs_descriptor.py", "docs/adr/ADR-003-filesystem-strategy.md"],
   x=["Descriptor-root model", "Relative traversal", "No string re-resolution", "Symlink policy", "TOCTOU resistance", "Parent traversal", "Absolute paths", "Mount boundary", "POSIX semantics", "Descriptor rights", "Creation semantics", "Deletion semantics", "Revocation", "Path limits", "Race harness", "EX:No production filesystem operation", "EX:Symlink/rename/mount-race adversar"],
   p=["Open-time validation", "Special files", "Privilege tests", "Audit fields", "EX:Static review confirms descriptor", "EX:Security test demonstrates a hosti"],
   gaps="Windows handle-relative implementation absent (fails closed); FIFO/device special-file policy only via O_NOFOLLOW + type checks on read; independent static review pending."),
 "MC-004": dict(status="IMPLEMENTED (reference table; INV-42 service external)", evidence=["host/descriptors.py", T+"test_authz.py::Descriptors", T+"test_adversarial.py::Races"],
   x=["Descriptor schema", "Stable identity", "Binding", "Ownership", "Inheritance", "Delegation", "Revocation", "Provenance chain", "Concurrency", "API abuse tests", "Cross-component tests", "EX:Revocation tests prove new operati", "EX:Stale/reused descriptor identifier"],
   p=["Issuance policy", "Audit", "Generation protection", "EX:Every active production capability"],
   gaps="No expiry, persistence, reconciliation, serialization/migration; authoritative INV-42 service must implement the DescriptorTable interface."),
 "MC-005": dict(status="IMPLEMENTED", evidence=["host/policy.py", T+"test_authz.py::Policy", T+"test_adversarial.py::Fuzz.test_policy_property_no_undeclared_authority"],
   x=["Policy model", "Deny by default", "Decision API", "Pre-instantiation gate", "Use-time checks", "Tenant isolation", "Policy input validation", "Policy provenance", "Atomic activation", "Rollback", "Reason safety", "Emergency controls", "Property tests", "Outage tests", "EX:Policy decisions are required and", "EX:Outage and malformed-policy tests"],
   p=["Decision telemetry", "Separation of duties", "Mutation tests"],
   gaps="No policy simulation/dry-run tooling, no decision caching, policy bundles unsigned, independent tenant-isolation review pending."),
 "MC-006": dict(status="PARTIAL (reference HMAC identity; PKI/attestation external)", evidence=["host/identity.py", T+"test_authz.py::Identity"],
   x=["Workload binding", "Freshness", "Failure behavior", "Replay/forgery tests", "Degraded mode", "Clock dependence", "Claims minimization"],
   p=["Identity taxonomy", "Credential type", "Attestation scope", "Verifier policy", "Rotation", "Audit", "EX:Revoked/expired identities cannot"],
   gaps="Shared-key HMAC is not production identity; no X.509/SPIFFE, key custody, revocation lists, channel binding or real TEE verifier. Fuzzing found and fixed a token-malleability defect (non-canonical base64)."),
 "MC-007": dict(status="IMPLEMENTED (host provider); engine binding open", evidence=["host/net.py", T+"test_net_http.py::Sockets"],
   x=["Capability taxonomy", "Address policy", "DNS authority", "Hostname binding", "Connect gate", "Bind/listen gate", "Protocol restrictions", "IPv4/IPv6", "Quota", "Error mapping", "No ambient fallback", "Egress adversarial tests", "EX:A component with no network capabi"],
   p=["Timeout/cancel", "Local metadata protection", "Telemetry", "EX:Destination-policy and DNS-rebindi", "EX:Quota/timeout/revocation behavior"],
   gaps="Accepted-socket inheritance, proxy semantics, UDP data path, race tests and platform matrix not done; not bound into guest ABI yet."),
 "MC-008": dict(status="IMPLEMENTED", evidence=["host/stdio_env.py", T+"test_providers.py::EnvStdio"],
   x=["Environment allowlist", "Argument policy", "Secret separation", "Secret retrieval", "Stdio model", "Output quotas", "Redaction", "No secret inheritance", "Test fixtures", "EX:Guest-visible env/args/stdio are p", "EX:Canary-secret leakage tests pass a", "EX:Secret access is identity/policy b", "EX:Resource/rate limits prevent unbou"],
   p=["Input quotas", "Secret lifetime", "Encoding normalization", "Audit", "Documentation"],
   gaps="Locale/timezone, cwd semantics, fd inheritance for spawned engine only partly (clean env passed to node), secret rotation."),
 "MC-009": dict(status="IMPLEMENTED", evidence=["host/clocks.py", T+"test_providers.py::Clocks"],
   x=["Clock taxonomy", "Provider binding", "Wall-clock semantics", "Monotonic semantics", "Precision policy", "Deterministic mode", "Backward jumps", "Clock denial", "Error mapping", "Replay tests", "EX:No world without clock authority c", "EX:Deterministic test clock cannot be"],
   p=["Side-channel review", "Timer API", "Forward jumps", "EX:Monotonic, wall-clock, precision,"],
   gaps="No timer/sleep API, no trusted-time dependency handling, side-channel review needs a human reviewer."),
 "MC-010": dict(status="IMPLEMENTED", evidence=["host/randomness.py", T+"test_providers.py::Randomness"],
   x=["Source selection", "Capability gating", "No silent downgrade", "Request bounds", "Backpressure", "Deterministic provider", "Production guard", "Error taxonomy", "Statistical smoke tests", "EX:Production random provider is cryp", "EX:Failure tests prove no insecure fa", "EX:Deterministic provider is mechanic", "EX:Load/quota tests demonstrate bound"],
   p=["Provider health", "Concurrency", "Known-answer tests"],
   gaps="FIPS mode and fork/snapshot reseed semantics are delegated to the OS; no dependency review sign-off."),
 "MC-011": dict(status="IMPLEMENTED", evidence=["host/resources.py", T+"test_errors_resources.py::ResourceTableTest", T+"test_adversarial.py::Races.test_resource_table_concurrent_push_drop"],
   x=["Table architecture", "Typed entries", "Opaque handles", "Generation counters", "Ownership", "Borrow lifetime", "Drop semantics", "Parent-child resources", "Capacity limits", "Leak detection", "Forced teardown", "Concurrency control", "ABA defense", "Fuzzing", "Shutdown tests", "EX:Stale, wrong-type, dropped, revoke", "EX:Leak tests return table/host resou", "EX:Concurrency/race tests show no dou", "EX:Quota exhaustion does not leak hos"],
   p=["Exception safety", "Admission control", "Metrics", "Revocation"],
   gaps="12-bit generation counter wraps after 4095 reuses of one slot (documented residual risk T-10)."),
 "MC-012": dict(status="IMPLEMENTED", evidence=["host/errors.py", T+"test_errors_resources.py::ErrorTaxonomy", "docs/adr/ADR-004-error-model.md"],
   x=["Top-level classes", "Stable codes", "Retry semantics", "Boundary mapping", "No raw passthrough", "Capability denials", "Timeout/cancel distinction", "Unknown errors", "Versioning", "Serialization", "Redaction tests", "Mapping completeness", "Documentation", "EX:Error conformance tests cover all", "EX:Canary leakage tests pass for gues", "EX:Unknown failures fail safely with"],
   p=["Quota detail", "Integrity failures", "Correlation", "Metrics", "Fault injection", "EX:Retry/idempotency behavior is docu"],
   gaps="Localization boundary not addressed; security review pending."),
 "MC-013": dict(status="PARTIAL", evidence=["host/aio.py", T+"test_providers.py::Async"],
   x=["Cancellation ownership", "Propagation", "Deadlines", "Bounded queues", "Backpressure", "Idempotency", "EX:No async queue or buffer grows unb"],
   p=["Async model", "Readiness semantics", "Timeout hierarchy", "Shutdown", "Deterministic tests"],
   gaps="asyncio reference only; not wired to engine pollables/futures; no fairness, partial-I/O or load tests."),
 "MC-014": dict(status="IMPLEMENTED (single node)", evidence=["host/config.py", T+"test_ops.py::Config", T+"test_adversarial.py::Races.test_concurrent_config_writers_single_winner"],
   x=["Declarative schema", "Strict validation", "Canonical form", "Provenance", "Immutable snapshot", "Staging", "Atomic switch", "Rollback", "Crash consistency", "Fault injection", "Audit", "EX:Activation tests prove no mixed sn", "EX:Rollback restores the prior known-"],
   p=["Stale-policy guard", "Drift detection", "EX:Crash/partition tests do not resul"],
   gaps="No distributed consistency / multi-node activation, approval gates, impact analysis or schema migration."),
 "MC-015": dict(status="PARTIAL (durable local sink; WORM/KMS external)", evidence=["host/audit_sink.py", T+"test_ops.py::Audit", "docs/adr/ADR-005-audit-and-export.md"],
   x=["Event schema", "Canonical encoding", "Chain construction", "Node identity binding", "Crash recovery", "Sequence/gap detection", "Clock handling", "Privacy", "Independent verifier", "Tamper tests", "EX:Independent verifier detects modif"],
   p=["Durable transport", "Backpressure policy", "Retention", "Outage tests", "Evidence export", "EX:Audit records bind back to authent"],
   gaps="No remote/WORM transport, checkpoint key rotation/custody, tenant-separated streams, access monitoring."),
 "MC-016": dict(status="PARTIAL", evidence=["host/telemetry.py", T+"test_ops.py::Telemetry", T+"test_integration.py"],
   x=["Security classes", "Cardinality control", "Histogram design", "Structured logging", "Redaction", "Backpressure/drop accounting", "Correlation", "EX:Canary-secret/privacy tests pass a", "EX:Telemetry remains bounded and non-"],
   p=["Telemetry schema", "Golden signals", "Identity fields", "Tenant/privacy routing"],
   gaps="No OTLP exporter, secure transport, dashboards, alert rules or runbook links (needs the org's observability stack)."),
 "MC-017": dict(status="PARTIAL", evidence=["host/quotas.py", T+"test_ops.py::Quotas", T+"test_integration.py::test_quota_quarantine_revocation"],
   x=["Resource inventory", "Quota hierarchy", "Admission gate", "Fairness", "Atomic accounting", "Error semantics", "Descriptor pressure", "Abuse tests", "Cross-tenant tests"],
   p=["Reservation model", "Backpressure integration", "Capacity model", "EX:Fairness tests show abusive tenant"],
   gaps="No priority classes, soft limits/burst, dynamic updates, memory-pressure limits inside the engine, operator overrides."),
 "MC-018": dict(status="PARTIAL", evidence=["host/http_out.py", T+"test_net_http.py::Http"],
   x=["Method policy", "URL parsing", "Scheme policy", "Destination authorization", "SSRF defense", "DNS rebinding defense", "Redirect policy", "Credential isolation", "TLS validation", "Body limits", "Timeouts", "Error mapping", "Adversarial tests", "EX:SSRF suite cannot reach protected", "EX:No implicit host credentials/proxy"],
   p=["Header policy", "Typed resources", "Capability binding", "EX:TLS, timeout, quota, cancellation,"],
   gaps="No connection pooling, proxy semantics, retry policy, HTTP/2 controls; not bound to guest ABI."),
 "MC-019": dict(status="IMPLEMENTED", evidence=["host/compat.py", "COMPAT_MATRIX.json", T+"test_wit_wasm.py::Negotiation"],
   x=["Version dimensions", "Compatibility matrix", "Negotiation protocol", "No best-effort ambiguity", "Backward compatibility", "Deprecation policy", "EOL enforcement", "Semantic diff", "Negative tests", "Downgrade resistance", "Release gate", "EX:Machine-readable compatibility mat", "EX:Unsupported/downgrade attempts fai"],
   p=["Provider compatibility", "Artifact metadata", "Documentation"],
   gaps="No rolling-upgrade/state-compat scenarios, generated-binding matrix."),
 "MC-020": dict(status="PARTIAL (1 of 16 declared cells executed)", evidence=["ci/matrix.yml", "COMPAT_MATRIX.json", "evidence/"],
   x=["Support matrix"], p=["Native CI", "Filesystem matrix", "Reproducibility", "Performance baseline"],
   gaps="Only linux/x86_64/Python 3.11/Node 22 executed; Windows fs provider absent; ARM64/macOS unrun."),
 "MC-021": dict(status="IMPLEMENTED (stdlib seeded fuzzing)", evidence=[T+"test_adversarial.py::Fuzz"],
   x=["Path fuzzer", "World/capability fuzzer", "Resource-ID fuzzer", "Property invariants", "Determinism", "Regression gate", "EX:Authority invariants execute conti"],
   p=["Threat-driven corpus", "WIT/ABI fuzzer", "Differential testing", "Timeout containment", "Crash triage", "EX:Every historical security-relevant"],
   gaps="No coverage-guided fuzzer (Atheris/libFuzzer), sanitizers, corpus minimisation or long campaigns."),
 "MC-022": dict(status="PARTIAL", evidence=[T+"test_adversarial.py::Races", T+"test_fs_descriptor.py::*test_symlink_swap_race"],
   x=["Grant/revoke race", "Descriptor reuse race", "Resource-table race", "Quota race", "Policy activation race", "Stress scheduler"],
   p=["Shutdown race", "Cancellation race", "Leak accounting", "EX:No tested interleaving broadens au"],
   gaps="No race detectors/sanitizers (pure Python), deterministic scheduler, identity-rotation or audit-chain race suites."),
 "MC-023": dict(status="IMPLEMENTED (in-process)", evidence=[T+"test_adversarial.py::Faults", T+"test_ops.py::Config.test_crash_between_steps_leaves_old_config"],
   x=["Failure catalog", "Runtime crash", "Control-plane loss", "Policy outage", "Identity outage", "Filesystem failures", "Random-provider failure", "Disk pressure", "Corruption", "No silent recovery", "EX:No injected outage results in ambi"],
   p=["Injection framework", "Network failures", "Restart/reconciliation", "Recovery ordering", "EX:Fault matrix covers every P0 depen"],
   gaps="No network partition, split-brain or memory-pressure chaos; no alert validation."),
 "MC-024": dict(status="IMPLEMENTED — with finding B-01 (resolve SLO missed)", evidence=["tools/bench.py", "BENCH_BASELINE.json", "evidence/bench.json"],
   x=["Benchmark taxonomy", "Environment pinning", "Warm/cold states", "Startup metrics", "Operation latency", "Descriptor density", "Overload test", "Soak test", "Regression threshold"],
   p=["Throughput", "Memory cost", "Burst test", "Security-overhead test", "Capacity planning", "EX:Tail latency, saturation, resource"],
   gaps="Lexical resolve p99 ≈ 61 µs vs the contract's 1 µs target (see AUDIT_REPORT B-01); single-host, short soak; no cross-platform baselines."),
 "MC-025": dict(status="PARTIAL", evidence=["tools/build.py", "SBOM.cdx.json", "PROVENANCE.intoto.json", "MANIFEST.sha256"],
   x=["Dependency manifest", "SBOM generation", "Artifact hashing", "Reproducible inputs", "Reproducibility", "Build provenance"],
   p=["Version locking", "Transitive visibility", "License policy", "EX:Rebuild or reproducibility check c"],
   gaps="Artifacts unsigned (no KMS), no vulnerability/secret scanning service, pk_core version unpinned."),
 "MC-026": dict(status="IMPLEMENTED", evidence=["pyproject.toml", "tools/build_backend.py", "tools/build.py", "evidence/gate.json (wheel install)"],
   x=["Packaging strategy", "Metadata", "`pk_core` dependency", "Runtime dependency", "Python policy", "Build backend", "Optional features", "Artifact contents", "Offline install", "Deterministic archive", "Smoke test"],
   p=["Build isolation", "Upgrade semantics", "EX:Clean-machine installation succeed", "EX:Version/runtime/dependency metadat"],
   gaps="No signature verification on install, uninstall/upgrade tests."),
 "MC-027": dict(status="IMPLEMENTED", evidence=["host/control.py", T+"test_ops.py::Controls", T+"test_integration.py::test_quota_quarantine_revocation"],
   x=["Control taxonomy", "Authorization", "Scope targeting", "Local kill switch", "Quarantine semantics", "In-flight operations", "Mutation freeze", "Policy rollback", "Audit", "Drill", "EX:Emergency revoke/quarantine reache"],
   p=["Artifact rollback", "Recovery", "Break-glass mode", "EX:Containment drills produce complet"],
   gaps="No two-person rule, partition behaviour or alerting; artifact (binary) rollback relies on release tooling."),
 "MC-028": dict(status="OPEN (template only)", evidence=["OWNERSHIP.md", "EXCEPTIONS.json"],
   x=[], p=["Severity model", "Runbooks", "Containment playbooks", "Exception process"],
   gaps="Named owners, on-call, escalation, reviews and drills must be supplied by the organisation."),
 "MC-029": dict(status="PARTIAL (enforced in code; legal sign-off open)", evidence=["PRIVACY_POLICY.md", "host/telemetry.py::PrivacyFilter", T+"test_ops.py"],
   x=["Data inventory", "Classification", "Minimization", "Pseudonymization", "Path policy", "Secret/content exclusion", "Configuration enforcement", "EX:Field-level inventory maps every c", "EX:Canary tests prove secret/content"],
   p=["Retention", "Regional routing", "Review cadence"],
   gaps="Retention/deletion enforcement, regional routing, access logging are policy text only."),
 "MC-030": dict(status="PARTIAL", evidence=["EDGE_CHARACTERIZATION.md", "evidence/bench.json"],
   x=["Offline operation", "No insecure fallback"], p=["Memory ceiling", "Restart behavior", "Replay recovery", "Capacity model", "Soak"],
   gaps="Power/thermal/battery measurements need physical edge hardware."),
 "MC-031": dict(status="IMPLEMENTED (unsigned)", evidence=["tools/gate.py", "TRACEABILITY.json", "evidence/EVIDENCE_MANIFEST.json"],
   x=["Requirement IDs", "Bidirectional matrix", "Code references", "Test references", "Security evidence", "Performance evidence", "Supply-chain evidence", "Immutable manifest", "Independent verifier", "Coverage gate", "Machine readability"],
   p=["Platform evidence", "Exception evidence", "Freshness rules", "EX:Automated verification reports zer", "EX:Independent reviewer can reproduce"],
   gaps="Manifest not signed; human approval step pending."),
 "MC-032": dict(status="PARTIAL (drafted; approvals pending)", evidence=["docs/adr/", "THREAT_MODEL.md"],
   x=["Adversary model", "ADR — runtime", "ADR — WASI/WIT target", "ADR — capability model", "ADR — filesystem", "ADR — error model", "ADR — audit", "Threat enumeration", "Control mapping", "Residual risk", "Security-test derivation", "EX:Every high-impact threat maps to a"],
   p=["System context", "Trust assumptions", "Abuse cases", "Security invariants", "Review triggers", "EX:Threat model contains explicit tru"],
   gaps="No ADRs for network/HTTP, identity, async/resource; ADR approval by named deciders pending."),
}
