"""Requirements traceability matrix for INV-27-C001..C100 (MC-015; C020).

    python -B -m inv27_unikernel_execution.tools.rtm [--check]

Each C requirement is traced through the missing components that cite it (ops/MC_STATUS_SOURCE.json)
to implementation refs, tests and waivers.  The 11 requirements no MC cites were established in v4.2.0
by the contract/README and are traced to those (ops/RTM_BASELINE.json).  Status:
  present  - every citing MC is verified_local (or baseline row with no blocker)
  partial  - at least one citing MC is partial, none blocked
  blocked  - at least one citing MC is blocked
Every ref must resolve; every non-present row names its waivers.  Writes evidence/RTM.json and ops/RTM.md.
"""
from __future__ import annotations

import json
import sys
from collections import Counter

from ._refs import ROOT, load, resolve


def build() -> tuple[dict, list[str]]:
    src, base, ck = load("ops/MC_STATUS_SOURCE.json"), load("ops/RTM_BASELINE.json"), load("CHECKLIST.json")
    errs, rows = [], []
    for item in ck["items"]:
        cid = item["check_id"]
        short = cid.split("-")[-1]
        mcs = [k for k, c in src["components"].items() if short in c["requirements"]]
        if mcs:
            sts = {src["components"][k]["status"] for k in mcs}
            status = "blocked" if "blocked" in sts else "partial" if "partial" in sts else "present"
            impl = sorted({r for k in mcs for r in src["components"][k]["implementation"]})
            tests = sorted({r for k in mcs for r in src["components"][k]["tests"]})
            blockers = sorted({b for k in mcs for b in src["components"][k]["blockers"]})
        else:
            b = base["rows"].get(cid)
            if b is None:
                errs.append(f"{cid}: not cited by any MC and no baseline row")
                continue
            status, impl, tests, blockers = b["status"], b["implementation"], b["tests"], b["blockers"]
        for r in impl + tests:
            why = resolve(r)
            if why:
                errs.append(f"{cid}: {why}")
        if status != "present" and not blockers:
            errs.append(f"{cid}: {status} without waiver")
        rows.append({"check_id": cid, "dimension": item["dimension"], "requirement": item["requirement"],
                     "missing_components": mcs, "status": status, "implementation": impl, "tests": tests,
                     "blockers": blockers})
    doc = {"schema": "PK_RTM/1", "component": "INV-27", "version": src["version"],
           "independence": "no row is independently reviewed; 'present' means verifiable in-archive, not accepted",
           "summary": dict(Counter(r["status"] for r in rows)), "rows": rows}
    return doc, errs


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    doc, errs = build()
    md = [f"# INV-27 RTM — v{doc['version']} (generated by tools/rtm.py)", "", f"Summary: {doc['summary']}", "",
          doc["independence"], "", "| ID | dimension | MCs | status | implementation | tests | waivers |", "|---|---|---|---|---|---|---|"]
    for r in doc["rows"]:
        md.append(f"| {r['check_id']} | {r['dimension']} | {', '.join(r['missing_components'])} | **{r['status']}** | "
                  f"{'<br>'.join('`%s`' % x for x in r['implementation'][:4])} | {'<br>'.join('`%s`' % x for x in r['tests'][:3])} | "
                  f"{', '.join(r['blockers'])} |")
    if "--check" not in argv:
        (ROOT / "evidence" / "RTM.json").write_text(json.dumps(doc, indent=1), encoding="utf-8")
        (ROOT / "ops" / "RTM.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    for e in errs:
        print("FAIL", e)
    print("RTM", "PASS" if not errs else "FAIL", json.dumps(doc["summary"]))
    return 0 if not errs else 1


if __name__ == "__main__":
    sys.exit(main())
