"""Generate docs/RUNBOOKS.md (component 56) from the bindings' runbook
fields, plus the shared escalation skeleton.  Escalation contacts are
UNASSIGNED on purpose: naming people is the owner's decision."""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
from gap09_unified_observability.components.checklist.bindings import C  # noqa: E402

HEAD = """# GAP-09 operator runbooks (component 56)

Generated by `tools/runbooks.py` from `checklist/bindings.py`. Escalation owner for every
entry: **UNASSIGNED** (component 56 stays BLOCKED until an owner and on-call rota are named).

## Shared procedure

1. **Identify** — read the stable error `code` (never parse messages). Codes: `malformed`,
   `unauthenticated`, `unauthorized`, `unverifiable`, `revoked`, `expired`,
   `dependency_unavailable`, `throttled`, `quota_exceeded`, `quarantined`, `corrupted`,
   `config_rejected`, `time_untrusted`, `replay_detected`, `reporter_untrusted`, `internal_error`.
2. **Contain** — `QuarantineRegistry.freeze(scope, name, reason=…, actor=…)` isolates a
   reporter, site or tenant without stopping unrelated ingestion.
3. **Preserve** — copy the audit ledger and record `AuditLedger.head()`; verify it against the
   last external anchor before any restart.
4. **Recover** — config `rollback()`; state `durable.restore()` (verifies digests first);
   replay a site with `ingest.reconcile()`.
5. **Close** — record the decision in the audit ledger and the waiver registry if a debt remains.

Security-sensitive validation never degrades to caller trust: if a trust dependency is down,
ingestion stops (`dependency_unavailable` / `time_untrusted`). That is the intended state.

## Per-component entries

| # | Component | Symptom | Action |
|---|---|---|---|
"""


def render() -> str:
    rows = []
    for cid, b in sorted(C.items()):
        if b["runbook"]:
            sym, act = b["runbook"]
            rows.append(f"| {cid} | {b['title']} | {sym} | {act} |")
    return HEAD + "\n".join(rows) + "\n"


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "RUNBOOKS.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(render())
    print(out)
