"""GENERATED by gen_bindings - do not edit.
generator: gap03-bindgen/1.0
python: 3.11+ (stdlib dataclasses only)
PK_FAIR_SHARE/1.0: sha256=dda511b54619c23721511710178c11aab8a3f7fe8f0c77d191c0ed3e25376550
PK_LOCALITY_COST/1.0: sha256=d16ac8972717ff3d36f343f05cacfaadbeb8105d1bf52bc015cc702d34c6a0d2
PK_TOPOLOGY/1.0: sha256=e5a14eda695d1fa40d672b8d87b93be6624fab4ff7ceb7b9c82d3d2e647e4bbe
PK_TOPOLOGY/1.1: sha256=f7abcc7fcb0e5b64d04f60168692fab0dfe12cd57aec6e6707a4f1f85e2dd904
"""
from __future__ import annotations

from dataclasses import dataclass, field

SCHEMA_DIGESTS = {
    'PK_FAIR_SHARE/1.0': 'dda511b54619c23721511710178c11aab8a3f7fe8f0c77d191c0ed3e25376550',
    'PK_LOCALITY_COST/1.0': 'd16ac8972717ff3d36f343f05cacfaadbeb8105d1bf52bc015cc702d34c6a0d2',
    'PK_TOPOLOGY/1.0': 'e5a14eda695d1fa40d672b8d87b93be6624fab4ff7ceb7b9c82d3d2e647e4bbe',
    'PK_TOPOLOGY/1.1': 'f7abcc7fcb0e5b64d04f60168692fab0dfe12cd57aec6e6707a4f1f85e2dd904',
}


@dataclass(frozen=True)
class PkFairShareV10:
    SCHEMA = 'PK_FAIR_SHARE/1.0'
    schema: str
    ledger_revision: int
    capacity: int
    tenant: str
    requested_slots: int
    allowed: bool
    reason: str
    reserved_slots: int
    held_slots: int
    state_token: str
    starved_tenants: list

    def to_wire(self) -> dict:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}

    @classmethod
    def from_wire(cls, obj: dict):
        from . import wire
        wire.validate(cls.SCHEMA, obj)
        return cls(**obj)


@dataclass(frozen=True)
class PkLocalityCostV10:
    SCHEMA = 'PK_LOCALITY_COST/1.0'
    schema: str
    topology_generation: int
    a: str
    b: str
    cost: int
    level: str

    def to_wire(self) -> dict:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}

    @classmethod
    def from_wire(cls, obj: dict):
        from . import wire
        wire.validate(cls.SCHEMA, obj)
        return cls(**obj)


@dataclass(frozen=True)
class PkTopologyV10:
    SCHEMA = 'PK_TOPOLOGY/1.0'
    schema: str
    environment: str
    generation: int
    nodes: list

    def to_wire(self) -> dict:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}

    @classmethod
    def from_wire(cls, obj: dict):
        from . import wire
        wire.validate(cls.SCHEMA, obj)
        return cls(**obj)


@dataclass(frozen=True)
class PkTopologyV11:
    SCHEMA = 'PK_TOPOLOGY/1.1'
    schema: str
    environment: str
    generation: int
    nodes: list
    provenance: str = ''

    def to_wire(self) -> dict:
        return {k: getattr(self, k) for k in self.__dataclass_fields__}

    @classmethod
    def from_wire(cls, obj: dict):
        from . import wire
        wire.validate(cls.SCHEMA, obj)
        return cls(**obj)
