"""Component specifications for MC-001..MC-046 (the source for docs/components/*.md).

Each spec is data, consumed by the certification runner for the templated
checks (CHK-001/003/004/005/016/019/020/021/022/023/024).  Invariants name the
exact tests that enforce them; the runner fails the check if a named test is
missing or did not pass.
"""
from __future__ import annotations

BOUNDARY = {
    "spoofing": "Callers authenticate with GAP03-ID/1 Ed25519 credentials; unknown issuer/kid/alg rejected (MC-012).",
    "tampering": "Canonical-JSON digests bind requests/artifacts; hash-chained WAL detects on-disk edits (MC-001/004).",
    "repudiation": "Privileged actions are written to the tamper-evident audit log before commit (MC-013).",
    "disclosure": "Error payloads, logs and explain output are redacted/pseudonymised (MC-014/020/024).",
    "dos": "Size/depth/cardinality bounds on every input; admission + rate limits (MC-001/025).",
    "elevation": "Least-privilege RBAC with two-person rule for high-blast-radius operations (MC-002/017).",
    "replay": "Single-use nonces with bounded cache; idempotency keys return the original outcome (MC-012/026).",
    "stale_state": "Generation / revision / fencing preconditions reject stale decisions (MC-004/005/006).",
    "cross_tenant": "Tenant-scoped reads; reservations of other tenants are never spendable (MC-003/005).",
}
LIBRARY = {k: f"Not applicable at this layer: in-process library without network ingress; {v}" for k, v in {
    "spoofing": "callers are the authenticated service boundary.",
    "tampering": "values are immutable (frozen dataclasses / tuples).",
    "repudiation": "decisions are recorded by the explain store of the caller.",
    "disclosure": "holds no tenant secrets; telemetry passes through privacy.sanitize.",
    "dos": "inputs are bounded by admission limits before reaching it.",
    "elevation": "exposes no privileged operation.",
    "replay": "pure function of its inputs; replay is harmless.",
    "stale_state": "keys/results include generations so stale inputs cannot match.",
    "cross_tenant": "never keys by tenant identity.",
}.items()}


def _i(name, protocol, auth, timeout, retry, failure):
    return {"name": name, "protocol": protocol, "auth": auth, "timeout": timeout, "retry": retry, "failure": failure}


INPROC = ("in-process call", "none (inside service boundary)", "caller deadline", "none", "raises SchedulerError")


def S(mc, title, modules, scope, non_goals, adjacent, interfaces, data_model, invariants, *, threats="boundary",
      threat_overrides=None, authz_na=None, crypto=("Not applicable - holds no keys; integrity via canonical digests.", False),
      sensitive="No tenant secrets; identifiers pseudonymised in telemetry.", fmea=None, concurrency=None, telemetry=(),
      runbook="runbooks/incident-response.md"):
    t = dict(BOUNDARY if threats == "boundary" else LIBRARY)
    t.update(threat_overrides or {})
    return {"mc": mc, "title": title, "modules": list(modules), "scope": scope, "non_goals": non_goals, "adjacent": adjacent,
            "interfaces": interfaces, "data_model": data_model, "invariants": invariants, "threats": t,
            "crypto": {"decision": crypto[0], "requires_external_kms": crypto[1]}, "sensitive": sensitive,
            "fmea": fmea or [], "concurrency": concurrency or "", "telemetry": list(telemetry), "runbook": runbook,
            "authz_na": authz_na}


FM_STORE = [("crash mid-write", "torn tail truncated on recovery; unacknowledged op never visible", "fail-closed"),
            ("disk full / read-only", "store flips read-only, writes refused with DEPENDENCY_UNAVAILABLE", "fail-closed"),
            ("corrupt record mid-log", "recovery refuses with INTEGRITY_FAILURE", "fail-closed"),
            ("duplicate delivery", "idempotency key returns original outcome", "safe"),
            ("stale writer", "fencing token / generation precondition rejects", "fail-closed"),
            ("operator error", "all mutations audited; restore from verified backup (MC-042)", "recoverable")]
FM_ADAPTER = [("dependency unavailable", "breaker opens; fallback per degraded MATRIX", "per-matrix"),
              ("timeout", "retry only transient codes within deadline", "bounded"),
              ("malformed / unknown version", "rejected before side effects", "fail-closed"),
              ("stale data", "TTL expiry -> treated as absent, never sufficient", "fail-closed"),
              ("duplicate / reordered", "revision ordering + request-id dedup", "safe")]
FM_LIB = [("invalid input", "raises SchedulerError INVALID_ARGUMENT", "fail-closed"),
          ("overload", "bounded by admission before invocation", "bounded")]
CONC_STORE = "Single writer per store under an RLock; cross-process ownership via fencing tokens (MC-006); every op idempotent by op_id; no internal retries - callers use MC-026."
CONC_LIB = "Pure/immutable; safe for concurrent use; no retries or cancellation state."

SPECS = [
    S("MC-001", "Versioned wire schemas", ["controlplane/wire.py", "controlplane/canonical.py", "controlplane/bindings.py", "controlplane/gen_bindings.py"],
      "Normative GAP03-IDL/1 schemas, bounded parser, canonical serialization, registry, negotiation, migration for PK_TOPOLOGY/1, PK_LOCALITY_COST/1, PK_FAIR_SHARE/1.",
      "Transport binding (HTTP/gRPC framing) and authentication of the carrying channel.", "Transport + identity: MC-012; peers own their emitted payloads.",
      [_i("PK_TOPOLOGY/1.1", "canonical JSON application/vnd.pk.topology.v1+json", "signed envelope (MC-012) when crossing trust boundary", "caller deadline", "idempotent read", "UNSUPPORTED_VERSION / INVALID_ARGUMENT"),
       _i("PK_LOCALITY_COST/1.0", "canonical JSON", "as above", "caller deadline", "idempotent", "INVALID_ARGUMENT"),
       _i("PK_FAIR_SHARE/1.0", "canonical JSON", "as above", "caller deadline", "idempotent", "INVALID_ARGUMENT")],
      "Schema {id, major, minor, media_type, reserved[], fields{type, unit, min, max, max_len, pattern, enum, required, default, since}}; payload identity = sha256(canonical bytes).",
      [("Malformed/duplicate/NaN/over-depth/over-size payloads never reach scheduling logic", "test_mc001_parser_rejects_malformed_and_adversarial"),
       ("Canonical encoding is unique per value", "test_mc001_canonical_serialization_is_deterministic"),
       ("Minor versions are additive only", "test_mc001_compatibility_gate_and_api_reference"),
       ("Generated bindings match the schema digests", "test_mc001_generated_bindings_in_sync_and_pinned")],
      fmea=FM_LIB + [("unknown peer version", "negotiation fails before side effects", "fail-closed")], concurrency=CONC_LIB,
      telemetry=["gap03_requests_total"], runbook="runbooks/schema.md",
      authz_na="schemas/parsers expose no privileged operation; authorization happens at the carrying service boundary (MC-002/MC-012)"),
    S("MC-002", "Authenticated topology mutation boundary", ["controlplane/topology_service.py", "controlplane/authz.py"],
      "Only authenticated, authorized, integrity-bound, audited, rate-limited, CAS-guarded topology mutations reach the durable topology store.",
      "Discovering hardware (GAP-02); node lifecycle ownership.", "Identity MC-012, store MC-004, audit MC-013.",
      [_i("TopologyService.mutate", "request + GAP03-ID/1 credential (req digest claim)", "Ed25519 token, aud gap03.topology; approvals aud gap03.topology.approve", "caller deadline", "idempotent by (sub, request_id)", "GAP03-ERR/1 external payload")],
      "Request {request_id, source_service, reason, expected_generation, mutations[{op, id, node_type, parent, labels, lifecycle, replace}]}.",
      [("No unauthenticated or unbound request mutates topology", "test_mc002_request_integrity_binding"),
       ("Re-parent needs a second, distinct approver", "test_mc002_rbac_and_two_person_rule_for_reparent"),
       ("Stale or invalid batches leave no partial state", "test_mc002_stale_generation_and_invalid_batch_roll_back_atomically"),
       ("No privileged mutation without an audit record", "test_mc002_audit_unavailable_blocks_mutation")],
      authz_na=None, crypto=("Ed25519 request credentials + approvals; keys held by reference; production custody in HSM/KMS.", True),
      fmea=[("audit down", "mutation refused", "fail-closed"), ("identity down", "mutation refused", "fail-closed"),
            ("stale generation", "STALE_STATE, client re-reads", "fail-closed"), ("mutation storm", "per-principal/global buckets", "bounded")],
      concurrency=CONC_STORE, telemetry=["gap03_topology_mutations_total"], runbook="runbooks/topology.md"),
    S("MC-003", "Tenant entitlement / reservation authority", ["controlplane/entitlement.py"],
      "Authoritative, normalised, CAS-versioned, signed entitlement snapshots with revocation/expiry and ledger reconciliation.",
      "Billing, quota purchase workflow, provisioning capacity to satisfy a share.", "Ledger MC-005 consumes snapshots; audit MC-013.",
      [_i("EntitlementAuthority.write", "in-process API behind service boundary", "principal with entitlement.write", "caller deadline", "CAS on revision", "PERMISSION_DENIED/STALE_STATE/FAIRNESS_DENIED"),
       _i("snapshot()", "GAP03-ENT/1 signed artifact", "Ed25519 artifact signature", "n/a", "idempotent", "UNAUTHENTICATED on verify")],
      "Record {tenant, dimension=slots, unit=slot, reserved, hard_limit, valid_from, expires_at, revision, revoked, issuer}; estate {capacity, oversubscription{ratio_ppm, approval}}.",
      [("Aggregate reservations never exceed approved limit", "test_mc003_aggregate_limit_and_approved_oversubscription"),
       ("Revoked/expired entitlement authorizes nothing", "test_mc003_revocation_and_expiry_stop_new_claims"),
       ("Concurrent updates: exactly one wins per revision", "test_mc003_concurrent_updates_cas")],
      crypto=("Ed25519-signed snapshots; signer key custody in HSM/KMS.", True), fmea=FM_STORE, concurrency=CONC_STORE,
      telemetry=["gap03_reconciliation_drift_total"], runbook="runbooks/fairness.md"),
    S("MC-004", "Durable topology state store", ["controlplane/topology_store.py", "controlplane/durable.py"],
      "Crash-safe, constraint-enforcing, generation-CAS topology storage with migrations, snapshots, export/import.",
      "Replication (requires a quorum volume or engine swap - blocked).", "Mutation boundary MC-002; fencing MC-006.",
      [_i("TopologyStore.submit(batch)", "WAL op", "fenced by coordination token", "fsync-bound", "none (callers retry idempotently)", "STALE_STATE/CONFLICT/FENCED/INTEGRITY_FAILURE")],
      "nodes{id: {type in region|site|rack|node, parent, labels<=32, lifecycle, rev}}, generation, fence; WAL {seq, ts, prev, op, hash}.",
      [("No orphan/cycle/type-violating topology can be persisted", "test_mc004_storage_constraints_reject_invalid_topology"),
       ("Acknowledged mutations survive crash; unacknowledged never visible", "test_mc004_crash_during_write_recovers_without_half_applied_state"),
       ("Superseded writer rejected", "test_mc004_fenced_writes_reject_superseded_writer")],
      fmea=FM_STORE, concurrency=CONC_STORE, telemetry=["gap03_stale_rejections_total"], runbook="runbooks/topology.md"),
    S("MC-005", "Durable fair-share ledger", ["controlplane/ledger_store.py"],
      "Durable claims (pending/committed/released/aborted/expired) enforcing capacity + reservation invariants at the store boundary.",
      "Placement decision (SCH-01); entitlement authorship (MC-003).", "Commit protocol MC-007; entitlement MC-003.",
      [_i("LedgerStore.submit(prepare|commit|abort|release|reclaim_expired|reconcile)", "WAL op", "fencing token", "fsync-bound", "idempotent by op_id", "GAP03-ERR/1 outcome")],
      "capacity, reserved{tenant}, entitlement_generation, fence, claims{id: {tenant, slots, state, owner, fence, expires_at, txn}}, outcomes{op_id}.",
      [("used <= capacity and >= 0 always", "test_mc005_store_boundary_enforces_fairness_and_capacity"),
       ("Replayed op never double-consumes", "test_mc005_idempotent_claim_ids"),
       ("Concurrent claims are linearizable", "test_mc005_concurrent_claims_linearizable")],
      fmea=FM_STORE, concurrency=CONC_STORE, telemetry=["gap03_orphaned_reservations", "gap03_fairness_denials_total"],
      runbook="runbooks/transactions.md"),
    S("MC-006", "Distributed coordination / leader fencing", ["controlplane/coordination.py"],
      "Majority lease, monotonic fencing tokens, safety-margin expiry, drain, status.",
      "Consensus implementation itself (production backing store is blocked).", "Every mutable store validates tokens.",
      [_i("LeaseReplica.request", "lease RPC (reference impl in-process)", "replica identity (mTLS in production - blocked)", "bounded attempts", "max_attempts, no storm", "ConnectionError -> not granted")],
      "replica record {term, holder, expires}; coordinator {term, deadline, role, draining}.",
      [("Two replicas never both hold a valid fencing token for protected writes", "test_mc006_stale_leader_cannot_mutate_under_asymmetric_partition"),
       ("Tokens strictly increase across leadership changes", "test_mc006_quorum_lease_and_monotonic_fencing")],
      fmea=[("partition", "minority side loses lease at deadline - margin", "fail-closed"), ("clock skew < margin", "safe by margin", "safe"),
            ("quorum loss", "no leader; commits blocked", "fail-closed")], concurrency="Coordinator guarded by RLock; bounded acquire attempts.",
      telemetry=["gap03_coordination_is_leader", "gap03_coordination_term"], runbook="runbooks/split-brain.md"),
    S("MC-007", "Distributed atomic placement commit protocol", ["controlplane/transactions.py"],
      "Saga with fenced idempotent journal binding immutable decision inputs; UNKNOWN resolution by downstream status.",
      "Final node selection policy (SCH-01).", "Ledger MC-005, SCH-01 MC-008, controls MC-017.",
      [_i("PlacementCoordinator.place/recover_all", "in-process orchestrator", "leader fencing token", "per-txn deadline", "idempotent by txn id", "terminal state record")],
      "txn {state BEGIN|PREPARED|UNKNOWN|COMMITTED|ABORTED, inputs{workload, candidate digest, generations, tokens, scoring version}, node, history}.",
      [("Committed txn <=> committed claim <=> downstream placement", "test_mc007_commit_binds_immutable_inputs"),
       ("Same txn id returns prior terminal state", "test_mc007_idempotent_steps_return_prior_terminal_state"),
       ("In-doubt transactions converge after crash", "test_mc007_crash_after_prepare_recovers_deterministically")],
      fmea=[("lost response", "UNKNOWN -> status query", "safe"), ("downstream refusal", "abort = compensation", "safe"),
            ("leader change", "old fence rejected everywhere", "fail-closed")], concurrency=CONC_STORE,
      telemetry=["gap03_placement_txn_total", "gap03_idempotent_replays_total"], runbook="runbooks/transactions.md"),
    S("MC-008", "SCH-01 integration", ["controlplane/adapters/sch01.py"],
      "Lossless GAP-03 -> SCH-01 request mapping, correlation, selection guard, error taxonomy + compensation, version negotiation.",
      "SCH-01 internals.", "SCH-01 owns final placement and lifecycle.",
      [_i("SCH01-PLACE/1.1 place/status/release", "SCH-01 RPC (conformance harness here)", "mTLS workload identity (production)", "per-txn deadline", "idempotent by txn", "SCH_ERRORS map")],
      "request {protocol, version, txn, idempotency_key, fence, traceparent, tenant, slots, topology_generation, ranked[], infeasible{}, fairness{}}.",
      [("SCH-01 cannot select an infeasible node without override", "test_mc008_sch01_cannot_bypass_hard_constraints"),
       ("Unsupported major rejected before side effects", "test_mc008_version_negotiation_before_side_effects")],
      fmea=FM_ADAPTER, concurrency="Harness is single-threaded; adapter stateless.", telemetry=["gap03_placement_txn_total"],
      runbook="runbooks/transactions.md"),
    S("MC-009", "GAP-02 hardware-capability feed", ["controlplane/adapters/gap02.py"],
      "Normalise, bind, freshness-gate and attest hardware facts; hard predicates; drift reconciliation.",
      "Hardware discovery itself.", "GAP-02 owns discovery.",
      [_i("GAP02-INV/1 report", "canonical JSON", "producer identity + attestation for security claims", "TTL 300 s", "revision ordering", "INVALID_ARGUMENT/STALE_STATE/CONFLICT")],
      "{device_id, node, isa, cpus, memory_mib, accelerators[], claims{tee}, generation, observed_at, source, attestation}.",
      [("Unknown or stale capability is never sufficient", "test_mc009_stale_unknown_never_sufficient_and_hard_predicates"),
       ("Security claims require verified attestation", "test_mc009_tee_claim_requires_attestation")],
      crypto=("Attestation reports verified with Ed25519 (identity.verify_attestation); hardware roots of trust are external.", True),
      fmea=FM_ADAPTER, concurrency=CONC_LIB, telemetry=["gap03_reconciliation_drift_total"], runbook="runbooks/reconciliation.md"),
    S("MC-010", "GAP-14 data-gravity", ["controlplane/adapters/gap14.py"],
      "Authenticated, revisioned data-location anchors converted into a bounded soft objective.",
      "Data residency policy ownership.", "GAP-14 owns data location.",
      [_i("GAP14-GRAV/1 anchor", "canonical JSON signed artifact", "Ed25519 artifact signature", "TTL 900 s", "revision ordering", "NOT_IN_TOPOLOGY/STALE_STATE/CONFLICT")],
      "{scoped id, tenant, replicas[{node, bytes}], reads_per_h, revision, observed_at, source, residency_hard}.",
      [("Replicas are alternatives (min), never summed", "test_mc010_fixture_suite"),
       ("Gravity is soft unless residency is hard", "test_mc010_scoped_ids_and_soft_unless_hard_residency")],
      sensitive="Dataset names never leave the adapter: keyed-hash scoped ids in telemetry.", fmea=FM_ADAPTER, concurrency=CONC_LIB,
      telemetry=["gap03_adapter_ingest_total"]),
    S("MC-011", "PLN-05 elasticity/demand", ["controlplane/adapters/pln05.py"],
      "Advisory demand signals with confidence/freshness gating, debounce, hysteresis, LKG fallback.",
      "Capacity provisioning.", "PLN-05 owns forecasts.",
      [_i("PLN05-DEMAND/1", "canonical JSON", "producer identity", "TTL 600 s + LKG 1800 s", "request-id dedup", "INVALID_ARGUMENT/UNSUPPORTED_VERSION")],
      "{request_id, tenant, resource_class=slots, unit, quantity, confidence, observed_at, revision}.",
      [("Demand can never override hard gates", "test_mc011_advisory_debounce_fallback_no_double_count"),
       ("Outage cannot create unbounded retries", "test_mc011_outage_cannot_cause_unbounded_retries")],
      fmea=FM_ADAPTER, concurrency=CONC_LIB, telemetry=["gap03_adapter_ingest_total"]),
    S("MC-012", "Identity, attestation, provenance", ["controlplane/identity.py", "controlplane/ed25519.py"],
      "SPIFFE-style identities, Ed25519 tokens/artifacts, trust store with rotation/revocation, replay protection, attestation.",
      "Certificate issuance / workload attestation infrastructure (external).", "Issuers are external trust roots.",
      [_i("TrustStore.verify_token", "GAP03-ID/1 token", "self", "n/a", "n/a", "UNAUTHENTICATED/REPLAY_DETECTED"),
       _i("sign_artifact/verify_artifact", "statement + Ed25519 signature", "self", "n/a", "n/a", "UNAUTHENTICATED/INTEGRITY_FAILURE")],
      "claims {alg, iss, kid, sub, aud, roles, iat, nbf, exp, nonce, req?}; key {kid, public, not_before, not_after, revoked}.",
      [("Only Ed25519 accepted (no downgrade)", "test_mc012_token_verification_negative_matrix"),
       ("Revoked key / removed root stops verifying immediately", "test_mc012_rotation_overlap_revocation_and_root_removal"),
       ("Signature implementation matches RFC 8032", "test_mc012_ed25519_rfc8032_vector")],
      crypto=("Ed25519 only; keys by reference (env:/file:); HSM/KMS custody and mTLS transport are production requirements.", True),
      sensitive="Private keys never in repr/logs/config dumps.", fmea=[("trust store unavailable", "all verification fails closed", "fail-closed"),
          ("key compromise", "revoke kid; verification stops immediately; audited", "fail-closed"),
          ("replay", "nonce cache rejects; full cache fails closed", "fail-closed"),
          ("clock skew", "bounded +-30 s window; beyond it tokens are refused", "fail-closed")], telemetry=["gap03_trust_verifications_total"],
      concurrency="Replay cache under a lock; bounded; full cache fails closed (OVERLOADED).", runbook="runbooks/security.md"),
    S("MC-013", "Tamper-evident security audit log", ["controlplane/audit.py"],
      "Separate append-only hash-chained audit store with signed checkpoints, redaction, holds, authorized query/export, continuous verify.",
      "SIEM storage/WORM media (external).", "Consumers: security team, exit gate.",
      [_i("AuditLog.append/query/export/verify", "in-process", "audit.read / audit.export roles", "fsync-bound", "none", "DEPENDENCY_UNAVAILABLE fails caller closed")],
      "event {event_id, actor, action, target, result, reason, ts_wall, ts_mono_ns, clock_source, clock_uncertainty_ms, request_id, generation, before/after digests, detail}.",
      [("Any edit to history is detected", "test_mc013_tamper_detection_and_alert"),
       ("Audit write failure blocks the privileged action", "test_mc002_audit_unavailable_blocks_mutation")],
      crypto=("SHA-256 chain + Ed25519 checkpoint signatures; signer custody in HSM/KMS.", True), fmea=FM_STORE, concurrency=CONC_STORE,
      telemetry=["gap03_audit_write_failures_total"], runbook="runbooks/audit.md"),
    S("MC-014", "Error model", ["controlplane/errors.py"],
      "Versioned GAP03-ERR/1 code catalog, single mapping boundary, transport mapping, redaction, bounded cause chain.",
      "Client retry implementation.", "All boundaries use to_external().",
      [_i("to_external()", "structured error payload", "n/a", "n/a", "retryable flag + retry_after_s", "INTERNAL for unknown")],
      "code {code, category, http_status, grpc_status, retryable, retry_after_s, severity, owner, template, stability} + aliases.",
      [("Stack traces/class names never cross the boundary", "test_mc014_golden_mapping_of_every_public_failure"),
       ("Cause depth bounded, payload redacted", "test_mc014_payloads_redacted_and_cause_depth_bounded")],
      threats="library", fmea=FM_LIB, concurrency=CONC_LIB, telemetry=["gap03_requests_total"]),
    S("MC-015", "Configuration subsystem", ["controlplane/config.py"],
      "Typed schema, precedence, signed documents, whole-snapshot transactional activation, rollback, redaction.",
      "Secret storage (references only).", "Consumers read ConfigManager.current.",
      [_i("ConfigManager.activate/rollback/dry_run", "in-process API", "config.write principal (service boundary)", "fsync-bound", "CAS on generation", "INVALID_ARGUMENT/STALE_STATE/PERMISSION_DENIED")],
      "snapshot {generation, digest, activated_at, actor, source, values{section{key}}}; history keyed by generation.",
      [("Workers only ever see whole snapshots", "test_mc015_concurrent_updates_and_partial_source_failure"),
       ("Safety changes need explicit risk acknowledgement", "test_mc015_dry_run_risk_ack_and_redaction")],
      crypto=("Signed config documents verified with Ed25519; secrets are secret:// references.", False), fmea=FM_STORE,
      concurrency=CONC_STORE, runbook="runbooks/config.md", telemetry=["gap03_config_activations_total"]),
    S("MC-016", "Degraded-mode / failover policy", ["controlplane/degraded.py"],
      "Dependency x operation fail-open/closed matrix, stale TTLs, overrides, recovery ordering with reconciliation gate.",
      "Automated site failover orchestration (policy only).", "Health MC-018 reports it.",
      [_i("DegradedPolicy.decide/require/override", "in-process", "degraded.override break-glass", "n/a", "n/a", "DEPENDENCY_UNAVAILABLE")],
      "status{dep: up, since, last_good, generation}; overrides[{dependency, op, scope, expires, actor, risk_ack}].",
      [("Commits blocked whenever integrity/ownership cannot be proven", "test_mc016_matrix_complete_and_commit_blocked_without_proof"),
       ("Overrides are scoped and expire", "test_mc016_override_scoped_authorized_audited_expiring")],
      fmea=[("dependency flapping", "reconciliation gate before commit resumes", "fail-closed"),
            ("partition", "commit-critical dependencies unreachable -> commits blocked, explain stays up", "fail-closed"),
            ("stale cache beyond TTL", "operation refused per matrix", "fail-closed"),
            ("operator error (bad override)", "scoped + expiring + audited; identity/audit/coordination not overridable", "bounded")], concurrency=CONC_LIB,
      telemetry=["gap03_dependency_up"], runbook="runbooks/degraded-mode.md"),
    S("MC-017", "Freeze / quarantine / disable controls", ["controlplane/controls.py"],
      "Durable scoped controls (7 scopes, 5 modes) checked in scoring and commit paths, with drain, OCC and idempotency.",
      "Incident management tooling.", "Placement coordinator re-checks before commit.",
      [_i("Controls.create/extend/clear/check", "in-process API", "control.write; hard-stop needs break-glass + dual approval", "fsync-bound", "idempotent by control_id", "FROZEN/PERMISSION_DENIED/STALE_STATE")],
      "control {scope, value, mode, reason, ticket, actor, created_at, expires_at, cleared, drain_deadline, approvers}.",
      [("A freeze landing between prepare and commit blocks the commit", "test_mc017_freeze_after_prepare_is_revalidated_before_commit"),
       ("Controls survive restart and expire on time", "test_mc017_persistence_expiry_idempotency_occ")],
      fmea=FM_STORE, concurrency=CONC_STORE, telemetry=["gap03_control_blocks_total"], runbook="runbooks/controls.md"),
    S("MC-018", "Health / readiness endpoints", ["controlplane/health.py"],
      "livez/startupz/readyz/deep endpoints with deadlines, hysteresis, authorization for diagnostics.",
      "Orchestrator configuration.", "Load balancer / deployment gates consume readyz.",
      [_i("/livez /startupz /readyz /healthz/deep", "HTTP/1.1 JSON", "Bearer token for deep", "250 ms probe deadline", "n/a", "503/403")],
      "readiness {status, failing[]}; deep {version, generations, coordination, dependencies, slo}.",
      [("A hung dependency cannot block the probe", "test_mc018_hung_dependency_cannot_block_probe"),
       ("Readiness means safe-to-commit, liveness means process", "test_mc018_distinct_probes_and_readiness_semantics")],
      fmea=[("dependency hang", "probe times out -> not ready", "fail-closed"), ("dependency flap", "hysteresis: 2 good to ready, 1 bad to not-ready", "fail-safe"),
            ("overload", "bounded pool, 250 ms deadline", "bounded"), ("shutdown", "readiness drops before exit", "fail-safe")],
      concurrency="Bounded worker pool; hysteresis state under lock.", telemetry=["gap03_health_probe_total"]),
    S("MC-019", "Metrics exporter", ["controlplane/metrics.py"], "Versioned catalog, Prometheus exposition, cardinality budgets, recording rules.",
      "Metrics backend.", "Scraped by Prometheus/OTel collector.",
      [_i("Metrics.export()", "Prometheus text 0.0.4", "scrape auth at ingress (deployment)", "n/a", "n/a", "n/a")],
      "catalog {name: (type, unit, labels, budget, owner, help)}.",
      [("Label sets are bounded; forbidden identifiers rejected", "test_mc019_cardinality_budget_and_forbidden_labels")],
      threats="library", fmea=FM_LIB, concurrency="O(1) updates under a short lock; export is a read."),
    S("MC-020", "Structured logging", ["controlplane/logpipe.py"], "Stable JSON log schema, event taxonomy, injection-safe, redacted, bounded buffer.",
      "Log shipping backend.", "Sink is injected.",
      [_i("Logger.log/flush", "JSON lines GAP03-LOG/1", "n/a", "non-blocking", "drop with counter", "dropped count")],
      "record {schema, ts, severity, event, code, service, version, instance, request_id, trace_id, ...sanitised fields}.",
      [("Log lines cannot be split/forged by input", "test_mc020_injection_and_redaction")], threats="library", fmea=FM_LIB,
      concurrency="Deque under lock; sink outside lock."),
    S("MC-021", "Distributed tracing", ["controlplane/tracing.py"], "W3C trace context validation/propagation, span taxonomy, sampling, outage fallback.",
      "Trace backend.", "Exporter injected.",
      [_i("traceparent/tracestate/baggage", "W3C Trace Context L1", "n/a", "n/a", "n/a", "invalid -> fresh trace")],
      "span {name, trace_id, span_id, parent_id, attrs(allow-listed), status, txn, duration_ms}.",
      [("Untrusted headers never adopted when malformed", "test_mc021_invalid_headers_and_baggage_limits")], threats="library", fmea=FM_LIB,
      concurrency="contextvars propagation; wrap() for threads."),
    S("MC-022", "Operator explain API", ["controlplane/explain.py"], "Immutable decision records, scoped query, audited access, non-mutating replay.",
      "UI rendering.", "Operators, tenants (own records only).",
      [_i("Explain.query/replay", "in-process API", "explain.read or own-tenant", "rate limited", "n/a", "PERMISSION_DENIED/OVERLOADED/INVALID_ARGUMENT")],
      "record {txn, tenant, workload_ref, inputs, candidates, tie_break, hard_filter, soft_components, sources, fairness, snapshot_ref, snapshot}.",
      [("Replay of identical inputs is identical", "test_mc022_replay_determinism_and_divergence_flag")], fmea=FM_STORE, concurrency=CONC_STORE,
      telemetry=["gap03_explain_queries_total"]),
    S("MC-023", "Dashboards and alerts", ["controlplane/alerts.py"], "Alerts/dashboards as code, classified, multi-window burn, runbook-linked, rehearsable.",
      "Alertmanager routing.", "SRE.", [_i("ALERTS/DASHBOARD", "data", "n/a", "n/a", "n/a", "n/a")], "alert {alert, class, severity, windows|signal, threshold, for_s, owner, runbook, escalation, first_diagnostics}.",
      [("Every alert has owner, severity and an existing runbook", "test_mc043_runbook_content_and_alert_links")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-024", "Telemetry privacy/retention/export", ["controlplane/privacy.py"], "Field classification, pseudonymisation, redaction, retention, export allow-list, offboarding.",
      "Legal DPA negotiation.", "All telemetry passes sanitize().", [_i("sanitize/check_export", "in-process", "n/a", "n/a", "n/a", "PERMISSION_DENIED")],
      "FIELD_CLASS, ALLOWED_IDS per signal, RETENTION_DAYS per class.",
      [("No confidential identifier reaches metrics", "test_mc024_classification_and_sanitize")], threats="library", fmea=FM_LIB,
      sensitive="This component IS the sensitive-data policy.", concurrency=CONC_LIB),
    S("MC-025", "Admission / shedding / breakers", ["controlplane/admission.py"], "Independent limits, tenant isolation, priority shedding, reserved control pool, breakers.",
      "Autoscaling.", "Service facade calls admit().", [_i("Admission.admit / CircuitBreaker.call", "in-process", "n/a", "n/a", "retry-after hint", "OVERLOADED/PAYLOAD_TOO_LARGE")],
      "limits {global_rps, tenant_rps, max_candidates, max_concurrent_scoring/commits, max_queue, reserved_control_slots, shed_threshold}.",
      [("Control-plane ops are admitted even at saturation", "test_mc025_priority_shedding_and_reserved_control_pool")], threats="library", fmea=FM_LIB,
      concurrency="Counters under lock; releasers idempotent.", telemetry=["gap03_admission_rejected_total", "gap03_breaker_state"], runbook="runbooks/overload.md"),
    S("MC-026", "Retry / backoff / idempotency", ["controlplane/retry.py"], "Operation classes, deadline budgets, full-jitter backoff, dedup, lost-response probe, budgets, poison quarantine.",
      "Transport-level retries.", "Adapters and commit path.", [_i("Retrier.run", "in-process", "n/a", "end-to-end deadline", "self", "DEADLINE_EXCEEDED/OVERLOADED")],
      "policy {max_attempts, base_s, cap_s, attempt_timeout_s, budget_ratio, budget_min, poison_after}.",
      [("Non-retryable codes are never retried", "test_mc026_only_transient_codes_retried"), ("Lost responses are probed before re-issue", "test_mc026_idempotency_and_lost_response_probe")],
      threats="library", fmea=FM_LIB, concurrency="Budget/dedup under locks.", telemetry=["gap03_retry_attempts_total", "gap03_retry_budget_exhausted_total"]),
    S("MC-027", "Latency refinement", ["controlplane/latency.py"], "Authenticated directional samples, EWMA, outlier/rate limits, TTL/confidence, class-band clamp.",
      "Probe infrastructure.", "Node probes produce samples.", [_i("LatencyEngine.ingest/refined_cost", "sample {src,dst,rtt_us,ts,sample_id}", "producer must own src", "TTL 120 s", "dedup by sample_id", "PERMISSION_DENIED/INVALID_ARGUMENT")],
      "pair (src,dst) {ewma, n, raw<=32, last, suspect, suspects}.",
      [("Measurement never moves a cost across locality classes", "test_mc027_never_crosses_class_and_directional"), ("Spikes cannot poison the estimate", "test_mc027_poisoning_route_change_stale_sparse")],
      fmea=FM_LIB + [("stale/sparse", "static fallback", "safe")], concurrency="Called under the service's scoring path; state bounded LRU.",
      telemetry=["gap03_latency_samples_total"]),
    S("MC-028", "Topology/cost cache", ["controlplane/cache.py"], "Generation-namespaced LRU with TTL, single-flight, immutable values; never caches fairness.",
      "Distributed cache.", "Scoring facade.", [_i("ScoreCache.get_or_compute", "in-process", "n/a", "5 s single-flight wait", "n/a", "compute errors propagate")],
      "key (topology_gen, config_gen, schema, scoring_version, anchor, candidates digest, spread digest) -> (ts, tuple).",
      [("Cached ranking == reference ranking", "test_mc033_topology_properties_and_reference_ranking")], threats="library", fmea=FM_LIB,
      concurrency="Lock + per-key Event single-flight.", telemetry=["gap03_cache_events_total"]),
    S("MC-029", "Multi-objective composition", ["controlplane/objectives.py"], "Integer weighted composition of normalised soft objectives; hard gates outside; lexicographic spread.",
      "Policy authoring UI.", "Scoring facade.", [_i("compose()", "in-process", "n/a", "n/a", "n/a", "ValueError on invalid weights")],
      "Composite {node, total, components, weights, feasible, hard_failures}; formula gap03-score/2.",
      [("Hard-infeasible candidates never outrank feasible ones", "test_mc029_hard_gates_outside_sum_missing_signals_tiebreak")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-030", "Capacity / saturation model", ["controlplane/capacity.py"], "Measured linear service-time fit, Erlang-C wait, single-leader commit ceiling, envelopes, recalibration.",
      "Autoscaler implementation.", "Operators / SRE.", [_i("fit/plan/envelope/recalibrate", "in-process", "n/a", "n/a", "n/a", "n/a")],
      "model {base_us, per_candidate_us, rmse_us}.", [("Model is fitted from measurement, not assumed", "test_mc030_fit_from_measurement")], threats="library",
      fmea=FM_LIB, concurrency=CONC_LIB, runbook="runbooks/capacity.md"),
    S("MC-031", "Benchmark baseline + regression gate", ["benchmarks/harness.py", "benchmarks/thresholds/"], "Matrix harness, metadata, percentiles, thresholds, gate, trend.",
      "Controlled runner hardware (blocked).", "CI.", [_i("python -m ...benchmarks.harness --gate", "CLI + JSON", "n/a", "n/a", "n/a", "exit 1 on regression")],
      "result {id, p50..p99, max, stdev, throughput, peak_mem_kib, checksum}; thresholds {status, cases{id: p99, mem, budget}}.",
      [("Regression beyond budget fails unless waived", "test_mc031_gate_fails_on_regression_unless_waived")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-032", "Fault-injection suite", ["controlplane/faults.py", "tests/cp/test_mc032_033_035_robustness.py"], "Deterministic crash/partition/skew/chaos harness with invariant assertions.",
      "Production chaos tooling.", "CI.", [_i("StoreFault/ManualClock/Network/Chaos/invariants", "in-process", "n/a", "n/a", "n/a", "n/a")],
      "invariants {no_capacity_overcommit, no_negative_usage, ledger_chain_ok, no_committed_without_placement, ledger_matches_journal, audit_chain_ok, topology_valid}.",
      [("Every scenario ends with all safety invariants true", "test_mc032_crash_points_in_every_phase")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-033", "Fuzz / property / adversarial tests", ["controlplane/fuzz.py", "tests/fuzz_corpus/"], "Seeded mutational fuzzing with minimisation + regression corpus; property + differential tests.",
      "Coverage-guided fuzzing engine.", "CI.", [_i("fuzz.run", "in-process", "n/a", "per-input time limit", "n/a", "findings list")],
      "finding {input hex, why, iteration|regression}.", [("Parsers raise only SchedulerError on any input", "test_mc033_fuzz_parsers_no_findings")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-034", "Adjacent contract fixtures", ["controlplane/fixtures/"], "Versioned fixture sets per adjacent service with required classes; deterministic harness.",
      "Owning the adjacent schemas.", "GAP-02/GAP-14/PLN-05/SCH-01 owners.", [_i("fixtures/*.json", "JSON", "n/a", "n/a", "n/a", "n/a")],
      "fixture {adapter, schema, versions_tested, owner_repo, cases[{name, class, input, expect|error}]}.",
      [("Every adapter has positive/boundary/malformed/unsupported fixtures", "test_mc034_fixture_sets_cover_required_classes")], threats="library", fmea=FM_ADAPTER, concurrency=CONC_LIB),
    S("MC-035", "Compatibility matrix + CI", ["controlplane/compat.py", "ci/matrix.yml"], "Declared runtime/protocol/adjacent matrix and startup guard.",
      "CI runners (blocked).", "Release engineering.", [_i("compat.check()", "in-process at startup", "n/a", "n/a", "n/a", "UNSUPPORTED_VERSION")],
      "MATRIX {python, os, arch, schemas, adjacent, dependencies, unsupported}.", [("Unsupported combinations refuse to start", "test_mc035_matrix_and_startup_guard")],
      threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-036", "Owner and escalation metadata", ["governance/OWNERS.json", "governance/CODEOWNERS", "controlplane/governance.py"], "Ownership, on-call, escalation, RACI, catalog, transfer, CI check.",
      "Naming the humans (owner decision).", "Organisation.", [_i("ownership_blockers()", "CI check", "n/a", "n/a", "n/a", "blocks release")], "OWNERS.json schema GAP03-OWNERS/1.",
      [("Placeholder owners block certification", "test_mc036_metadata_complete_and_check_blocks_placeholders")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-037", "Architecture decision record", ["docs/adr/ADR-0001-gap03-control-plane.md"], "ADR-0001 covering decision, alternatives, invariants, trade-offs, diagram, approvals.",
      "Approving it (humans).", "Architecture board.", [_i("adr_status()", "CI check", "n/a", "n/a", "n/a", "n/a")], "ADR markdown with required sections.",
      [("ADR is complete but not marked approved without approvers", "test_mc037_adr_sections_and_honest_status")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-038", "Requirements traceability matrix", ["certification/run_checklist.py"], "Generated bidirectional RTM over 1,380 checks + PG gates with CI validation.",
      "Requirement authorship.", "Exit gate.", [_i("run_checklist", "CLI -> evidence/RTM.json", "n/a", "n/a", "n/a", "exit 1 on broken refs")],
      "RTM row {id, mc, category, text, status, blockers, tests[], modules[], artifacts[], evidence[]}.",
      [("Every test binding refers to an existing check and vice versa", "test_mc038_rtm_bidirectional_and_ci_validation")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-039", "MASTER.md source bundle", ["governance/MC-039_MASTER_md_provenance.json"], "Record of the missing source and what is needed to recover it.",
      "Fabricating the document.", "Original author.", [_i("provenance record", "JSON", "n/a", "n/a", "n/a", "n/a")], "GAP03-PROVENANCE/1.",
      [("Absence is recorded; nothing is fabricated", "test_mc039_absence_recorded_not_fabricated")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-040", "Supply chain", ["controlplane/supply_chain.py"], "Manifest, CycloneDX SBOM, in-toto provenance, Ed25519 release signature, sourced-advisory scan.",
      "Builder identity + key custody (blocked).", "Release engineering.", [_i("manifest/sbom/provenance/sign_release/verify_release", "JSON artifacts", "release key", "n/a", "n/a", "UNAUTHENTICATED/INTEGRITY_FAILURE")],
      "manifest {path: sha256}; statement in-toto v1.", [("Signature cannot be reused for another artifact", "test_mc040_release_signature_bound_to_digest")],
      crypto=("Ed25519 release signatures; key custody + builder attestation require HSM/KMS and a trusted builder.", True), threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-041", "Canary controller", ["controlplane/rollout.py"], "Staged promotion with gate binding and automatic rollback.", "Traffic-shifting infrastructure.", "Deployment system.",
      [_i("rollout.run", "in-process controller", "exit gate GO for digest", "bake per stage", "n/a", "PERMISSION_DENIED / ROLLED_BACK")], "stage (pct, bake_s); criteria thresholds.",
      [("No promotion without GO for the exact digest", "test_mc041_automatic_rollback_and_gate_binding")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB, runbook="runbooks/rollout.md"),
    S("MC-042", "Backup / restore / migration", ["controlplane/backup.py", "controlplane/durable.py"], "Consistent multi-store backup with digests; verified restore; migrations with rollback point.",
      "Off-site storage.", "SRE.", [_i("backup/restore", "tar.gz + BACKUP_MANIFEST.json", "operator", "n/a", "n/a", "INTEGRITY_FAILURE/CONFLICT")],
      "manifest {stores{name: {kind, seq, head, files{path: sha256}}}}.", [("Tampered backup never restores", "test_mc042_tampered_or_unsafe_restore_refused")],
      threats="library", fmea=FM_STORE, concurrency=CONC_STORE, runbook="runbooks/backup-restore.md"),
    S("MC-043", "Incident response runbook", ["runbooks/incident-response.md"], "Severity, paging, containment, forensics, recovery, post-incident.", "Paging tool.", "On-call.",
      [_i("runbook", "markdown", "n/a", "n/a", "n/a", "n/a")], "runbook sections.", [("Every alert links an existing runbook", "test_mc043_runbook_content_and_alert_links")],
      threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-044", "Patch / vulnerability / EOL policy", ["policy/SUPPORT_POLICY.md", "policy/support_policy.json"], "Support windows, SLAs, EOL rules.", "Approving it.", "Security.",
      [_i("support_policy.json", "JSON", "n/a", "n/a", "n/a", "n/a")], "GAP03-SUPPORT/1.", [("Policy EOL dates agree with the compatibility matrix", "test_mc044_policy_machine_readable_and_honest")],
      threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-045", "Waiver / debt registry", ["controlplane/waivers.py", "WAIVERS.json"], "Owner/expiry/approval-validated waivers.", "Approving waivers.", "Release managers.",
      [_i("waivers.validate/covers/expiring", "in-process", "n/a", "n/a", "n/a", "problem list")], "waiver {id, control_ids, severity, scope, owner, created, expires, compensating_controls, approval, status, rationale}.",
      [("Expired or ownerless waivers cover nothing", "test_mc045_validation_expiry_and_coverage")], threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
    S("MC-046", "Production exit-gate evidence bundle", ["controlplane/exitgate.py", "certification/run_checklist.py"], "Digest-bound evidence classes, mandatory checks, four independent signed sign-offs, signed result.",
      "Human sign-off.", "Deployment automation.", [_i("exitgate.evaluate/sign_result/verify_result", "JSON", "Ed25519 sign-offs", "14-day freshness", "n/a", "NO_GO")],
      "bundle {artifact_digest, evidence{class: {artifact_digest, produced_at, status}}, mandatory_checks[], signoffs{role: envelope}}.",
      [("Any missing/stale/mismatched/unsigned element => NO_GO", "test_mc046_fail_closed_matrix")],
      crypto=("Ed25519 sign-offs from four distinct issuers; key custody external.", True), threats="library", fmea=FM_LIB, concurrency=CONC_LIB),
]
BY_MC = {s["mc"]: s for s in SPECS}
STRIDE = tuple(BOUNDARY)


def render(spec: dict) -> str:
    L = [f"# {spec['mc']} — {spec['title']}", "", f"**Modules:** {', '.join('`'+m+'`' for m in spec['modules'])}", "",
         "## Scope", spec["scope"], "", "## Non-goals", spec["non_goals"], "", "## Owned by adjacent services", spec["adjacent"], "",
         "## Interfaces", "", "| Interface | Protocol / version | AuthN/Z | Timeout | Retry | Failure semantics |", "|---|---|---|---|---|---|"]
    L += [f"| {i['name']} | {i['protocol']} | {i['auth']} | {i['timeout']} | {i['retry']} | {i['failure']} |" for i in spec["interfaces"]]
    L += ["", "## Data / state model", spec["data_model"], "", "## Invariants → enforcing tests", ""]
    L += [f"- {t} — `{n}`" for t, n in spec["invariants"]]
    L += ["", "## Threat model (STRIDE + replay / stale-state / cross-tenant)", "", "| Threat | Treatment |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in spec["threats"].items()]
    L += ["", "## Cryptography / secrets", spec["crypto"]["decision"] + (" **(production custody blocked: external HSM/KMS)**" if spec["crypto"]["requires_external_kms"] else ""),
          "", "## Sensitive data", spec["sensitive"], "", "## Failure modes", "", "| Failure | Behaviour | Mode |", "|---|---|---|"]
    L += [f"| {a} | {b} | {c} |" for a, b, c in spec["fmea"]]
    L += ["", "## Concurrency / idempotency / retry", spec["concurrency"], "", "## Telemetry", ", ".join(f"`{t}`" for t in spec["telemetry"]) or "via caller",
          "", "## Runbook", f"`{spec['runbook']}`", ""]
    return "\n".join(L)


def write_docs(root: str | None = None) -> list[str]:
    import os
    root = root or os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "components")
    os.makedirs(root, exist_ok=True)
    out = []
    for s in SPECS:
        p = os.path.join(root, f"{s['mc']}.md")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(render(s))
        out.append(p)
    return out


if __name__ == "__main__":
    write_docs()
