"""Machine-readable M01-M86 implementation registry (single source for traceability,
acceptance evidence and the exit gate). Each entry names the concrete artifacts and
test classes that evidence it, and - where the item cannot be closed inside this
repository - the blocker and the waiver id. Statuses:

  LOCALLY_VERIFIED  implemented here and exercised by tests that ran and passed
  PARTIAL           some required behaviour implemented/verified; remainder blocked
  BLOCKED           needs an external environment, a human decision or approval

No entry is COMPLETE: the checklist's own rule requires production-boundary evidence,
a named independent reviewer and a signed exit gate, none of which exist yet.
"""
T = "tests/"
M = {
 "M01": ("PARTIAL", ["MASTER.md", "docs/MASTER_INDEX.md"], ["test_governance.Docs"], "MASTER.md restored verbatim from the owner's series (UC32 payload); approval state/owner sign-off not recorded", "W-APPROVALS"),
 "M02": ("BLOCKED", ["NOTICE", "THIRD-PARTY-NOTICES.md", "LICENSE-DECISION.md"], ["test_governance.Packaging"], "project licence must be chosen by the owner; no SPDX id can be asserted on his behalf", "W-M02"),
 "M03": ("LOCALLY_VERIFIED", ["pyproject.toml", "requirements-lock.txt"], ["test_governance.Packaging"], "", None),
 "M04": ("PARTIAL", ["tools/gen_sbom.py", "release/sbom.cdx.json"], ["test_governance.Packaging"], "SBOM generated (zero third-party runtime deps); no vulnerability feed/attestation signing available offline", "W-SUPPLY"),
 "M05": ("PARTIAL", [".github/workflows/ci.yml", "tools/ci.py"], ["test_governance.CI"], "CI definition + local runner exist and ran here; never executed on a hosted runner", "W-CI"),
 "M06": ("BLOCKED", ["OWNERSHIP.json", "CODEOWNERS"], ["test_governance.Ownership"], "structure and gate check exist; named people, pager and backup contact are owner decisions (placeholders fail the gate)", "W-OWNERS"),
 "M07": ("PARTIAL", ["docs/ADR-0001-wasm-fabric.md"], ["test_governance.Docs"], "ADR written with status 'proposed'; approvers not recorded", "W-APPROVALS"),
 "M08": ("LOCALLY_VERIFIED", ["docs/requirements.json", "docs/REQUIREMENTS.md"], ["test_governance.Requirements"], "", None),
 "M09": ("LOCALLY_VERIFIED", ["fabric/errors.py", "schemas/RESULT.schema.json"], ["test_semantics.ResultModel"], "", None),
 "M10": ("LOCALLY_VERIFIED", ["fabric/lifecycle.py", "docs/LIFECYCLE.md"], ["test_semantics.Lifecycle"], "", None),
 "M11": ("PARTIAL", ["docs/COMPATIBILITY.md"], ["test_semantics.Negotiation"], "policy + N/N-1 protocol pair tests; no prior released wire version exists to test against", "W-APPROVALS"),
 "M12": ("LOCALLY_VERIFIED", ["fabric/limits.py"], ["test_semantics.ResourceLimits", "test_resilience.Concurrency"], "", None),
 "M13": ("LOCALLY_VERIFIED", ["fabric/membership.py"], ["test_resilience.Membership"], "", None),
 "M14": ("LOCALLY_VERIFIED", ["fabric/placement.py", "docs/PLACEMENT.md"], ["test_resilience.Placement"], "", None),
 "M15": ("LOCALLY_VERIFIED", ["tools/gen_traceability.py", "release/TRACEABILITY.json", "release/TRACEABILITY.md"], ["test_governance.Traceability"], "", None),
 "M16": ("LOCALLY_VERIFIED", ["wit/lattice.wit", "schemas/PK_LATTICE_START.schema.json", "schemas/PK_LATTICE_LINK.schema.json", "schemas/PK_LATTICE_CALL.schema.json"], ["test_semantics.Interfaces"], "", None),
 "M17": ("LOCALLY_VERIFIED", ["fabric/identity.py", "fabric/ed25519.py"], ["test_security.Authentication", "test_security.Ed25519Vectors"], "", None),
 "M18": ("LOCALLY_VERIFIED", ["fabric/authz.py"], ["test_security.Authorization"], "", None),
 "M19": ("LOCALLY_VERIFIED", ["fabric/resilience.py"], ["test_resilience.Deadlines", "test_resilience.Retries"], "", None),
 "M20": ("LOCALLY_VERIFIED", ["fabric/errors.py", "schemas/ERROR_REGISTRY.json"], ["test_semantics.ResultModel"], "", None),
 "M21": ("LOCALLY_VERIFIED", ["fabric/negotiation.py"], ["test_semantics.Negotiation"], "", None),
 "M22": ("LOCALLY_VERIFIED", ["fabric/limits.py", "fabric/wire.py"], ["test_semantics.ResourceLimits", "test_semantics.Interfaces"], "", None),
 "M23": ("LOCALLY_VERIFIED", ["fixtures/INDEX.json", "fixtures/validate.mjs", "tools/gen_fixtures.py"], ["test_semantics.Interfaces"], "", None),
 "M24": ("BLOCKED", [], [], "needs wasmCloud hosts + NATS + wadm + real providers in an ephemeral environment", "W-M25"),
 "M25": ("PARTIAL", ["fabric/wasm_backend.py", "fabric/fabric.py"], ["test_config_observability.WasmExecution"], "real WebAssembly executes (V8 via Node) behind the hardened control plane; the wasmCloud/NATS/wadm adapter fails closed", "W-M25"),
 "M26": ("PARTIAL", ["SUPPORT_MATRIX.json"], ["test_governance.Matrix"], "matrix records tested combinations here; wasmCloud/NATS/wadm pins are 'untested' until W-M25 closes", "W-M25"),
 "M27": ("LOCALLY_VERIFIED", ["fabric/config.py", "config/base.json", "docs/CONFIG_REFERENCE.md"], ["test_config_observability.Schema"], "", None),
 "M28": ("LOCALLY_VERIFIED", ["config/overlays"], ["test_config_observability.Overlays"], "", None),
 "M29": ("PARTIAL", ["fabric/config.py"], ["test_config_observability.Activation"], "provenance fields enforced; cryptographic attestation of config revisions not wired", "W-SUPPLY"),
 "M30": ("LOCALLY_VERIFIED", ["fabric/config.py"], ["test_config_observability.Activation"], "", None),
 "M31": ("LOCALLY_VERIFIED", ["fabric/config.py", "docs/runbooks/ROLLOUT.md"], ["test_config_observability.Activation"], "", None),
 "M32": ("PARTIAL", ["fabric/config.py"], ["test_config_observability.Secrets"], "reference type, ACL, TTL, rotation, zeroize, scanning done; no real Vault/KMS adapter", "W-M25"),
 "M33": ("PARTIAL", ["tools/bootstrap.py"], ["test_governance.Bootstrap"], "deterministic, idempotent reference bootstrap with evidence; does not provision NATS/wasmCloud", "W-M25"),
 "M34": ("LOCALLY_VERIFIED", ["docs/THREAT_MODEL.json", "docs/THREAT_MODEL.md"], ["test_governance.ThreatModel"], "", None),
 "M35": ("LOCALLY_VERIFIED", ["fabric/signing.py"], ["test_security.ArtifactSigning"], "", None),
 "M36": ("PARTIAL", ["fabric/identity.py"], ["test_security.Authentication"], "identity, enrolment, clone detection and reference attestation done; no hardware (TPM/TEE) attestation", "W-HW"),
 "M37": ("PARTIAL", ["fabric/authz.py", "fabric/placement.py", "fabric/wasm_backend.py"], ["test_security.Authorization", "test_config_observability.WasmExecution"], "tenant-scoped authz/grants/placement + import-free Wasm sandbox; no network/filesystem namespace enforcement", "W-M25"),
 "M38": ("BLOCKED", [], [], "transport encryption and managed key rotation require the real NATS/TLS/KMS layer", "W-M25"),
 "M39": ("LOCALLY_VERIFIED", ["fabric/identity.py", "fabric/authz.py", "fabric/signing.py", "fabric/config.py"], ["test_security.Authentication", "test_security.Authorization", "test_security.ArtifactSigning", "test_config_observability.Secrets"], "", None),
 "M40": ("LOCALLY_VERIFIED", ["fabric/ledger.py"], ["test_resilience.Ledger"], "", None),
 "M41": ("LOCALLY_VERIFIED", ["tests/test_security.py"], ["test_security.Adversarial"], "", None),
 "M42": ("LOCALLY_VERIFIED", ["fabric/membership.py"], ["test_resilience.Membership"], "", None),
 "M43": ("LOCALLY_VERIFIED", ["fabric/resilience.py"], ["test_resilience.Retries"], "", None),
 "M44": ("LOCALLY_VERIFIED", ["fabric/resilience.py", "fabric/limits.py"], ["test_resilience.Breaker", "test_semantics.ResourceLimits"], "", None),
 "M45": ("LOCALLY_VERIFIED", ["fabric/placement.py", "fabric/fabric.py"], ["test_resilience.Placement"], "", None),
 "M46": ("LOCALLY_VERIFIED", ["fabric/fabric.py"], ["test_resilience.EmergencyControls", "test_resilience.Membership"], "", None),
 "M47": ("LOCALLY_VERIFIED", ["fabric/store.py"], ["test_resilience.Durability"], "", None),
 "M48": ("LOCALLY_VERIFIED", ["fabric/membership.py"], ["test_resilience.Membership"], "", None),
 "M49": ("LOCALLY_VERIFIED", ["fabric/fabric.py"], ["test_resilience.EmergencyControls"], "", None),
 "M50": ("PARTIAL", ["tests/test_resilience.py"], ["test_resilience.Chaos"], "seeded in-process fault injection; no process/network-level chaos against a real lattice", "W-M25"),
 "M51": ("PARTIAL", ["tools/bench.py", "release/BENCHMARK.json"], ["test_governance.Bench"], "reproducible in-process benchmark + baseline on this container; not representative hardware", "W-PERF"),
 "M52": ("LOCALLY_VERIFIED", ["docs/SLO.md", "release/BENCHMARK.json"], ["test_governance.Bench"], "", None),
 "M53": ("PARTIAL", ["docs/PERFORMANCE.md"], ["test_governance.Bench"], "copy/hop analysis for the reference path; real transport serialization unmeasured", "W-PERF"),
 "M54": ("LOCALLY_VERIFIED", ["fabric/limits.py", "fabric/telemetry.py"], ["test_semantics.ResourceLimits", "test_config_observability.Telemetry"], "", None),
 "M55": ("BLOCKED", ["docs/PERFORMANCE.md"], [], "edge power/thermal needs physical hardware and instrumentation", "W-HW"),
 "M56": ("PARTIAL", ["tools/bench.py", "release/BENCHMARK.json"], ["test_governance.Bench"], "saturation curve for the reference control plane only", "W-PERF"),
 "M57": ("LOCALLY_VERIFIED", ["tools/bench.py", "release/BENCHMARK_BASELINE.json"], ["test_governance.Bench"], "", None),
 "M58": ("LOCALLY_VERIFIED", ["fabric/fabric.py"], ["test_config_observability.Telemetry"], "", None),
 "M59": ("LOCALLY_VERIFIED", ["fabric/telemetry.py"], ["test_config_observability.Telemetry"], "", None),
 "M60": ("LOCALLY_VERIFIED", ["fabric/telemetry.py"], ["test_config_observability.Telemetry"], "", None),
 "M61": ("LOCALLY_VERIFIED", ["fabric/telemetry.py"], ["test_config_observability.Telemetry"], "", None),
 "M62": ("LOCALLY_VERIFIED", ["fabric/telemetry.py"], ["test_config_observability.Telemetry"], "", None),
 "M63": ("LOCALLY_VERIFIED", ["fabric/telemetry.py", "fabric/placement.py"], ["test_config_observability.Telemetry", "test_resilience.Placement"], "", None),
 "M64": ("PARTIAL", ["release/ACCEPTANCE.json"], ["test_governance.Evidence"], "release lineage (version, source digest, config digest) recorded; no infrastructure graph to correlate with", "W-M25"),
 "M65": ("LOCALLY_VERIFIED", ["fabric/telemetry.py", "docs/TELEMETRY_POLICY.md"], ["test_config_observability.Telemetry"], "", None),
 "M66": ("PARTIAL", ["ops/alerts.json", "ops/dashboard.json"], ["test_config_observability.Telemetry"], "rules/dashboards defined against emitted metric names; not deployed to a monitoring stack", "W-M25"),
 "M67": ("LOCALLY_VERIFIED", ["tests/test_semantics.py", "tests/test_security.py"], ["test_semantics.Interfaces", "test_semantics.ResultModel"], "", None),
 "M68": ("BLOCKED", [], [], "same environment as M24", "W-M25"),
 "M69": ("PARTIAL", ["SUPPORT_MATRIX.json"], ["test_semantics.Negotiation", "test_semantics.Interfaces"], "protocol pairs + Python/Node consumers; CPU/OS matrix and real providers untested", "W-CI"),
 "M70": ("LOCALLY_VERIFIED", ["tests/test_fuzz.py"], ["test_fuzz.Fuzz"], "", None),
 "M71": ("LOCALLY_VERIFIED", ["tests/test_resilience.py"], ["test_resilience.Concurrency", "test_resilience.ConcurrencyRegressions"], "", None),
 "M72": ("LOCALLY_VERIFIED", ["docs/THREAT_MODEL.json"], ["test_security.Adversarial", "test_governance.ThreatModel"], "", None),
 "M73": ("BLOCKED", ["tools/bench.py"], [], "soak/fleet-scale needs a fleet and hours of runtime", "W-PERF"),
 "M74": ("PARTIAL", ["tests/test_resilience.py"], ["test_resilience.Chaos", "test_resilience.Membership"], "partition/reconnect in-process; no degraded real control plane", "W-M25"),
 "M75": ("LOCALLY_VERIFIED", ["tools/build_evidence.py", "release/ACCEPTANCE.json"], ["test_governance.Evidence"], "", None),
 "M76": ("LOCALLY_VERIFIED", ["../pk_core", "requirements-lock.txt"], ["test_component.ConformanceTest"], "", None),
 "M77": ("PARTIAL", ["docs/SLO.md"], ["test_governance.Docs"], "SLO measurement/burn-rate policy written; support hours and ownership are owner decisions", "W-OWNERS"),
 "M78": ("PARTIAL", ["docs/runbooks/ROLLOUT.md"], ["test_governance.Docs"], "staged rollout with abort thresholds written; never rehearsed", "W-DRILLS"),
 "M79": ("PARTIAL", ["SUPPORT_MATRIX.json", "docs/COMPATIBILITY.md"], ["test_governance.Matrix"], "see M26", "W-M25"),
 "M80": ("BLOCKED", ["docs/SUPPORT_POLICY.md"], [], "patching/EOL SLA commitments are owner decisions", "W-OWNERS"),
 "M81": ("PARTIAL", ["docs/runbooks/BACKUP_RESTORE.md"], ["test_resilience.Durability"], "restore from snapshot+WAL is tested; no drill on real storage", "W-DRILLS"),
 "M82": ("PARTIAL", ["docs/runbooks/DAY0.md", "docs/runbooks/DAY1.md", "docs/runbooks/DAY2.md"], ["test_governance.Docs"], "written, not rehearsed", "W-DRILLS"),
 "M83": ("PARTIAL", ["docs/runbooks/INCIDENT.md"], ["test_governance.Docs"], "plan written; paging integration and named escalation are owner decisions", "W-OWNERS"),
 "M84": ("PARTIAL", ["REVIEWS.json"], ["test_governance.Governance"], "cadence defined; no review has been held", "W-APPROVALS"),
 "M85": ("LOCALLY_VERIFIED", ["WAIVERS.json"], ["test_governance.Governance"], "", None),
 "M86": ("BLOCKED", ["tools/exit_gate.py", "release/EXIT_GATE.json"], ["test_governance.Evidence"], "gate evaluates mechanically and returns NO_GO: waivers unapproved, no independent reviewer, blocked items", "W-APPROVALS"),
}

# C-ids cited by each M (from the audit), used for the C001-C100 traceability matrix.
CITES = {
 "M06": ["C009"], "M07": ["C010"], "M08": ["C011", "C012", "C013"], "M09": ["C014"], "M10": ["C015"], "M11": ["C016"],
 "M12": ["C017"], "M13": ["C018"], "M14": ["C019"], "M15": ["C020"], "M16": ["C021", "C022"], "M17": ["C023"],
 "M18": ["C024"], "M19": ["C025"], "M20": ["C026"], "M21": ["C027"], "M22": ["C028"], "M23": ["C029"], "M24": ["C030"],
 "M25": ["C031"], "M26": ["C031", "C032"], "M27": ["C033", "C034"], "M28": ["C035"], "M29": ["C036"], "M30": ["C037"],
 "M31": ["C038"], "M32": ["C039"], "M33": ["C040"], "M34": ["C041"], "M35": ["C045"], "M36": ["C044"],
 "M37": ["C042", "C043", "C046"], "M38": ["C047"], "M39": ["C048"], "M40": ["C049"], "M41": ["C050"], "M42": ["C051", "C052"],
 "M43": ["C053"], "M44": ["C054"], "M45": ["C055"], "M46": ["C056"], "M47": ["C057"], "M48": ["C058"], "M49": ["C059"],
 "M50": ["C060"], "M51": ["C061", "C063", "C064"], "M52": ["C062"], "M53": ["C065", "C066"], "M54": ["C067"], "M55": ["C068"],
 "M56": ["C069"], "M57": ["C070"], "M58": ["C071"], "M59": ["C072"], "M60": ["C073"], "M61": ["C074"], "M62": ["C075"],
 "M63": ["C076", "C077"], "M64": ["C078"], "M65": ["C079"], "M66": ["C080"], "M67": ["C081", "C082"], "M68": ["C083"],
 "M69": ["C084"], "M70": ["C085"], "M71": ["C086"], "M72": ["C087"], "M73": ["C088"], "M74": ["C089"], "M75": ["C090"],
 "M77": ["C091"], "M78": ["C092"], "M79": ["C093"], "M80": ["C094"], "M81": ["C095"], "M82": ["C096"], "M83": ["C097"],
 "M84": ["C098"], "M85": ["C099"], "M86": ["C100"],
}
