"""Generate / check MASTER.md - the 100 per-requirement prompt/workflow entries (MC-001).

    python -B -m inv28_unikernel_implementations.tools.master [--check]

MASTER.md is **generated** from CHECKLIST.json (the normative requirement text) plus the mapping below;
CHECKLIST.json is authoritative for the requirement wording, MASTER.md is the non-normative workflow
guide.  ``--check`` fails on missing/duplicate/extra IDs, requirement-text drift, or any hand edit.
"""
from __future__ import annotations

import re
import sys

from ._common import ROOT, read_json

DIM = {
    "Architecture & Scope": ("contract.py, docs/ARCHITECTURE.md", "tests/test_component.py"),
    "Requirements & Semantics": ("selection.py, policy.py, errors.py", "tests/test_selection.py"),
    "Interfaces & Integration": ("schemas/, binding.py, certification.py, rollout.py",
                                 "tests/test_interfaces.py, tests/test_integration.py"),
    "Implementation & Configuration": ("model.py, registry.py, config/policy.default.json",
                                       "tests/test_model.py, tests/test_registry.py"),
    "Security, Trust & Isolation": ("trust.py, policy.py (waivers), binding.py, docs/THREAT_MODEL.md",
                                    "tests/test_security.py"),
    "Resilience & Failure Handling": ("registry.py (FileStore, rollback), selection.py (deadline)",
                                      "tests/test_resilience.py, tests/test_registry.py"),
    "Performance & Resource Efficiency": ("selection.py (bounds, cache), ops/CAPACITY.json", "tests/test_ops.py, tools/bench.py"),
    "Observability & Explainability": ("observability.py, service.py, explain.py", "tests/test_observability.py"),
    "Testing & Certification": ("tests/, tools/coverage.py, tools/mutation.py", "tests/run_all.py"),
    "Operations, Release & Governance": ("ops/, tools/release_gate.py", "tests/test_gates.py"),
}
HEADER = """# INV-28 MASTER - per-requirement prompt/workflow index

> GENERATED by `tools/master.py` from `CHECKLIST.json` - do not edit by hand (`--check` fails on drift).
> **Normative source:** `CHECKLIST.json` (requirement text) and `contract.py` (binding contract).
> This file is the non-normative workflow guide: for each requirement it names the objective, preconditions,
> inputs, steps, verification, evidence path and NO_GO conditions.

"""


def render() -> str:
    cl = read_json(ROOT / "CHECKLIST.json")
    out = [HEADER]
    for it in cl["items"]:
        impl, tests = DIM[it["dimension"]]
        cid = it["check_id"]
        out.append(f"## {cid} - {it['dimension']}\n\n"
                   f"**Requirement:** {it['requirement']}\n\n"
                   f"- **Objective:** satisfy {cid} with behaviour that is exercised, not only declared.\n"
                   f"- **Preconditions:** contract validates (`pk_core Contract.validate() == []`); schemas load.\n"
                   f"- **Inputs:** `contract.py`, {impl}.\n"
                   f"- **Steps:** (1) locate the owning module; (2) implement or confirm fail-closed behaviour; "
                   f"(3) add positive/boundary/negative tests asserting stable reason codes; (4) regenerate evidence.\n"
                   f"- **Verification:** {tests}; `tools/pk_gate.py` finding {cid}.\n"
                   f"- **Evidence:** `evidence/PK_GATE_RESULTS.json` ({cid}), `evidence/TEST_RESULTS.json`.\n"
                   f"- **NO_GO if:** the finding is partial/blocked, the behaviour is only declared, a refusal is not asserted "
                   f"by code, or the test profile fails under `python -O`.\n")
    return "\n".join(out)


def check() -> list[str]:
    errs = []
    cl = read_json(ROOT / "CHECKLIST.json")
    ids = [i["check_id"] for i in cl["items"]]
    if len(ids) != 100 or len(set(ids)) != 100 or ids != [f"INV-28-C{n:03d}" for n in range(1, 101)]:
        errs.append("CHECKLIST.json ids are not exactly INV-28-C001..C100")
    path = ROOT / "MASTER.md"
    if not path.exists():
        return errs + ["MASTER.md missing"]
    text = path.read_text(encoding="utf-8")
    found = re.findall(r"^## (INV-28-C\d{3}) ", text, flags=re.M)
    if sorted(found) != sorted(ids) or len(found) != len(set(found)):
        errs.append(f"MASTER.md ids mismatch: missing={sorted(set(ids) - set(found))} dup={len(found) - len(set(found))}")
    if text != render():
        errs.append("MASTER.md drifted from CHECKLIST.json (regenerate with tools/master.py)")
    return errs


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if "--check" in argv:
        errs = check()
        for e in errs:
            print("FAIL", e)
        print("MASTER", "OK" if not errs else "FAIL")
        return 0 if not errs else 1
    (ROOT / "MASTER.md").write_text(render(), encoding="utf-8")
    print("wrote MASTER.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
