"""Produce the executed copy of the v4.2.0 closure checklist with a status on every box.

  python tools/annotate_checklist.py SOURCE.md OUT.md

Legend: [x] done with evidence · [~] done here, but final closure needs an external
input named on the box · [ ] OWNER — needs a human approval/decision · [ ] EXTERNAL —
needs real hardware/backends/pk_core.  Per-box state is classified from the
closure ledger + keyword rules below; the package-level line under each heading
(from CLOSURE_LEDGER.json) is authoritative.
"""
from __future__ import annotations

import json
from pathlib import Path
import re
import sys

PKG = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG / "tools"))
import closure_map as cm  # noqa: E402

OWNER_WORDS = ("require review", "reviewer", "sign-off", "legal", "owner approval", "approved artifact path",
               "select the intended repository license", "approval by", "formally approved")
EXTERNAL_WORDS = ("hypervisor", "real ", "fleet", "power", "thermal", "hardware",
                  "pk_core", "kernel bypass", "zero-copy", "line rate", "exercised against the release candidate",
                  "sealed and retained", "signature")
GLOBAL_NOTES = {
    0: "[x] io_model invariants unchanged and regression-covered (tests/test_io_model.py + fuzz + fixtures)",
    1: "[x] every doc and perf report states reference-model scope; production claims waived (WVR-002/003)",
    2: "[x] verify.py: any skipped mandatory test => PARTIAL (exit 2), never PASS",
    3: "[x] schemas/, requirements/traceability.json, CLOSURE_LEDGER.json, gate results are machine-readable",
    4: "[~] waiver register + expiry gate implemented; approvals of WVR-001..003 are OWNER",
    5: "[~] manifest/SBOM/provenance bound to tree digest; signing key/Sigstore EXTERNAL (TD-002)",
    6: "[x] RTM/AUDIT_MATRIX regenerated by tools/build_rtm.py; drift fails the gate",
}


def load_ledger() -> dict[str, dict]:
    led = json.loads((PKG / "CLOSURE_LEDGER.json").read_text())
    return {p["id"]: p for p in led["packages"]}


def evidence_for(pkg_id: str) -> str:
    short = pkg_id.split("-")[-1]
    if short in cm.ROWS:
        impl, tests, docs, _x, _m = cm.ROWS[short]
        items = impl[:2] + tests[:1]
    elif pkg_id in cm.REPO:
        items = cm.REPO[pkg_id][1][:3]
    else:
        return ""
    return ", ".join(f"`{i}`" for i in items)


def classify(box: str, pkg: dict | None) -> str:
    low = box.lower()
    if pkg is None:
        return "[ ] OWNER"
    blockers = " ".join(pkg["blockers"]).lower()
    if "is closed" in low and "definition" not in low or low.startswith("**inv-35-c"):
        return "[ ] OPEN — closes when blockers clear: " + "; ".join(pkg["blockers"])
    if "update `audit_matrix.json` only after" in low:
        return "[x] complied — row kept `%s` until approval (AUDIT_MATRIX.json regenerated)" % pkg["now"]
    if low.startswith("create or update an authoritative"):
        return "[~] OWNER — artifact created with owner and approval state PENDING; approval not yet recorded"
    if any(w in low for w in OWNER_WORDS):
        return "[ ] OWNER"
    if pkg["now"] == "missing":
        return "[ ] EXTERNAL"
    if any(w in low for w in EXTERNAL_WORDS) and ("wvr" in blockers or "pk_core" in blockers or "backend" in blockers
                                                  or "hardware" in blockers or "key" in blockers):
        return "[~] EXTERNAL"
    if "roles unassigned" in blockers and re.search(r"escalation|on-call|contact|codeowners|owners\.yaml|naming accountable", low):
        return "[~] OWNER — structure implemented; named people/on-call destination still UNASSIGNED"
    return "[x]"


def main(src: str, out: str) -> int:
    ledger = load_ledger()
    lines = Path(src).read_text(encoding="utf-8").splitlines()
    result = []
    current = None
    section = None
    gi = 0
    tallies: dict[str, int] = {}
    for line in lines:
        m = re.match(r"^### ((?:INV-35-C|REPO-)\d{3})", line)
        if m:
            current = ledger.get(m.group(1))
            result.append(line)
            if current:
                result.append("")
                result.append(f"> **v4.3.0 closure:** `{current['closure']}` (audit status now `{current['now']}`, was "
                              f"`{current['baseline']}`). Evidence: {evidence_for(m.group(1))}. Blockers: "
                              + ("; ".join(current["blockers"]) or "none") + ".")
            continue
        h2 = re.match(r"^## (.+)", line)
        if h2:
            section = h2.group(1)
            if section in ("Global closure rules", "Final production-exit verification"):
                current = None
        if line.startswith("- [ ] "):
            box = line[6:]
            if section == "Global closure rules":
                state = GLOBAL_NOTES.get(gi, "[ ]")
                gi += 1
                tag, _, note = state.partition(" ")
                result.append(f"- {tag} {box}  \n  _{note}_")
                tallies[tag] = tallies.get(tag, 0) + 1
                continue
            if section == "Final production-exit verification":
                result.append(f"- [ ] {box}  \n  _OPEN — see conformance/PK_GATE_RESULTS.json blockers_")
                tallies["[ ]"] = tallies.get("[ ]", 0) + 1
                continue
            state = classify(box, current)
            tag = state.split(" ")[0] + (" " + state.split(" ")[1] if state.startswith("[ ]") or state.startswith("[~]") else "")
            key = state[:3]
            tallies[key] = tallies.get(key, 0) + 1
            mark = state[:3]
            note = state[3:].strip()
            result.append(f"- {mark} {box}" + (f"  \n  _{note}_" if note else ""))
            continue
        result.append(line)
    header = [
        "<!-- Executed by the v4.3.0 closure pass. Generated by tools/annotate_checklist.py; do not hand-edit. -->",
        "",
        "**Execution legend:** `[x]` done with evidence in the v4.3.0 tree · `[~]` implemented here, final closure needs "
        "the external input named · `[ ] OWNER` needs a human approval/decision · `[ ] EXTERNAL/OPEN` not closable in this "
        "repository. Box tallies: " + ", ".join(f"`{k}` {v}" for k, v in sorted(tallies.items())) + ".",
        "",
    ]
    Path(out).write_text("\n".join(result[:2] + header + result[2:]) + "\n", encoding="utf-8")
    print(json.dumps(tallies))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
