"""Items 01, 08, 50, 52 and the release/provenance tooling."""
from __future__ import annotations

import datetime as dt
import importlib.util
import json
import pathlib
import shutil
import tempfile
import unittest

PKG = pathlib.Path(__file__).resolve().parents[1]


def _load(name):
    spec = importlib.util.spec_from_file_location(name, PKG / "tools" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


gov = _load("verify_governance")
table = _load("status_table")


class _Copy(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = pathlib.Path(self.tmp.name) / "pkg"
        shutil.copytree(PKG, self.root, ignore=shutil.ignore_patterns("__pycache__", "evidence", "release", "conformance"))

    def tearDown(self):
        self.tmp.cleanup()


class ProvenanceTest(_Copy):
    def test_current_package_is_consistent_but_not_production_ready(self):
        rep = gov.check(PKG, dt.date(2026, 9, 22))
        self.assertTrue(rep["consistent"], rep["failures"])
        self.assertFalse(rep["production_ready"])
        codes = {b["code"] for b in rep["blockers"]}
        self.assertTrue({"provenance_artifact_missing", "owner_unassigned", "pk_core_unpinned",
                         "license_undecided"} <= codes)

    def test_digest_mismatch_fails(self):
        (self.root / "CHECKLIST.json").write_text("{}")
        rep = gov.check(self.root, dt.date(2026, 9, 22))
        self.assertIn("provenance_digest_mismatch", {f["code"] for f in rep["failures"]})

    def test_fabricated_master_is_caught(self):
        (self.root / "MASTER.md").write_text("# totally the original\n")
        rep = gov.check(self.root, dt.date(2026, 9, 22))
        self.assertIn("provenance_declared_missing_but_present", {f["code"] for f in rep["failures"]})

    def test_missing_without_exception_fails(self):
        p = self.root / "provenance" / "PROVENANCE.json"
        d = json.loads(p.read_text())
        d["artifacts"][0]["exception"] = None
        p.write_text(json.dumps(d))
        rep = gov.check(self.root, dt.date(2026, 9, 22))
        self.assertIn("provenance_missing_without_exception", {f["code"] for f in rep["failures"]})


class ExceptionLedgerTest(_Copy):
    def test_expiry_is_enforced(self):
        rep = gov.check(self.root, dt.date(2027, 1, 1))
        self.assertIn("exception_expired", {f["code"] for f in rep["failures"]})
        self.assertEqual(gov.main(["--root", str(self.root), "--today", "2027-01-01"]), 2)

    def test_strict_mode_blocks(self):
        self.assertEqual(gov.main(["--root", str(self.root), "--today", "2026-09-22"]), 0)
        self.assertEqual(gov.main(["--root", str(self.root), "--today", "2026-09-22", "--strict"]), 1)

    def test_approved_owner_and_license_clear_those_blockers(self):
        o = self.root / "governance" / "OWNERS.json"
        d = json.loads(o.read_text())
        d.update(accountable_owner="x", owning_team="y", security_contact="z", on_call_rotation="r")
        o.write_text(json.dumps(d))
        (self.root / "LICENSE").write_text("license text")
        (self.root / "NOTICE").write_text("approved")
        codes = {b["code"] for b in gov.check(self.root, dt.date(2026, 9, 22))["blockers"]}
        self.assertNotIn("owner_unassigned", codes)
        self.assertNotIn("license_undecided", codes)


class TraceabilityTest(unittest.TestCase):
    def test_status_table_covers_all_52_items(self):
        self.assertEqual(sorted(table.ITEMS), [f"{i:02d}" for i in range(1, 53)])
        for k, (state, evidence, blocked) in table.ITEMS.items():
            self.assertIn(state, {table.L, table.P, table.B}, k)
            self.assertTrue(evidence, k)
            if state != table.L:
                self.assertTrue(blocked, f"item {k} is {state} but names no blocker")

    def test_evidence_paths_exist(self):
        for k, (_s, evidence, _b) in table.ITEMS.items():
            for e in evidence:
                path = e.split("::")[0].split("#")[0].split(" ")[0]
                if path.startswith(("evidence/", "release/", "conformance/", "sbom", "SHA256SUMS", "TRACEABILITY")):
                    continue  # generated by tools/build_release.py
                if "*" in path:
                    self.assertTrue(list(PKG.glob(path)), (k, path))
                    continue
                self.assertTrue((PKG / path).exists(), (k, path))

    def test_every_control_is_traced(self):
        mapped = set(table.EXTRA_CONTROLS)
        md = (PKG / "remediation" / "INV43_v4.2.0_MISSING_COMPONENT_REMEDIATION_CHECKLIST.md").read_text()
        import re
        for a, b in re.findall(r"C(\d{3})(?:-C(\d{3}))?", md):
            mapped |= {f"C{i:03d}" for i in range(int(a), int(b or a) + 1)}
        self.assertEqual(mapped, {f"C{i:03d}" for i in range(1, 101)})


if __name__ == "__main__":
    unittest.main()
