"""Generate docs/REQUIREMENTS.md and conformance/traceability.json from CHECKLIST.json + closure map (MC-003)."""
from __future__ import annotations

import json
import pathlib

PKG = pathlib.Path(__file__).resolve().parents[1]


def main() -> None:
    checklist = json.loads((PKG / "CHECKLIST.json").read_text())
    cmap = json.loads((PKG / "governance" / "closure_map.json").read_text())["components"]
    by_control: dict[str, list[str]] = {}
    for mc, c in cmap.items():
        for ctl in c["controls"]:
            by_control.setdefault(ctl, []).append(mc)
    rows, trace = [], []
    for item in checklist["items"]:
        cid, req = item["check_id"], item["requirement"].rstrip(".")
        shall = f"PLN-01 SHALL {req[0].lower()}{req[1:]}."
        mcs = by_control.get(cid, [])
        if mcs:
            evidence = sorted({e for m in mcs for e in cmap[m]["evidence"]})
            tests = sorted({t for m in mcs for t in cmap[m]["tests"]})
            statuses = {cmap[m]["status"] for m in mcs}
            status = "PARTIAL" if "PARTIAL" in statuses else "CLOSED_LOCAL"
            waivers = sorted({cmap[m]["waiver"] for m in mcs if cmap[m]["waiver"]})
        else:
            evidence, tests = ["graph.py", "contract.py", "README.md"], ["tests/test_component.py::CoreGraphTest"]
            status, waivers = "SATISFIED_V420", []
        trace.append({"control": cid, "dimension": item["dimension"], "requirement": shall, "residuals": mcs,
                      "status": status, "evidence": evidence, "tests": tests, "waivers": waivers})
        rows.append(f"| {cid} | {shall} | {', '.join(mcs) or '—'} | {status} | {', '.join(waivers) or '—'} |")
    (PKG / "conformance" / "traceability.json").write_text(json.dumps({"schema": "PLN01_TRACE/1", "controls": trace}, indent=1))
    md = ["# PLN-01 normative requirements and traceability (MC-003)", "",
          "Each checklist control is restated as a SHALL requirement. Evidence/test paths per requirement are in",
          "`conformance/traceability.json` (generated by `tools/gen_requirements.py`; do not edit by hand).",
          "Status: CLOSED_LOCAL = implemented + tested in this repository; PARTIAL = local mechanism present, external",
          "evidence/approval outstanding under the named waiver; SATISFIED_V420 = not a residual in the v4.2.0 audit.",
          "Baseline approval: **PENDING** (governance/APPROVALS.json).", "",
          "| Control | Requirement | Residual components | Status | Waiver |", "|---|---|---|---|---|", *rows, ""]
    (PKG / "docs" / "REQUIREMENTS.md").write_text("\n".join(md))


if __name__ == "__main__":
    main()
