"""Requirements traceability matrix (C020) + post-remediation audit rerun.

    python -m inv69_agentic_workload_layer.tools.rtm [--check] [--out-json evidence/RTM.json] [--out-md ops/RTM.md]

Validates ops/RTM_SOURCE.json against CHECKLIST.json and the tree:
  * all 100 control IDs present, each with status/owner and a known status value
  * every implementation/test ref resolves: file exists; ``file::Sym`` / ``file::Class.method`` exists in the AST
  * ``present`` requires >=1 implementation ref, >=1 test-or-evidence ref and no blockers
  * non-present statuses must name at least one blocker
Renders RTM.json/RTM.md (with the v4.2.0 -> v4.3.0 delta for the 49 formerly-missing controls).
"""
from __future__ import annotations

import argparse
import ast
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _symbols(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    out = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            out.add(node.name)
            if isinstance(node, ast.ClassDef):
                for sub in node.body:
                    if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        out.add(f"{node.name}.{sub.name}")
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            for t in targets:
                if isinstance(t, ast.Name):
                    out.add(t.id)
    return out


def resolve_ref(ref: str) -> str | None:
    """Return None if the ref resolves, else a reason."""
    file, _, sym = ref.partition("::")
    p = ROOT / file
    if not p.exists():
        return f"missing path {file}"
    if sym:
        if p.suffix != ".py":
            return f"symbol on non-python file {file}"
        if sym not in _symbols(p):
            return f"missing symbol {sym} in {file}"
    return None


def validate(src: dict, checklist: dict) -> list[str]:
    errs = []
    ids = [i["check_id"] for i in checklist["items"]]
    ctl = src["controls"]
    if sorted(ids) != sorted(ctl):
        errs.append(f"control set mismatch: missing={sorted(set(ids) - set(ctl))} extra={sorted(set(ctl) - set(ids))}")
    for cid, c in ctl.items():
        if c.get("status") not in src["status_values"]:
            errs.append(f"{cid}: unknown status {c.get('status')}")
        if not c.get("owner"):
            errs.append(f"{cid}: no owner")
        for ref in c["implementation"] + c["tests"] + c["evidence"]:
            why = resolve_ref(ref) if not ref.startswith("evidence/") else (None if (ROOT / ref).exists() else f"missing evidence {ref}")
            if why:
                errs.append(f"{cid}: {why}")
        if c["status"] == "present":
            if not c["implementation"] or not (c["tests"] or c["evidence"]) or c["blockers"]:
                errs.append(f"{cid}: 'present' without implementation+verification or with blockers")
        elif not c["blockers"]:
            errs.append(f"{cid}: status {c['status']} names no blocker")
    return errs


def render(src: dict, checklist: dict, prior: dict) -> tuple[dict, str]:
    req = {i["check_id"]: i for i in checklist["items"]}
    prior_status = {c["check_id"]: c["status"] for c in prior["checks"]}
    rows = []
    for cid in sorted(src["controls"]):
        c = src["controls"][cid]
        rows.append({"check_id": cid, "dimension": req[cid]["dimension"], "requirement": req[cid]["requirement"],
                     "v4_2_0_status": prior_status.get(cid), "status": c["status"], "owner": c["owner"],
                     "implementation": c["implementation"], "tests": c["tests"], "evidence": c["evidence"],
                     "blockers": c["blockers"], "note": c["note"], "last_verified_version": src["version"]})
    was_missing = [r for r in rows if r["v4_2_0_status"] == "missing"]
    summary = {"all": dict(Counter(r["status"] for r in rows)),
               "formerly_missing_49": dict(Counter(r["status"] for r in was_missing)),
               "v4_2_0": dict(Counter(prior_status.values()))}
    doc = {"schema": "PK_RTM/1", "component": "INV-69", "version": src["version"], "summary": summary, "rows": rows}
    md = [f"# INV-69 requirements traceability matrix — v{src['version']} (generated by tools/rtm.py)", "",
          f"All 100: {summary['all']}  ", f"Formerly missing (49): {summary['formerly_missing_49']}  ",
          f"v4.2.0 audit: {summary['v4_2_0']}", "",
          "| ID | dimension | v4.2.0 | v4.3.0 | owner | implementation | verification | blockers |", "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        impl = "<br>".join(f"`{x}`" for x in r["implementation"][:4]) + (" …" if len(r["implementation"]) > 4 else "")
        ver = "<br>".join(f"`{x}`" for x in (r["tests"] + r["evidence"])[:3])
        md.append(f"| {r['check_id']} | {r['dimension']} | {r['v4_2_0_status']} | **{r['status']}** | {r['owner']} | "
                  f"{impl} | {ver} | {'; '.join(r['blockers'])[:220]} |")
    return doc, "\n".join(md) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out-json", default=str(ROOT / "evidence" / "RTM.json"))
    ap.add_argument("--out-md", default=str(ROOT / "ops" / "RTM.md"))
    a = ap.parse_args(argv)
    src = json.loads((ROOT / "ops" / "RTM_SOURCE.json").read_text())
    checklist = json.loads((ROOT / "CHECKLIST.json").read_text())
    prior = json.loads((ROOT / "GAP_AUDIT.json").read_text())
    errs = validate(src, checklist)
    for e in errs:
        print("FAIL", e)
    doc, md = render(src, checklist, prior)
    if not a.check:
        Path(a.out_json).write_text(json.dumps(doc, indent=1), encoding="utf-8")
        Path(a.out_md).write_text(md, encoding="utf-8")
    print("RTM", "PASS" if not errs else "FAIL", json.dumps(doc["summary"]))
    return 0 if not errs else 1


if __name__ == "__main__":
    sys.exit(main())
