"""Repository integrity: declared artifacts exist and agree (MC-001, MC-003, MC-007, MC-008, MC-081..MC-093)."""
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import unittest

import harness  # noqa: F401

PKG = pathlib.Path(__file__).resolve().parents[1]


class Artifacts(unittest.TestCase):
    REQUIRED = ["MASTER.md", "LICENSE", "SECURITY.md", "CONTRIBUTING.md", "DEVELOPMENT.md", "THIRD-PARTY-NOTICES.md",
                "pyproject.toml", "requirements.lock", ".pre-commit-config.yaml", ".github/workflows/ci.yml",
                ".github/workflows/release.yml", ".github/workflows/review-freshness.yml", ".github/CODEOWNERS",
                "docs/ARCHITECTURE.md", "docs/THREAT_MODEL.md", "docs/MIGRATION.md",
                "docs/ADR-0001-production-maturity.md", "docs/ADR-0002-osv-representation.md",
                "docs/ADR-0003-review-time-provenance.md", "ops/RUNBOOK.md", "ops/SLA.md", "ops/TECH_DEBT.md",
                "ops/OWNERS.json", "ops/DECISIONS.json", "ops/WAIVERS.json", "ops/REVIEWS.json", "ops/CAPACITY.json",
                "ops/COMPATIBILITY_MATRIX.json", "ops/TELEMETRY_POLICY.json", "ops/alerts.json", "ops/dashboards.json",
                "ops/PERF_THRESHOLDS.json", "ops/MC_STATUS.json", "catalog/catalog.json", "config/policy.default.json"]

    def test_required_files_exist(self):
        missing = [f for f in self.REQUIRED if not (PKG / f).exists()]
        self.assertEqual(missing, [])

    def test_master_consistent_with_checklist(self):                              # MC-001
        from inv28_unikernel_implementations.tools import master
        self.assertEqual(master.check(), [])

    def test_version_consistent(self):
        v = (PKG / "VERSION").read_text().strip()
        import inv28_unikernel_implementations as pkg
        self.assertEqual(pkg.__version__, v)
        self.assertIn(f'version = "{v}"', (PKG / "pyproject.toml").read_text())
        self.assertIn(f"## {v}", (PKG / "CHANGELOG.md").read_text())
        self.assertIn(f"**Version:** {v}", (PKG / "README.md").read_text())

    def test_vendored_pk_core_digests(self):                                        # MC-002
        prov = json.loads((PKG / "_vendor" / "PK_CORE_PROVENANCE.json").read_text())
        for f, h in prov["files_sha256"].items():
            self.assertEqual(hashlib.sha256((PKG / "_vendor" / "pk_core" / f).read_bytes()).hexdigest(), h, f)

    def test_pk_core_from_vendor_when_not_installed(self):
        code = ("import sys; sys.path=[p for p in sys.path if 'pk_core' not in p]; "
                "import inv28_unikernel_implementations as m; c=m.COMPONENT(); "
                "import pk_core; print(pk_core.__file__)")
        out = subprocess.run([sys.executable, "-B", "-W", "ignore", "-c", code], cwd=str(PKG.parent),
                             capture_output=True, text=True)
        self.assertEqual(out.returncode, 0, out.stderr)
        self.assertIn("_vendor", out.stdout)

    def test_licence_decision_recorded(self):                                       # MC-007
        dec = {d["id"]: d for d in json.loads((PKG / "ops" / "DECISIONS.json").read_text())["decisions"]}
        self.assertIn("D-004", dec)
        self.assertIn("LICENCE NOT YET CHOSEN", (PKG / "LICENSE").read_text())

    def test_security_policy_points_at_owners(self):                                # MC-008
        self.assertIn("ops/OWNERS.json", (PKG / "SECURITY.md").read_text())

    def test_changelog_links_resolve(self):                                          # MC-093
        text = (PKG / "CHANGELOG.md").read_text()
        section = text.split("\n## ")[1]
        refs = re.findall(r"`((?:evidence|ops|docs|tools|schemas)/[A-Za-z0-9_./-]+)`", section)
        self.assertGreaterEqual(len(refs), 8)
        produced = "\n".join(p.read_text() for p in (PKG / "tools").glob("*.py"))
        for r in refs:
            with self.subTest(ref=r):
                if r.startswith("evidence/"):
                    # evidence is (re)generated by the lanes that run after this test; the link must name an
                    # artifact some tool actually writes
                    self.assertIn(pathlib.Path(r).name, produced, r)
                else:
                    self.assertTrue((PKG / r).exists(), r)

    def test_ci_runs_optimized_and_matrix(self):                                     # MC-081
        ci = (PKG / ".github" / "workflows" / "ci.yml").read_text()
        self.assertIn("check_all", ci)
        for v in ("3.10", "3.11", "3.12", "3.13"):
            self.assertIn(v, ci)
        check_all = (PKG / "tools" / "check_all.py").read_text()
        self.assertIn('"-O"', check_all)

    def test_pyproject_has_no_runtime_dependencies(self):                            # MC-003, MC-083
        self.assertRegex((PKG / "pyproject.toml").read_text(), r"(?m)^dependencies = \[\]")

    def test_readme_does_not_claim_absent_artifacts(self):
        readme = (PKG / "README.md").read_text()
        for m in re.findall(r"`([A-Za-z0-9_./-]+\.(?:md|json|py|toml|yml))`", readme):
            with self.subTest(ref=m):
                self.assertTrue((PKG / m).exists() or (PKG / "tools" / m).exists() or (PKG / "tests" / m).exists(), m)


if __name__ == "__main__":
    unittest.main()
