"""MC-45: generate the versioned API reference (docs/api/INV10_API_REFERENCE_<ver>.md) from source."""
import inspect, json
import _path  # noqa: F401
from _path import ROOT
import inv10_component_composition_system as pkg
from inv10_component_composition_system import (adapters, composition, controlplane, errors, features, governance,
                                                manifest, observability, pkcore_compat, schemas, security, wit, cli)

MODULES = [composition, schemas, manifest, wit, adapters, governance, security, observability, controlplane,
           features, errors, pkcore_compat, cli]


def sig(obj):
    try:
        return str(inspect.signature(obj))
    except (TypeError, ValueError):
        return "(...)"


def render():
    out = [f"# INV-10 API reference — {pkg.__version__}", "",
           "Generated by `tools/gen_docs.py`; do not edit by hand.", ""]
    out += ["## Error codes", "", "| code | class |", "|---|---|"]
    classes = {c.code: c.__name__ for c in [composition.CompositionError, *composition.CompositionError.__subclasses__()]}
    out += [f"| `{c}` | `{classes.get(c, '')}` |" for c in errors.ERROR_CODES] + [""]
    out += ["## Default limits", "", "```json", json.dumps(vars(composition.DEFAULT_LIMITS), indent=1), "```", ""]
    for m in MODULES:
        out += [f"## `{m.__name__}`", "", (inspect.getdoc(m) or "").strip(), ""]
        for name, obj in sorted(vars(m).items()):
            if name.startswith("_") or getattr(obj, "__module__", None) != m.__name__:
                continue
            if inspect.isclass(obj):
                out += [f"### class `{name}{sig(obj)}`", "", (inspect.getdoc(obj) or "").strip(), ""]
                for mn, mo in sorted(vars(obj).items()):
                    if not mn.startswith("_") and callable(mo):
                        out += [f"- `{mn}{sig(mo)}` — {(inspect.getdoc(mo) or '').splitlines()[0] if inspect.getdoc(mo) else ''}"]
                out.append("")
            elif inspect.isfunction(obj):
                out += [f"### `{name}{sig(obj)}`", "", (inspect.getdoc(obj) or "").strip(), ""]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    d = ROOT / "docs" / "api"
    d.mkdir(parents=True, exist_ok=True)
    p = d / f"INV10_API_REFERENCE_{pkg.__version__}.md"
    p.write_text(render(), encoding="utf-8")
    print(f"wrote {p.relative_to(ROOT)}")
