"""Generate ``_wire.py`` and ``docs/WIRE.md`` from ``schema/pk_ctrl.idl.json`` (MC-06.008/.012/.024).

``python -m inv36_control_transport.tools.gen_wire --check`` exits 1 when the
checked-in generated files are stale.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
IDL = PKG / "schema" / "pk_ctrl.idl.json"
OUT_PY = PKG / "_wire.py"
OUT_MD = PKG / "docs" / "WIRE.md"
GENERATOR_VERSION = "gen_wire/1.0.0"


def _preamble(pre: dict) -> bytes:
    return bytes.fromhex(pre["const_hex"]) + bytes([pre["version_byte"], pre["reserved_byte"]])


def render() -> tuple[str, str]:
    raw = IDL.read_bytes()
    idl = json.loads(raw)
    digest = hashlib.sha256(raw).hexdigest()
    p = idl["protocols"]
    reg = idl["registries"]
    lines = [
        '"""GENERATED by tools/gen_wire.py from schema/pk_ctrl.idl.json - do not edit."""',
        "from __future__ import annotations",
        "",
        f"IDL_SHA256 = {digest!r}",
        f"IDL_REVISION = {idl['idl_revision']}",
        f"GENERATOR = {GENERATOR_VERSION!r}",
        "",
        f"FRAME_VERSION = {p['PK_CTRL_FRAME']['version']}",
        f"FRAME_MAGIC = {p['PK_CTRL_FRAME']['header'][0]['const_ascii'].encode()!r}",
        f"FRAME_ALGORITHMS = {p['PK_CTRL_FRAME']['header'][2]['enum']!r}",
        f"FRAME_MAX_PLAINTEXT = {p['PK_CTRL_FRAME']['limits']['max_plaintext']}",
        f"FRAME_TAG_SIZE = {p['PK_CTRL_FRAME']['limits']['tag_size']}",
        f"STREAM_VERSION = {p['PK_CTRL_STREAM']['version']}",
        f"STREAM_PREAMBLE = {_preamble(p['PK_CTRL_STREAM']['preamble'])!r}",
        f"STREAM_RECORD_TYPES = {p['PK_CTRL_STREAM']['record_header'][0]['enum']!r}",
        f"STREAM_MAX_RECORD = {p['PK_CTRL_STREAM']['record_header'][2]['max']}",
        f"MSG_VERSION = {p['PK_CTRL_MSG']['version']}",
        f"MSG_TENANT_MAX = {p['PK_CTRL_MSG']['fields'][5]['max']}",
        f"MSG_BODY_MAX = {p['PK_CTRL_MSG']['fields'][7]['max']}",
        f"MESSAGE_TYPES = {reg['message_types']!r}",
        f"MESSAGE_TYPE_RANGES = {reg['message_type_ranges']!r}",
        f"HS_VERSION = {p['PK_CTRL_HS']['version']}",
        f"HS_MESSAGES = {p['PK_CTRL_HS']['messages']!r}",
        f"HS_SUITES = {p['PK_CTRL_HS']['suites']!r}",
        f"HS_LIMITS = {p['PK_CTRL_HS']['limits']!r}",
        "",
    ]
    md = [
        "# INV-36 wire reference (generated)",
        "",
        f"Generated by `{GENERATOR_VERSION}` from `schema/pk_ctrl.idl.json` (sha256 `{digest}`). Do not edit by hand.",
        "",
    ]
    for name, proto in p.items():
        md += [f"## {name}/{proto['version']} ({proto['status']})", ""]
        fields = proto.get("header") or proto.get("fields") or proto.get("record_header") or []
        if fields:
            md += ["| Field | Type | Constraint |", "|---|---|---|"]
            for f in fields:
                cons = {k: v for k, v in f.items() if k not in {"name", "type"}}
                md.append(f"| `{f['name']}` | {f['type']} | `{json.dumps(cons, sort_keys=True)}` |")
            md.append("")
        for key in ("body", "limits", "aad", "rules", "messages", "suites", "preamble"):
            if key in proto:
                md.append(f"- **{key}:** `{json.dumps(proto[key], sort_keys=True)}`")
        md.append("")
    md += ["## Message-type registry", "", "| Type | Id |", "|---|---|"]
    md += [f"| {k} | {v} |" for k, v in reg["message_types"].items()]
    md += ["", f"Ranges: `{json.dumps(reg['message_type_ranges'])}`", "", reg["registry_process"], ""]
    return "\n".join(lines), "\n".join(md)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    py, md = render()
    if a.check:
        stale = [str(f.name) for f, t in ((OUT_PY, py), (OUT_MD, md)) if not f.exists() or f.read_text() != t]
        if stale:
            print("stale generated files:", ", ".join(stale))
            return 1
        print("generated wire files up to date")
        return 0
    OUT_PY.write_text(py)
    OUT_MD.write_text(md)
    print("wrote", OUT_PY.name, OUT_MD.name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
