"""Missing-component checklist ledger (the supplied INV-36 v5.0.0 checklist) - validation and rendering.

    python -m inv36_control_transport.tools.mc_status --check    # CI
    python -m inv36_control_transport.tools.mc_status --render   # writes docs/MC_CHECKLIST_STATUS.md

Status vocabulary (MC_CHECKLIST_STATUS.json):

* ``DONE`` - implemented in this repository **and** verified by repository
  tests/evidence.  Never used for items that need a named person, legal
  decision, approval, or external infrastructure.
* ``PARTIAL`` - implemented or specified here, but some part of the item
  depends on an external system, a real deployment, or a CI run that has not
  happened yet; ``note`` says what is missing.
* ``OPEN_EXTERNAL`` - cannot be closed from this repository (real pk_core,
  certified VM rows, KMS/HSM, managed signing identity, long-running runners).
* ``OPEN_GOVERNANCE`` - needs owner/legal/approver action.
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import re
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
SOURCE = PKG / "docs" / "source" / "INV36_v5.0.0_MISSING_COMPONENTS_COMPREHENSIVE_CHECKLIST.md"
LEDGER = PKG / "MC_CHECKLIST_STATUS.json"
OUT = PKG / "docs" / "MC_CHECKLIST_STATUS.md"
STATUSES = ("DONE", "PARTIAL", "OPEN_EXTERNAL", "OPEN_GOVERNANCE")
ITEM = re.compile(r"^- \[ \] \*\*(MC-\d\d\.\d{3})\*\* — (.*)$")
HUMAN = re.compile(
    r"(explicit owner|named owner|legal(?:ly| authority| review| counsel| approval| hold)|reviewer approval|"
    r"security review|two-person|repository-owner|production-exit-gate record|named approvers|"
    r"assign technical and security approvers|security-owner approval|protected-environment approval|"
    r"approved owner)", re.I)


def parse_source() -> dict[str, dict]:
    items: dict[str, dict] = {}
    mc = section = ""
    for line in SOURCE.read_text().splitlines():
        if line.startswith("## MC-"):
            mc = line[3:8]
        elif line.startswith("### "):
            section = line[4:].strip()
        m = ITEM.match(line)
        if m:
            items[m.group(1)] = {"mc": mc, "section": section, "text": m.group(2)}
    return items


def _evidence_exists(ev: str) -> bool:
    path = ev.split("::")[0].split("#")[0].strip()
    if not path:
        return False
    if "*" in path:
        return any(PKG.glob(path))
    return (PKG / path).exists()


def check() -> dict:
    src = parse_source()
    ledger = json.loads(LEDGER.read_text())
    items = ledger["items"]
    problems = []
    for iid in src:
        if iid not in items:
            problems.append(f"{iid}: missing from ledger")
    for iid, rec in items.items():
        if iid not in src:
            problems.append(f"{iid}: not in source checklist")
            continue
        st = rec.get("status")
        if st not in STATUSES:
            problems.append(f"{iid}: invalid status {st!r}")
        if st in ("DONE", "PARTIAL") and not rec.get("evidence"):
            problems.append(f"{iid}: {st} without evidence")
        for ev in rec.get("evidence", []):
            if not _evidence_exists(ev):
                problems.append(f"{iid}: evidence path not found: {ev}")
        if st == "DONE" and HUMAN.search(src[iid]["text"]):
            problems.append(f"{iid}: human-gated item marked DONE")
        if st != "DONE" and not rec.get("note"):
            problems.append(f"{iid}: non-DONE item needs a note")
    counts = collections.Counter(r["status"] for r in items.values())
    by_mc: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for iid, rec in items.items():
        by_mc[iid[:5]][rec["status"]] += 1
    return {"items": len(src), "counts": dict(counts), "by_mc": {k: dict(v) for k, v in sorted(by_mc.items())},
            "problems": problems}


def render() -> str:
    src = parse_source()
    ledger = json.loads(LEDGER.read_text())
    res = check()
    mark = {"DONE": "[x]", "PARTIAL": "[~]", "OPEN_EXTERNAL": "[ ]", "OPEN_GOVERNANCE": "[ ]"}
    out = ["# INV-36 missing-component checklist - status after 5.1.0 (generated)", "",
           "Generated by `tools/mc_status.py --render` from `MC_CHECKLIST_STATUS.json` against the supplied checklist "
           "(`docs/source/`, SHA-256 in `docs/source/SOURCES.json`).", "",
           "`[x]` DONE (implemented + verified by repository evidence) - `[~]` PARTIAL - `[ ]` OPEN_EXTERNAL / "
           "OPEN_GOVERNANCE. DONE means repository-local closure, **not** production certification.", "",
           f"Totals: {json.dumps(res['counts'], sort_keys=True)} of {res['items']} items.", "",
           "| MC | DONE | PARTIAL | OPEN_EXTERNAL | OPEN_GOVERNANCE |", "|---|---:|---:|---:|---:|"]
    for mc, c in res["by_mc"].items():
        out.append(f"| {mc} | {c.get('DONE', 0)} | {c.get('PARTIAL', 0)} | {c.get('OPEN_EXTERNAL', 0)} | "
                   f"{c.get('OPEN_GOVERNANCE', 0)} |")
    out.append("")
    cur_mc = cur_sec = ""
    for iid, meta in src.items():
        if meta["mc"] != cur_mc:
            cur_mc, cur_sec = meta["mc"], ""
            out += ["", f"## {cur_mc}", ""]
        if meta["section"] != cur_sec:
            cur_sec = meta["section"]
            out += [f"### {cur_sec}", ""]
        rec = ledger["items"][iid]
        ev = "; ".join(f"`{e}`" for e in rec.get("evidence", []))
        note = f" - _{rec['note']}_" if rec.get("note") else ""
        out.append(f"- {mark[rec['status']]} **{iid}** {rec['status']} - {meta['text']}"
                   f"{' Evidence: ' + ev if ev else ''}{note}")
    extra = ledger.get("global", {})
    if extra:
        out += ["", "## Global definition of done / execution order / final certification", ""]
        for k, v in extra.items():
            out.append(f"- {mark.get(v['status'], '[ ]')} **{k}** {v['status']} - {v['text']} _{v.get('note', '')}_")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--render", action="store_true")
    a = ap.parse_args(argv)
    res = check()
    if a.render:
        OUT.write_text(render())
    stale = a.check and OUT.exists() and OUT.read_text() != render()
    print(json.dumps({"items": res["items"], "counts": res["counts"], "problems": res["problems"][:50],
                      "stale_render": bool(stale)}))
    return 1 if res["problems"] or stale else 0


if __name__ == "__main__":
    sys.exit(main())
