"""Requirements <-> implementation <-> tests <-> evidence traceability (MC-20).

    python -m inv36_control_transport.tools.traceability --write   # regenerate docs
    python -m inv36_control_transport.tools.traceability --check   # CI: fail on orphans/drift

Tests declare what they verify with a class docstring line
``REQ: INV36-REQ-001, INV36-REQ-002 | KIND: security``.  The tool fails when a
requirement has no verifying test (unless its verification method is
inspection/benchmark/monitoring and it names an evidence artifact), when a
test class has no REQ tag (orphan test), when a tag names an unknown
requirement, or when an implementation symbol no longer exists.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import json
import pathlib
import re
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
REQS = PKG / "requirements" / "requirements.json"
OUT_MD = PKG / "docs" / "TRACEABILITY.md"
OUT_REQ_MD = PKG / "docs" / "REQUIREMENTS.md"
OUT_JSON = PKG / "requirements" / "traceability.json"
TAG = re.compile(r"REQ:\s*([A-Z0-9, -]+?)\s*\|\s*KIND:\s*(\w+)")
NON_TEST_METHODS = ("inspection", "benchmark", "monitoring")


def load_requirements() -> list[dict]:
    return json.loads(REQS.read_text())["requirements"]


def scan_tests() -> tuple[dict[str, list[dict]], list[str]]:
    by_req: dict[str, list[dict]] = {}
    orphans: list[str] = []
    for f in sorted((PKG / "tests").glob("test_*.py")):
        tree = ast.parse(f.read_text())
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and any(
                    isinstance(b, ast.Attribute) and b.attr == "TestCase" or isinstance(b, ast.Name) and
                    b.id == "TestCase" for b in node.bases):
                doc = ast.get_docstring(node) or ""
                m = TAG.search(doc)
                ref = f"tests/{f.name}::{node.name}"
                if not m:
                    orphans.append(ref)
                    continue
                for rid in [x.strip() for x in m.group(1).split(",") if x.strip()]:
                    by_req.setdefault(rid, []).append({"test": ref, "kind": m.group(2)})
    return by_req, orphans


def symbol_exists(sym: str) -> bool:
    if sym.startswith("docs/"):
        return (PKG / sym.split("#")[0]).exists()
    parts = sym.split(".")
    for i in range(len(parts), 0, -1):
        mod = "inv36_control_transport." + ".".join(parts[:i])
        try:
            obj = importlib.import_module(mod)
        except ImportError:
            continue
        for attr in parts[i:]:
            if not hasattr(obj, attr):
                return False
            obj = getattr(obj, attr)
        return True
    return False


def build() -> dict:
    reqs = load_requirements()
    tests, orphans = scan_tests()
    ids = {r["id"] for r in reqs}
    problems = [f"orphan test (no REQ tag): {o}" for o in orphans]
    problems += [f"unknown requirement {rid} tagged by {t[0]['test']}" for rid, t in tests.items() if rid not in ids]
    rows = []
    for r in reqs:
        ts = tests.get(r["id"], [])
        missing_syms = [s for s in r["implementation"] if not symbol_exists(s)]
        if missing_syms:
            problems.append(f"{r['id']}: implementation symbols missing {missing_syms}")
        needs_test = not any(m in r["verification"] for m in NON_TEST_METHODS) or "test" in r["verification"]
        if needs_test and not ts:
            problems.append(f"{r['id']}: no verifying test")
        kinds = sorted({t["kind"] for t in ts})
        status = "verified-local" if ts else ("evidence-external" if not needs_test else "unverified")
        rows.append({**r, "tests": ts, "test_kinds": kinds, "status": status})
    return {"schema": "inv36.traceability/1", "baseline": json.loads(REQS.read_text())["baseline"], "rows": rows,
            "orphan_tests": orphans, "problems": problems}


def render(tr: dict) -> tuple[str, str]:
    md = ["# INV-36 traceability matrix (generated)", "",
          "Generated by `tools/traceability.py` from `requirements/requirements.json` and test REQ tags. "
          "`verified-local` means repository tests exist and pass in CI; it is **not** production certification.", "",
          "| Requirement | Design | Implementation | Config | Unit | Integration | Security | Performance/fuzz | "
          "Runbook | Evidence | Status | Owner | Release |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in tr["rows"]:
        def tl(kind, r=r):
            return "<br>".join(t["test"].split("::")[1] for t in r["tests"] if t["kind"] == kind) or "-"
        md.append(f"| {r['id']} | {r['design']} | {'<br>'.join('`'+s+'`' for s in r['implementation'])} | "
                  f"{', '.join(r['config']) or '-'} | {tl('unit')} | {tl('integration')} | {tl('security')} | "
                  f"{tl('performance') if tl('performance') != '-' else tl('fuzz')} | {r['runbook'] or '-'} | "
                  f"{r['evidence']} | {r['status']} | {r['owner'].split(' (')[0]} | {r['baseline']} |")
    md += ["", f"Problems: {len(tr['problems'])}", ""] + [f"- {p}" for p in tr["problems"]]
    rq = ["# INV-36 requirements specification (generated from requirements/requirements.json)", "",
          f"Baseline **{json.loads(REQS.read_text())['baseline']}**, approval state **proposed** - every requirement "
          "awaits named technical and security owner approval (see docs/GOVERNANCE.md).", "",
          "Each SHALL statement is atomic and has a verification method. `critical` marks safety/security-critical "
          "requirements.", ""]
    for cat in sorted({r["category"] for r in tr["rows"]}):
        rq += [f"## {cat}", ""]
        for r in tr["rows"]:
            if r["category"] != cat:
                continue
            rq.append(f"- **{r['id']}** ({r['type'].replace('_', '-')}{', critical' if r['safety_security_critical'] else ''}; "
                      f"verify: {r['verification']}{'; threshold: ' + r['threshold'] if r['threshold'] else ''}) - "
                      f"{r['text']} _Source: {r['source']}._")
        rq.append("")
    rq += ["## Precedence", "", "INV36-REQ-039 governs conflicts: security/integrity > tenant isolation/residency > "
           "availability > latency SLO > cost > operator preference.", "",
           "## Change control", "", "A requirement change must update `requirements/requirements.json`, the affected "
           "tests' REQ tags and this generated document in the same change; CI runs `traceability --check`. "
           "Each release freezes the baseline by tagging the requirements digest into the gate evidence.", ""]
    return "\n".join(md), "\n".join(rq)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    tr = build()
    md, rq = render(tr)
    if a.write:
        OUT_MD.write_text(md)
        OUT_REQ_MD.write_text(rq)
        OUT_JSON.write_text(json.dumps(tr, indent=1))
    stale = a.check and (not OUT_MD.exists() or OUT_MD.read_text() != md or OUT_REQ_MD.read_text() != rq)
    print(json.dumps({"requirements": len(tr["rows"]), "problems": tr["problems"], "stale_docs": bool(stale)}))
    return 1 if tr["problems"] or stale else 0


if __name__ == "__main__":
    sys.exit(main())
