"""MC traceability matrix for the applied checklist (MC-001..MC-100) - "final repository-wide closure gate".

    python -B -m inv28_unikernel_implementations.tools.rtm [--check]

Validates ops/MC_STATUS.json: all 100 MC ids, known status, owner, every implementation/test/evidence ref
resolves (``file``, ``file::Symbol`` or ``file::Class.method`` via AST), non-``complete`` items name at
least one blocker, ``implemented_unreviewed`` needs >=1 implementation and >=1 test ref.  Renders
evidence/MC_STATUS.json and ops/MC_STATUS.md.  Nothing is ever ``complete`` here: that status requires
an independent reviewer, which this tooling cannot be.
"""
from __future__ import annotations

import argparse
import ast
import sys
from collections import Counter
from functools import cache

from ._common import EVIDENCE, ROOT, read_json, write_json


@cache
def _symbols(path) -> frozenset:
    tree = ast.parse((ROOT / path).read_text(encoding="utf-8"))
    out = set()

    def visit(body, prefix=""):
        for node in body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                out.add(prefix + node.name)
                if isinstance(node, ast.ClassDef):
                    visit(node.body, prefix + node.name + ".")
            elif isinstance(node, (ast.Assign, ast.AnnAssign)):
                for t in (node.targets if isinstance(node, ast.Assign) else [node.target]):
                    if isinstance(t, ast.Name):
                        out.add(prefix + t.id)
    visit(tree.body)
    return frozenset(out)


def resolve(ref: str, *, allow_missing_evidence=False) -> str | None:
    file, _, sym = ref.partition("::")
    if not (ROOT / file).exists():
        return None if allow_missing_evidence else f"missing path {file}"
    if sym and sym not in _symbols(file):
        return f"missing symbol {sym} in {file}"
    return None


def validate(src: dict, *, evidence_required=True) -> list[str]:
    errs = []
    ids = sorted(src["items"])
    if ids != [f"MC-{n:03d}" for n in range(1, 101)]:
        errs.append("MC ids are not exactly MC-001..MC-100")
    for mc, it in src["items"].items():
        if it["status"] not in src["status_values"]:
            errs.append(f"{mc}: unknown status {it['status']}")
        if it["status"] == "complete":
            errs.append(f"{mc}: 'complete' requires an independent review record, which this repository cannot mint")
        if not it.get("owner"):
            errs.append(f"{mc}: no owner")
        if not it["blockers"]:
            errs.append(f"{mc}: non-complete item names no blocker")
        if it["status"] == "implemented_unreviewed" and (not it["implementation"] or not it["tests"]):
            errs.append(f"{mc}: implemented without implementation+test refs")
        for r in it["implementation"] + it["tests"]:
            why = resolve(r)
            if why:
                errs.append(f"{mc}: {why}")
        for r in it["evidence"]:
            why = resolve(r, allow_missing_evidence=not evidence_required)
            if why:
                errs.append(f"{mc}: {why}")
    return errs


def render(src: dict) -> tuple[dict, str]:
    rows = [{"mc": k, **v} for k, v in sorted(src["items"].items())]
    summ = {"all": dict(Counter(r["status"] for r in rows)),
            "P0": dict(Counter(r["status"] for r in rows if r["priority"] == "P0")),
            "P2": dict(Counter(r["status"] for r in rows if r["priority"] == "P2"))}
    doc = {"schema": "PK_MC_STATUS/1", "component": "INV-28", "version": src["version"],
           "applied_checklist": src["applied_checklist"], "summary": summ, "rows": rows}
    md = [f"# INV-28 missing-components status - v{src['version']} (generated by tools/rtm.py)", "",
          f"Applied: `{src['applied_checklist']}`", "",
          "Legend: " + "; ".join(f"**{k}** = {v}" for k, v in src["status_values"].items()), "",
          f"All 100: {summ['all']}  ", f"P0 ({sum(summ['P0'].values())}): {summ['P0']}  ",
          f"P2 ({sum(summ['P2'].values())}): {summ['P2']}", "",
          "| MC | item | pri | status | owner | implementation | verification | open blocker(s) |",
          "|---|---|---|---|---|---|---|---|"]
    for r in rows:
        impl = "<br>".join(f"`{x}`" for x in r["implementation"][:3])
        ver = "<br>".join(f"`{x}`" for x in (r["tests"] + r["evidence"])[:3])
        blk = "; ".join(b for b in r["blockers"] if not b.startswith("independent review")) or "independent review"
        md.append(f"| {r['mc']} | {r['title']} | {r['priority']} | **{r['status']}** | {r['owner']} | {impl} | {ver} | {blk} |")
    return doc, "\n".join(md) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--no-evidence", action="store_true", help="allow evidence files not generated yet")
    a = ap.parse_args(argv)
    src = read_json(ROOT / "ops" / "MC_STATUS.json")
    errs = validate(src, evidence_required=not a.no_evidence)
    for e in errs:
        print("FAIL", e)
    doc, md = render(src)
    if not a.check:
        write_json(EVIDENCE / "MC_STATUS.json", doc)
        (ROOT / "ops" / "MC_STATUS.md").write_text(md, encoding="utf-8")
    print("MC_STATUS", "PASS" if not errs else "FAIL", doc["summary"]["all"])
    return 0 if not errs else 1


if __name__ == "__main__":
    sys.exit(main())
