"""Item-level mapping for the 420 component-specific controls (NN.01-NN.12).
Value: (state, [evidence refs], note).  R = EVIDENCE_READY (implemented; every ref must
pass in the evidence run or the item is downgraded), P = IN_PROGRESS (partly done; the
note names the gap), B = BLOCKED (needs an input this build cannot supply).
No item is VERIFIED: that needs an independent reviewer (see verify_release)."""
T = lambda *xs: ["T:" + x for x in xs]
A = lambda *xs: ["A:" + x for x in xs]
G = lambda *xs: ["G:" + x for x in xs]
X = lambda *xs: ["X:" + x for x in xs]
NOCORE = "real pk_core not supplied; lock UNRESOLVED"
NOWASI = "no WASI 0.2 runtime / compiled component / WIT toolchain available"
NOINV15 = "real INV-15 not supplied; proven against protocol only"
NOREV = "needs an independent reviewer/approver record"
NOOWN = "owners UNASSIGNED"

M = {
 "01.01": ("P", A("deps/pk_core.lock.json"), "declaration exists (name, interpreter range, policy); version/source/digest UNRESOLVED: " + NOCORE),
 "01.02": ("P", T("C01PkCorePin.test_c01_floating_and_mutable_pins_rejected"), "rejection of floating/mutable pins implemented; the pin itself awaits the core"),
 "01.03": ("B", A("deps/pk_core.lock.json"), "transitive lock cannot be produced: " + NOCORE),
 "01.04": ("R", A("deps/pk_core.lock.json"), "production path (vendored, tree-digest pinned) and offline path declared in the lock"),
 "01.05": ("R", T("C01PkCorePin.test_c01_probe_absent_version_hash_api_ok_paths", "C01PkCorePin.test_c01_api_incompatible_core_refused"), "probe checks symbols/version/digest against a fixture core; real schema/behavioural capability checks need the real core"),
 "01.06": ("R", T("C01PkCorePin", "C27ReleasePipeline.test_c27_missing_pk_core_blocks_release_exit_2"), "stable PK_CORE_* codes; gate exits 2 (BLOCKED) with the code"),
 "01.07": ("B", [], "clean-room venv bootstrap of pk_core impossible: " + NOCORE + " (INV-14 itself is clean-room tested from the zip)"),
 "01.08": ("B", [], "resolver-conflict test needs pk_core's dependency graph: " + NOCORE),
 "01.09": ("P", T("C00Diagnostics"), "version/hash in diagnostics and release report; audit/certification-report inclusion pending a real pin"),
 "01.10": ("B", G("pk_core_pinned_and_compatible"), "100-item assessment cannot run: " + NOCORE),
 "01.11": ("R", A("deps/pk_core.lock.json"), "upgrade/downgrade policy recorded in lock"),
 "01.12": ("B", A("sbom/dependency_scan.json"), "scan of pk_core INDETERMINATE until pinned"),
 "02.01": ("R", A("wit/inv14-legacy-poll.wit") + T("C03Contracts.test_c03_wit_records_match_json_schemas"), "world inv14-legacy-host imports wasi:io/poll@0.2.0 and wasi:clocks/monotonic-clock@0.2.0"),
 "02.02": ("P", A("wit/inv14-legacy-poll.wit"), "authoritative WIT present; not validated by a WIT parser: " + NOWASI),
 "02.03": ("B", [], "bindings generation needs wit-bindgen/jco: " + NOWASI),
 "02.04": ("R", T("C02WasiAdapter"), "translation layer over integer handles (no Python identity crosses the boundary); proven on the reference host"),
 "02.05": ("P", T("C02WasiAdapter.test_c02_empty_set_refused_before_trap_and_timer_dropped"), "timer drop on all paths; member-handle double-drop/use-after-drop is the runtime's resource table: " + NOWASI),
 "02.06": ("R", T("C02WasiAdapter.test_c02_foreign_duplicate_and_limit_refusals"), "adapter errors map to PK_POLL_ERROR/1; runtime traps unmapped until a runtime exists"),
 "02.07": ("R", T("C02WasiAdapter.test_c02_tick_to_wasi_duration_is_exact_integer", "C16Clock"), "ticks*tick_ns -> subscribe-duration"),
 "02.08": ("P", T("C02WasiAdapter"), "zero/immediate/delayed/multiple/timeout/foreign/empty fixtures on reference host; invalid-resource and resource-drop fixtures need a real runtime"),
 "02.09": ("B", [], NOWASI),
 "02.10": ("P", T("C02WasiAdapter.test_c02_empty_set_refused_before_trap_and_timer_dropped"), "return/timeout cleanup proven on reference host; trap/termination/shutdown need a runtime"),
 "02.11": ("B", [], "interop traces need a real runtime: " + NOWASI),
 "02.12": ("B", G("wasi_0_2_interop"), "gate exists and is BLOCKED: " + NOWASI),
 "03.01": ("R", T("C03Contracts.test_c03_wit_records_match_json_schemas") + A("schemas/pk_poll.schema.json", "schemas/pk_pollable.schema.json", "schemas/pk_poll_error.schema.json", "schemas/pk_poll_metrics.schema.json"), ""),
 "03.02": ("R", A("docs/CONTRACT_POLICY.md", "schemas/pk_poll.schema.json"), "widths/bounds/ordering/uniqueness/max sizes in policy + schema"),
 "03.03": ("R", A("docs/CONTRACT_POLICY.md") + T("C16Clock.test_c16_config_validation_bounds"), ""),
 "03.04": ("R", A("schemas/error_codes.json") + T("C00Diagnostics.test_c00_error_registry_has_retry_class_and_action_for_every_code"), "string ids + WIT enum + retry class + caller action + details policy"),
 "03.05": ("R", A("docs/CONTRACT_POLICY.md"), "ordering/duplicates/removal semantics defined"),
 "03.06": ("R", A("schemas/pk_poll_metrics.schema.json", "docs/CONTRACT_POLICY.md"), ""),
 "03.07": ("R", A("docs/CONTRACT_POLICY.md"), ""),
 "03.08": ("R", T("C21ContractFixtures"), "8 golden + 27 negative fixtures incl. unknown-field and version cases"),
 "03.09": ("R", T("C03Contracts.test_c03_generated_contracts_are_current"), "error enum generated into registry, WIT and schema"),
 "03.10": ("R", T("C21ContractFixtures.test_c21_golden_matches_current_behaviour"), "field-level golden comparison"),
 "03.11": ("R", T("C03Contracts.test_c03_every_schema_is_versioned", "C00Diagnostics"), "ids + digests in diagnostics; manifest hashes"),
 "03.12": ("B", A("docs/CONTRACT_POLICY.md", "CODEOWNERS"), "review gate defined; approval requires a named reviewer: " + NOREV),
 "04.01": ("P", A("migration.py"), "readiness/timeout/cancel mapping documented in module; field-by-field mapping to real INV-15 awaits its ABI"),
 "04.02": ("R", T("C04Migration"), "versioned forward/reverse shims (protocol-level)"),
 "04.03": ("P", T("C04Migration.test_c04_forward_shim_cancel_is_idempotent"), "type mismatches refused with PK_MIGRATION_*; full unsupported-difference list needs INV-15"),
 "04.04": ("R", T("C04Migration.test_c04_parity_between_legacy_and_shim"), "dual-path parity harness"),
 "04.05": ("P", T("C04Migration.test_c04_state_machine_requires_parity_and_allows_rollback"), "LEGACY/DUAL_STACK/CANARY/MIGRATED/ROLLED_BACK; inventory/eligible/exception/blocked stages live in the registry, not the machine"),
 "04.06": ("R", T("C13MigrationRegistry", "C04Migration"), "per-consumer machine + registry gate"),
 "04.07": ("P", T("C11Tracing.test_c11_service_returns_child_traceparent"), "correlation/trace carried by the service; not yet threaded through the shims"),
 "04.08": ("R", T("C04Migration.test_c04_state_machine_requires_parity_and_allows_rollback"), "rollback legal from DUAL_STACK/CANARY; no readiness state is owned by the bridge"),
 "04.09": ("P", T("C04Migration.test_c04_parity_between_legacy_and_shim"), "immediate/delayed/timeout parity; cancellation/ownership/restart/overload parity pending INV-15"),
 "04.10": ("B", [], "bridge overhead budget needs real INV-15 to compare: " + NOINV15),
 "04.11": ("P", [], "stage history exists; no exported migration metric series yet"),
 "04.12": ("R", T("C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused", "C35Eol"), "MIGRATED regression refused; bridge removed with EOL REMOVED"),
 "05.01": ("R", T("C05Cancellation"), "states active -> cancelled (latched, terminal)"),
 "05.02": ("R", T("C05Cancellation.test_c05_precancelled_token_and_readiness_wins_tie"), "ready > cancel > timeout; disable refuses before wait"),
 "05.03": ("R", T("C05Cancellation.test_c05_cancel_wakes_blocked_poll_with_structured_error") + A("schemas/error_codes.json"), "PK_POLL_CANCELLED retry_class=caller"),
 "05.04": ("R", T("C05Cancellation.test_c05_cancel_race_stress_no_leak_no_hang", "C23Concurrency.test_c23_exhaustive_model_check_and_mutant_detected"), ""),
 "05.05": ("R", T("C05Cancellation.test_c05_cancel_is_idempotent_and_token_type_checked"), ""),
 "05.06": ("R", T("C05Cancellation.test_c05_precancelled_token_and_readiness_wins_tie"), "ready result wins and does not consume readiness (level-triggered); cancel after completion is a no-op"),
 "05.07": ("B", [], "WASI/INV-15 cancellation propagation: " + NOWASI + "; " + NOINV15),
 "05.08": ("P", T("C05Cancellation.test_c05_cancel_wakes_blocked_poll_with_structured_error"), "polls_cancelled counter + outcome=cancelled; late-cancel and cancellation-latency series not yet"),
 "05.09": ("R", T("C05Cancellation"), "pre-cancel, during-wait, after-ready, races"),
 "05.10": ("R", T("C05Cancellation.test_c05_cancel_race_stress_no_leak_no_hang") + X("interleave"), ""),
 "05.11": ("R", A("polling.py"), "tokens are unaddressable caller-held objects; no API cancels by id"),
 "05.12": ("P", A("schemas/error_codes.json", "wit/inv14-legacy-poll.wit"), "in error schema/WIT enum; bridge + runbook coverage partial"),
 "06.01": ("P", T("C06Admission"), "global + per-tenant + per-process poll-set registry cap; per-component ceiling not separate"),
 "06.02": ("R", T("C06Admission.test_c06_bounded_fifo_queue_and_timeout"), "queue_depth=0 default; bounded FIFO when enabled"),
 "06.03": ("R", A("admission.py"), "strict per-tenant quota (ADM-5)"),
 "06.04": ("R", T("C06Admission.test_c06_global_and_tenant_ceilings_shed_deterministically") + A("schemas/error_codes.json"), "quota vs transient distinguished"),
 "06.05": ("R", A("schemas/error_codes.json"), "jittered exponential backoff guidance on PK_POLL_OVERLOADED"),
 "06.06": ("R", T("C12EmergencyDisable") + A("service.py"), "admission precedes PollSet/waiter allocation"),
 "06.07": ("P", A("lifecycle.py"), "DRAINING sheds all new legacy polls; no privileged class exists in INV-14 to starve others"),
 "06.08": ("P", T("C06Admission"), "active/queued/peak/shed in snapshot; queue age and fairness deviation not exported"),
 "06.09": ("R", T("C25Soak") + X("soak"), "burst beyond limits, deterministic shed, recovery"),
 "06.10": ("P", T("C25Soak"), "300-tenant mixed load; no dedicated adversarial-vs-latency-sensitive assertion"),
 "06.11": ("R", T("C30Config"), "limits in PK_POLL_CONFIG/1 with provenance + atomic update"),
 "06.12": ("R", A("config.py"), "defaults 1024 global / 64 tenant / no queue; v4.2.0 small workloads unaffected (12 tests pass)"),
 "07.01": ("R", A("identity.py"), "HMAC capability token from a trusted issuer key"),
 "07.02": ("P", T("C07Identity"), "tenant/component/instance subject, issuer kid, rights, expiry signed; audience claim not implemented"),
 "07.03": ("R", T("C07Identity.test_c07_malformed_tokens_and_principals"), "lower-case ASCII segments"),
 "07.04": ("P", T("C07Identity"), "issuer/kid/signature/exp/nbf/right checked before ownership; no audience"),
 "07.05": ("B", [], "no nonce/session store; short TTL bearer tokens only -- replay window = TTL"),
 "07.06": ("P", T("C07Identity.test_c07_right_and_key_rotation"), "multi-key rotation; no revocation list"),
 "07.07": ("R", A("service.py") + T("C31Redaction.test_c31_error_details_and_diagnostics_carry_no_secrets"), "verify() before any PollSet touch"),
 "07.08": ("R", T("C07Identity.test_c07_refusal_does_not_disclose_other_principal"), ""),
 "07.09": ("R", T("C08Audit") + A("service.py"), "poll.refused.identity / foreign_owner audited"),
 "07.10": ("P", T("C07Identity"), "tamper, cross-tenant, stale kid, Unicode segments; no audience/revocation cases"),
 "07.11": ("R", T("C07Identity.test_c07_malformed_tokens_and_principals"), "no trust root => PK_POLL_NO_TRUST_ROOT (fail closed)"),
 "07.12": ("P", A("schemas/error_codes.json", "docs/RUNBOOK.md"), "codes in contracts, runbook R3; WIT carries no token field yet"),
 "08.01": ("P", A("schemas/pk_poll_audit.schema.json"), "seq, ts, event, correlation, details, prev, mac; no separate principal/policy-version fields"),
 "08.02": ("R", A("audit.py"), "closed EVENT_TYPES incl. refusals, deprecated use, lifecycle, config, migration, cancel"),
 "08.03": ("B", [], "append-only local file only; approved durable sink not available"),
 "08.04": ("R", T("C08Audit.test_c08_chain_verifies_and_detects_edit_delete_reorder_truncate"), "hash chain + HMAC + external head"),
 "08.05": ("R", T("C08Audit.test_c08_reopen_resumes_and_corrupt_log_refused"), "seq continues across restart; ts is recorded, ordering by seq"),
 "08.06": ("P", A("audit.py"), "at-most-once per append; seq is the dedup id; no retry layer"),
 "08.07": ("P", A("audit.py"), "synchronous append, fail-closed; bounded async buffer not implemented"),
 "08.08": ("R", T("C08Audit.test_c08_unwritable_sink_fails_closed_and_secrets_redacted"), ""),
 "08.09": ("B", [], "retention/legal hold/access needs an owner: " + NOOWN),
 "08.10": ("R", T("C08Audit") + T("C33Runbook"), "verify_chain + runbook verify-audit"),
 "08.11": ("P", T("C08Audit") + X("faults"), "outage, corrupt chain, restart, key mismatch; partial write/duplicate/full buffer not covered"),
 "08.12": ("P", T("C00Diagnostics"), "audit_head in diagnostics; no backlog metric/alert"),
 "09.01": ("R", A("telemetry.py", "ops/dashboard.json"), ""),
 "09.02": ("R", A("telemetry.py"), "counter/histogram, ms units, process-local reset"),
 "09.03": ("R", T("C09Telemetry.test_c09_prometheus_exposition_parses_with_stable_labels", "C09Telemetry.test_c09_otlp_json_shape"), "Prometheus text + OTLP/JSON body"),
 "09.04": ("R", T("C09Telemetry.test_c09_prometheus_exposition_parses_with_stable_labels"), ""),
 "09.05": ("R", T("C09Telemetry.test_c09_tenant_cardinality_is_bounded"), ""),
 "09.06": ("R", A("telemetry.py"), "pull-based; record() is O(1) under a lock and cannot block on I/O"),
 "09.07": ("P", T("C09Telemetry.test_c09_sampling_applies_to_latency_only"), "samples_dropped exposed; exporter health/last-success belong to the collector"),
 "09.08": ("P", X("bench"), "buckets 1..60000 ms informed by bench; set-size histogram not exported"),
 "09.09": ("R", A("docs/CONTRACT_POLICY.md"), "process-local, process_epoch marks resets"),
 "09.10": ("P", T("C09Telemetry"), "high rate, cardinality attack, sampling; endpoint failure N/A without a collector"),
 "09.11": ("R", A("ops/dashboard.json", "ops/alerts.yml") + T("C32DashboardAlerts"), ""),
 "09.12": ("R", A("docs/CONTRACT_POLICY.md"), ""),
 "10.01": ("R", T("C10Logging.test_c10_records_match_schema_with_stable_ids_and_redaction"), ""),
 "10.02": ("P", A("pollog.py", "audit.py"), "operation vocabulary closed; event names follow <op>.<outcome> but are not a closed enum"),
 "10.03": ("R", T("C12EmergencyDisable") + A("service.py"), "code= field in refusal logs"),
 "10.04": ("R", T("C31Redaction"), ""),
 "10.05": ("R", T("C10LoggingService.test_c10_injection_safe_single_line_with_monotonic_duration"), ""),
 "10.06": ("P", A("pollog.py"), "security refusals always WARN and audited; no configurable sampling yet"),
 "10.07": ("R", T("C10Logging.test_c10_records_match_schema_with_stable_ids_and_redaction"), "4 KiB bound, _truncated marker"),
 "10.08": ("R", T("C11Tracing.test_c11_service_returns_child_traceparent") + A("service.py"), "correlation id propagated or created; never a metric label"),
 "10.09": ("R", T("C10LoggingService.test_c10_injection_safe_single_line_with_monotonic_duration"), ""),
 "10.10": ("R", T("C10Logging", "C10LoggingService"), ""),
 "10.11": ("R", A("pollog.py") + T("C10Logging.test_c10_unknown_level_and_operation_are_normalised_and_stream_failure_counted"), "backend failure -> dropped counter; transport is integration-owned"),
 "10.12": ("R", A("pollog.py"), ""),
 "11.01": ("R", A("tracing.py"), "W3C Trace Context level 1"),
 "11.02": ("R", T("C11Tracing.test_c11_service_returns_child_traceparent"), "traceparent/tracestate kwargs"),
 "11.03": ("P", A("tracing.py"), "child span id created; no span object/attributes exported"),
 "11.04": ("R", A("tracing.py"), "only ids and bounded tracestate carried"),
 "11.05": ("B", [], NOWASI + "; " + NOINV15),
 "11.06": ("B", [], "span links need a span exporter"),
 "11.07": ("R", T("C11Tracing.test_c11_invalid_parent_starts_new_root_and_is_flagged"), ""),
 "11.08": ("R", T("C11Tracing.test_c11_invalid_parent_starts_new_root_and_is_flagged"), "tracestate <= 512 / 32 members"),
 "11.09": ("R", A("service.py"), "audit written regardless of trace flags"),
 "11.10": ("P", T("C11Tracing"), "sampled/missing/malformed; adapter hops pending"),
 "11.11": ("B", [], "no tracing backend"),
 "11.12": ("R", A("docs/RUNBOOK.md") + T("C10Logging"), "trace_id + correlation_id in every log; correlation_id in audit"),
 "12.01": ("P", A("lifecycle.py", "schemas/pk_poll_lifecycle.json"), "enabled/deprecated/draining/disabled/quarantined; warn-only and deny-new modes not separate"),
 "12.02": ("R", A("service.py"), "lifecycle.enter() is the first check"),
 "12.03": ("R", T("C12EmergencyDisable.test_c12_disable_refuses_new_polls_drains_inflight_then_rolls_back"), "in-flight allowed to finish"),
 "12.04": ("R", A("lifecycle.py"), "single condition variable"),
 "12.05": ("B", [], "actor recorded but not authenticated: no admin identity provider"),
 "12.06": ("P", T("C33Runbook"), "runbook transitions audited with actor; previous value not stored in the record"),
 "12.07": ("B", [], "break-glass needs time-limited admin authorisation"),
 "12.08": ("B", [], "no fleet deployment exists"),
 "12.09": ("R", T("C12EmergencyDisable", "C33Runbook"), "rollback under active load tested"),
 "12.10": ("P", T("C12EmergencyDisable", "C14Lifecycle"), "disable vs in-flight, repeated toggles; unauthorised change/stale policy not testable yet"),
 "12.11": ("R", T("C00Diagnostics"), "lifecycle state + model version"),
 "12.12": ("R", A("ops/alerts.yml", "docs/RUNBOOK.md") + T("C32DashboardAlerts"), "every alert links a runbook anchor"),
 "13.01": ("P", A("governance/MIGRATION_REGISTRY.json") + T("C13MigrationRegistry"), "id/owner/stage/dates; tenant/environment/API versions fields not yet"),
 "13.02": ("R", T("C34Waivers"), "waivers carry owner/approver/expiry/commitment"),
 "13.03": ("B", [], "no production telemetry to reconcile against"),
 "13.04": ("R", T("C04Migration"), ""),
 "13.05": ("P", A("governance.py"), "ConsumerGate API; no report CLI"),
 "13.06": ("B", [], "needs usage telemetry"),
 "13.07": ("R", T("C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused") + A("ops/alerts.yml"), "PK_POLL_MIGRATION_REGRESSION + Inv14MigrationRegression"),
 "13.08": ("P", A("ops/alerts.yml"), "refusal alerts exist; pre-deadline alerts need a scheduler"),
 "13.09": ("P", T("C04Migration"), "parity record gates advancement; canary windows are operational"),
 "13.10": ("P", A("MANIFEST.sha256"), "registry versioned with the package; no separate history store"),
 "13.11": ("R", A("service.py"), "consumer_gate evaluated in the poll path"),
 "13.12": ("B", [], "closure workflow needs governance owner"),
 "14.01": ("P", A("schemas/pk_poll_lifecycle.json"), "7 states; RETIRED represented by EOL REMOVED"),
 "14.02": ("P", A("schemas/pk_poll_lifecycle.json", "lifecycle.py"), "table + actor/reason; per-edge authorisation not implemented"),
 "14.03": ("R", T("C14Lifecycle.test_c14_every_illegal_transition_refused_and_state_unchanged"), ""),
 "14.04": ("R", T("C14Lifecycle.test_c14_admission_by_state_and_artifact_matches_code"), ""),
 "14.05": ("P", A("checkpoint.py"), "single process: checkpoint is source of truth; distributed N/A"),
 "14.06": ("R", T("C00Diagnostics"), "PK_POLL_LIFECYCLE/1 in diagnostics"),
 "14.07": ("R", T("C12EmergencyDisable"), "enter() and transition() share one lock"),
 "14.08": ("P", T("C33Runbook"), "transitions audited; no lifecycle metric"),
 "14.09": ("R", T("C14Lifecycle.test_c14_admission_by_state_and_artifact_matches_code"), "table checked against machine model"),
 "14.10": ("R", T("C14Lifecycle"), "all 42 ordered pairs"),
 "14.11": ("R", T("C12EmergencyDisable.test_c12_drain_timeout_leaves_draining_not_disabled"), ""),
 "14.12": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md", "docs/RUNBOOK.md", "governance/EOL_POLICY.json"), ""),
 "15.01": ("R", A("checkpoint.py"), "RST-1..4 classification"),
 "15.02": ("R", A("checkpoint.py"), "RST-4: not replayed; caller retries"),
 "15.03": ("P", T("C00Diagnostics"), "process_epoch exists; pollable handles are in-process objects and cannot outlive the process"),
 "15.04": ("R", T("C15Restart.test_c15_checkpoint_roundtrip_never_persists_readiness"), "level-triggered, re-derived"),
 "15.05": ("R", A("docs/CONTRACT_POLICY.md", "checkpoint.py"), ""),
 "15.06": ("R", T("C15Restart"), ""),
 "15.07": ("R", A("checkpoint.py"), "polls are idempotent readiness reads"),
 "15.08": ("P", A("tools/runbook.py"), "status restores checkpoint; automatic reconcile-before-accept not wired"),
 "15.09": ("P", X("faults"), "SIGKILL during blocking wait; other kill points not injected"),
 "15.10": ("P", T("C15Restart.test_c15_atomic_save_leaves_no_temp_files"), "repeated save bounded; no restart-loop harness"),
 "15.11": ("P", T("C00Diagnostics"), "epoch in diagnostics and poll logs; not in audit records"),
 "15.12": ("R", A("checkpoint.py", "docs/adr/ADR-0001-retain-legacy-poll-model.md"), ""),
 "16.01": ("R", A("clock.py", "schemas/pk_clock_config.schema.json"), ""),
 "16.02": ("R", A("clock.py"), "monotonic only; wall source refused"),
 "16.03": ("R", T("C02WasiAdapter.test_c02_tick_to_wasi_duration_is_exact_integer", "C16Clock"), "integer arithmetic, rejection at ceiling"),
 "16.04": ("R", A("docs/CONTRACT_POLICY.md"), "no rounding"),
 "16.05": ("R", A("docs/CONTRACT_POLICY.md") + T("C16Clock.test_c16_config_validation_bounds"), "zero refused; tick*max <= 60 s"),
 "16.06": ("P", T("C16Clock.test_c16_backward_clock_cannot_extend_wait") + X("faults"), "jumps/anomalies bounded; suspend/VM pause not simulated"),
 "16.07": ("R", A("docs/CONTRACT_POLICY.md"), "after validation, at registration"),
 "16.08": ("R", T("C00Diagnostics"), ""),
 "16.09": ("R", T("C16Clock", "C03Contracts") + ["T:PollingPrimitiveTest.test_identity_and_limit_validation"], ""),
 "16.10": ("R", T("C16Clock.test_c16_backward_clock_cannot_extend_wait"), "injectable clock"),
 "16.11": ("P", T("C02WasiAdapter.test_c02_timeout_maps_timer_index_to_timed_out"), "Python vs reference adapter; real runtime pending"),
 "16.12": ("R", A("docs/CONTRACT_POLICY.md"), ""),
 "17.01": ("B", A("governance/OWNERS.json"), NOOWN),
 "17.02": ("B", A("CODEOWNERS"), "paths mapped; team handles " + NOOWN),
 "17.03": ("B", A("governance/OWNERS.json"), NOOWN),
 "17.04": ("B", [], NOOWN),
 "17.05": ("P", A("governance/OWNERS.json"), "support boundary written; hours/targets need owner"),
 "17.06": ("P", A("docs/RUNBOOK.md", "ops/dashboard.json"), "runbook/dashboard refs; service catalog/change system unknown"),
 "17.07": ("P", A("MANIFEST.sha256"), "versioned with package"),
 "17.08": ("R", T("C17Owners"), "validator + blocker"),
 "17.09": ("B", [], NOREV),
 "17.10": ("R", T("C13MigrationRegistry.test_c13_registry_validation"), "owner required per consumer"),
 "17.11": ("R", T("C13MigrationRegistry"), "unregistered/ownerless consumer refused"),
 "17.12": ("R", A("governance/OWNERS.json"), "roles, no personal names"),
 "18.01": ("P", A("docs/adr/ADR-0001-retain-legacy-poll-model.md"), "numbered, status PROPOSED; deciders absent"),
 "18.02": ("P", A("docs/adr/ADR-0001-retain-legacy-poll-model.md"), "rationale stated; concrete consumers unknown"),
 "18.03": ("P", [], "alternatives not yet enumerated in the ADR"),
 "18.04": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md", "docs/COMPONENT_SPECS.md"), ""),
 "18.05": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md") + X("bench"), ""),
 "18.06": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md", "MISSING_COMPONENTS.md", "checkpoint.py"), "restart semantics in ADR limits + RST-1..4; blockers vs follow-on listed in CHANGELOG release verdict"),
 "18.07": ("R", A("governance/EOL_POLICY.json", "governance/WAIVERS.json"), ""),
 "18.08": ("R", A("docs/COMPATIBILITY_MATRIX.json"), ""),
 "18.09": ("R", A("docs/COMPONENT_SPECS.md"), ""),
 "18.10": ("P", A("docs/adr/ADR-0001-retain-legacy-poll-model.md"), "links to lifecycle/runbook implicit; add explicit links"),
 "18.11": ("B", A("CODEOWNERS"), NOREV),
 "18.12": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md"), "first ADR; nothing superseded"),
 "19.01": ("R", A("docs/COMPATIBILITY_MATRIX.json"), ""),
 "19.02": ("R", T("C19CompatMatrix"), "UNTESTED is never supported"),
 "19.03": ("P", A("deps/pk_core.lock.json"), "python_requires >=3.10,<3.14; known-bad list empty"),
 "19.04": ("P", A("ci/release.yml"), "matrix defined; not executed on a CI service"),
 "19.05": ("P", A("ci/release.yml"), "arm64 runner declared; not executed"),
 "19.06": ("B", [], NOWASI),
 "19.07": ("P", A("evidence/environment.json"), "exact interpreter/platform for the one executed cell"),
 "19.08": ("B", [], "no prior supported release to roll back to"),
 "19.09": ("R", A("docs/COMPATIBILITY_MATRIX.json"), ""),
 "19.10": ("B", [], NOREV),
 "19.11": ("P", A("core_probe.py"), "interpreter range enforced by probe"),
 "19.12": ("R", A("evidence/test_results.json"), "archived with release"),
 "20.01": ("B", [], "INV-13/INV-15/GAP-15 not supplied"),
 "20.02": ("B", T("C20Adjacent"), "tests written against real modules; skipped: layers absent"),
 "20.03": ("B", T("C20Adjacent"), "layers absent"),
 "20.04": ("B", [], "layers absent"),
 "20.05": ("B", [], "layers absent"),
 "20.06": ("B", [], "layers absent"),
 "20.07": ("R", T("C01PkCorePin", "C27ReleasePipeline"), "version mismatch fails closed"),
 "20.08": ("B", [], "layers absent"),
 "20.09": ("R", A("tests/_support.py"), "stdlib-only, temp dirs, no network"),
 "20.10": ("R", T("C27ReleasePipeline.test_c27_release_mode_turns_absent_layers_into_failures"), ""),
 "20.11": ("R", A("evidence/test_results.json"), ""),
 "20.12": ("R", A("verify_release.py"), "--skip-slow smoke vs full"),
 "21.01": ("R", T("C21ContractFixtures.test_c21_golden_fixtures_validate"), ""),
 "21.02": ("R", T("C21ContractFixtures.test_c21_golden_matches_current_behaviour"), ""),
 "21.03": ("R", T("C21ContractFixtures.test_c21_negative_fixtures_are_rejected"), ""),
 "21.04": ("R", T("C21ContractFixtures.test_c21_negative_fixtures_are_rejected"), "extra_property negatives; policy in CONTRACT_POLICY"),
 "21.05": ("R", T("C21ContractFixtures.test_c21_negative_fixtures_are_rejected"), "wrong_schema_const (future major) rejected"),
 "21.06": ("R", ["T:PollingPrimitiveTest.test_duplicate_handle_and_duplicate_name_are_refused"] + T("C21ContractFixtures"), ""),
 "21.07": ("R", T("C00Diagnostics.test_c00_error_registry_has_retry_class_and_action_for_every_code", "C03Contracts.test_c03_error_schema_enum_equals_code_registry"), ""),
 "21.08": ("R", T("C21ContractFixtures", "C09Telemetry.test_c09_prometheus_exposition_parses_with_stable_labels"), ""),
 "21.09": ("B", [], NOWASI),
 "21.10": ("R", A("MANIFEST.sha256") + T("C21ContractFixtures.test_c21_golden_matches_current_behaviour"), ""),
 "21.11": ("R", T("C02WasiAdapter.test_c02_ready_indexes_exclude_timer_and_match_python_semantics"), "reference vs adapter"),
 "21.12": ("R", A("schema_check.py", "tests/fixtures/golden"), "python3 schema_check.py usable by downstream"),
 "22.01": ("P", X("fuzz"), "poll/token/config/trace targets; schema-decoding target separate not built"),
 "22.02": ("R", A("tools/fuzz.py"), "structure-aware mutation of valid documents"),
 "22.03": ("P", A("tools/fuzz.py"), "seeded from valid config/token; golden corpus not loaded"),
 "22.04": ("R", A("tools/fuzz.py"), "unicode, extremes, type confusion, duplicates"),
 "22.05": ("R", A("tools/fuzz.py"), "structured-code oracle + schema-valid result + 2 s per input"),
 "22.06": ("P", A("tools/fuzz.py"), "time limit; no memory limit"),
 "22.07": ("R", T("C22Fuzz.test_c22_regression_D02_non_json_config_is_structured", "C22Fuzz.test_c22_regression_D03_unknown_provenance_key_refused"), "findings promoted to regression tests"),
 "22.08": ("R", A("evidence/fuzz.json"), "seed, iterations, per-target counts"),
 "22.09": ("P", A("verify_release.py"), "8,000-iteration release budget; no scheduled campaign"),
 "22.10": ("B", [], "no coverage tool in stdlib environment"),
 "22.11": ("P", A("docs/DEFECTS.json"), ""),
 "22.12": ("R", A("tools/fuzz.py"), "in-process, no network/files"),
 "23.01": ("R", A("tools/interleave.py"), ""),
 "23.02": ("R", A("tools/interleave.py"), "S1 (latch under lock) and REG are the linearisation points"),
 "23.03": ("R", X("interleave"), "exhaustive state exploration"),
 "23.04": ("P", X("interleave"), "signal before/during/after register, clear-vs-signal, cancel-vs-ready; disable-vs-register covered by C12"),
 "23.05": ("R", T("C23Concurrency.test_c23_thread_stress_clear_vs_signal_multi_set") + ["T:PollingPrimitiveTest.test_multiple_waiters_receive_same_level_trigger"], ""),
 "23.06": ("R", X("interleave") + T("C23Concurrency"), ""),
 "23.07": ("P", T("C23Concurrency", "C25Soak"), "randomised threads; no process-level repetition"),
 "23.08": ("B", [], "no native bindings exist yet"),
 "23.09": ("R", A("tools/interleave.py"), "counterexample states returned"),
 "23.10": ("R", T("C05Cancellation.test_c05_cancel_race_stress_no_leak_no_hang"), ""),
 "23.11": ("P", T("C12EmergencyDisable"), "policy transitions under load; restart not in campaigns"),
 "23.12": ("R", G("interleave_model_check"), "release gate requires zero violations"),
 "24.01": ("P", X("bench"), "ready/wake/timeout/fan-out/import separated; per-phase split not instrumented"),
 "24.02": ("P", X("bench"), "p50/p95/p99/max; no p90/p99.9/variance"),
 "24.03": ("R", X("bench"), "1, 64, 1024, 4096"),
 "24.04": ("R", X("bench"), "timeout_overshoot separate"),
 "24.05": ("P", X("soak"), "saturation via soak; not a stepped concurrency sweep"),
 "24.06": ("P", X("bench"), "wall time, alloc peak; CPU/RSS/threads not"),
 "24.07": ("B", [], NOWASI + "; " + NOINV15),
 "24.08": ("P", A("evidence/bench.json"), "host metadata; no affinity/power control"),
 "24.09": ("B", A("ops/perf_thresholds.json"), "PROPOSED thresholds: " + NOREV),
 "24.10": ("P", A("tools/bench.py"), "repeated samples; no statistical comparison"),
 "24.11": ("P", A("evidence/bench.json"), "summaries archived; raw samples not"),
 "24.12": ("R", G("bench_thresholds"), "gate compares against thresholds (PROPOSED)"),
 "25.01": ("P", A("tools/soak.py"), "one profile (200-300 tenants, mixed ready/timeout)"),
 "25.02": ("B", [], "long-duration soak not run in this environment"),
 "25.03": ("R", X("soak"), "4x burst"),
 "25.04": ("R", T("C25Soak"), "300 tenants, telemetry bounded"),
 "25.05": ("P", X("soak"), "counts/shed/waiters/audit; memory/GC not"),
 "25.06": ("R", X("soak"), "zero active/in-flight/waiters after"),
 "25.07": ("B", [], "no rolling-restart harness"),
 "25.08": ("P", X("soak"), "mixed tenants; abusive class not separated"),
 "25.09": ("P", X("faults"), "audit loss (F3) outside soak"),
 "25.10": ("R", A("tools/soak.py"), "numeric invariants"),
 "25.11": ("P", A("evidence/soak.json"), "summary archived"),
 "25.12": ("R", G("soak_burst"), "short burst per release"),
 "26.01": ("R", A("tools/faults.py"), ""),
 "26.02": ("P", X("faults"), "jumps via fake clock; suspend/resume not"),
 "26.03": ("P", X("faults"), "admission exhaustion (soak), dropped timer; waiter-registration failure not injected"),
 "26.04": ("R", A("tools/faults.py"), "boundary recorded: no networked layer inside INV-14 (proposed N/A needs reviewer)"),
 "26.05": ("R", A("tools/faults.py"), ""),
 "26.06": ("R", X("faults"), ""),
 "26.07": ("R", A("tools/faults.py"), "deterministic triggers"),
 "26.08": ("P", X("faults"), "before admission, during wait; not every boundary"),
 "26.09": ("R", T("C33Runbook"), "runbook disable works with no telemetry/pk_core"),
 "26.10": ("P", X("faults"), "consistency asserted; recovery time not measured"),
 "26.11": ("B", [], "no production incidents yet"),
 "26.12": ("R", A("tools/faults.py"), "temp dirs, child processes, no credentials"),
 "27.01": ("P", A("ci/release.yml"), "actions pinned by major tag, not digest"),
 "27.02": ("R", G("compile_all_sources"), ""),
 "27.03": ("R", G("test_polling.py:normal", "test_polling.py:optimized"), ""),
 "27.04": ("B", G("pk_core_pinned_and_compatible"), NOCORE),
 "27.05": ("P", G("contracts_generated", "test_p0_components.py:normal"), "schema/golden in gate; WIT parser and real runtime absent"),
 "27.06": ("P", X("sbom"), "dependency scan; no static analysis/secret scanner"),
 "27.07": ("R", G("fuzz", "interleave_model_check", "fault_injection", "bench_thresholds"), ""),
 "27.08": ("R", A("sbom/inv14.cdx.json", "MANIFEST.sha256", "evidence/test_results.json"), ""),
 "27.09": ("B", G("trusted_signature"), "no protected release signing context"),
 "27.10": ("B", [], "branch protection is a repository setting"),
 "27.11": ("P", A("ci/release.yml"), "upload-artifact step"),
 "27.12": ("R", A("evidence/clean_room.json"), "clean-room run from the zip"),
 "28.01": ("P", A("deps/pk_core.lock.json", "sbom/dependency_scan.json"), "INV-14 has zero runtime deps; pk_core unresolved"),
 "28.02": ("R", T("C28Sbom"), ""),
 "28.03": ("P", A("sbom/inv14.cdx.json"), "files + pk_core + optional cryptography; build container N/A"),
 "28.04": ("P", A("sbom/provenance.intoto.json"), "unsigned; builder identity absent"),
 "28.05": ("P", A("sbom/provenance.intoto.json"), "subject digest over file set; archive checksum recorded in evidence"),
 "28.06": ("B", [], "pk_core INDETERMINATE; no vulnerability DB in environment"),
 "28.07": ("P", A("sbom/dependency_scan.json"), "no third-party runtime code to attribute"),
 "28.08": ("B", [], NOOWN),
 "28.09": ("R", A("sbom/dependency_scan.json"), "stdlib only: nothing to mirror (pk_core pending)"),
 "28.10": ("R", A("evidence/reproducibility.json"), "two builds compared"),
 "28.11": ("R", T("C28Sbom"), ""),
 "28.12": ("R", A("docs/RUNBOOK.md", "tools/sign.py"), ""),
 "29.01": ("R", A("tools/sign.py", "governance/TRUSTED_KEYS.json"), "Ed25519 detached over manifest"),
 "29.02": ("P", A("MANIFEST.sha256.sig.json"), "manifest covers SBOM/provenance/schemas; archive signed via its manifest"),
 "29.03": ("B", [], "no HSM/KMS or protected release credential"),
 "29.04": ("B", A("governance/TRUSTED_KEYS.json"), "only UNTRUSTED_DEV key; trust root " + NOOWN),
 "29.05": ("R", T("C29Signing"), "one command: tools/sign.py verify --require-trusted"),
 "29.06": ("R", T("C29Signing.test_c29_sign_verify_tamper_and_trust_policy"), ""),
 "29.07": ("P", A("governance/TRUSTED_KEYS.json"), "REVOKED status honoured; rotation procedure not exercised with overlap"),
 "29.08": ("B", [], "no timestamp/transparency service"),
 "29.09": ("R", T("C29Signing"), "altered manifest, wrong/untrusted/revoked signer"),
 "29.10": ("R", A("MANIFEST.sha256.sig.json"), "key id + manifest digest, no private material"),
 "29.11": ("R", A("verify_release.py") + T("C27ReleasePipeline.test_c27_missing_pk_core_blocks_release_exit_2"), "trusted_signature is a required external gate in verify_release (currently BLOCKED: UNTRUSTED_DEV)"),
 "29.12": ("P", A("governance/TRUSTED_KEYS.json"), "public keys ship in-package"),
 "30.01": ("R", A("schemas/pk_poll_config.schema.json"), ""),
 "30.02": ("R", A("schemas/pk_poll_config.schema.json", "config.py"), ""),
 "30.03": ("R", T("C30Config.test_c30_overlays_atomic_update_history"), "base -> environment -> site"),
 "30.04": ("R", T("C30Config"), ""),
 "30.05": ("R", T("C30Config.test_c30_missing_provenance_and_unknown_keys_refused"), ""),
 "30.06": ("R", T("C30Config.test_c30_overlays_atomic_update_history"), ""),
 "30.07": ("P", A("config.py"), "all fields dynamic via store; restart-only fields not classified"),
 "30.08": ("P", T("C30Config"), "history of versions/digests; rollback = re-apply previous doc"),
 "30.09": ("B", [], "no admin identity"),
 "30.10": ("R", A("config.py"), "no secret fields in schema"),
 "30.11": ("P", T("C30Config") + X("fuzz", "faults"), "schema/bounds/precedence/atomicity/corruption; concurrent updates not tested"),
 "30.12": ("P", T("C00Diagnostics"), "diagnostics expose schema digests; active config version not yet"),
 "31.01": ("P", A("redaction.py"), "classification implicit in redaction policy; no table"),
 "31.02": ("R", A("redaction.py"), ""),
 "31.03": ("P", A("pollog.py", "audit.py"), "fixed top-level fields; free-form fields rely on pattern redaction"),
 "31.04": ("R", T("C31Redaction"), ""),
 "31.05": ("R", T("C31Redaction.test_c31_error_details_and_diagnostics_carry_no_secrets"), ""),
 "31.06": ("R", A("telemetry.py", "identity.py"), "tenant bucketed in metrics; foreign names never disclosed"),
 "31.07": ("R", T("C01PkCorePin.test_c01_probe_absent_version_hash_api_ok_paths") + A("errors.py"), ""),
 "31.08": ("R", T("C31Redaction.test_c31_error_details_and_diagnostics_carry_no_secrets"), "canary token and key"),
 "31.09": ("P", T("C31Redaction"), "nested/oversized/unicode; base64-only secrets not detected"),
 "31.10": ("B", [], NOOWN),
 "31.11": ("B", A("CODEOWNERS"), NOREV),
 "31.12": ("P", A("docs/RUNBOOK.md"), "R3 covers key rotation; full exposure procedure pending"),
 "32.01": ("R", A("ops/dashboard.json"), ""),
 "32.02": ("R", A("ops/dashboard.json"), ""),
 "32.03": ("P", A("ops/dashboard.json"), "legacy use + policy refusals; bridge ratio needs migration metrics"),
 "32.04": ("R", A("ops/dashboard.json"), ""),
 "32.05": ("P", A("ops/dashboard.json"), "no pk_core/exporter/audit health series"),
 "32.06": ("B", A("ops/alerts.yml"), "thresholds not SLO-derived: " + NOREV),
 "32.07": ("R", T("C32DashboardAlerts"), "class labels + severity"),
 "32.08": ("P", [], "no absent()/freshness alert yet"),
 "32.09": ("R", T("C32DashboardAlerts"), ""),
 "32.10": ("R", T("C32DashboardAlerts"), ""),
 "32.11": ("B", [], "no live alerting stack"),
 "32.12": ("B", [], NOOWN),
 "33.01": ("P", A("docs/RUNBOOK.md"), "entry conditions via alerts; severity map pending owner"),
 "33.02": ("R", A("docs/RUNBOOK.md") + T("C33Runbook"), "status command gives versions/state"),
 "33.03": ("R", A("docs/RUNBOOK.md") + T("C33Runbook"), ""),
 "33.04": ("R", A("docs/RUNBOOK.md", "schemas/error_codes.json"), ""),
 "33.05": ("P", A("docs/RUNBOOK.md"), "config/release/lifecycle rollback; signing trust rollback not"),
 "33.06": ("R", A("docs/RUNBOOK.md") + X("faults"), ""),
 "33.07": ("R", A("docs/RUNBOOK.md"), ""),
 "33.08": ("B", [], NOOWN),
 "33.09": ("P", [], "no communication templates"),
 "33.10": ("P", A("lifecycle.py"), "drain bounded; retry stop conditions via retry_class"),
 "33.11": ("B", T("C33Runbook"), "technical drill via tests; game day needs a team"),
 "33.12": ("R", A("docs/RUNBOOK.md", "MANIFEST.sha256"), ""),
 "34.01": ("P", A("governance/WAIVERS.json"), "id/consumer/owner/approver/dates/commitment; risk/requirement fields not"),
 "34.02": ("P", A("governance.py"), "scoped to one component_id; env/tenant scope not"),
 "34.03": ("B", [], "compensating-control evidence needs owners"),
 "34.04": ("R", T("C34Waivers"), "<= 180 days"),
 "34.05": ("R", T("C34Waivers"), "approver != owner"),
 "34.06": ("R", T("C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused"), ""),
 "34.07": ("B", [], "needs scheduler/owner"),
 "34.08": ("B", [], NOREV),
 "34.09": ("P", A("MANIFEST.sha256"), "versioned in package"),
 "34.10": ("R", T("C34Waivers"), ""),
 "34.11": ("B", [], "no waivers exist yet"),
 "34.12": ("B", [], NOREV),
 "35.01": ("R", A("governance/EOL_POLICY.json"), ""),
 "35.02": ("R", A("governance/EOL_POLICY.json"), "DEPRECATED, NEW_CONSUMERS_REFUSED, WAIVER_ONLY, REMOVED"),
 "35.03": ("B", A("governance/EOL_POLICY.json"), "dates PROPOSED; approving authority " + NOOWN),
 "35.04": ("R", T("C35Eol.test_c35_eol_phases_enforced"), "registry closes"),
 "35.05": ("R", A("governance/EOL_POLICY.json"), "support_window"),
 "35.06": ("B", [], "needs production telemetry"),
 "35.07": ("R", A("governance/EOL_POLICY.json") + T("C35Eol"), "waivers cannot pass REMOVED"),
 "35.08": ("P", A("docs/adr/ADR-0001-retain-legacy-poll-model.md", "migration.py"), "guidance in ADR; consumer validation steps pending INV-15"),
 "35.09": ("B", [], NOOWN),
 "35.10": ("R", A("docs/adr/ADR-0001-retain-legacy-poll-model.md"), ""),
 "35.11": ("B", [], "tombstone written at removal"),
 "35.12": ("B", [], NOREV),
}
