"""Machine-readable specification of the 35 v4.3.0 components (source of docs/COMPONENTS.json
and docs/COMPONENT_SPECS.md).  Evidence refs: T:<TestClass>[.<test>] (must pass in the evidence
run), A:<path> (must exist), G:<release gate> (must PASS), X:<tool> (tool run ok).
Every requirement carries >= 1 evidence ref; the evidence runner re-checks all of them."""

RT = ["T:C31Redaction.test_c31_error_details_and_diagnostics_carry_no_secrets"]
LEAK = "T:C05Cancellation.test_c05_cancel_race_stress_no_leak_no_hang"
SVC_ORDER = "T:C12EmergencyDisable.test_c12_disable_refuses_new_polls_drains_inflight_then_rolls_back"


def c(id_, title, modules, artifacts, reqs, *, boundary, ceilings, config, threats, fail_mode, interface,
      concurrency, cleanup, correlation, signals, runbook, codes, blocked=(), defects=(), kind="runtime"):
    return {"id": id_, "title": title, "kind": kind, "modules": modules, "artifacts": artifacts,
            "requirements": [{"id": f"R{id_}-{i + 1:02d}", "text": t, "evidence": ev} for i, (t, ev) in enumerate(reqs)],
            "boundary": boundary, "ceilings": ceilings, "config_sources": config,
            "compat_impact": "Additive to v4.2.0: PK_POLL/1 result fields, ready/timeout/ownership semantics and the 12 v4.2.0 tests are unchanged (G:test_polling.py:normal, G:test_polling.py:optimized).",
            "threats": threats, "fail_mode": fail_mode, "interface": interface, "concurrency": concurrency,
            "cleanup_evidence": cleanup, "correlation": correlation, "signals": signals, "runbook": runbook,
            "codes": codes, "blocked_by": list(blocked), "defects": list(defects), "owner": "UNASSIGNED"}


SPECS = [
 c("01", "Pinned pk_core runtime/dependency package", ["core_probe.py"], ["deps/pk_core.lock.json"], [
   ("The lock MUST name pk_core with an exact X.Y.Z version, immutable source and tree sha256; floating/mutable pins MUST be rejected.", ["T:C01PkCorePin.test_c01_floating_and_mutable_pins_rejected"]),
   ("The probe MUST fail closed with a stable code for unpinned, absent, wrong-version, hash-mismatched, API-incompatible or wrong-interpreter cores.", ["T:C01PkCorePin"]),
   ("Diagnostics MUST NOT disclose local filesystem paths.", ["T:C01PkCorePin.test_c01_probe_absent_version_hash_api_ok_paths"]),
   ("Release MUST be BLOCKED while the lock is UNRESOLVED.", ["T:C27ReleasePipeline.test_c27_missing_pk_core_blocks_release_exit_2"])],
   boundary="Owns the declaration and verification of pk_core. Does not own pk_core itself, its build or its index.",
   ceilings="Lock file read once; tree digest bounded by the core's file count.",
   config={"constant": "REQUIRED_SYMBOLS", "external_policy": "deps/pk_core.lock.json", "runtime": "installed pk_core tree"},
   threats=[{"threat": "substituted or tampered core", "mitigation": "tree sha256 + version equality", "tests": ["T:C01PkCorePin.test_c01_probe_absent_version_hash_api_ok_paths"]},
            {"threat": "silent skip when core absent", "mitigation": "gate exits 2", "tests": ["T:C27ReleasePipeline"]}],
   fail_mode="fail closed on every dependency condition; no degraded mode", interface="core_probe.probe() -> {ok, code, core}",
   concurrency="stateless", cleanup=["T:C01PkCorePin"], correlation="core version/hash in diagnostics", signals="diagnostics.pk_core",
   runbook="R0", codes=["PK_CORE_*"], blocked=["The exact compatible pk_core was not supplied; lock is UNRESOLVED"]),
 c("02", "WASI 0.2 / wasi:io integration adapter", ["wasi_adapter.py", "clock.py"], ["wit/inv14-legacy-poll.wit"], [
   ("The adapter MUST append a monotonic-clock timer pollable and map a timer-only result to timed_out.", ["T:C02WasiAdapter.test_c02_timeout_maps_timer_index_to_timed_out"]),
   ("ready_indexes MUST exclude the timer and match the Python reference semantics.", ["T:C02WasiAdapter.test_c02_ready_indexes_exclude_timer_and_match_python_semantics"]),
   ("Empty sets MUST be refused before wasi:io/poll can trap; the timer handle MUST be dropped on every path.", ["T:C02WasiAdapter.test_c02_empty_set_refused_before_trap_and_timer_dropped"]),
   ("Foreign/duplicate/over-limit requests MUST map to the canonical PK_POLL_ERROR/1 codes.", ["T:C02WasiAdapter.test_c02_foreign_duplicate_and_limit_refusals"]),
   ("Interop MUST be proven on a real WASI 0.2 runtime before release.", ["G:wasi_0_2_interop"])],
   boundary="Owns the translation PK_POLL/1 <-> wasi:io/poll. Does not own the runtime, handles' underlying resources or component compilation.",
   ceilings="Set <= max_pollables; timeout <= max_timeout_ticks and 60 s.", config={"constant": "WASI_IO/WASI_CLOCK ids", "config": "PK_CLOCK_CONFIG/1", "runtime": "host handles"},
   threats=[{"threat": "foreign handle smuggled into poll", "mitigation": "owner_of check before subscribe", "tests": ["T:C02WasiAdapter.test_c02_foreign_duplicate_and_limit_refusals"]}],
   fail_mode="fail closed on invalid input; real-runtime gate BLOCKED", interface="WasiHost protocol (subscribe_duration, poll, drop, owner_of)",
   concurrency="host-provided; reference host uses one condition variable", cleanup=["T:C02WasiAdapter.test_c02_empty_set_refused_before_trap_and_timer_dropped"],
   correlation="result carries owner/set_size", signals="same PK_POLL/1 result", runbook="R8", codes=["PK_POLL_*"],
   blocked=["No WASI 0.2 runtime (wasmtime/jco) or compiled component fixture in this environment", "No WIT parser/toolchain (wasm-tools) available to validate the WIT in CI"]),
 c("03", "Versioned WIT/JSON schema contracts", ["schema_check.py", "tools/gen_contracts.py"], ["wit/inv14-legacy-poll.wit", "schemas/pk_poll.schema.json", "schemas/pk_pollable.schema.json", "schemas/pk_poll_error.schema.json", "schemas/pk_poll_metrics.schema.json", "schemas/error_codes.json", "docs/CONTRACT_POLICY.md"], [
   ("Every PK_POLL/1, PK_POLLABLE/1, PK_POLL_ERROR/1, PK_POLL_METRICS/1 field MUST be defined in both WIT and JSON Schema and the two MUST agree.", ["T:C03Contracts.test_c03_wit_records_match_json_schemas"]),
   ("The error-code enumeration MUST be generated from source and the committed artifacts MUST be current.", ["T:C03Contracts.test_c03_generated_contracts_are_current", "T:C03Contracts.test_c03_error_schema_enum_equals_code_registry"]),
   ("Every schema MUST carry an immutable version id; digests MUST appear in diagnostics.", ["T:C03Contracts.test_c03_every_schema_is_versioned", "T:C00Diagnostics"]),
   ("The validator MUST fail closed on unsupported schema keywords.", ["T:C03Contracts.test_c03_validator_fails_closed_on_unknown_keyword"])],
   boundary="Owns the serialized contract. Does not own transport encodings beyond JSON and the component model.",
   ceilings="set_size <= 65536, strings <= 256, message <= 1024 (schema maxima).", config={"constant": "schema files", "generated": "error_codes.json, WIT enum, error schema enum"},
   threats=[{"threat": "contract drift between code and schema", "mitigation": "generated artifacts + --check gate", "tests": ["T:C03Contracts"]}],
   fail_mode="gate fails on drift", interface="schemas/*.json, wit/*.wit", concurrency="static artifacts", cleanup=["T:C03Contracts"],
   correlation="schema ids in every payload", signals="n/a (static)", runbook="R1", codes=["(defines all)"], defects=["D-05"], kind="artifact"),
 c("04", "INV-14 -> INV-15 migration bridge", ["migration.py"], [], [
   ("Forward and reverse shims MUST give the same ready/timeout outcomes as the legacy path (parity).", ["T:C04Migration.test_c04_parity_between_legacy_and_shim", "T:C04Migration.test_c04_reverse_shim_signals_once_from_inv15_future"]),
   ("A consumer MUST NOT advance past DUAL_STACK/CANARY without a passing parity record; rollback MUST be legal from those stages only.", ["T:C04Migration.test_c04_state_machine_requires_parity_and_allows_rollback"]),
   ("Cancel on the forward shim MUST be idempotent.", ["T:C04Migration.test_c04_forward_shim_cancel_is_idempotent"]),
   ("A MIGRATED consumer MUST NOT silently regress to INV-14.", ["T:C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused"]),
   ("The bridge MUST be proven against the real INV-15.", ["T:C20Adjacent.test_c20_inv15_future_satisfies_bridge_protocol"])],
   boundary="Owns shims and per-consumer stage machine. Does not own INV-15 or consumer code.", ceilings="One PollSet per forward shim; stage history bounded by transitions.",
   config={"runtime": "per-consumer MigrationStateMachine", "external_policy": "governance/MIGRATION_REGISTRY.json"},
   threats=[{"threat": "cutover without parity", "mitigation": "PK_MIGRATION_PARITY_REQUIRED", "tests": ["T:C04Migration.test_c04_state_machine_requires_parity_and_allows_rollback"]}],
   fail_mode="refuse advancement on missing/failed parity", interface="PollableFuture, FuturePollable, MigrationStateMachine, parity_check",
   concurrency="state machine guarded by a lock", cleanup=["T:C04Migration"], correlation="consumer id + stage history", signals="migration stage per consumer", runbook="R7",
   codes=["PK_MIGRATION_*"], blocked=["INV-15 real ABI not supplied; shims proven against the protocol only"]),
 c("05", "Cancellation contract", ["polling.py"], [], [
   ("A CancelToken MUST wake a blocked poll and raise PK_POLL_CANCELLED distinct from timeout.", ["T:C05Cancellation.test_c05_cancel_wakes_blocked_poll_with_structured_error"]),
   ("Readiness MUST win a tie with cancellation; a pre-cancelled token MUST refuse before waiting.", ["T:C05Cancellation.test_c05_precancelled_token_and_readiness_wins_tie"]),
   ("cancel() MUST be idempotent and latched.", ["T:C05Cancellation.test_c05_cancel_is_idempotent_and_token_type_checked"]),
   ("Cancellation races MUST NOT leak waiters or hang.", ["T:C05Cancellation.test_c05_cancel_race_stress_no_leak_no_hang", "X:interleave"])],
   boundary="Owns caller-driven cancellation of one poll. Does not own INV-15 cancellation semantics.", ceilings="Reason truncated to 64 chars; one waiter per poll per token.",
   config={"constant": "precedence ready > cancel > timeout"}, threats=[{"threat": "cross-principal cancellation", "mitigation": "token is a caller-held object, never addressable by id", "tests": ["T:C05Cancellation"]}],
   fail_mode="n/a", interface="PollSet.poll(..., cancel=CancelToken)", concurrency="lock + durable Event registration", cleanup=[LEAK],
   correlation="correlation_id added to error details by the service", signals="polls_cancelled, outcome=cancelled", runbook="R8", codes=["PK_POLL_CANCELLED", "PK_POLL_INVALID_CANCEL_TOKEN"]),
 c("06", "Admission / backpressure", ["admission.py"], [], [
   ("Global and per-tenant concurrent-poll ceilings MUST shed deterministically with PK_POLL_OVERLOADED / PK_POLL_TENANT_QUOTA.", ["T:C06Admission.test_c06_global_and_tenant_ceilings_shed_deterministically"]),
   ("Queueing, when enabled, MUST be bounded FIFO with a bounded wait.", ["T:C06Admission.test_c06_bounded_fifo_queue_and_timeout"]),
   ("Slots MUST be released on every path.", ["T:C06Admission.test_c06_slot_releases_on_exception", "X:soak"]),
   ("Admission MUST run before waiter allocation.", [SVC_ORDER])],
   boundary="Owns in-process admission. Does not own fleet-wide quotas.", ceilings="max_concurrent<=100000, tenant_max<=max_concurrent, queue_depth<=100000.",
   config={"config": "PK_POLL_CONFIG/1 limits"}, threats=[{"threat": "tenant monopolises wait capacity", "mitigation": "per-tenant quota", "tests": ["T:C25Soak", "T:C06Admission"]}],
   fail_mode="shed (fail closed) on overload", interface="AdmissionController.acquire/release/slot/snapshot", concurrency="Condition variable", cleanup=["T:C06Admission.test_c06_slot_releases_on_exception"],
   correlation="refusal audited with correlation id", signals="reason=admission, snapshot.shed/peak", runbook="R4", codes=["PK_POLL_OVERLOADED", "PK_POLL_TENANT_QUOTA"]),
 c("07", "Authenticated identity / capability", ["identity.py"], [], [
   ("A poll MUST present an HMAC-signed capability whose subject equals the PollSet owner principal tenant/component/instance.", ["T:C07Identity.test_c07_valid_token_binds_owner"]),
   ("Forged, untrusted, expired, cross-tenant and wrong-right tokens MUST be refused with distinct stable codes.", ["T:C07Identity.test_c07_cross_tenant_expired_forged_untrusted_refused", "T:C07Identity.test_c07_right_and_key_rotation"]),
   ("Refusals MUST NOT disclose another principal.", ["T:C07Identity.test_c07_refusal_does_not_disclose_other_principal"]),
   ("Principal segments MUST be canonical lower-case ASCII (no Unicode look-alikes).", ["T:C07Identity.test_c07_malformed_tokens_and_principals"]),
   ("Identity MUST be bound to runtime attestation.", ["G:independent_review"])],
   boundary="Owns token format and verification. Does not own key distribution or attestation.", ceilings="token <= 2048 bytes, ttl <= 3600 s, key >= 32 bytes.",
   config={"external_policy": "trusted issuer keys", "constant": "TOKEN_SCHEMA"}, threats=[{"threat": "owner-string spoofing", "mitigation": "signed subject", "tests": ["T:C07Identity"]}],
   fail_mode="fail closed (no trust root => refuse)", interface="Issuer.mint / Verifier.verify", concurrency="stateless", cleanup=["T:C07Identity"],
   correlation="refusal audited", signals="reason=identity", runbook="R3", codes=["PK_POLL_TOKEN_*"], blocked=["No runtime attestation service; no replay-nonce store (tokens are short-lived bearer capabilities)"]),
 c("08", "Tamper-evident audit sink", ["audit.py"], ["schemas/pk_poll_audit.schema.json"], [
   ("Records MUST be hash-chained and HMAC'd; verify MUST detect edit, delete, reorder and (with external head) truncation.", ["T:C08Audit.test_c08_chain_verifies_and_detects_edit_delete_reorder_truncate"]),
   ("An unwritable sink MUST fail the operation closed with PK_AUDIT_UNAVAILABLE.", ["T:C08Audit.test_c08_unwritable_sink_fails_closed_and_secrets_redacted", "X:faults"]),
   ("A corrupt existing log MUST be refused on open; a valid one MUST resume its sequence.", ["T:C08Audit.test_c08_reopen_resumes_and_corrupt_log_refused"]),
   ("Records MUST be redacted and schema-valid.", ["T:C08Audit.test_c08_unwritable_sink_fails_closed_and_secrets_redacted"])],
   boundary="Owns record format, chaining and local append. Does not own durable/WORM storage, retention or export.", ceilings="record <= 4096 bytes; closed event vocabulary.",
   config={"external_policy": "audit key", "runtime": "sink path"}, threats=[{"threat": "log tampering", "mitigation": "chain + MAC + external head", "tests": ["T:C08Audit"]}],
   fail_mode="fail closed", interface="AuditSink.append / verify_chain", concurrency="lock around append", cleanup=["T:C08Audit"], correlation="correlation_id per record", signals="audit_head in diagnostics", runbook="R3",
   codes=["PK_AUDIT_*"], blocked=["No approved durable/WORM sink, retention owner or key custody"]),
 c("09", "Telemetry exporter", ["telemetry.py"], ["ops/dashboard.json"], [
   ("Prometheus exposition MUST parse and carry only allow-listed labels.", ["T:C09Telemetry.test_c09_prometheus_exposition_parses_with_stable_labels"]),
   ("Tenant label cardinality MUST be bounded.", ["T:C09Telemetry.test_c09_tenant_cardinality_is_bounded"]),
   ("Sampling MUST apply to latency only; counters are never sampled.", ["T:C09Telemetry.test_c09_sampling_applies_to_latency_only"]),
   ("An OTLP/JSON body MUST be produced.", ["T:C09Telemetry.test_c09_otlp_json_shape"])],
   boundary="Owns metric catalog and exposition bodies. Does not own push transport or collectors.", ceilings="<= 64 tenant series + 16 buckets; closed outcome/reason sets.",
   config={"constant": "OUTCOMES, REASONS, LATENCY_BUCKETS_MS", "config": "sample_rate"}, threats=[{"threat": "cardinality attack", "mitigation": "bucketing", "tests": ["T:C09Telemetry.test_c09_tenant_cardinality_is_bounded"]}],
   fail_mode="pull-based; cannot block poll", interface="Telemetry.record / prometheus_text / otlp_json", concurrency="lock", cleanup=["T:C09Telemetry"], correlation="no ids as labels (TEL-2)", signals="inv14_polls_total, inv14_poll_latency_ms", runbook="R4",
   codes=[], blocked=["No collector endpoint for remote export"]),
 c("10", "Structured logging", ["pollog.py"], ["schemas/pk_poll_log.schema.json"], [
   ("Every record MUST match PK_POLL_LOG/1 with tenant, workload, component, operation, correlation and trace ids.", ["T:C10Logging.test_c10_records_match_schema_with_stable_ids_and_redaction"]),
   ("Records MUST be single-line JSON (injection safe) and include monotonic duration for polls.", ["T:C10LoggingService.test_c10_injection_safe_single_line_with_monotonic_duration"]),
   ("Emission MUST be concurrency-safe and backend failure MUST NOT change poll semantics.", ["T:C10LoggingService.test_c10_concurrent_emission_produces_whole_records", "T:C10Logging.test_c10_unknown_level_and_operation_are_normalised_and_stream_failure_counted"])],
   boundary="Owns log schema and emission. Does not own transport/retention.", ceilings="line <= 4096 bytes.", config={"constant": "LEVELS, OPERATIONS"},
   threats=[{"threat": "log injection / secret leakage", "mitigation": "JSON encoding + redaction", "tests": ["T:C10LoggingService", "T:C31Redaction"]}],
   fail_mode="fail open (drop + count) -- logging never blocks polls; audit is the fail-closed record", interface="StructLogger.log", concurrency="lock", cleanup=["T:C10Logging"], correlation="correlation_id, trace_id", signals="dropped counter", runbook="R8", codes=[]),
 c("11", "Trace-context propagation", ["tracing.py"], [], [
   ("A valid W3C traceparent MUST be propagated as the parent of a new child span.", ["T:C11Tracing.test_c11_valid_parent_propagates_trace_id"]),
   ("Invalid context MUST start a new root without failing the poll.", ["T:C11Tracing.test_c11_invalid_parent_starts_new_root_and_is_flagged"]),
   ("The service MUST return the child traceparent.", ["T:C11Tracing.test_c11_service_returns_child_traceparent"])],
   boundary="Owns context parsing/propagation. Does not own span export.", ceilings="tracestate <= 512 chars / 32 members.", config={"constant": "W3C version 00"},
   threats=[{"threat": "baggage as data channel", "mitigation": "bounded tracestate", "tests": ["T:C11Tracing"]}], fail_mode="fail open (new root)", interface="child_context()",
   concurrency="stateless", cleanup=["T:C11Tracing"], correlation="trace_id in logs", signals="inbound_valid flag", runbook="R8", codes=[], blocked=["No span exporter/tracing backend"]),
 c("12", "Emergency disable / policy hook", ["lifecycle.py", "service.py"], ["docs/RUNBOOK.md"], [
   ("Disable MUST refuse new polls at once, let in-flight polls finish, then reach DISABLED.", ["T:C12EmergencyDisable.test_c12_disable_refuses_new_polls_drains_inflight_then_rolls_back"]),
   ("A drain that does not complete in time MUST stay DRAINING, never force DISABLED.", ["T:C12EmergencyDisable.test_c12_drain_timeout_leaves_draining_not_disabled"]),
   ("Rollback DISABLED -> DEPRECATED MUST be available and attributed.", ["T:C12EmergencyDisable", "T:C33Runbook"]),
   ("Policy changes MUST be authenticated separately from poll callers.", ["G:independent_review"])],
   boundary="Owns process-local switch. Does not own fleet propagation.", ceilings="drain <= 60 s.", config={"runtime": "lifecycle state", "external": "operator"},
   threats=[{"threat": "abuse continues during incident", "mitigation": "DRAINING refuses immediately", "tests": ["T:C12EmergencyDisable"]}],
   fail_mode="fail closed", interface="Lifecycle.emergency_disable / transition", concurrency="Condition variable; admission atomic with state", cleanup=["T:C12EmergencyDisable"],
   correlation="transition audited", signals="reason=policy", runbook="R2", codes=["PK_POLL_DRAINING", "PK_POLL_DISABLED"], blocked=["Actor is recorded but not authenticated (no admin identity provider)", "No fleet policy distribution"]),
 c("13", "Per-component migration registry", ["governance.py"], ["governance/MIGRATION_REGISTRY.json"], [
   ("Unregistered consumers MUST be refused.", ["T:C13MigrationRegistry.test_c13_unregistered_consumer_refused_registered_admitted"]),
   ("Overdue consumers MUST need a live waiver; MIGRATED consumers MUST NOT regress.", ["T:C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused"]),
   ("Registry entries MUST validate (ids, stages, dates).", ["T:C13MigrationRegistry.test_c13_registry_validation"]),
   ("The registry MUST contain the real deployed consumer inventory.", ["G:governance"])],
   boundary="Owns schema + enforcement. Does not own the inventory data.", ceilings="component_id <= 128 chars.", config={"external_policy": "governance/*.json"},
   threats=[{"threat": "shadow consumers", "mitigation": "ConsumerGate", "tests": ["T:C13MigrationRegistry"]}], fail_mode="fail closed", interface="ConsumerGate.check/register",
   concurrency="read-mostly", cleanup=["T:C13MigrationRegistry"], correlation="consumer id", signals="reason=policy", runbook="R7", codes=["PK_POLL_UNREGISTERED_CONSUMER", "PK_POLL_MIGRATION_*"],
   blocked=["No consumer inventory supplied (inventory_status NOT_STARTED)"]),
 c("14", "Lifecycle/state model", ["lifecycle.py"], ["schemas/pk_poll_lifecycle.json"], [
   ("Every illegal transition MUST be refused leaving state unchanged; every legal one MUST apply.", ["T:C14Lifecycle.test_c14_every_illegal_transition_refused_and_state_unchanged"]),
   ("Admission per state MUST match the machine-readable model.", ["T:C14Lifecycle.test_c14_admission_by_state_and_artifact_matches_code"]),
   ("Transitions MUST be attributed; repeats idempotent.", ["T:C14Lifecycle.test_c14_unattributed_and_idempotent_transitions"])],
   boundary="Process-local state machine.", ceilings="history <= 128.", config={"constant": "TRANSITIONS", "artifact": "schemas/pk_poll_lifecycle.json"},
   threats=[{"threat": "coerced state", "mitigation": "explicit table", "tests": ["T:C14Lifecycle"]}], fail_mode="fail closed", interface="Lifecycle", concurrency="Condition variable", cleanup=["T:C14Lifecycle"],
   correlation="transition records", signals="diagnostics.lifecycle", runbook="R2", codes=["PK_POLL_ILLEGAL_TRANSITION"], blocked=["No RETIRED state yet (EOL removal withdraws the package instead); replica reconciliation not applicable in-process"]),
 c("15", "Restart/replay semantics", ["checkpoint.py"], [], [
   ("Readiness MUST NOT be persisted; counters/lifecycle/config version MUST be checkpointed atomically with a digest.", ["T:C15Restart.test_c15_checkpoint_roundtrip_never_persists_readiness", "T:C15Restart.test_c15_atomic_save_leaves_no_temp_files"]),
   ("Corrupt/tampered/oversized checkpoints MUST be refused.", ["T:C15Restart.test_c15_corrupt_truncated_tampered_checkpoints_refused"]),
   ("A killed process MUST restart from its checkpoint and re-observe live resources.", ["X:faults"])],
   boundary="Owns process-local checkpoint. Readiness reconstruction is the host's job (RST-1).", ceilings="checkpoint <= 16 KiB.", config={"runtime": "checkpoint path"},
   threats=[{"threat": "false wake from stale readiness", "mitigation": "readiness_persisted=false", "tests": ["T:C15Restart"]}], fail_mode="fail closed to safe defaults", interface="checkpoint.save/load/restore_or_default",
   concurrency="atomic os.replace", cleanup=["T:C15Restart.test_c15_atomic_save_leaves_no_temp_files"], correlation="process_epoch in diagnostics/logs", signals="checkpoint_error", runbook="R10", codes=["PK_CHECKPOINT_*"]),
 c("16", "Clock/tick authority", ["clock.py", "polling.py"], ["schemas/pk_clock_config.schema.json"], [
   ("One tick MUST be an integer nanosecond count of the monotonic clock with tick*max <= 60 s.", ["T:C16Clock.test_c16_config_validation_bounds"]),
   ("PollSet MUST follow the configured tick and max.", ["T:C16Clock.test_c16_pollset_follows_clock_authority"]),
   ("A clock anomaly MUST NOT extend a wait past the real monotonic bound.", ["T:C16Clock.test_c16_backward_clock_cannot_extend_wait", "X:faults"]),
   ("Tick->WASI duration MUST be exact integer arithmetic.", ["T:C02WasiAdapter.test_c02_tick_to_wasi_duration_is_exact_integer"])],
   boundary="Owns tick semantics.", ceilings="1 us <= tick <= 1 s.", config={"config": "PK_CLOCK_CONFIG/1"},
   threats=[{"threat": "clock manipulation extends blocking", "mitigation": "independent monotonic hard deadline", "tests": ["T:C16Clock"]}], fail_mode="fail closed on bad config", interface="validate_clock_config, ticks_to_ns",
   concurrency="stateless", cleanup=["T:C16Clock"], correlation="tick in diagnostics", signals="diagnostics.tick_seconds", runbook="R8", codes=["PK_CLOCK_*"]),
 c("17", "Owner/escalation metadata", ["governance.py"], ["governance/OWNERS.json", "CODEOWNERS"], [
   ("An owners file MUST exist and validate.", ["T:C17Owners"]),
   ("UNASSIGNED ownership MUST block certification.", ["T:C17Owners", "G:governance"])],
   boundary="Metadata only.", ceilings="n/a", config={"external_policy": "governance/OWNERS.json"}, threats=[{"threat": "orphaned component", "mitigation": "production_blockers", "tests": ["T:C17Owners"]}],
   fail_mode="blocks certification", interface="governance/OWNERS.json", concurrency="static", cleanup=["T:C17Owners"], correlation="n/a", signals="verify_release governance gate", runbook="R0", codes=["PK_GOVERNANCE_INVALID"],
   blocked=["The build cannot name owners, on-call routes or escalation"], kind="governance"),
 c("18", "Architecture Decision Record", [], ["docs/adr/ADR-0001-retain-legacy-poll-model.md"], [
   ("ADR MUST state status, context, decision, limits, migration target, retirement criteria, consequences.", ["T:C18Adr"]),
   ("ADR MUST be approved by named deciders.", ["G:governance"])],
   boundary="Documentation.", ceilings="n/a", config={}, threats=[], fail_mode="n/a", interface="docs/adr/", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R0", codes=[],
   blocked=["ADR is PROPOSED; no deciders exist to approve it"], kind="governance"),
 c("19", "Compatibility matrix", [], ["docs/COMPATIBILITY_MATRIX.json"], [
   ("The matrix MUST be machine-readable, never equate untested with supported, and tie TESTED_PASS to evidence.", ["T:C19CompatMatrix"]),
   ("Supported cells MUST be run in CI.", ["A:ci/release.yml"])],
   boundary="Documentation + CI matrix.", ceilings="n/a", config={}, threats=[], fail_mode="untested = unsupported", interface="docs/COMPATIBILITY_MATRIX.json", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R1", codes=[],
   blocked=["Only one cell (CPython 3.11 / linux / x86_64, simulated WASI) could be executed here"], kind="governance"),
 c("20", "Adjacent-layer integration tests", [], ["tests/test_integration_adjacent.py"], [
   ("Integration tests MUST run against real INV-13/INV-15/GAP-15.", ["T:C20Adjacent"]),
   ("Absent layers MUST fail in release mode and be visible skips otherwise.", ["T:C27ReleasePipeline.test_c27_release_mode_turns_absent_layers_into_failures"])],
   boundary="Tests only.", ceilings="n/a", config={"env": "PK_ADJACENT_PATH, INV14_RELEASE"}, threats=[], fail_mode="fail in release", interface="unittest", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R1", codes=[],
   blocked=["INV-13, INV-15 and GAP-15 packages were not supplied"], kind="verification"),
 c("21", "WIT/protocol contract tests", ["tools/gen_fixtures.py"], ["tests/fixtures/golden", "tests/fixtures/negative"], [
   ("Golden fixtures MUST validate and match current behaviour.", ["T:C21ContractFixtures.test_c21_golden_fixtures_validate", "T:C21ContractFixtures.test_c21_golden_matches_current_behaviour"]),
   ("Negative fixtures MUST be rejected.", ["T:C21ContractFixtures.test_c21_negative_fixtures_are_rejected"])],
   boundary="Tests only.", ceilings="n/a", config={}, threats=[], fail_mode="fail on drift", interface="fixtures", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R1", codes=[],
   blocked=["No WIT bindings in a second language to round-trip"], kind="verification"),
 c("22", "Fuzz harness", ["tools/fuzz.py"], [], [
   ("Seeded fuzzing of poll, token, config and trace targets MUST produce zero findings.", ["T:C22Fuzz.test_c22_seeded_fuzz_has_no_findings", "G:fuzz"]),
   ("Every fuzz finding MUST become a regression test.", ["T:C22Fuzz.test_c22_regression_D02_non_json_config_is_structured", "T:C22Fuzz.test_c22_regression_D03_unknown_provenance_key_refused"])],
   boundary="Tests only.", ceilings="2 s per input.", config={}, threats=[], fail_mode="n/a", interface="tools/fuzz.py", concurrency="n/a", cleanup=[], correlation="seed", signals="n/a", runbook="R8", codes=[],
   defects=["D-02", "D-03"], blocked=["No coverage-guided engine (atheris) or coverage report"], kind="verification"),
 c("23", "Concurrency model checking", ["tools/interleave.py"], [], [
   ("Exhaustive interleavings of the wake protocol MUST have zero lost wakeups, and the known mutant MUST be caught.", ["T:C23Concurrency.test_c23_exhaustive_model_check_and_mutant_detected", "G:interleave_model_check"]),
   ("Thread stress with clear-vs-signal over multiple poll sets MUST not leak or hang.", ["T:C23Concurrency.test_c23_thread_stress_clear_vs_signal_multi_set"])],
   boundary="Tests only; the model is of the protocol, not the bytecode.", ceilings="n/a", config={}, threats=[], fail_mode="n/a", interface="tools/interleave.py", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R8", codes=[],
   defects=["D-01"], blocked=["No TSAN-equivalent: no native bindings exist yet"], kind="verification"),
 c("24", "Benchmarks + thresholds", ["tools/bench.py"], ["ops/perf_thresholds.json"], [
   ("p50/p95/p99/max latency, wake latency, overshoot, throughput, fan-out and allocation MUST be measured on the executing host.", ["T:C24Bench", "G:bench_thresholds"]),
   ("Thresholds MUST be approved per cell.", ["G:governance"])],
   boundary="Tests only.", ceilings="n/a", config={"external_policy": "ops/perf_thresholds.json"}, threats=[], fail_mode="n/a", interface="tools/bench.py", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R8", codes=[],
   blocked=["Thresholds are PROPOSED; power/thermal not measurable"], kind="verification"),
 c("25", "Soak/burst harness", ["tools/soak.py"], [], [
   ("Burst beyond admission limits MUST shed with registered codes and recover with >= 99% success and zero leaked slots/waiters.", ["T:C25Soak", "G:soak_burst"])],
   boundary="Tests only; single process.", ceilings="n/a", config={}, threats=[], fail_mode="n/a", interface="tools/soak.py", concurrency="n/a", cleanup=["T:C25Soak"], correlation="n/a", signals="n/a", runbook="R4", codes=[],
   blocked=["Long-duration and fleet-scale runs not performed here"], kind="verification"),
 c("26", "Fault-injection harness", ["tools/faults.py"], [], [
   ("Clock jumps, audit loss, stall, dependency loss, SIGKILL, torn checkpoint and control-plane degradation MUST each reach their defined outcome.", ["T:C26Faults", "T:C27ReleasePipeline.test_c27_missing_pk_core_blocks_release_exit_2", "G:fault_injection"])],
   boundary="Tests only. Network partition not applicable (no network I/O).", ceilings="n/a", config={}, threats=[], fail_mode="n/a", interface="tools/faults.py", concurrency="n/a", cleanup=["T:C26Faults"], correlation="n/a", signals="n/a", runbook="R10", codes=[],
   defects=["D-04"], kind="verification"),
 c("27", "CI release pipeline", ["verify_release.py", "tools/manifest.py"], ["ci/release.yml"], [
   ("The release verifier MUST run every local gate and exit 1 on failure, 2 on any unmet external gate, 0 only when all pass.", ["T:C27ReleasePipeline", "G:manifest"]),
   ("The CI workflow MUST run the verifier in release mode across a version/OS matrix.", ["T:C27ReleasePipeline.test_c27_ci_workflow_runs_gate_in_release_mode_across_matrix"])],
   boundary="Pipeline definition.", ceilings="n/a", config={"env": "INV14_RELEASE"}, threats=[{"threat": "assumed-pass path", "mitigation": "no pass without all gates", "tests": ["T:C27ReleasePipeline"]}], fail_mode="fail closed",
   interface="verify_release.py", concurrency="n/a", cleanup=[], correlation="report JSON", signals="n/a", runbook="R0", codes=[], defects=["D-04"],
   blocked=["The workflow has not executed on a CI service; branch protection is a repository setting"], kind="verification"),
 c("28", "SBOM / provenance", ["tools/sbom.py"], ["sbom/inv14.cdx.json", "sbom/provenance.intoto.json", "sbom/dependency_scan.json"], [
   ("A CycloneDX SBOM with per-file hashes and an import scan proving stdlib-only runtime MUST be generated.", ["T:C28Sbom", "G:sbom_stdlib_only"]),
   ("Provenance MUST be signed by a trusted builder.", ["G:trusted_signature"])],
   boundary="Supply-chain metadata.", ceilings="n/a", config={}, threats=[{"threat": "undeclared dependency", "mitigation": "AST import scan", "tests": ["T:C28Sbom"]}], fail_mode="INDETERMINATE is not a pass", interface="sbom/*", concurrency="n/a", cleanup=[], correlation="digest", signals="n/a", runbook="R0", codes=[],
   blocked=["pk_core cannot be scanned until pinned; provenance unsigned"], kind="supply-chain"),
 c("29", "Artifact signing + verification", ["tools/sign.py"], ["governance/TRUSTED_KEYS.json", "MANIFEST.sha256.sig.json"], [
   ("verify MUST fail closed on missing signature, unknown/revoked/untrusted signer, manifest change or bad signature.", ["T:C29Signing.test_c29_sign_verify_tamper_and_trust_policy"]),
   ("Two independent backends MUST agree.", ["T:C29Signing.test_c29_openssl_backend_agrees_when_present"]),
   ("Releases MUST be signed by a TRUSTED key.", ["G:trusted_signature"])],
   boundary="Signing tooling; key custody is external.", ceilings="n/a", config={"external_policy": "governance/TRUSTED_KEYS.json"}, threats=[{"threat": "tampered release", "mitigation": "Ed25519 over manifest", "tests": ["T:C29Signing"]}],
   fail_mode="fail closed", interface="tools/sign.py", concurrency="n/a", cleanup=[], correlation="key_id", signals="n/a", runbook="R0", codes=[], defects=["D-06"],
   blocked=["Only an UNTRUSTED_DEV key exists; no HSM/KMS, trust root or transparency log"], kind="supply-chain"),
 c("30", "Configuration schema + provenance", ["config.py"], ["schemas/pk_poll_config.schema.json"], [
   ("Config MUST carry provenance and exactly the governed limit keys within bounds; unknown keys refused.", ["T:C30Config.test_c30_missing_provenance_and_unknown_keys_refused"]),
   ("Overlays MUST merge base->environment->site; updates MUST be atomic, keep history and refuse version reuse.", ["T:C30Config.test_c30_overlays_atomic_update_history"]),
   ("Code validation and the JSON schema MUST agree.", ["T:C22Fuzz.test_c22_regression_D03_unknown_provenance_key_refused", "X:fuzz"])],
   boundary="Owns validation and activation.", ceilings="doc <= 64 KiB, history <= 64.", config={"config": "PK_POLL_CONFIG/1"}, threats=[{"threat": "unsafe live change", "mitigation": "validate-then-swap", "tests": ["T:C30Config"]}],
   fail_mode="fail closed (active config kept)", interface="ConfigStore.update", concurrency="lock", cleanup=["T:C30Config"], correlation="config version + digest", signals="history", runbook="R4", codes=["PK_CONFIG_*"], defects=["D-02", "D-03"],
   blocked=["Update authorization not authenticated (no admin identity)"]),
 c("31", "Secret handling / redaction", ["redaction.py"], [], [
   ("Secret-named keys and credential-shaped values MUST be redacted; output bounded in size/depth/items.", ["T:C31Redaction.test_c31_secret_keys_and_shapes_redacted", "T:C31Redaction.test_c31_bounds_and_totality"]),
   ("Tokens and keys MUST never appear in logs, audit or diagnostics.", RT)],
   boundary="Owns redaction function.", ceilings="256 chars, depth 4, 32 items.", config={"constant": "patterns"}, threats=[{"threat": "credential leak", "mitigation": "key + value patterns", "tests": ["T:C31Redaction"]}],
   fail_mode="redact on doubt", interface="redact()", concurrency="pure", cleanup=[], correlation="n/a", signals="n/a", runbook="R3", codes=[]),
 c("32", "Dashboards + alerts", [], ["ops/dashboard.json", "ops/alerts.yml"], [
   ("Alerts MUST reference exported metrics, closed reasons, runbook anchors, and distinguish failure classes.", ["T:C32DashboardAlerts"])],
   boundary="Ops as code.", ceilings="n/a", config={}, threats=[], fail_mode="n/a", interface="ops/*", concurrency="n/a", cleanup=[], correlation="n/a", signals="n/a", runbook="R3", codes=[],
   blocked=["Not loaded into a live Prometheus/Grafana; thresholds not SLO-approved; no data-freshness alert source"], kind="operations"),
 c("33", "Incident runbook", ["tools/runbook.py"], ["docs/RUNBOOK.md"], [
   ("status, disable, rollback, transition, verify-audit MUST execute and refuse illegal actions.", ["T:C33Runbook"])],
   boundary="Ops procedure.", ceilings="n/a", config={"env": "INV14_AUDIT_KEY_HEX"}, threats=[], fail_mode="refuse without audit key", interface="tools/runbook.py", concurrency="n/a", cleanup=[], correlation="audit records", signals="n/a", runbook="R0-R10", codes=[],
   blocked=["No game-day/tabletop with a real on-call team; paging targets UNASSIGNED"], kind="operations"),
 c("34", "Waiver registry", ["governance.py"], ["governance/WAIVERS.json"], [
   ("Waivers MUST name owner and a different approver, be <= 180 days, and admit only their consumer while live.", ["T:C34Waivers", "T:C13MigrationRegistry.test_c13_overdue_needs_live_waiver_and_migrated_regression_refused"])],
   boundary="Schema + enforcement; data is organisational.", ceilings="180 days.", config={"external_policy": "governance/WAIVERS.json"}, threats=[{"threat": "self-approved waiver", "mitigation": "approver != owner", "tests": ["T:C34Waivers"]}],
   fail_mode="fail closed", interface="validate_waivers, ConsumerGate", concurrency="static", cleanup=[], correlation="waiver_id", signals="basis in gate result", runbook="R7", codes=["PK_GOVERNANCE_*"], kind="governance"),
 c("35", "Formal end-of-life policy", ["governance.py"], ["governance/EOL_POLICY.json"], [
   ("EOL phases MUST be enforced: registry closure, waiver-only, removal.", ["T:C35Eol.test_c35_eol_phases_enforced"]),
   ("Milestones MUST be strictly increasing and end in REMOVED.", ["T:C35Eol.test_c35_eol_validation"]),
   ("The policy MUST be APPROVED by a named authority.", ["G:governance"])],
   boundary="Policy + enforcement.", ceilings="n/a", config={"external_policy": "governance/EOL_POLICY.json"}, threats=[{"threat": "silent support extension", "mitigation": "waivers cannot pass REMOVED", "tests": ["T:C35Eol"]}],
   fail_mode="fail closed after REMOVED", interface="eol_phase, ConsumerGate", concurrency="static", cleanup=[], correlation="n/a", signals="eol_phase", runbook="R7", codes=["PK_POLL_EOL_REMOVED", "PK_POLL_REGISTRY_CLOSED"],
   blocked=["Dates are PROPOSED; no approving authority"], kind="governance"),
]
