"""Write CHECKLIST_STATUS.md: the governing checklist with a status block under every component
and a roll-up table.  Boxes are NOT ticked: the checklist's own rule is that `[x]` requires reviewed
evidence, and no independent review exists.  Source text is otherwise reproduced unchanged."""
from __future__ import annotations

import json
import pathlib
import re

PKG = pathlib.Path(__file__).resolve().parents[1]
SRC = PKG / "docs" / "checklist" / "INV54_v4.2.0_MISSING_COMPONENTS_PROFESSIONAL_CHECKLIST.md"


def main() -> None:
    st = json.loads((PKG / "evidence" / "component_status.json").read_text())
    gate = json.loads((PKG / "evidence" / "exit_gate.json").read_text())
    by = {c["id"]: c for c in st["components"]}
    md = SRC.read_text()

    def block(m: re.Match) -> str:
        c = by[f"{int(m[1]):02d}"]
        passed = sum(1 for v in c["tests"].values() if v == "PASS")
        other = {t.rsplit(".", 1)[-1]: v for t, v in c["tests"].items() if v != "PASS"}
        lines = [m[0].rstrip("\n"), "", f"> **v4.3.0 status: `{c['status']}` · gate: `{c['gate']}`**  ",
                 f"> Artifacts: {', '.join('`' + a + '`' for a in c['artifacts'])}  ",
                 f"> Mapped tests: {passed} passing" + (f"; not passing: {other}" if other else "") + "  "]
        if c["gaps"]:
            lines.append(f"> Open: {c['gaps']}  ")
        lines.append("> Gate blocked by: " + "; ".join(c["gate_reasons"]))
        return "\n".join(lines) + "\n"

    out = re.sub(r"^## (\d\d+)\. P\d — .+?\n\n\*\*Controls:\*\* .+?\n", block, md, flags=re.M)
    rows = "\n".join(f"| {c['id']} | {c['priority']} | {c['title']} | `{c['status']}` | {c['gate']} |"
                     for c in st["components"])
    counts = ", ".join(f"{k}: {v}" for k, v in sorted(st["counts"].items()))
    head = f"""# INV-54 v4.3.0 — checklist execution status

Generated by `tools/annotate_checklist.py` from `evidence/component_status.json` ({st['ts']}).

- **Exit-gate verdict: `{gate['verdict']}`** (`evidence/exit_gate.json`)
- Tests: {gate['tests']}
- Component status: {counts}
- Providers: {gate['provider_certification']} · pk_core: {gate['pk_core_certification']}
- No checkbox below is ticked. The checklist requires reviewed evidence for `[x]`; this pass is
  self-verified only, and its own gate refuses to let the builder review its own work.

| # | P | Component | Status | Gate |
|---|---|---|---|---|
{rows}

---

"""
    (PKG / "CHECKLIST_STATUS.md").write_text(head + out)
    print("CHECKLIST_STATUS.md written")


if __name__ == "__main__":
    main()
