"""Record the execution status of every checkbox in the supplied implementation checklist.

    python -B tools/checklist_status.py   # writes governance/CHECKLIST_EXECUTION.json + CHECKLIST_EXECUTED.md

Rule-based and conservative (the rules are the code below):
  * lines that need a named person, an independent reviewer, sign-off, paging or
    on-call -> BLOCKED_HUMAN; lines that need pk_core, a live mesh/fleet/edge
    hardware or a representative environment -> BLOCKED_EXTERNAL;
  * otherwise the line inherits its work package's state from governance/RTM.json:
    DONE only when every mapped requirement is VERIFIED_LOCAL or DEFINED,
    PARTIAL when any is PARTIAL/BLOCKED, BLOCKED when all are BLOCKED.
A DONE line is never a claim of independent verification: every work package
also carries the standing BLOCKED_HUMAN review line.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "governance" / "INV58_v4.2.0_MISSING_COMPONENTS_IMPLEMENTATION_CHECKLIST.md"
HUMAN = re.compile(r"(?i)accountable owner|assign an? |independent|reviewer|sign(s)? off|signed|paging|on-call|approved requirements|approve")
EXTERNAL = re.compile(r"(?i)pk_core|representative non-production|fleet|power|thermal|live|supported CPU|every supported old/new peer|hypervisor")
MANUAL_MC = {"MC-001": "BLOCKED", "MC-041": "PARTIAL"}
MC_NOTES = {"MC-001": "MASTER.md is verbatim source material and was not supplied; README-declared-artifact test added.",
            "MC-041": "pyproject, CI, inheritance statement and notices added; pk_core pin and licence choice are owner inputs."}


def mc_status(rtm):
    mcs = {}
    for r in rtm["rows"]:
        if r["work_package"]:
            mcs.setdefault(r["work_package"], []).append(r["status"])
    out = {}
    for mc, sts in mcs.items():
        if all(s == "BLOCKED" for s in sts):
            out[mc] = "BLOCKED"
        elif any(s in ("PARTIAL", "BLOCKED") for s in sts):
            out[mc] = "PARTIAL"
        else:
            out[mc] = "DONE"
    out.update(MANUAL_MC)
    return out


def classify(text, mc, mcs):
    if HUMAN.search(text):
        return "BLOCKED_HUMAN", "needs a named person / independent review"
    if EXTERNAL.search(text):
        return "BLOCKED_EXTERNAL", "needs pk_core, live infrastructure or hardware not available"
    st = mcs.get(mc, "DONE" if mc in ("GLOBAL", "CLOSURE") else "PARTIAL")
    return st, {"DONE": "implemented + evidenced (see RTM)", "PARTIAL": "implemented in part (see RTM blockers)",
                "BLOCKED": "work package blocked (see RTM)"}[st]


def main(argv):
    rtm = json.loads((ROOT / "governance" / "RTM.json").read_text())
    mcs = mc_status(rtm)
    lines = SRC.read_text().splitlines()
    mc, section, items, out_md = "GLOBAL", "", [], []
    for ln in lines:
        m = re.match(r"^## (MC-\d{3})", ln)
        if m:
            mc = m.group(1)
        elif ln.startswith("## Final repository closure"):
            mc = "CLOSURE"
        elif ln.startswith("## Global completion"):
            mc = "GLOBAL"
        if ln.startswith("### ") or ln.startswith("#### "):
            section = ln.lstrip("# ").strip()
        if ln.startswith("- [ ] "):
            text = ln[6:]
            st, why = classify(text, mc, mcs)
            if mc == "CLOSURE" and st == "DONE" and re.search(r"(?i)immutable/signed|fresh missing-components audit|every prior MC", text):
                st, why = "PARTIAL", "record generated but unsigned / blockers remain"
            items.append({"n": len(items) + 1, "work_package": mc, "section": section, "item": text, "status": st, "basis": why})
            mark = {"DONE": "[x]", "PARTIAL": "[~]"}.get(st, "[!]")
            out_md.append(f"- {mark} {text}  _({st}: {why})_")
        else:
            out_md.append(ln)
    counts = {}
    for it in items:
        counts[it["status"]] = counts.get(it["status"], 0) + 1
    per_mc = {}
    for it in items:
        per_mc.setdefault(it["work_package"], {}).setdefault(it["status"], 0)
        per_mc[it["work_package"]][it["status"]] += 1
    doc = {"schema": "PK_MESH_CHECKLIST_EXECUTION/1", "source": SRC.name, "items": len(items), "counts": counts,
           "work_package_status": mcs, "work_package_notes": MC_NOTES, "per_work_package": per_mc, "rows": items}
    (ROOT / "governance" / "CHECKLIST_EXECUTION.json").write_text(json.dumps(doc, indent=1) + "\n")
    header = ("> Execution copy generated by `tools/checklist_status.py` for v4.3.0. `[x]` DONE, `[~]` PARTIAL, `[!]` BLOCKED. "
              "Rule-based and conservative; see the tool docstring. Totals: " + json.dumps(counts) + "\n\n")
    (ROOT / "governance" / "CHECKLIST_EXECUTED.md").write_text(header + "\n".join(out_md) + "\n")
    print(json.dumps({"items": len(items), "counts": counts}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
