"""Build the release evidence bundle and the machine-derived production gate
(MC015, MC017-MC019, MC021, MC022, MC040, MC041, MC092, MC101, MC103).

Run after tools/run_tests.py (and tools/bench.py):

    python tools/build_release.py [--environment production]

Writes (all excluded from the source digest because they are derived from it):
  dependencies.lock.json            pinned dependency manifest
  ops/alerts.yaml                   alert rules from telemetry.ALERT_RULES
  security/secret_scan.json         secret scan result
  security/vuln_scan.json           vulnerability scan result
  sbom/inv29.cdx.json               CycloneDX 1.5 SBOM
  release/SHA256SUMS                checksum manifest of every source file
  release/provenance.intoto.json    SLSA v1 provenance statement (UNSIGNED)
  release/evidence-manifest.json    hashes of every mandatory artifact; fails if one is absent/stale
  conformance/TRACEABILITY.json     INV-29-C001..C100 -> components -> status/evidence
  conformance/evidence_ledger.jsonl hash-chained ledger (appended)
  conformance/PK_GATE_RESULTS.json  GO / CONDITIONAL_GO / NO_GO
Exit status: 0 if the bundle was built (whatever the verdict), 2 if a mandatory artifact is missing.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import pathlib
import platform
import sys
import uuid

PKG = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG.parent))
sys.path.insert(0, str(PKG / "tools"))
from inv29_hybrid_wasm_unikernel import __version__  # noqa: E402
from inv29_hybrid_wasm_unikernel import deps as D  # noqa: E402
from inv29_hybrid_wasm_unikernel import evidence as E  # noqa: E402
from inv29_hybrid_wasm_unikernel.telemetry import ALERT_RULES  # noqa: E402
import secret_scan  # noqa: E402

GENERATED = ("release/", "sbom/", "security/", "conformance/", "fuzz/", "dist/", "perf/latest.json",
             "perf/regression_gate.json", "ops/alerts.yaml", "dependencies.lock.json")
MANDATORY = ["pyproject.toml", "dependencies.lock.json", "schemas/pk_hybrid_composition_1.schema.json",
             "schemas/pk_hybrid_verification_1.schema.json", "docs/ARCHITECTURE.md", "docs/THREAT_MODEL.md",
             "docs/SCHEMA_EVOLUTION.md", "docs/COMPATIBILITY.md", "docs/CAPACITY.md", "docs/OBSERVABILITY.md",
             "governance/RUNBOOKS.md", "governance/ROLLOUT.md", "governance/WAIVERS.json", "OWNERS.md",
             "CODEOWNERS", "RELEASE_CHECKLIST.md", "MISSING_COMPONENTS_STATUS.json", "perf/baseline.json",
             "conformance/test_results.json", "security/secret_scan.json", "security/vuln_scan.json",
             "sbom/inv29.cdx.json", "release/SHA256SUMS", "release/provenance.intoto.json", "ops/alerts.yaml",
             "conformance/TRACEABILITY.json"]


def sha(p: pathlib.Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def source_files():
    for p in sorted(PKG.rglob("*")):
        rel = p.relative_to(PKG).as_posix()
        if p.is_file() and "__pycache__" not in rel and not rel.startswith(GENERATED):
            yield rel, p


def write(rel: str, obj) -> pathlib.Path:
    p = PKG / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(obj if isinstance(obj, str) else json.dumps(obj, indent=2, sort_keys=False) + "\n")
    return p


def yaml_alerts() -> str:
    out = ["# generated by tools/build_release.py from telemetry.ALERT_RULES - do not edit", "groups:",
           "  - name: inv29", "    rules:"]
    for r in ALERT_RULES:
        out += [f"      - alert: {r['alert']}", f"        expr: {json.dumps(r['expr'])}", f"        for: {r['for']}",
                "        labels:", f"          severity: {r['severity']}", f"          class: {r['class']}",
                "        annotations:", f"          action: {json.dumps(r['action'])}"]
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--environment", default="production")
    args = ap.parse_args()
    now = dt.datetime.now(dt.timezone.utc).replace(microsecond=0)

    write("dependencies.lock.json", {
        "schema": "INV29_DEPENDENCY_LOCK/1", "element": "INV-29", "version": __version__,
        "python": {"requires": ">=3.10", "locked_interpreter_for_this_bundle": platform.python_version()},
        "runtime_third_party_packages": [],
        "external": {k: {**v, "pinned_digest": None, "pin_status": "UNRESOLVED - artifact not available"}
                     for k, v in D.DEPENDENCIES.items()},
        "dev_override": "PK_CORE_PATH (development only; not a production resolution mechanism)"})
    write("ops/alerts.yaml", yaml_alerts())
    write("security/secret_scan.json", secret_scan.scan())
    write("security/vuln_scan.json", {
        "tool": "inv29-vuln-inventory/1", "scanned_at": now.isoformat(),
        "third_party_runtime_packages": [], "findings": [],
        "interpreter": platform.python_version(),
        "not_scanned": ["CPython interpreter (needs CVE feed in CI)"] + [k for k in D.DEPENDENCIES],
        "note": "No bundled third-party code; external elements are scanned by their owners."})

    files = list(source_files())
    source_digest = E.tree_digest(PKG, exclude=GENERATED)
    write("release/SHA256SUMS", "".join(f"{sha(p)}  {rel}\n" for rel, p in files))
    write("sbom/inv29.cdx.json", {
        "bomFormat": "CycloneDX", "specVersion": "1.5", "serialNumber": f"urn:uuid:{uuid.uuid5(uuid.NAMESPACE_URL, source_digest)}",
        "version": 1,
        "metadata": {"timestamp": now.isoformat(), "component": {
            "type": "library", "bom-ref": "inv29", "name": "inv29-hybrid-wasm-unikernel", "version": __version__,
            "hashes": [{"alg": "SHA-256", "content": source_digest.split(":")[1]}],
            "licenses": [{"license": {"name": "UNDECIDED (see NOTICE)"}}]}},
        "components": [{"type": "file", "bom-ref": f"file:{rel}", "name": rel,
                        "hashes": [{"alg": "SHA-256", "content": sha(p)}]} for rel, p in files] +
                      [{"type": "library", "bom-ref": k, "name": k, "scope": "required" if v["required"] else "optional",
                        "description": f"external element, not bundled ({v['api']})"} for k, v in D.DEPENDENCIES.items()],
        "dependencies": [{"ref": "inv29", "dependsOn": [k for k in D.DEPENDENCIES]}]})
    write("release/provenance.intoto.json", {
        "_type": "https://in-toto.io/Statement/v1",
        "subject": [{"name": "inv29-hybrid-wasm-unikernel-source", "digest": {"sha256": source_digest.split(":")[1]}}],
        "predicateType": "https://slsa.dev/provenance/v1",
        "predicate": {"buildDefinition": {"buildType": "inv29/tools/build_release.py@1",
                                          "externalParameters": {"environment": args.environment},
                                          "resolvedDependencies": []},
                      "runDetails": {"builder": {"id": "UNTRUSTED-local-build"},
                                     "metadata": {"startedOn": now.isoformat(),
                                                  "python": platform.python_version()}}},
        "signature": None, "signature_status": "UNSIGNED - needs trusted builder + owner signing key (MC018/MC019)"})

    status = json.loads((PKG / "MISSING_COMPONENTS_STATUS.json").read_text())
    trace = {}
    for c in status["components"]:
        for req in c["requirements"]:
            trace.setdefault(req, []).append({"component": c["id"], "status": c["status"], "evidence": c["evidence"]})
    checklist = json.loads((PKG / "CHECKLIST.json").read_text())
    trace_doc = {"schema": "INV29_TRACEABILITY/1", "version": __version__, "requirements": []}
    for item in checklist["items"]:
        links = trace.get(item["check_id"], [])
        closed = bool(links) and all(l["status"] in E.CLOSED_STATES for l in links)
        trace_doc["requirements"].append({"id": item["check_id"], "dimension": item["dimension"],
                                          "components": links, "all_linked_components_closed": closed})
    write("conformance/TRACEABILITY.json", trace_doc)

    missing = [m for m in MANDATORY if not (PKG / m).exists()]
    tests_p = PKG / "conformance" / "test_results.json"
    tests = json.loads(tests_p.read_text()) if tests_p.exists() else {}
    manifest = {"schema": "INV29_EVIDENCE_MANIFEST/1", "version": __version__, "source_digest": source_digest,
                "generated_at": now.isoformat(),
                "artifacts": {m: sha(PKG / m) for m in MANDATORY if (PKG / m).exists()},
                "missing": missing}
    write("release/evidence-manifest.json", manifest)

    led = E.Ledger(PKG / "conformance" / "evidence_ledger.jsonl")
    led.append("test-run", {"source_digest": source_digest, "summary": {k: tests.get(k) for k in
               ("passed", "failed", "errors", "certification_critical_skips", "python")}})
    led.append("scan", {"secret_clean": json.loads((PKG / "security/secret_scan.json").read_text())["clean"],
                        "vuln_findings": 0})
    perf = PKG / "perf" / "regression_gate.json"
    led.append("perf", json.loads(perf.read_text()) if perf.exists() else {"status": "not run"})
    led.append("release-manifest", {"source_digest": source_digest,
                                    "manifest_sha256": sha(PKG / "release/evidence-manifest.json")})

    waivers = json.loads((PKG / "governance" / "WAIVERS.json").read_text())["waivers"]
    gate = E.derive_gate(status, tests=tests or {"failed": 1, "errors": 1}, manifest=manifest,
                         source_digest=source_digest, waivers=waivers, today=now.date(),
                         version=__version__, environment=args.environment)
    gate["evidence_ledger_head"] = led.head()
    gate["evidence_ledger_entries"] = led.verify()["entries"]
    gate["local_readiness"] = {
        "components_total": len(status["components"]),
        "closed": sum(c["status"] == "CLOSED" for c in status["components"]),
        "requirements_fully_traced_and_closed": sum(r["all_linked_components_closed"] for r in trace_doc["requirements"]),
    }
    if missing:
        gate["verdict"] = "NO_GO"
        gate["blockers"].append({"id": "MANIFEST", "priority": "P0", "status": "INCOMPLETE", "reason": f"missing {missing}"})
    write("conformance/PK_GATE_RESULTS.json", gate)
    led.append("gate", {"verdict": gate["verdict"], "p0_open": gate["p0_open"], "blockers": len(gate["blockers"])})
    print(f"source {source_digest}\nverdict {gate['verdict']}  blockers={len(gate['blockers'])}  "
          f"p0_open={gate['p0_open']}  status={gate['status_counts']}\nledger head {led.head()}")
    if missing:
        print("MISSING mandatory artifacts:", missing)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
