"""SHALL-level requirements registry (MC-003) — the RTM (MC-004) is generated from it.

SPDX-License-Identifier: NOASSERTION

Each entry: id, SHALL text, source checklist IDs, implementation locations,
and test identifiers (``module.Class.method`` under ``tests/``).  ``tools/rtm.py``
verifies every referenced test exists and every code path exists, so the
matrix cannot silently drift from the code.
"""
from __future__ import annotations

P = "production/"
T = "test_production."
E = "test_expansion."

REQUIREMENTS = [
    ("INV34-REQ-001", "The service SHALL only increase a VM's desired vCPU count; any lower target SHALL be refused.",
     ["C001", "C010"], ["expansion.py", P + "adapters/cloud_hypervisor.py"],
     [E + "ExpansionControllerTest", T + "CloudHypervisorAdapterTest.test_never_sends_shrink",
      T + "ReconcilerTest.test_policy_quota_degraded_and_limits"]),
    ("INV34-REQ-002", "The service SHALL keep desired and observed vCPUs as separate facts and SHALL report convergence only when an independent guest observation equals desired.",
     ["C011", "C021"], ["expansion.py", P + "reconciler.py", P + "observation.py"],
     [T + "ReconcilerTest.test_accept_present_observe_converge"]),
    ("INV34-REQ-003", "A target SHALL NOT exceed the VM maximum, the host capacity, or any tenant/site/fleet quota.",
     ["C012", "C045"], ["expansion.py", P + "security.py"],
     [T + "SecurityTest.test_quota_tenant_site_fleet_fairness", T + "ReconcilerTest.test_policy_quota_degraded_and_limits"]),
    ("INV34-REQ-004", "Unknown mandatory security, residency or capacity state SHALL fail closed for new expansion.",
     ["C050", "C052"], [P + "policy.py"], [T + "ResilienceTelemetryAuditTest.test_precedence"]),
    ("INV34-REQ-005", "A request_id SHALL be idempotent across process restarts; reuse with different parameters SHALL be rejected.",
     ["C025", "C061"], [P + "reconciler.py", P + "store.py"], [T + "ReconcilerTest.test_durable_idempotency_across_restart"]),
    ("INV34-REQ-006", "State writes SHALL be compare-and-swap on a revision and SHALL detect torn or tampered documents.",
     ["C060", "C062"], [P + "store.py"], [T + "StoreTest.test_cas_and_corruption_detection", T + "StoreTest.test_multiprocess_cas_no_lost_update"]),
    ("INV34-REQ-007", "Only the holder of the current lease SHALL issue adapter actions, and every action SHALL carry a monotonic fence token.",
     ["C063", "C064"], [P + "store.py", P + "adapters/base.py"],
     [T + "StoreTest.test_lease_exclusive_and_fence_monotonic", T + "ReconcilerTest.test_two_replicas_one_lease",
      T + "CloudHypervisorAdapterTest.test_stale_fence_refused_before_side_effect"]),
    ("INV34-REQ-008", "An ambiguous adapter outcome SHALL be resolved by reading live hypervisor state before any retry.",
     ["C065", "C066"], [P + "reconciler.py"], [T + "ReconcilerTest.test_timeout_after_action_no_double_hotadd",
                                              T + "ReconcilerTest.test_timeout_before_action_reissues_once"]),
    ("INV34-REQ-009", "Pending expansions SHALL be reconstructed from the durable journal after a crash.",
     ["C067"], [P + "reconciler.py"], [T + "ReconcilerTest.test_crash_between_accept_and_reconcile_recovers"]),
    ("INV34-REQ-010", "Retries SHALL use bounded full-jitter exponential backoff within a retry budget and SHALL terminate.",
     ["C066"], [P + "resilience.py"], [T + "ResilienceTelemetryAuditTest.test_backoff_bounded_jitter",
                                       T + "ReconcilerTest.test_retry_exhaustion_fails_closed"]),
    ("INV34-REQ-011", "An unhealthy mandatory dependency SHALL place the service in degraded mode refusing new expansion while status stays available.",
     ["C068"], [P + "resilience.py", P + "reconciler.py"], [T + "ReconcilerTest.test_policy_quota_degraded_and_limits"]),
    ("INV34-REQ-012", "Overload SHALL be shed with a retryable error rather than queued without bound.",
     ["C046"], [P + "resilience.py", P + "service.py"], [T + "ApiTest.test_overload_sheds", T + "ResilienceTelemetryAuditTest.test_admission"]),
    ("INV34-REQ-013", "Every caller, observer and operator SHALL be authenticated; credentials SHALL expire and SHALL NOT be replayable.",
     ["C051"], [P + "security.py"], [T + "SecurityTest.test_authn_accept_replay_forge_skew"]),
    ("INV34-REQ-014", "Authorization SHALL bind each action to tenant/VM scope with least privilege and SHALL deny cross-tenant access.",
     ["C052"], [P + "security.py", P + "service.py"], [T + "SecurityTest.test_authz_least_privilege_and_cross_tenant",
                                                       T + "ApiTest.test_error_mapping"]),
    ("INV34-REQ-015", "Guest observations SHALL be authenticated, bound to one source per VM, fresh, and sequence-monotonic across restarts.",
     ["C053"], [P + "observation.py"], [T + "ObservationTest.test_verified_and_rejections",
                                        T + "ReconcilerTest.test_observation_replay_protection_survives_restart"]),
    ("INV34-REQ-016", "Observed vCPUs SHALL NOT regress and SHALL NOT exceed desired.",
     ["C011"], ["expansion.py"], [T + "ReconcilerTest.test_regressive_observation_refused"]),
    ("INV34-REQ-017", "The HTTP boundary SHALL validate every input against the versioned contract before side effects, reject unknown fields, and never return 5xx for hostile payloads.",
     ["C021", "C022"], [P + "service.py"], [T + "ApiTest.test_hostile_payloads_fuzz", T + "ApiTest.test_error_mapping"]),
    ("INV34-REQ-018", "Unsupported protocol versions SHALL be refused with the supported list; expired deadlines SHALL cause no side effect.",
     ["C016", "C023"], [P + "service.py"], [T + "ApiTest.test_error_mapping"]),
    ("INV34-REQ-019", "Configuration SHALL be validated whole, activated atomically, carry provenance, require a distinct approver in production, and be rollback-able.",
     ["C033", "C034", "C035"], [P + "config.py"], [T + "ConfigTest.test_activate_provenance_rollback", T + "ConfigTest.test_validation_rejects"]),
    ("INV34-REQ-020", "An operator SHALL be able to freeze expansion per VM; freezing SHALL NOT remove CPUs.",
     ["C070"], [P + "reconciler.py", P + "service.py"], [T + "ApiTest.test_quarantine_explain_health_metrics",
                                                         T + "ReconcilerTest.test_freeze_blocks_new_expansion_keeps_cpus"]),
    ("INV34-REQ-021", "Security-relevant events SHALL be written to a tamper-evident chain whose head can be anchored externally.",
     ["C057"], [P + "audit.py"], [T + "ResilienceTelemetryAuditTest.test_audit_chain_tamper"]),
    ("INV34-REQ-022", "Logs and diagnostics SHALL redact secrets and credential-shaped strings; metric labels SHALL be a bounded vocabulary.",
     ["C058", "C075"], [P + "telemetry.py"], [T + "ResilienceTelemetryAuditTest.test_redaction_and_bounded_labels"]),
    ("INV34-REQ-023", "Trace context SHALL propagate (W3C traceparent) from request to journal and adapter call.",
     ["C074"], [P + "telemetry.py", P + "service.py"], [T + "ApiTest.test_full_path_and_trace_propagation",
                                                        T + "ResilienceTelemetryAuditTest.test_traceparent"]),
    ("INV34-REQ-024", "The service SHALL expose liveness, readiness (dependency-aware), version and metrics endpoints and an explain view.",
     ["C071", "C072", "C076"], [P + "service.py"], [T + "ApiTest.test_quarantine_explain_health_metrics"]),
    ("INV34-REQ-025", "The Cloud Hypervisor adapter SHALL use only documented vm.info / vm.resize and SHALL map timeouts and 5xx to UNKNOWN.",
     ["C031", "C040"], [P + "adapters/cloud_hypervisor.py"], [T + "CloudHypervisorAdapterTest"]),
    ("INV34-REQ-026", "Stalled and partially stalled convergence SHALL be classified against explicit thresholds; missing observation SHALL be reported as unknown, not as stalled or converged.",
     ["C069"], [P + "observation.py"], [T + "ObservationTest.test_stall_thresholds"]),
    ("INV34-REQ-027", "Conflicting constraints SHALL be resolved by a configured precedence order with a recorded trace.",
     ["C047"], [P + "policy.py"], [T + "ResilienceTelemetryAuditTest.test_precedence"]),
    ("INV34-REQ-028", "Backups SHALL be digest-verified and restored state SHALL be marked for reconciliation before use.",
     ["C096"], [P + "store.py"], [T + "StoreTest.test_backup_restore_marks_needs_reconcile"]),
    ("INV34-REQ-029", "Concurrent duplicate submissions SHALL commit at most one operation.",
     ["C062"], [P + "reconciler.py"], [T + "ReconcilerTest.test_concurrent_submits_single_commit"]),
    ("INV34-REQ-030", "Random interleavings of submit/reconcile/observe with injected faults SHALL preserve observed<=desired<=max and monotonic presentation.",
     ["C081", "C085"], [P + "reconciler.py"], [T + "ReconcilerTest.test_property_random_sequences_invariants"]),
]
