"""GENERATED by witgen.py from wit/inv20.wit -- DO NOT EDIT (CI checks freshness)."""
SOURCE_SHA256 = "70207097204de8735404cff4ee407c43b5abeca9dc98ac47ca2c473694d1d308"
WIT = {
 "interfaces": {
  "handler": [
   "handle"
  ],
  "outgoing": [
   "send"
  ],
  "types": [
   "body",
   "entries",
   "finish",
   "get",
   "head",
   "headers",
   "read",
   "status",
   "trailers",
   "write"
  ]
 },
 "package": "pk:inv20@4.3.0",
 "worlds": {
  "middleware": {
   "export": [
    "handler"
   ],
   "import": [
    "handler"
   ]
  },
  "service": {
   "export": [
    "handler"
   ],
   "import": []
  },
  "service-with-egress": {
   "export": [
    "handler"
   ],
   "import": [
    "outgoing"
   ]
  }
 }
}
