"""WIT structural validator + deterministic binding-metadata generator (checklist component 2).

This is *not* a replacement for ``wit-bindgen``/``wasm-tools``; it is the dependency-free gate
that (a) checks every INV-20 world obeys the contract (exactly one handler export, outgoing only
as an explicit import, no ambient sockets/filesystem), (b) enforces major-version compatibility,
and (c) generates ``_wit_generated.py`` — a Python symbol table used by the traceability map and
by tests — with a source digest so CI fails on stale output.

    python -m inv20_http_component_worlds.witgen            # regenerate
    python -m inv20_http_component_worlds.witgen --check    # CI: exit 1 if stale or invalid
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import re
import sys
from dataclasses import dataclass, field
from typing import Dict, List, Tuple

PKG = pathlib.Path(__file__).resolve().parent
WIT = PKG / "wit" / "inv20.wit"
OUT = PKG / "_wit_generated.py"
SUPPORTED_MAJOR = 4
ALLOWED_IMPORTS = {"handler", "outgoing"}
_COMMENT = re.compile(r"//[^\n]*")
_PKG = re.compile(r"^\s*package\s+([a-z][a-z0-9-]*):([a-z][a-z0-9-]*)@(\d+)\.(\d+)\.(\d+)\s*;", re.M)
_BLOCK = re.compile(r"\b(interface|world)\s+([a-z][a-z0-9-]*)\s*\{")
_FUNC = re.compile(r"([a-z][a-z0-9-]*)\s*:\s*func\s*\(")
_ITEM = re.compile(r"\b(import|export)\s+([^;{}]+);")


class WitError(ValueError):
    pass


@dataclass
class WitPackage:
    namespace: str
    name: str
    version: Tuple[int, int, int]
    interfaces: Dict[str, List[str]] = field(default_factory=dict)
    worlds: Dict[str, Dict[str, List[str]]] = field(default_factory=dict)


def _blocks(text: str):
    for m in _BLOCK.finditer(text):
        depth, i = 1, m.end()
        while depth and i < len(text):
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        if depth:
            raise WitError(f"unterminated {m.group(1)} {m.group(2)}")
        yield m.group(1), m.group(2), text[m.end(): i - 1]


def parse(text: str) -> WitPackage:
    src = _COMMENT.sub("", text)
    if src.count("{") != src.count("}"):
        raise WitError("unbalanced braces")
    pm = _PKG.search(src)
    if not pm:
        raise WitError("missing or malformed package declaration")
    pkg = WitPackage(pm.group(1), pm.group(2), (int(pm.group(3)), int(pm.group(4)), int(pm.group(5))))
    for kind, name, body in _blocks(src):
        if kind == "interface":
            if name in pkg.interfaces:
                raise WitError(f"duplicate interface {name}")
            pkg.interfaces[name] = sorted(set(_FUNC.findall(body)))
        else:
            items = {"import": [], "export": []}
            for d, target in _ITEM.findall(body):
                items[d].append(target.strip())
            pkg.worlds[name] = items
    return pkg


def validate(pkg: WitPackage, *, require_major: int | None = None) -> None:
    if require_major is not None and pkg.version[0] != require_major:
        raise WitError(f"version skew: {pkg.version[0]}.x not supported (need {require_major}.x)")
    if not pkg.worlds:
        raise WitError("no worlds declared")
    for wname, items in pkg.worlds.items():
        handlers = [e for e in items["export"] if e.split(".")[0] in pkg.interfaces]
        if len(items["export"]) != 1 or len(handlers) != 1:
            raise WitError(f"world {wname}: must export exactly one handler interface")
        for imp in items["import"]:
            if ":" in imp or imp not in ALLOWED_IMPORTS or imp not in pkg.interfaces:
                raise WitError(f"world {wname}: import {imp!r} is not an allowed explicit capability")
        if wname == "service" and "outgoing" in items["import"]:
            raise WitError("world service must not import outgoing HTTP")


def generate(src_path: pathlib.Path = WIT) -> str:
    text = src_path.read_text()
    pkg = parse(text)
    validate(pkg, require_major=SUPPORTED_MAJOR)
    digest = hashlib.sha256(text.encode()).hexdigest()
    table = {"package": f"{pkg.namespace}:{pkg.name}@{'.'.join(map(str, pkg.version))}",
             "interfaces": pkg.interfaces, "worlds": pkg.worlds}
    return ('"""GENERATED by witgen.py from wit/inv20.wit -- DO NOT EDIT (CI checks freshness)."""\n'
            f'SOURCE_SHA256 = "{digest}"\n'
            f"WIT = {json.dumps(table, sort_keys=True, indent=1)}\n")


def main(argv: List[str]) -> int:
    try:
        out = generate()
    except WitError as exc:
        print(f"WIT INVALID: {exc}", file=sys.stderr)
        return 1
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text() != out:
            print("STALE: _wit_generated.py does not match wit/inv20.wit; run witgen", file=sys.stderr)
            return 1
        print("WIT bindings fresh")
        return 0
    OUT.write_text(out)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
