"""Hand-maintained implementation status for MC-001..MC-106 (source for TRACEABILITY.json).
Status vocabulary:
  IMPLEMENTED  code + positive/negative tests pass on this build host (NOT an acceptance)
  PARTIAL      some of the component exists; ``gap`` says exactly what is missing
  BLOCKED      cannot be completed inside the repository; ``gap`` names the external input
No entry is ACCEPTED: acceptance needs an independent human reviewer (MC-093)."""
I, P, B = "IMPLEMENTED", "PARTIAL", "BLOCKED"
S = {
 "MC-001": (B, ["docs/OWNERSHIP.md"], [], "a named accountable owner, security reviewer, on-call and release approver"),
 "MC-002": (P, ["docs/ADR-0001-enforcement-backends.md"], [], "ADR is Proposed; owner approval"),
 "MC-003": (P, ["docs/REQUIREMENTS.md"], ["test_enforcement_linux", "test_service_e2e"], "owner approval; FR-14 (macOS) unverified"),
 "MC-004": (P, ["docs/NFR.json", "tools/bench.py"], [], "numbers PROPOSED, measured on one host; owner approval"),
 "MC-005": (I, ["errors.py"], ["test_contracts_and_fixtures.ErrorTaxonomyTest"], ""),
 "MC-006": (I, ["lifecycle.py", "runtime.py"], ["test_control_plane.LeaseQuarantineLifecycleTest"], ""),
 "MC-007": (P, ["docs/COMPATIBILITY.md", "control.py::negotiate"], ["test_contracts_and_fixtures.NegotiationTest"], "policy owner approval; migration tooling for /1 consumers"),
 "MC-008": (I, ["control.py::Admission", "docs/LIMITS_AND_CAPACITY.md"], ["test_control_plane.AdmissionTest"], "values PROPOSED"),
 "MC-009": (I, ["runtime.py", "config.py::offline_mode", "docs/OPERATING_POLICY.md"], ["test_service_e2e.RefusalPathTest", "test_resilience"], "cached-profiles-only mode is declared but launch path treats it as allow; profile pinning store not built"),
 "MC-010": (P, ["docs/OPERATING_POLICY.md", "config.py::TIGHTEN_ONLY"], ["test_evidence_and_config.ConfigTest.test_overlay_tighten_only"], "residency/cost inputs do not exist in this tier; owner approval"),
 "MC-011": (P, ["TRACEABILITY.json", "tools/gen_traceability.py"], ["test_release.TraceabilityTest"], "owners UNASSIGNED for all 100 checks"),
 "MC-012": (P, ["docs/COMPATIBILITY.md"], [], "only x86_64 / kernel 6.18 / Python 3.11 exercised"),
 "MC-013": (I, ["control.py::issue_token/authenticate"], ["test_control_plane.AuthTest"], "IdP / key distribution integration is external"),
 "MC-014": (I, ["control.py::Authorizer"], ["test_control_plane.AuthzTest"], ""),
 "MC-015": (I, ["control.py::IdempotencyCache/retry", "linux/launcher.py (timeout, cancel)"], ["test_control_plane.RetryIdempotencyTest", "test_enforcement_linux.EnforcementTest.test_cancellation_kills_tree"], ""),
 "MC-016": (I, ["errors.py", "schemas/PK_SANDBOX_ERROR-1.schema.json"], ["test_contracts_and_fixtures"], ""),
 "MC-017": (I, ["control.py::negotiate"], ["test_contracts_and_fixtures.NegotiationTest"], ""),
 "MC-018": (I, ["docs/LIMITS_AND_CAPACITY.md", "control.py::Limits"], ["test_control_plane.AdmissionTest"], "no request queue: max_queue reserved"),
 "MC-019": (I, ["fixtures/", "tools/make_fixtures.py"], ["test_contracts_and_fixtures.FixtureContractTest"], ""),
 "MC-020": (P, ["integration.py"], ["test_service_e2e.InteropTest"], "tested against reference stubs only; real PLN-04/GAP-13/GAP-09 builds not available"),
 "MC-021": (P, ["pyproject.toml"], [], "pk_core wheel + digest not supplied"),
 "MC-022": (I, ["tools/build_release.py"], ["test_release.ReleaseTest.test_reproducible"], ""),
 "MC-023": (I, ["config.py::load/validate"], ["test_evidence_and_config.ConfigTest", "test_backends_and_fuzz.FuzzTest.test_config_loader"], ""),
 "MC-024": (I, ["config.py::overlay"], ["test_evidence_and_config.ConfigTest.test_overlay_tighten_only"], ""),
 "MC-025": (I, ["config.py::ConfigStore"], ["test_evidence_and_config.ConfigTest.test_atomic_activation_provenance_and_rollback"], ""),
 "MC-026": (I, ["config.py::ConfigStore._write_atomic"], ["test_evidence_and_config.ConfigTest.test_atomic_activation_provenance_and_rollback"], ""),
 "MC-027": (I, ["config.py::ConfigStore.rollback"], ["test_evidence_and_config.ConfigTest.test_atomic_activation_provenance_and_rollback"], ""),
 "MC-028": (I, ["config.py::redact", "docs/OPERATING_POLICY.md"], ["test_evidence_and_config.ConfigTest.test_redaction", "test_evidence_and_config.TelemetryTest.test_logger_ids_and_redaction"], ""),
 "MC-029": (P, ["tools/bootstrap.sh"], [], "run on this container only, not on a freshly provisioned supported node"),
 "MC-030": (I, ["linux/seccomp.py", "linux/syscall_tables.py"], ["test_backends_and_fuzz.CompilerTest", "test_enforcement_linux"], ""),
 "MC-031": (P, ["backends.py::bwrap_argv"], ["test_backends_and_fuzz.BackendAdapterTest.test_bwrap_argv"], "bwrap not installed on build host; adapter never executed"),
 "MC-032": (B, ["backends.py::seatbelt_profile/seatbelt_argv"], ["test_backends_and_fuzz.BackendAdapterTest.test_seatbelt_profile"], "a macOS host to execute and certify the Seatbelt backend"),
 "MC-033": (I, ["backends.py::probe/require"], ["test_backends_and_fuzz.BackendAdapterTest.test_probe_never_raises_and_require_fails_closed"], ""),
 "MC-034": (I, ["linux/seccomp.py::set_no_new_privs"], ["test_enforcement_linux.EnforcementTest.test_kernel_read_back_shows_controls"], ""),
 "MC-035": (I, ["linux/primitives.py::switch_ids/write_id_maps/lock_securebits"], ["test_enforcement_linux.EnforcementTest.test_run_as_unprivileged_identity", "test_enforcement_linux.EnforcementTest.test_all_escape_probes_blocked"], ""),
 "MC-036": (I, ["linux/primitives.py::drop_capabilities"], ["test_enforcement_linux.EnforcementTest.test_kernel_read_back_shows_controls"], ""),
 "MC-037": (P, ["linux/primitives.py::make_mounts_private/mount_private_tmpfs"], ["test_enforcement_linux.EnforcementTest.test_kernel_read_back_shows_controls"], "no pivot_root / read-only root in the native backend (bwrap path provides it, unexecuted)"),
 "MC-038": (I, ["linux/landlock.py"], ["test_enforcement_linux.EnforcementTest.test_landlock_confines_reads"], ""),
 "MC-039": (P, ["linux/launcher.py (net ns)"], ["test_enforcement_linux.EnforcementTest.test_network_namespace_blocks_egress_even_with_socket_allowed"], "deny-all egress only; no allow-listed egress / interface policy"),
 "MC-040": (P, ["linux/primitives.py::mount_fresh_proc"], ["test_enforcement_linux.EnforcementTest.test_all_escape_probes_blocked"], "/sys and /dev still host views in native backend"),
 "MC-041": (I, ["linux/primitives.py::close_fds_except"], ["test_enforcement_linux.EnforcementTest.test_all_escape_probes_blocked"], ""),
 "MC-042": (I, ["linux/primitives.py::sanitize_env"], ["test_backends_and_fuzz.BackendAdapterTest.test_env_sanitizer", "test_enforcement_linux"], ""),
 "MC-043": (P, ["linux/primitives.py::apply_rlimits"], ["test_enforcement_linux.EnforcementTest.test_kernel_read_back_shows_controls"], "cgroup v2 CPU/memory/IO not implemented (EX-004)"),
 "MC-044": (I, ["linux/launcher.py::launch"], ["test_enforcement_linux.EnforcementTest.test_pre_exec_refusal_means_nothing_runs"], ""),
 "MC-045": (I, ["linux/launcher.py::_supervisor"], ["test_enforcement_linux.EnforcementTest.test_timeout_kills_whole_tree", "test_enforcement_linux.EnforcementTest.test_host_crash_kills_sandbox"], ""),
 "MC-046": (I, ["linux/launcher.py::read_back/verify", "runtime.py", "attestation.py"], ["test_service_e2e.EndToEndTest.test_launch_produces_verifiable_signed_evidence"], "trust root is an HMAC node key (see MC-050)"),
 "MC-047": (P, ["linux/launcher.py (program digest)", "docs/EXCEPTIONS.json EX-003"], [], "rule contents launcher-attested; PTRACE_SECCOMP_GET_FILTER read-back not built"),
 "MC-048": (P, ["docs/THREAT_MODEL.json"], ["test_threat_model"], "draft; owner/security sign-off"),
 "MC-049": (P, ["attestation.py", "profiles.py"], [], "no asymmetric signatures on policy artifacts; downgrade protection covers config overlays only"),
 "MC-050": (P, ["attestation.py::NodeIdentity"], [], "hardware-rooted node attestation (TPM/TEE) and an identity service"),
 "MC-051": (I, ["tools/escape_probes.c"], ["test_enforcement_linux"], "memory boundary = separate address spaces; no dedicated test"),
 "MC-052": (P, ["docs/OPERATING_POLICY.md"], [], "design only; no transport exists; at-rest encryption delegated to disk encryption"),
 "MC-053": (I, ["attestation.py::EvidenceVerifier", "runtime.py"], ["test_evidence_and_config.EvidenceTest.test_time_source_down_fails_safe", "test_service_e2e.RefusalPathTest"], ""),
 "MC-054": (I, ["attestation.py::AuditChain"], ["test_evidence_and_config.AuditChainTest"], "external anchoring of the head hash is an operator step"),
 "MC-055": (I, ["tools/escape_probes.c"], ["test_enforcement_linux", "test_threat_model"], "side channels are residual (T15)"),
 "MC-056": (P, ["docs/OPERATING_POLICY.md"], ["test_resilience"], "site/control-plane failure rows are design statements"),
 "MC-057": (P, ["runtime.py::status"], [], "no watchdog / stall detector with quantified thresholds"),
 "MC-058": (I, ["control.py::retry"], ["test_control_plane.RetryIdempotencyTest"], ""),
 "MC-059": (I, ["control.py::Admission"], ["test_control_plane.AdmissionTest", "test_resilience"], ""),
 "MC-060": (P, ["docs/OPERATING_POLICY.md"], [], "no cross-node failover by design; needs PLN-04 confirmation"),
 "MC-061": (P, ["docs/OPERATING_POLICY.md"], [], "telemetry-export degraded mode described; GAP-09 exporter not built"),
 "MC-062": (I, ["config.py", "attestation.py", "linux/launcher.py"], ["test_resilience"], ""),
 "MC-063": (P, ["control.py::LeaseTable"], ["test_control_plane.LeaseQuarantineLifecycleTest.test_fenced_leases"], "leases are in-process; multi-controller needs a shared store"),
 "MC-064": (P, ["control.py::Quarantine"], ["test_control_plane.LeaseQuarantineLifecycleTest.test_quarantine_authorized_and_audited"], "quarantine blocks new launches; does not yet kill already-running sandboxes"),
 "MC-065": (P, ["tests/test_resilience.py"], ["test_resilience"], "local fault injection only; no recovery-objective numbers"),
 "MC-066": (I, ["tools/bench.py"], [], ""),
 "MC-067": (P, ["docs/NFR.json"], [], "thresholds PROPOSED"),
 "MC-068": (P, ["tools/bench.py"], [], "steady + burst only; overload/scale/recovery scenarios missing"),
 "MC-069": (P, ["observability.py"], [], "per-profile metrics; per-tenant CPU/memory accounting needs cgroups"),
 "MC-070": (P, ["evidence/profile-launch.txt"], [], "one cProfile run; no hop/copy analysis"),
 "MC-071": (B, [], [], "depends on MC-070 analysis; no optimisation claimed"),
 "MC-072": (P, ["docs/LIMITS_AND_CAPACITY.md"], [], "single-node model only"),
 "MC-073": (B, [], [], "edge hardware and a power meter"),
 "MC-074": (I, ["tools/bench.py --gate", "ci/ci.sh"], [], "thresholds PROPOSED"),
 "MC-075": (I, ["runtime.py::status", "schemas/PK_SANDBOX_STATUS-1.schema.json"], ["test_service_e2e.EndToEndTest"], ""),
 "MC-076": (I, ["observability.py::Metrics"], ["test_evidence_and_config.TelemetryTest"], ""),
 "MC-077": (I, ["observability.py::Logger"], ["test_evidence_and_config.TelemetryTest.test_logger_ids_and_redaction"], ""),
 "MC-078": (I, ["observability.py::new_traceparent"], ["test_evidence_and_config.TelemetryTest.test_trace_propagation", "test_service_e2e.EndToEndTest"], ""),
 "MC-079": (I, ["observability.py::Diagnostics"], ["test_evidence_and_config.TelemetryTest.test_diagnostics_sampled_and_redacted"], ""),
 "MC-080": (I, ["observability.py::Reasons"], ["test_service_e2e.RefusalPathTest"], ""),
 "MC-081": (I, ["observability.py::Reasons.explain"], ["test_evidence_and_config.TelemetryTest.test_reasons_and_explain"], "API only, no UI"),
 "MC-082": (P, ["runtime.py (release_digest in evidence)"], [], "live infrastructure graph does not exist here"),
 "MC-083": (P, ["docs/OPERATING_POLICY.md", "config.py::telemetry"], [], "retention enforced by the export target, not built"),
 "MC-084": (P, ["observability.py::ALERT_RULES"], ["test_evidence_and_config.TelemetryTest.test_alert_classes_distinct"], "dashboards not deployed"),
 "MC-085": (I, ["schema_check.py", "fixtures/"], ["test_contracts_and_fixtures"], ""),
 "MC-086": (P, ["tests/test_enforcement_linux.py", "tests/test_service_e2e.py"], ["test_enforcement_linux", "test_service_e2e"], "real OS enforcement verified; adjacent layers are stubs"),
 "MC-087": (B, [".github/workflows/ci.yml"], [], "runners for aarch64, other kernels, Python 3.10/3.12/3.13, bwrap and macOS"),
 "MC-088": (I, ["tests/test_backends_and_fuzz.py::FuzzTest"], ["test_backends_and_fuzz.FuzzTest"], "generative, seeded; no coverage-guided fuzzer"),
 "MC-089": (I, ["tests"], ["test_service_e2e.EndToEndTest.test_concurrent_launches_respect_quota_and_isolate_evidence", "test_control_plane.AdmissionTest.test_concurrent_acquire_never_exceeds_ceiling"], ""),
 "MC-090": (I, ["docs/THREAT_MODEL.json"], ["test_threat_model"], ""),
 "MC-091": (B, ["tools/bench.py"], [], "soak (>1 h) and fleet-scale environments"),
 "MC-092": (P, ["tests/test_resilience.py"], ["test_resilience"], "partition/reconnect need a real control plane"),
 "MC-093": (B, ["tools/exit_gate.py (acceptance bundle)"], [], "an independent human reviewer's signing key and signature"),
 "MC-094": (B, ["tests/test_component.py"], [], "pk_core framework (fails under INV39_CERT_TARGET=1)"),
 "MC-095": (P, ["docs/OPERATIONS.md", "config.py::rollback", "control.py::Quarantine"], [], "no fleet orchestrator"),
 "MC-096": (P, ["docs/COMPATIBILITY.md"], [], "see MC-012"),
 "MC-097": (P, ["docs/OPERATIONS.md"], [], "advisory channel + SLA owner unassigned"),
 "MC-098": (P, ["docs/OPERATIONS.md"], ["test_resilience"], "restore drill not performed"),
 "MC-099": (P, ["docs/OPERATIONS.md"], [], "not exercised by an operator"),
 "MC-100": (P, ["docs/OPERATIONS.md"], [], "paging integration + owner"),
 "MC-101": (P, ["docs/OPERATIONS.md"], [], "owner + calendar"),
 "MC-102": (P, ["docs/EXCEPTIONS.json"], [], "every entry owner _UNASSIGNED_"),
 "MC-103": (I, ["tools/exit_gate.py"], ["test_release.ReleaseTest.test_exit_gate_reports_no_go"], "verdict is NO_GO by construction until owners/acceptance exist"),
 "MC-104": (P, ["ci/ci.sh", ".github/workflows/ci.yml"], [], "ci.sh executed locally; hosted workflow never run"),
 "MC-105": (P, ["tools/build_release.py"], ["test_release"], "SBOM+provenance done; release signing key not provisioned"),
 "MC-106": (B, ["pyproject.toml"], [], "the owner's choice of licence and NOTICE text"),
}
