"""Typed-binding generator for GAP03-IDL/1 (MC-001 CHK-010).

``python -m gap03_topology_aware_scheduler.controlplane.gen_bindings`` rewrites
``bindings.py``; CI (test_mc001) fails if the checked-in file drifts.
"""
from __future__ import annotations

import pathlib
import sys

from . import wire

GENERATOR_VERSION = "gap03-bindgen/1.0"
PY = {"string": "str", "integer": "int", "boolean": "bool", "array": "list", "object": "dict"}


def render() -> str:
    lines = ['"""GENERATED by gen_bindings - do not edit.', f"generator: {GENERATOR_VERSION}",
             f"python: {sys.version_info.major}.{sys.version_info.minor}+ (stdlib dataclasses only)"]
    for name in sorted(wire.SCHEMAS):
        lines.append(f"{name}: sha256={wire.fingerprint(name)}")
    lines += ['"""', "from __future__ import annotations", "", "from dataclasses import dataclass, field", ""]
    lines.append("SCHEMA_DIGESTS = {")
    for name in sorted(wire.SCHEMAS):
        lines.append(f"    {name!r}: {wire.fingerprint(name)!r},")
    lines += ["}", ""]
    for name in sorted(wire.SCHEMAS):
        cls = name.replace("/", "_V").replace(".", "_").title().replace("_", "")
        lines += ["", "@dataclass(frozen=True)", f"class {cls}:", f"    SCHEMA = {name!r}"]
        req = [(f, s) for f, s in wire.SCHEMAS[name]["fields"].items() if s.get("required", True)]
        opt = [(f, s) for f, s in wire.SCHEMAS[name]["fields"].items() if not s.get("required", True)]
        for f, s in req:
            lines.append(f"    {f}: {PY[s['type']]}")
        for f, s in opt:
            lines.append(f"    {f}: {PY[s['type']]} = {s.get('default')!r}")
        lines += ["", "    def to_wire(self) -> dict:",
                  "        return {k: getattr(self, k) for k in self.__dataclass_fields__}", "",
                  "    @classmethod", "    def from_wire(cls, obj: dict):",
                  "        from . import wire", "        wire.validate(cls.SCHEMA, obj)",
                  "        return cls(**obj)", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    target = pathlib.Path(__file__).with_name("bindings.py")
    target.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
