"""Render REMEDIATION_REPORT.md from STATUS_REGISTER.json, TRACEABILITY.json, test-report.json,
acceptance-manifest.json and the benchmark bundle.  The report is generated from machine data only
(MC-57: no independent, contradictory status list)."""
from __future__ import annotations

import json
import os

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(name):
    with open(os.path.join(PKG, name), encoding="utf-8") as fh:
        return json.load(fh)


def main() -> int:
    reg, tr = load("STATUS_REGISTER.json"), load("TRACEABILITY.json")
    rep, man = load("test-report.json"), load("acceptance-manifest.json")
    bench = load("evidence/benchmark/summary.json")
    L = ["# INV-57 v4.3.0 — Remediation Report", "",
         "_Generated by `tools/render_report.py` from the machine-readable register, test report, benchmark "
         "bundle and acceptance manifest. Edit those sources, not this file._", "",
         "## Verdict", "",
         f"**Production exit gate: {man['verdict']}.** Full manifest (with digest): `acceptance-manifest.json` — unsigned.", ""]
    L += [f"- {b}" for b in man["blockers"]]
    L += ["", "## Numbers", "", "| Measure | v4.2.0 | v4.3.0 |", "|---|---|---|",
          "| Remediation components CLOSED | 0 / 82 | " + f"{reg['counts'].get('CLOSED', 0)} / 82 |",
          "| … IMPLEMENTED_LOCAL / PARTIAL / BLOCKED / OPEN | — | "
          + " / ".join(str(reg['counts'].get(k, 0)) for k in ("IMPLEMENTED_LOCAL", "PARTIAL", "BLOCKED", "OPEN")) + " |",
          "| C-items present / partial / missing | 11 / 27 / 62 | "
          + " / ".join(str(tr['counts'].get(k, 0)) for k in ("present", "partial", "missing")) + " |",
          f"| Tests (passed / skipped / failed) | 13 / 2 / 0 | {rep['counts'].get('passed', 0)} / "
          f"{rep['counts'].get('skipped', 0)} / {rep['counts'].get('failed', 0) + rep['counts'].get('error', 0)} |",
          "| 1000-event replay p99 (build machine) | ~3,700 ms (measured on baseline) | "
          f"{bench['replay_inmemory_1000_events']['p99_ms']} ms |",
          f"| SQLite durable append throughput | n/a | {bench['sqlite_durable_append_events_per_s']} events/s |",
          "", "No C-item was promoted to `present`: the checklist's exit gates require production evidence and an "
          f"approval that this pass cannot supply. {tr['counts'].get('partial', 0) - 27} C-items moved from `missing` "
          "to `partial` on resolving evidence plus passing tests.", ""]
    by = {}
    for c in reg["components"]:
        by.setdefault(c["status"], []).append(c)
    for st in ("IMPLEMENTED_LOCAL", "PARTIAL", "OPEN", "BLOCKED"):
        L += [f"## {st} ({len(by.get(st, []))})", "", "| ID | Component | Done | Remaining / blocker |", "|---|---|---|---|"]
        for c in by.get(st, []):
            rem = "; ".join(c["blockers"]) if st == "BLOCKED" and c["blockers"] else (c["remaining"] or "production evidence / approval")
            if st != "BLOCKED" and c["blockers"]:
                rem += " — blocked by: " + "; ".join(c["blockers"])
            L.append(f"| {c['id']} | {c['title']} | {c['done'] or '—'} | {rem} |")
        L.append("")
    blockers = {}
    for c in reg["components"]:
        for b in c["blockers"]:
            blockers.setdefault(b, []).append(c["id"])
    L += ["## What unblocks the most", "", "| External input needed | Components it gates |", "|---|---|"]
    for b, ids in sorted(blockers.items(), key=lambda kv: -len(kv[1])):
        L.append(f"| {b} | {len(ids)}: {', '.join(ids)} |")
    L += ["", "## Gate evidence problems", ""] + [f"- {p['owner']}: {p['problem']}" for p in man["problems"]] + [""]
    with open(os.path.join(PKG, "REMEDIATION_REPORT.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
