# SPDX-License-Identifier: LicenseRef-LinearFinance-Proprietary
"""Requirements traceability matrix generator (INV30-GAP-009 · INV-30-C020).

Maps every INV-30-Cxxx control and every INV30-GAP-xxx to implementation, tests,
docs and release-gate evidence. ``check()`` fails if any referenced path is
missing, so the matrix cannot silently rot. Output: docs/TRACEABILITY.json + .md.
"""
from __future__ import annotations

import json
from pathlib import Path

PKG = Path(__file__).resolve().parent

# control range -> (implementation, tests, docs)
BANDS = [
    (1, 10, ["contract.py", "backend.py"], ["tests/test_component.py"], ["README.md", "docs/ADR-0001-cheri-capability-tier.md", "docs/OWNERSHIP.md"]),
    (11, 20, ["core.py", "lifecycle.py", "policy.py", "limits.py", "traceability.py"], ["tests/test_capability_core.py", "tests/test_service.py"], ["docs/REQUIREMENTS.md", "docs/DEPLOYMENT_CONTEXTS.md", "docs/NFR.md", "docs/LIFECYCLE.md", "docs/PRECEDENCE.md"]),
    (21, 30, ["schema.py", "errors.py", "authz.py", "service.py", "limits.py"], ["tests/test_contracts.py", "tests/test_framework_integration.py"], ["docs/INTERFACES.md"]),
    (31, 40, ["config.py", "secret_refs.py", "deps.py", "ops.py"], ["tests/test_config_integrity.py", "tests/test_ops.py"], ["docs/CONFIGURATION.md", "docs/INSTALL.md", "docs/CHERI_SPEC_PIN.md"]),
    (41, 50, ["authz.py", "audit.py", "integrity.py", "service.py"], ["tests/test_security.py"], ["docs/THREAT_MODEL.md", "docs/SUPPLY_CHAIN.md"]),
    (51, 60, ["resilience.py", "service.py", "backend.py"], ["tests/test_resilience.py", "tests/test_concurrency.py"], ["docs/RESILIENCE.md", "docs/STATE_AND_RECOVERY.md"]),
    (61, 70, ["bench.py", "limits.py", "resilience.py"], ["tests/test_security.py"], ["docs/PERFORMANCE.md", "config/perf_thresholds.json"]),
    (71, 80, ["telemetry.py", "service.py"], ["tests/test_service.py"], ["docs/OBSERVABILITY.md", "ops/dashboards/inv30.json", "ops/alerts/inv30-alerts.yaml"]),
    (81, 90, ["release.py"], ["tests/test_capability_core.py", "tests/test_contracts.py", "tests/test_framework_integration.py", "tests/test_hardware_backend.py", "tests/test_properties.py", "tests/test_concurrency.py", "tests/test_security.py", "tests/test_resilience.py"], ["docs/TESTING.md", "docs/RELEASE_AND_EXIT_GATE.md"]),
    (91, 100, ["ops.py", "release.py"], ["tests/test_ops.py"], ["docs/SUPPORT_SLO.md", "docs/ROLLOUT.md", "docs/COMPATIBILITY_MATRIX.md", "docs/VULN_AND_EOL.md", "docs/STATE_AND_RECOVERY.md", "docs/RUNBOOKS.md", "docs/INCIDENT_RESPONSE.md", "docs/REVIEW_PROCESS.md", "WAIVERS.json", "docs/RELEASE_AND_EXIT_GATE.md"]),
]
HARDWARE_BLOCKED = {"INV-30-C031", "INV-30-C084", "INV-30-C068"}
SIGNOFF_PENDING = {"INV-30-C009", "INV-30-C010"}
PARTIAL_EXTERNAL = {"INV-30-C088": "fleet-scale soak needs estate cluster",
                    "INV-30-C047": "TLS/at-rest encryption delegated to host platform"}


def build() -> dict:
    checklist = json.loads((PKG / "CHECKLIST.json").read_text(encoding="utf-8"))["items"]
    gaps = json.loads((PKG / "MISSING_COMPONENTS.json").read_text(encoding="utf-8"))["items"]
    by_ctrl: dict[str, list[str]] = {}
    for g in gaps:
        for c in g["checklist_ids"]:
            by_ctrl.setdefault(c, []).append(g["gap_id"])
    rows = []
    for item in checklist:
        n = item["ordinal"]
        impl, tests, docs = next((i, t, d) for lo, hi, i, t, d in BANDS if lo <= n <= hi)
        cid = item["check_id"]
        status = ("blocked-hardware" if cid in HARDWARE_BLOCKED else "pending-signoff" if cid in SIGNOFF_PENDING
                  else "partial-external" if cid in PARTIAL_EXTERNAL else "implemented")
        rows.append({"control": cid, "dimension": item["dimension"], "requirement": item["requirement"],
                     "gaps": by_ctrl.get(cid, []), "implementation": impl, "tests": tests, "docs": docs,
                     "release_evidence": ["evidence/RELEASE_EVIDENCE.json#gate", "pk_core gate (PK_GATE_RESULTS/1)"],
                     "status": status, "note": PARTIAL_EXTERNAL.get(cid, "")})
    gap_rows = [{"gap": g["gap_id"], "component": g["component"], "controls": g["checklist_ids"]} for g in gaps]
    return {"schema": "INV30_TRACEABILITY/1", "controls": rows, "gaps": gap_rows}


def check(matrix: dict) -> list[str]:
    missing = []
    for r in matrix["controls"]:
        for p in r["implementation"] + r["tests"] + r["docs"]:
            if not (PKG / p).exists():
                missing.append(f"{r['control']}: {p}")
    if len(matrix["controls"]) != 100:
        missing.append("matrix does not cover 100 controls")
    return missing


def write() -> dict:
    m = build()
    (PKG / "docs" / "TRACEABILITY.json").write_text(json.dumps(m, indent=1))
    lines = ["# INV-30 requirements traceability matrix (generated by traceability.py — do not edit)", "",
             "| Control | Dimension | Gaps | Implementation | Tests | Docs | Status |", "|---|---|---|---|---|---|---|"]
    for r in m["controls"]:
        lines.append(f"| {r['control']} | {r['dimension']} | {', '.join(g.replace('INV30-', '') for g in r['gaps']) or '—'} | "
                     f"{', '.join(r['implementation'])} | {', '.join(t.replace('tests/', '') for t in r['tests'])} | "
                     f"{', '.join(d.replace('docs/', '') for d in r['docs'])} | {r['status']} |")
    lines += ["", "Every row also traces to `evidence/RELEASE_EVIDENCE.json#gate` and the pk_core gate output.",
              "REQ-xxx ↔ control mapping: docs/REQUIREMENTS.md."]
    (PKG / "docs" / "TRACEABILITY.md").write_text("\n".join(lines) + "\n")
    return m


if __name__ == "__main__":
    mm = write()
    probs = check(mm)
    print(json.dumps({"controls": len(mm["controls"]), "problems": probs}, indent=1))
    raise SystemExit(bool(probs))
