"""Render docs/CLOSURE_LEDGER.md from tools/closure_status.py (single source of truth)."""
import pathlib
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PKG / "tools"))
import closure_status as cs  # noqa: E402

EXIT = [
    ("Every P0 component PASS with linked evidence", "NO - see P0 rows not PASS"),
    ("P1/P2 items for the deployment topology PASS or waived", "NO - waivers not yet issued by the owner"),
    ("All 100 C001-C100 items in the machine-readable bundle", "YES - represented as NOT_ASSESSED (pk_core absent)"),
    ("No mandatory test reported PASS while skipped", "YES - 3 pk_core tests skipped and never counted"),
    ("Standalone tests pass normal + -O on Tier-1 interpreters", "YES - CPython 3.10-3.13 on Linux x86_64"),
    ("Real bridge/lowering/ABI/cancellation/composition end-to-end",
     "PARTIAL - real bridge + ABI; siblings surrogate"),
    ("Exactly-once + isolation pass race/stress/property/soak/fault", "YES (local model)"),
    ("Explicit bounds for tombstones, ids, in-flight, queues, waiters", "YES"),
    ("p99 bridge SLO measured on the certified environment", "NO - measured on the Python model only"),
    ("Metrics/logs/traces diagnose refusal/saturation/cancel/trap/dup", "YES (local); live backends not wired"),
    ("Threat model, scans, SBOM, licence review without open blockers", "PARTIAL - owner sign-off + licence pending"),
    ("Metadata, matrix, CI, gates, signing, artifacts reproducible",
     "PARTIAL - CI not yet run on a host; no owner key"),
    ("Canary, disable, rollback, runbooks, ownership exercised", "PARTIAL - rollback + canary exercised in-process"),
    ("pk_core verify passes on the final ledger", "NO - pk_core absent (local chain verifies)"),
    ("Final release record names approvers/risks/waivers/digests", "PARTIAL - digests in evidence; approver = owner"),
]


def main():
    rows = ["| # | Component | Pri | Status | Evidence | Notes |", "|---|---|---|---|---|---|"]
    for n, t, p, s, ev, note in cs.ITEMS:
        rows.append(f"| {n} | {t} | {p} | **{s}** | {'<br>'.join(f'`{e}`' for e in ev)} | {note} |")
    counts = {s: sum(1 for i in cs.ITEMS if i[3] == s) for s in ("PASS", "PARTIAL", "BLOCKED", "OPEN")}
    p0 = [i for i in cs.ITEMS if i[2] == "P0" and i[3] != "PASS"]
    out = [
        "# INV-16 v4.2.0 → 4.3.0 Missing-Components Closure Ledger", "",
        f"Owner: {cs.OWNER} · Target version: {cs.TARGET} · Waivers: none issued · "
        "Generated by `tools/render_ledger.py`.",
        "Evidence paths are relative to `evidence/` unless they name a repository file.", "",
        "**Totals:** " + " · ".join(f"{k} {v}" for k, v in counts.items()),
        "", f"**Production certification:** NO_GO — {len(p0)} P0 items are not PASS: "
        + ", ".join(f"#{i[0]}" for i in p0) + ".", "", *rows, "",
        "## Final production-exit checklist", "", "| Exit criterion | State |", "|---|---|",
        *[f"| {a} | {b} |" for a, b in EXIT], "",
        "## What unblocks certification (owner / sibling inputs)", "",
        "1. Supply and pin `pk_core` (version + hash) → items 1, 41, and the 100-item gate.",
        "2. Supply pinned INV-15, INV-11, INV-10, INV-17, INV-20 fixtures → replace `fixtures/` surrogates; "
        "items 2-6, 10, 25.",
        "3. Supply the production compiler backend and native wait primitive → items 7, 8, 21 on the certified host.",
        "4. Owner decisions: licence terms (42), residual-risk sign-off (27), release key (36), on-call (40), "
        "waivers.",
        "5. Run `.github/workflows/ci.yml` on a CI host (31, 32, 34, 35) and a production-length soak (19).", "",
    ]
    (PKG / "docs" / "CLOSURE_LEDGER.md").write_text("\n".join(out))


if __name__ == "__main__":
    main()
