"""Generate ops/SPEC.md from the code's own normative tables so the specification cannot drift
from the implementation (C012, C015, C016, C018, C019, C025, C026, C033, C048, C052, C053, C079).

    python -m inv69_agentic_workload_layer.tools.gen_spec [--check]

``--check`` exits 1 if the committed SPEC.md differs from what the code generates (CI drift gate).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .. import compat, config, context, errors, health, lifecycle, precedence, retry, telemetry, trust

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ops" / "SPEC.md"


def _table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    for r in rows:
        out.append("| " + " | ".join(str(x).replace("|", "\\|") for x in r) + " |")
    return "\n".join(out)


def generate() -> str:
    s = ["# INV-69 normative specification (generated — do not edit)", "",
         "Generated by `tools/gen_spec.py` from the implementation's own tables. `--check` in CI fails on drift.", ""]
    profiles = config.load_profiles()
    s += ["## C012 Deployment contexts and profiles (`config/profiles/*.json`, `config.resolve`)", "",
          _table(["context", "applicability", "rationale", "mandatory capabilities", "prohibited capabilities", "security posture"],
                 [(p["context"], p["applicability"], p["rationale"], ", ".join(p["mandatory_capabilities"]),
                   ", ".join(p["prohibited_capabilities"]), p["security_posture"]) for p in profiles.values()]), "",
          _table(["context", "network", "control plane", "storage", "clock", "hardware", "operator access"],
                 [(p["context"], *(p["environment"][k] for k in ("network", "control_plane", "storage", "clock", "hardware",
                                                                  "operator_access"))) for p in profiles.values()]), "",
          "Profile selection happens at configuration activation; unknown or internally inconsistent profiles are "
          "rejected (AGT-CFG-001); capabilities are derived from the effective configuration, never from environment "
          "detection.", ""]
    s += ["## C015 Lifecycle state machines (`lifecycle.py`)", ""]
    for name, (enum, table) in lifecycle.TABLES.items():
        rows = [(f.value, ", ".join(sorted(t.value for t in table.get(f, set()))) or "(terminal)") for f in enum]
        s += [f"### {name}", "", _table(["from", "legal targets"], rows), ""]
    s += ["Invariants enforced by `Lifecycle.transition`:", ""] + [f"- {i}" for i in lifecycle.INVARIANTS] + [
        "- duplicate `request_id` returns the original transition (idempotent); reuse for a different target is AGT-LCY-001",
        "- restore replays history through the same guards (`Lifecycle.restore`)", ""]
    s += ["## C016/C027 Versioning and compatibility (`compat.py`)", "",
          f"Component {compat.COMPONENT} {compat.COMPONENT_VERSION}; protocol {compat.PROTOCOL}.", "",
          "- MAJOR: breaking wire/persisted change; MINOR: additive; PATCH: fix.",
          "- Readers: current major + N-1 via registered migrators (`compat.migrate`); newer majors are refused.",
          "- Writers: current major only. Peers: same protocol major, features by capability intersection.",
          "- Deprecation stages: announce -> warn -> disable-by-default -> remove; minimum notice one minor release "
          "or 90 days, whichever is longer; security exceptions may shorten with a waiver (ops/WAIVERS.json).", "",
          _table(["schema", "major"], sorted(compat.SCHEMAS.items())), "",
          _table(["deprecated", "stage", "replacement", "removal"],
                 [(k, *v) for k, v in compat.DEPRECATIONS.items()]), ""]
    s += ["## C018/C048/C056 Dependency criticality and connectivity (`trust.py`)", "",
          _table(["dependency", "critical", "max cache age s", *trust.PHASES],
                 [(n, d["critical"], d["max_age_s"], *(d[p] for p in trust.PHASES)) for n, d in trust.DEPENDENCY_MATRIX.items()]),
          "", _table(["network operation", "offline class"], sorted(trust.NETWORK_OPS.items())), "",
          "Reconnect: deferred ops are returned in local-sequence order and re-evaluated by `trust.reconcile` "
          "against current assumptions (policy version etc.); duplicates are suppressed; nothing is replayed blindly.", ""]
    s += ["## C019 Precedence policy (`precedence.PRECEDENCE_POLICY`)", "",
          f"Version {precedence.PRECEDENCE_POLICY['version']}. Order (highest first): " +
          " > ".join(precedence.PRECEDENCE_POLICY["order"]) + ".", "",
          f"Hard (never waivable): {', '.join(precedence.PRECEDENCE_POLICY['hard'])}. Waivable: "
          f"{', '.join(precedence.PRECEDENCE_POLICY['waivable'])} (max {precedence.PRECEDENCE_POLICY['max_waiver_s']//86400} days).", "",
          _table(["collision", "resolution"], precedence.PRECEDENCE_POLICY["collisions"].items()), ""]
    s += ["## C025 Timeouts, cancellation, idempotency, backpressure (`context.py`, `retry.py`)", "",
          _table(["operation", "default budget s"], context.DEFAULT_TIMEOUTS.items()), "",
          _table(["operation class", "retry safety"], retry.OPERATION_CLASSES.items()), "",
          "- Deadlines are absolute (monotonic) and child deadlines never exceed the parent.",
          "- Cancellation propagates parent -> child. A cancel observed after DISPATCHED leaves the invocation "
          "INDETERMINATE (side effect unknown) and it is never auto-retried.",
          "- Admission: `max_active` running, `max_waiting` bounded waiters (up to their deadline), overflow shed with "
          "AGT-CAP-003 (retryable). `reserved_critical` slots serve priority=critical only.", ""]
    s += ["## C026 Error code registry (`errors.REGISTRY`)", "",
          f"Registry {errors.REGISTRY_VERSION}. Codes are immutable; retired codes are never reused.", "",
          _table(["code", "category", "retryable", "severity", "rpc", "http", "hint"],
                 [(c.code, c.category, c.retryable, c.severity, c.rpc_status, c.http_status, c.hint)
                  for c in errors.REGISTRY.values()]), "",
          "Caller-safe fields: code, category, retryable, message, correlation_id. Operator: + details (redacted). "
          "Audit: code + details digest only. Exception messages and tracebacks are never exported.", ""]
    s += ["## C033/C035 Configuration fields (`config.F`)", "",
          "Precedence: " + " -> ".join(config.SCOPES) + " (emergency may only tighten).", "",
          _table(["field", "type", "range", "unit", "reloadable", "sensitive", "settable up to scope", "safer direction",
                  "secure default"],
                 [(k, v[0].__name__, "" if v[1] is None else f"{v[1]}..{v[2]}", v[3] or "", v[4], v[5], v[6], v[7] or "",
                   config.flatten(config.SECURE_DEFAULTS).get(k)) for k, v in config.F.items()]), "",
          "Maps merge per field; scalars and lists replace; null is rejected (omit to inherit). Code and package "
          "bytes are identical across sites: only external layer documents differ (see `tests/test_v43.py::ConfigTest`).", ""]
    s += ["## C052 Health and stall detection (`health.py`)", "",
          _table(["reason code", "meaning"], health.REASON_CODES.items()), "",
          _table(["condition", "automatic action"], health.ACTIONS.items()), "",
          "Dimensions: " + ", ".join(health.HEALTH_DIMENSIONS) + ". Thresholds come from `health.*` in the effective "
          "configuration; per-tool `expected_max_s` distinguishes legitimately long tools from stalls.", ""]
    s += ["## C053 Retry (`retry.py`)", "",
          "Full jitter `uniform(0, min(max_delay, base_delay * 2^attempt))`; max 10 attempts; never sleeps past the "
          "deadline; retry budget = 10 + 20% of first attempts (storm protection); side-effecting operations retry "
          "only with an idempotency key; every attempt is recorded (attempt, code, delay, outcome).", ""]
    s += ["## C079 Telemetry policy (`telemetry.TELEMETRY_POLICY`)", "",
          _table(["type", "sensitivity", "retention days", "sampling", "access"],
                 [(t, v["sensitivity"], v["retention_days"], v["sampling"], v["access"])
                  for t, v in telemetry.TELEMETRY_POLICY["types"].items()]), "",
          f"Residency: {telemetry.TELEMETRY_POLICY['residency']}. Encryption: {telemetry.TELEMETRY_POLICY['encryption']}. "
          f"Deletion: {telemetry.TELEMETRY_POLICY['deletion']}.", ""]
    return "\n".join(s) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    text = generate()
    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != text:
            print("SPEC.md drift: regenerate with tools/gen_spec.py")
            return 1
        print("SPEC.md up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
