"""The C001-C100 control map: implementation artifacts, verification tests, disposition.

Single source for ``tools/gen_requirements.py`` (SHALL spec), ``tools/rtm.py`` (RTM) and
``tools/mc_status.py`` (MC checklist execution).  Status is *engineering* status; nothing
here is ever ``PASS`` for production, because every control still needs an independent
review recorded in ``release/reviews.jsonl`` (the MC D05 item).

status vocabulary:
  ENGINEERED       implemented + automated evidence exists and must pass in CI
  PARTIAL          implemented in part; ``gap`` names what is missing
  OPEN_HUMAN       needs an owner decision/approval/assignment that code cannot make
  OPEN_EXTERNAL    needs a system/environment not available to this build
  NA_PROPOSED      proposed not-applicable; needs approval (a waiver until then)
"""
from __future__ import annotations

T = "tests."
U, C, S, F, Z, IT, X, D = (T + "unit.", T + "contract.", T + "security.", T + "fuzz.", T + "concurrency.",
                          T + "integration.", T + "fault.", T + "disaster.")

CONTROLS: dict[str, dict] = {
    "C001": dict(status="ENGINEERED", artifacts=["contract.py", "README.md", "docs/adr/ADR-0001-enterprise-wasm-control-plane.md"], tests=[C + "test_contracts"]),
    "C002": dict(status="ENGINEERED", artifacts=["contract.py", "README.md"], tests=[C + "test_contracts"]),
    "C003": dict(status="ENGINEERED", artifacts=["contract.py", "docs/TOPOLOGY.md", "docs/INTERFACES.md"], tests=[IT + "test_e2e"]),
    "C004": dict(status="ENGINEERED", artifacts=["docs/SOURCE_OF_TRUTH.md", "production/journal.py"], tests=[U + "test_units.JournalTest", D + "test_disaster.DisasterTest.test_backup_restore_reconstructs_identical_state"]),
    "C005": dict(status="ENGINEERED", artifacts=["contract.py", "docs/TOPOLOGY.md", "docs/PARTITION_SEMANTICS.md"], tests=[X + "test_faults"]),
    "C006": dict(status="ENGINEERED", artifacts=["production/rbac.py", "docs/TOPOLOGY.md"], tests=[U + "test_units.RbacTest", S + "test_threats.ThreatTest.test_T07_confused_deputy_workload_other_tenant"]),
    "C007": dict(status="ENGINEERED", artifacts=["contract.py", "docs/adr/ADR-0001-enterprise-wasm-control-plane.md"], tests=[]),
    "C008": dict(status="ENGINEERED", artifacts=["docs/TOPOLOGY.md", "README.md"], tests=[]),
    "C009": dict(status="OPEN_HUMAN", artifacts=["governance/owners.json", "CODEOWNERS"], tests=[], gap="owners/rotations UNASSIGNED"),
    "C010": dict(status="OPEN_HUMAN", artifacts=["docs/adr/ADR-0001-enterprise-wasm-control-plane.md"], tests=[], gap="ADR PROPOSED, not approved"),
    "C011": dict(status="ENGINEERED", artifacts=["requirements/requirements.json", "production/adapters.py"], tests=[IT + "test_e2e.EndToEndTest.test_gitops_ingestion_goes_through_admission"]),
    "C012": dict(status="PARTIAL", artifacts=["requirements/requirements.json", "docs/TOPOLOGY.md"], tests=[], gap="near/far-edge contexts declared unsupported (NA pending approval)"),
    "C013": dict(status="ENGINEERED", artifacts=["requirements/requirements.json", "release/perf_thresholds.json"], tests=["tools.perf_gate"]),
    "C014": dict(status="ENGINEERED", artifacts=["docs/LIFECYCLE.md", "production/errors.py"], tests=[X + "test_faults"]),
    "C015": dict(status="ENGINEERED", artifacts=["production/lifecycle.py", "docs/LIFECYCLE.md"], tests=[U + "test_units.SmallPartsTest.test_lifecycle"]),
    "C016": dict(status="ENGINEERED", artifacts=["release/compatibility.json", "fixtures/compat"], tests=[C + "test_contracts.CompatibilityTest"]),
    "C017": dict(status="ENGINEERED", artifacts=["production/quota.py", "production/resilience.py", "docs/CAPACITY.md"], tests=[U + "test_units.SmallPartsTest.test_quota", U + "test_units.SmallPartsTest.test_shedder_fairness", X + "test_faults.FaultTest.test_quota_exhaustion_is_retryable_and_journaled"]),
    "C018": dict(status="ENGINEERED", artifacts=["docs/PARTITION_SEMANTICS.md"], tests=[D + "test_disaster.DisasterTest.test_partition_from_deployment_manager_then_reconnect"]),
    "C019": dict(status="ENGINEERED", artifacts=["docs/PRECEDENCE.md", "production/policy_engine.py"], tests=[U + "test_units.PolicyEngineTest"]),
    "C020": dict(status="ENGINEERED", artifacts=["release/rtm.json", "tools/rtm.py"], tests=["tools.rtm"]),
    "C021": dict(status="ENGINEERED", artifacts=["docs/INTERFACES.md", "schemas"], tests=[C + "test_contracts"]),
    "C022": dict(status="ENGINEERED", artifacts=["schemas", "tools/gen_schemas.py"], tests=[C + "test_contracts.SchemaContractTest"]),
    "C023": dict(status="PARTIAL", artifacts=["production/identity.py", "production/http_api.py"], tests=[U + "test_units.IdentityTest", IT + "test_e2e.MutualTlsTest"], gap="live IdP/JWKS discovery and revocation not integrated"),
    "C024": dict(status="ENGINEERED", artifacts=["production/rbac.py"], tests=[U + "test_units.RbacTest", C + "test_contracts.SchemaContractTest.test_rbac_api_contract"]),
    "C025": dict(status="ENGINEERED", artifacts=["production/resilience.py", "docs/INTERFACES.md"], tests=[U + "test_units.SmallPartsTest", Z + "test_races.RaceTest.test_idempotent_duplicates_under_race_yield_one_decision"]),
    "C026": dict(status="ENGINEERED", artifacts=["production/errors.py", "schemas/PK_ECP_ERROR_1.schema.json", "schemas/ERROR_REGISTRY.pin"], tests=[U + "test_units.ErrorRegistryTest"]),
    "C027": dict(status="ENGINEERED", artifacts=["release/compatibility.json"], tests=[C + "test_contracts.CompatibilityTest", IT + "test_e2e.EndToEndTest.test_http_errors_are_typed_envelopes"]),
    "C028": dict(status="ENGINEERED", artifacts=["docs/INTERFACES.md", "production/config.py"], tests=[S + "test_threats.ThreatTest.test_T10_parser_bombs_and_resource_exhaustion"]),
    "C029": dict(status="ENGINEERED", artifacts=["fixtures/compat", "config/examples"], tests=[C + "test_contracts.CompatibilityTest.test_frozen_v1_fixtures_still_validate"]),
    "C030": dict(status="PARTIAL", artifacts=["production/adapters.py", "production/policy_engine.py"], tests=[IT + "test_e2e"], gap="exercised against protocol-faithful stubs, not real INV-63/GAP-13/IdP/registry/wasmCloud"),
    "C031": dict(status="PARTIAL", artifacts=["constraints.txt", "pyproject.toml", "release/compatibility.json"], tests=[], gap="Cosmonic Control/wasmCloud versions not pinned (no integration); hash lock pending"),
    "C032": dict(status="ENGINEERED", artifacts=["docs/SOURCE_OF_TRUTH.md", "pyproject.toml"], tests=["tools.release.package"]),
    "C033": dict(status="ENGINEERED", artifacts=["schemas/PK_ECP_CONFIG_1.schema.json", "config/examples"], tests=[U + "test_units.ConfigTest"]),
    "C034": dict(status="ENGINEERED", artifacts=["production/config.py"], tests=[U + "test_units.ConfigTest.test_invalid_config_never_staged"]),
    "C035": dict(status="ENGINEERED", artifacts=["production/config.py", "config/examples"], tests=[U + "test_units.ConfigTest.test_layered_overrides"]),
    "C036": dict(status="ENGINEERED", artifacts=["production/config.py"], tests=[U + "test_units.ConfigTest.test_dual_authorization_and_author_exclusion"]),
    "C037": dict(status="ENGINEERED", artifacts=["production/config.py"], tests=[Z + "test_races.RaceTest.test_config_activation_race_one_winner"]),
    "C038": dict(status="ENGINEERED", artifacts=["production/config.py", "deploy/rollout.json"], tests=[U + "test_units.ConfigTest.test_cas_conflict_and_rollback"]),
    "C039": dict(status="ENGINEERED", artifacts=["production/keys.py", "production/telemetry.py"], tests=[U + "test_units.KeysTest.test_secret_provider", S + "test_threats.ThreatTest.test_T12_secrets_and_tokens_never_logged_or_journaled"]),
    "C040": dict(status="PARTIAL", artifacts=["docs/runbooks/RB-DAY0.md", "deploy/Dockerfile", "deploy/inv66.service"], tests=["tools.release.package"], gap="container base image not pinned/built here"),
    "C041": dict(status="ENGINEERED", artifacts=["docs/THREAT_MODEL.md"], tests=[S + "test_threats"]),
    "C042": dict(status="ENGINEERED", artifacts=["production/rbac.py", "deploy/inv66.service"], tests=[U + "test_units.RbacTest"]),
    "C043": dict(status="PARTIAL", artifacts=["deploy/inv66.service", "deploy/Dockerfile", "production/adapters.py"], tests=[S + "test_threats.ThreatTest.test_T17_adapter_endpoints_only_http"], gap="sandboxing declared in unit/image, not verified on a host"),
    "C044": dict(status="PARTIAL", artifacts=["production/identity.py", "production/provenance.py"], tests=[IT + "test_e2e.MutualTlsTest", U + "test_units.ProvenanceTest"], gap="node/provider attestation absent"),
    "C045": dict(status="PARTIAL", artifacts=["production/provenance.py"], tests=[U + "test_units.ProvenanceTest", S + "test_threats.ThreatTest.test_T05_signature_replay_onto_other_component_or_digest"], gap="no transparency log; live registry resolution absent"),
    "C046": dict(status="ENGINEERED", artifacts=["production/rbac.py", "production/quota.py"], tests=[S + "test_threats.ThreatTest.test_T07_confused_deputy_workload_other_tenant", U + "test_additions.AdditionsTest.test_audit_cursor_pagination_and_filters"]),
    "C047": dict(status="PARTIAL", artifacts=["production/keys.py", "production/http_api.py"], tests=[U + "test_units.KeysTest", U + "test_units.JournalTest.test_encrypted_bodies", IT + "test_e2e.MutualTlsTest"], gap="managed KMS keys absent; local keyring only"),
    "C048": dict(status="ENGINEERED", artifacts=["docs/PARTITION_SEMANTICS.md"], tests=[X + "test_faults.FaultTest.test_policy_engine_down_fails_closed_or_uses_fresh_cache"]),
    "C049": dict(status="ENGINEERED", artifacts=["production/journal.py"], tests=[U + "test_units.JournalTest", U + "test_additions.AdditionsTest.test_background_verification_alerts"]),
    "C050": dict(status="ENGINEERED", artifacts=["tests/security/test_threats.py", "tests/fuzz/test_fuzz.py"], tests=[S + "test_threats", F + "test_fuzz"]),
    "C051": dict(status="ENGINEERED", artifacts=["docs/PARTITION_SEMANTICS.md", "docs/TOPOLOGY.md"], tests=[]),
    "C052": dict(status="ENGINEERED", artifacts=["production/resilience.py", "production/service.py"], tests=[X + "test_faults.FaultTest.test_journal_failure_admits_nothing_and_degrades"]),
    "C053": dict(status="ENGINEERED", artifacts=["production/resilience.py"], tests=[U + "test_units.SmallPartsTest.test_retry_classification", U + "test_units.SmallPartsTest.test_retry_respects_deadline"]),
    "C054": dict(status="ENGINEERED", artifacts=["production/resilience.py"], tests=[U + "test_units.SmallPartsTest.test_breaker", X + "test_faults.FaultTest.test_overload_sheds_before_work"]),
    "C055": dict(status="PARTIAL", artifacts=["production/replication.py"], tests=[D + "test_disaster.DisasterTest.test_site_loss_failover_with_fencing"], gap="single-site lease over shared storage; multi-site replication absent"),
    "C056": dict(status="ENGINEERED", artifacts=["docs/PARTITION_SEMANTICS.md"], tests=[D + "test_disaster.DisasterTest.test_partition_from_deployment_manager_then_reconnect"]),
    "C057": dict(status="ENGINEERED", artifacts=["production/journal.py"], tests=[U + "test_units.JournalTest.test_torn_tail_recovered_interior_corruption_fails", X + "test_faults.FaultTest.test_crash_between_decision_and_delivery_resumes_after_restart"]),
    "C058": dict(status="ENGINEERED", artifacts=["production/replication.py", "production/journal.py"], tests=[Z + "test_races.RaceTest.test_stale_leader_is_fenced", Z + "test_races.RaceTest.test_multiprocess_fenced_writers_keep_one_chain"]),
    "C059": dict(status="ENGINEERED", artifacts=["production/quarantine.py"], tests=[S + "test_threats.ThreatTest.test_T13_quarantine_needs_two_to_release", S + "test_threats.ThreatTest.test_T14_freeze_survives_restart"]),
    "C060": dict(status="ENGINEERED", artifacts=["tests/fault/test_faults.py"], tests=[X + "test_faults"]),
    "C061": dict(status="PARTIAL", artifacts=["tools/bench.py", "release/bench.json"], tests=["tools.bench"], gap="network/power overhead not measured; single environment"),
    "C062": dict(status="PARTIAL", artifacts=["release/perf_thresholds.json"], tests=["tools.perf_gate"], gap="thresholds PROPOSED, not approved"),
    "C063": dict(status="PARTIAL", artifacts=["tools/bench.py"], tests=["tools.bench"], gap="scale-out/in not measured (single host)"),
    "C064": dict(status="ENGINEERED", artifacts=["tools/bench.py", "docs/CAPACITY.md"], tests=["tools.bench"]),
    "C065": dict(status="ENGINEERED", artifacts=["docs/CAPACITY.md"], tests=["tools.bench"]),
    "C066": dict(status="PARTIAL", artifacts=["docs/CAPACITY.md"], tests=[], gap="batching of journal fsyncs not implemented (debt D-01)"),
    "C067": dict(status="ENGINEERED", artifacts=["production/resilience.py", "production/telemetry.py", "production/journal.py"], tests=[U + "test_units.TelemetryTest.test_prometheus_and_bounded_series", D + "test_disaster.DisasterTest.test_retention_compaction_then_restart_preserves_state", "tools.bench.soak"]),
    "C068": dict(status="NA_PROPOSED", artifacts=["docs/EDGE_POWER_THERMAL.md"], tests=[], gap="N/A needs architecture approval"),
    "C069": dict(status="ENGINEERED", artifacts=["docs/CAPACITY.md"], tests=["tools.bench"]),
    "C070": dict(status="PARTIAL", artifacts=["tools/perf_gate.py", "release/perf_thresholds.json"], tests=["tools.perf_gate"], gap="thresholds unapproved; no approved baseline environment"),
    "C071": dict(status="ENGINEERED", artifacts=["production/service.py", "production/http_api.py"], tests=[IT + "test_e2e.EndToEndTest.test_full_admission_path_over_http", U + "test_additions.AdditionsTest.test_health_runtime_gauges"]),
    "C072": dict(status="ENGINEERED", artifacts=["production/telemetry.py"], tests=[U + "test_units.TelemetryTest"]),
    "C073": dict(status="ENGINEERED", artifacts=["production/telemetry.py"], tests=[U + "test_units.TelemetryTest.test_log_allowlist_and_redaction"]),
    "C074": dict(status="ENGINEERED", artifacts=["production/telemetry.py"], tests=[U + "test_units.TelemetryTest.test_trace_propagation", IT + "test_e2e.EndToEndTest.test_full_admission_path_over_http"]),
    "C075": dict(status="ENGINEERED", artifacts=["docs/TELEMETRY_POLICY.md"], tests=[S + "test_threats.ThreatTest.test_T12_secrets_and_tokens_never_logged_or_journaled"]),
    "C076": dict(status="ENGINEERED", artifacts=["production/service.py"], tests=[C + "test_contracts.SchemaContractTest.test_every_denial_reason_uses_registered_code"]),
    "C077": dict(status="ENGINEERED", artifacts=["production/service.py"], tests=[IT + "test_e2e.EndToEndTest.test_full_admission_path_over_http"]),
    "C078": dict(status="PARTIAL", artifacts=["production/adapters.py", "production/service.py"], tests=[IT + "test_e2e.EndToEndTest.test_gitops_ingestion_goes_through_admission"], gap="live infrastructure graph (observed runtime state) not ingested"),
    "C079": dict(status="ENGINEERED", artifacts=["docs/TELEMETRY_POLICY.md"], tests=[]),
    "C080": dict(status="ENGINEERED", artifacts=["ops/dashboards/inv66-overview.json", "ops/alerts/inv66-rules.yml"], tests=["tools.ci.observability"]),
    "C081": dict(status="ENGINEERED", artifacts=["tests/unit"], tests=[U + "test_units"]),
    "C082": dict(status="ENGINEERED", artifacts=["tests/contract"], tests=[C + "test_contracts"]),
    "C083": dict(status="PARTIAL", artifacts=["tests/integration"], tests=[IT + "test_e2e"], gap="stubs, not real adjacent layers"),
    "C084": dict(status="PARTIAL", artifacts=["release/compatibility.json", ".github/workflows/ci.yml"], tests=[], gap="only CPython 3.11/x86_64/Linux actually run"),
    "C085": dict(status="ENGINEERED", artifacts=["tests/fuzz/test_fuzz.py"], tests=[F + "test_fuzz"]),
    "C086": dict(status="ENGINEERED", artifacts=["tests/concurrency/test_races.py"], tests=[Z + "test_races"]),
    "C087": dict(status="ENGINEERED", artifacts=["tests/security/test_threats.py", "docs/THREAT_MODEL.md"], tests=[S + "test_threats"]),
    "C088": dict(status="PARTIAL", artifacts=["tools/bench.py"], tests=["tools.bench"], gap="fleet-scale not run"),
    "C089": dict(status="ENGINEERED", artifacts=["tests/disaster/test_disaster.py"], tests=[D + "test_disaster"]),
    "C090": dict(status="PARTIAL", artifacts=["release/evidence.json"], tests=["tools.release"], gap="pk_core 100-item gate NOT RUN (pk_core not bundled)"),
    "C091": dict(status="OPEN_HUMAN", artifacts=["contract.py", "governance/owners.json"], tests=[], gap="SLOs declared; error-budget policy and support commitment undecided"),
    "C092": dict(status="PARTIAL", artifacts=["deploy/rollout.json", "production/quarantine.py"], tests=[S + "test_threats.ThreatTest.test_T14_freeze_survives_restart"], gap="no orchestrator integration for canary"),
    "C093": dict(status="ENGINEERED", artifacts=["release/compatibility.json"], tests=[C + "test_contracts.CompatibilityTest.test_matrix_is_consistent_with_code"]),
    "C094": dict(status="OPEN_HUMAN", artifacts=["SECURITY.md", "docs/SUPPORT_POLICY.md"], tests=[], gap="SLAs/EOL PROPOSED, unapproved; SCA scanner not run"),
    "C095": dict(status="ENGINEERED", artifacts=["docs/runbooks/RB-BACKUP.md", "production/cli.py"], tests=[D + "test_disaster.DisasterTest.test_backup_restore_reconstructs_identical_state"]),
    "C096": dict(status="ENGINEERED", artifacts=["docs/runbooks/RB-DAY0.md", "docs/runbooks/RB-DAY1.md", "docs/runbooks/RB-DAY2.md"], tests=["tools.ci.docs"]),
    "C097": dict(status="PARTIAL", artifacts=["docs/runbooks/RB-INCIDENT.md"], tests=[], gap="paging rotations unassigned"),
    "C098": dict(status="PARTIAL", artifacts=["tools/review.py", ".github/workflows/review.yml"], tests=["tools.review"], gap="reviewer dispositions require humans"),
    "C099": dict(status="ENGINEERED", artifacts=["release/waivers.json"], tests=["tools.release.waivers"]),
    "C100": dict(status="ENGINEERED", artifacts=["tools/release.py", "release/exit_gate.json"], tests=["tools.release.gate"]),
}
