"""Regenerate derived docs: docs/LIFECYCLE.md diagram header and docs/CAPACITY.md (from release/bench.json)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT.parent))


def capacity() -> str:
    b = json.loads((ROOT / "release" / "bench.json").read_text())
    sc, env = b["scenarios"], b["environment"]
    l1, l3, l20, nf = sc["latency_fsync_1c"], sc["latency_fsync_3c"], sc["latency_fsync_20c"], sc["latency_nofsync_3c"]
    tp, rp, mem = sc["throughput_threads_8"], sc["replay_startup"], sc["memory"]
    fsync_ms = max(0.0, l3["p50_ms"] - nf["p50_ms"])
    per_comp = max(0.0, (l20["p50_ms"] - l3["p50_ms"]) / 17)
    bpa = l3["journal_bytes_per_admission"]
    safe_qps = round(0.7 * tp["admissions_per_s"], 1)
    soak = sc.get("soak", {})
    return f"""# Capacity and saturation model (MC-009, MC-047)

Generated by `tools/gen_docs.py` from `release/bench.json`. These are measurements on **one**
environment ({env['machine']}, {env['cpus']} vCPU, CPython {env['python']}, kernel {env['kernel']}).
They are not certified sizing. Re-run `tools/bench.py` on production-class hardware before relying on them.

## Measured

| Quantity | Value |
|---|---|
| p50 / p99 admission, 1 component, fsync | {l1['p50_ms']} / {l1['p99_ms']} ms |
| p50 / p99 admission, 3 components, fsync | {l3['p50_ms']} / {l3['p99_ms']} ms |
| p50 / p99 admission, 20 components, fsync | {l20['p50_ms']} / {l20['p99_ms']} ms |
| p50 admission, 3 components, no fsync | {nf['p50_ms']} ms (so fsync costs ≈ {fsync_ms:.2f} ms) |
| Marginal cost per component (Ed25519 verify + checks) | ≈ {per_comp:.2f} ms |
| Throughput, 8 client threads, fsync | {tp['admissions_per_s']} admissions/s |
| Journal growth | ≈ {bpa} bytes per admission (decision + 2 lifecycle records) |
| Replay (startup) | {rp['records_per_s']} records/s ({rp['journal_records']} records in {rp['replay_seconds']} s) |
| Peak traced heap (whole benchmark) | {mem['tracemalloc_peak_kb']} KiB |
| Soak | {soak.get('admissions', 'not run')} admissions in {soak.get('seconds', '-')} s; FD drift {soak.get('fd_drift', '-')}; metric series final {soak.get('series_final', '-')} |

## Model

- **Leader admission capacity** ≈ `1 / (t_eval(components) + t_fsync)` per serialised journal
  section. With the numbers above, **safe sustained QPS ≈ {safe_qps}/s** (70 % of measured throughput,
  leaving 30 % headroom for bursts and GC).
- **Latency budget** for the p99 < 50 ms SLO: `t_schema+authn + t_rbac + n·t_component + t_policy + t_fsync`.
  The budget table is in `release/perf_thresholds.json`. An external GAP-13 call is the largest variable term.
- **Journal growth** = QPS × {bpa} B. At the safe QPS, that is ≈ {round(safe_qps * bpa * 86400 / 1e9, 2)} GB/day before compaction.
  Retention (`retention_days`) plus compaction bounds it.
- **Startup (RTO component)** = records ÷ replay rate. Checkpoints plus compaction keep it bounded.
- **Memory**: projections are O(live inventory + idempotency window (100k cap) + replay cache (100k cap)).
  The metrics registry is capped at 1000 series per metric.
- **Followers** scale read traffic linearly. They add no write capacity (single writer).

## Saturation signals → action

| Signal | Threshold (PROPOSED) | Action |
|---|---|---|
| p99 `ecp_admission_latency_ms` | > 40 ms for 10 min | check component counts and GAP-13 latency; scale the leader vertically (faster disk for fsync) |
| `ecp_inflight` / `max_inflight` | > 0.8 for 5 min | raise `max_inflight` within the CPU budget, or shed via per-tenant quotas |
| `rate(ecp_shed_total)` | > 0 | capacity event (alert Inv66Overloaded) |
| `ecp_delivery_pending` | growing for 30 min | INV-63 dependency problem, not capacity |
| journal disk used | > 70 % | run `enforce_retention`; grow the volume |
| startup replay time | > 60 s | lower `audit_segment_records` / checkpoint more often |

Scale-out rules: add followers when read QPS exceeds 70 % of one replica. Hysteresis: 15 min above
the threshold to scale up, 60 min below to scale down. Minimum 2 replicas (N+1), maximum bounded by
lease contention (a single writer).

## Known nonlinearities
- Group commit isn't implemented (debt D-01), so throughput is fsync-bound under concurrency.
- The Python GIL serialises signature verification, so more threads don't add CPU throughput.
- Replay was O(n²) before fix D6 (the 4.3.0 build found and fixed this).
"""


if __name__ == "__main__":
    (ROOT / "docs" / "CAPACITY.md").write_text(capacity())
    print("wrote docs/CAPACITY.md")
