"""Per-MC execution map for the INV-66 v4.2.0 missing-components checklist (1,420 items).

``EV[mc]``     evidence for the MC: artifact paths and test ids (checked mechanically by mc_status.py)
``OPEN[mc]``   the MC-specific items (Txx) that are NOT DONE, with a status and a reason.  Every other
               specific item of that MC is DONE: implemented in this tree and covered by EV[mc].
Generic items (the shared Txx family blocks and D01-D07) are decided by rules in mc_status.py.

Status vocabulary (item level):
  DONE           implemented here; evidence exists and is verified by CI; NOT independently reviewed
  PARTIAL        implemented in part; the reason says what is missing
  OPEN_HUMAN     needs an owner decision / approval / assignment / human exercise
  OPEN_EXTERNAL  needs a system or environment not available to this build
  NA_PROPOSED    proposed not-applicable, pending approval
"""
from __future__ import annotations

P = "production/"
EV: dict[str, list[str]] = {
    "MC-001": ["MASTER.md", "tools/gen_master.py", "RELEASE_MANIFEST.sha256", "lane:master"],
    "MC-002": ["docs/adr/ADR-0001-enterprise-wasm-control-plane.md"],
    "MC-003": ["governance/owners.json", "CODEOWNERS", "tools/review.py"],
    "MC-004": ["docs/TOPOLOGY.md"],
    "MC-005": ["docs/SOURCE_OF_TRUTH.md", P + "journal.py", "tests.disaster.test_disaster.DisasterTest.test_backup_restore_reconstructs_identical_state", "tests.fault.test_faults.FaultTest.test_crash_between_decision_and_delivery_resumes_after_restart"],
    "MC-006": ["requirements/requirements.json", "tools/gen_requirements.py", "lane:requirements-drift"],
    "MC-007": ["release/rtm.json", "tools/rtm.py", "docs/COVERAGE.md", "release/rtm-history", "lane:rtm"],
    "MC-008": [P + "lifecycle.py", "docs/LIFECYCLE.md", "tests.unit.test_units.SmallPartsTest.test_lifecycle", "tests.concurrency.test_races.RaceTest.test_idempotent_duplicates_under_race_yield_one_decision"],
    "MC-009": [P + "quota.py", P + "resilience.py", "docs/CAPACITY.md", "tests.unit.test_units.SmallPartsTest.test_quota", "tests.unit.test_units.SmallPartsTest.test_shedder_fairness", "tests.fault.test_faults.FaultTest.test_quota_exhaustion_is_retryable_and_journaled"],
    "MC-010": ["docs/PARTITION_SEMANTICS.md", "tests.fault.test_faults", "tests.disaster.test_disaster.DisasterTest.test_partition_from_deployment_manager_then_reconnect"],
    "MC-011": ["docs/PRECEDENCE.md", P + "policy_engine.py", "tests.unit.test_units.PolicyEngineTest"],
    "MC-012": ["schemas/PK_ECP_ADMIT_REQUEST_1.schema.json", "schemas/PK_ECP_ADMIT_DECISION_1.schema.json", "fixtures/compat", "tests.contract.test_contracts", "tests.fuzz.test_fuzz"],
    "MC-013": ["schemas/PK_ECP_RBAC_REQUEST_1.schema.json", P + "service.py", "tests.contract.test_contracts.SchemaContractTest.test_rbac_api_contract", "tests.unit.test_additions.AdditionsTest.test_rbac_optimistic_concurrency", "tests.security.test_threats.ThreatTest.test_T08_privilege_escalation_by_delegation"],
    "MC-014": ["schemas/PK_ECP_AUDIT_RECORD_2.schema.json", "schemas/PK_ECP_AUDIT_QUERY_1.schema.json", P + "journal.py", P + "siem.py", "tests.unit.test_additions", "tests.unit.test_units.JournalTest.test_query_export"],
    "MC-015": [P + "identity.py", P + "http_api.py", "tests.unit.test_units.IdentityTest", "tests.integration.test_e2e.MutualTlsTest", "tests.security.test_threats.ThreatTest.test_T04_spoofed_identity_and_forged_token"],
    "MC-016": [P + "errors.py", "schemas/PK_ECP_ERROR_1.schema.json", "schemas/ERROR_REGISTRY.pin", "tests.unit.test_units.ErrorRegistryTest", "tests.contract.test_contracts.SchemaContractTest.test_every_denial_reason_uses_registered_code"],
    "MC-017": [P + "resilience.py", "docs/INTERFACES.md", "tests.unit.test_units.SmallPartsTest", "tests.fault.test_faults.FaultTest.test_deadline_exceeded_records_nothing", "tests.concurrency.test_races.RaceTest.test_idempotent_duplicates_under_race_yield_one_decision"],
    "MC-018": ["release/compatibility.json", "fixtures/compat", "tests.contract.test_contracts.CompatibilityTest"],
    "MC-019": [P + "adapters.py", "tests.integration.test_e2e.EndToEndTest.test_deployment_manager_outage_and_refusal", "tests.fault.test_faults.FaultTest.test_deployment_outage_then_reconnect_delivers_once"],
    "MC-020": [P + "adapters.py", P + "policy_engine.py", "docs/INTERFACES.md", "tests.integration.test_e2e"],
    "MC-021": [P + "adapters.py", "tests.integration.test_e2e.EndToEndTest.test_gitops_ingestion_goes_through_admission"],
    "MC-022": ["schemas/PK_ECP_CONFIG_1.schema.json", P + "config.py", "config/examples", "tests.unit.test_units.ConfigTest"],
    "MC-023": [P + "config.py", "tests.unit.test_units.ConfigTest.test_dual_authorization_and_author_exclusion"],
    "MC-024": [P + "config.py", "tests.unit.test_units.ConfigTest", "tests.concurrency.test_races.RaceTest.test_config_activation_race_one_winner"],
    "MC-025": [P + "config.py", P + "rbac.py", P + "journal.py", "tests.unit.test_units.RbacTest", "tests.unit.test_additions.AdditionsTest.test_rbac_optimistic_concurrency"],
    "MC-026": [P + "config.py", P + "provenance.py", "tests.unit.test_units.ProvenanceTest", "tests.unit.test_additions.AdditionsTest.test_policy_impact_dry_run"],
    "MC-027": [P + "keys.py", "tests.unit.test_units.KeysTest.test_secret_provider"],
    "MC-028": ["pyproject.toml", "constraints.txt", "deploy/Dockerfile", "deploy/inv66.service", "tools/check_package.py", "lane:package", "release/sbom.cdx.json"],
    "MC-029": [P + "provenance.py", "tests.unit.test_units.ProvenanceTest", "tests.security.test_threats.ThreatTest.test_T05_signature_replay_onto_other_component_or_digest"],
    "MC-030": [P + "provenance.py", "tests.unit.test_units.ProvenanceTest.test_attestation", "tests.unit.test_units.ProvenanceTest.test_registry_resolver"],
    "MC-031": [P + "identity.py", "tests.unit.test_units.IdentityTest"],
    "MC-032": [P + "rbac.py", "tests.unit.test_units.RbacTest", "tests.security.test_threats.ThreatTest.test_T08_privilege_escalation_by_delegation"],
    "MC-033": [P + "policy_engine.py", "tests.fault.test_faults.FaultTest.test_policy_engine_down_fails_closed_or_uses_fresh_cache", "tests.fault.test_faults.FaultTest.test_policy_version_pin", "tests.integration.test_e2e.EndToEndTest.test_policy_engine_outage_fails_closed"],
    "MC-034": [P + "keys.py", P + "http_api.py", "tests.unit.test_units.KeysTest", "tests.unit.test_units.JournalTest.test_encrypted_bodies", "tests.integration.test_e2e.MutualTlsTest"],
    "MC-035": [P + "journal.py", "tests.unit.test_units.JournalTest", "tests.unit.test_additions.AdditionsTest.test_background_verification_alerts"],
    "MC-036": ["docs/THREAT_MODEL.md", "tests.security.test_threats"],
    "MC-037": ["tests/fuzz/test_fuzz.py", "tests/security/test_threats.py", "tests.fuzz.test_fuzz", "tests.security.test_threats", "lane:lint"],
    "MC-038": [P + "journal.py", P + "service.py", "tests.unit.test_units.JournalTest.test_torn_tail_recovered_interior_corruption_fails", "tests.fault.test_faults.FaultTest.test_crash_between_decision_and_delivery_resumes_after_restart"],
    "MC-039": [P + "replication.py", "tests.concurrency.test_races.RaceTest.test_stale_leader_is_fenced", "tests.concurrency.test_races.RaceTest.test_multiprocess_fenced_writers_keep_one_chain", "tests.disaster.test_disaster.DisasterTest.test_site_loss_failover_with_fencing"],
    "MC-040": [P + "resilience.py", P + "service.py", "tests.fault.test_faults.FaultTest.test_journal_failure_admits_nothing_and_degrades"],
    "MC-041": [P + "resilience.py", "tests.unit.test_units.SmallPartsTest.test_breaker", "tests.unit.test_units.SmallPartsTest.test_retry_classification", "tests.fault.test_faults.FaultTest.test_breaker_opens_on_repeated_delivery_failure"],
    "MC-042": [P + "quarantine.py", "tests.security.test_threats.ThreatTest.test_T13_quarantine_needs_two_to_release", "tests.security.test_threats.ThreatTest.test_T14_freeze_survives_restart"],
    "MC-043": ["tests/fault/test_faults.py", "tests.fault.test_faults"],
    "MC-044": ["tools/bench.py", "release/bench.json"],
    "MC-045": ["tools/perf_gate.py", "release/perf_thresholds.json", "release/perf_gate.json", "lane:perf-gate"],
    "MC-046": [P + "journal.py", "tests.unit.test_units.JournalTest.test_compaction_holds_and_summary_chain", "tests.disaster.test_disaster.DisasterTest.test_retention_compaction_then_restart_preserves_state"],
    "MC-047": ["docs/CAPACITY.md", "release/bench.json"],
    "MC-048": ["docs/EDGE_POWER_THERMAL.md"],
    "MC-049": [P + "service.py", P + "http_api.py", "schemas/PK_ECP_HEALTH_1.schema.json", "tests.unit.test_additions.AdditionsTest.test_health_runtime_gauges", "tests.integration.test_e2e.EndToEndTest.test_full_admission_path_over_http"],
    "MC-050": [P + "telemetry.py", "tests.unit.test_units.TelemetryTest", "lane:observability"],
    "MC-051": [P + "telemetry.py", "tests.unit.test_units.TelemetryTest.test_log_allowlist_and_redaction", "tests.security.test_threats.ThreatTest.test_T12_secrets_and_tokens_never_logged_or_journaled"],
    "MC-052": [P + "telemetry.py", "tests.unit.test_units.TelemetryTest.test_trace_propagation", "tests.integration.test_e2e.EndToEndTest.test_full_admission_path_over_http"],
    "MC-053": [P + "service.py", "tests.integration.test_e2e.EndToEndTest.test_full_admission_path_over_http"],
    "MC-054": ["docs/TELEMETRY_POLICY.md", "ops/dashboards/inv66-overview.json", "ops/alerts/inv66-rules.yml", "lane:observability"],
    "MC-055": ["tests/contract/test_contracts.py", "tests.contract.test_contracts", "tests.integration.test_e2e.EndToEndTest.test_http_errors_are_typed_envelopes"],
    "MC-056": ["tests/integration/test_e2e.py", "tests.integration.test_e2e"],
    "MC-057": [".github/workflows/ci.yml", "release/compatibility.json"],
    "MC-058": ["tests/concurrency/test_races.py", "tests.concurrency.test_races"],
    "MC-059": ["tests/disaster/test_disaster.py", "tests.disaster.test_disaster"],
    "MC-060": ["release/evidence.json", "tools/release.py"],
    "MC-061": [".github/workflows/ci.yml", ".github/workflows/release.yml", "deploy/rollout.json", "tools/ci.py", "tools/release.py"],
    "MC-062": ["release/sbom.cdx.json", "SECURITY.md", "docs/SUPPORT_POLICY.md"],
    "MC-063": ["docs/runbooks/RB-BACKUP.md", P + "cli.py", "tests.disaster.test_disaster.DisasterTest.test_backup_restore_reconstructs_identical_state", "tests.disaster.test_disaster.DisasterTest.test_restore_detects_tampered_backup"],
    "MC-064": ["docs/runbooks/RB-DAY0.md", "docs/runbooks/RB-DAY1.md", "docs/runbooks/RB-DAY2.md", "lane:docs"],
    "MC-065": ["docs/runbooks/RB-INCIDENT.md"],
    "MC-066": ["tools/review.py", ".github/workflows/review.yml", "release/review.json", "lane:review"],
    "MC-067": ["release/waivers.json", "docs/TECH_DEBT.md", "tools/check_waivers.py", "lane:waivers"],
    "MC-068": ["tools/release.py", "release/exit_gate.json"],
    "MC-069": [P + "service.py", "schemas/PK_ECP_INVENTORY_1.schema.json", "tests.unit.test_additions.AdditionsTest.test_inventory_pagination"],
    "MC-070": [P + "journal.py", P + "siem.py", "tests.unit.test_additions.AdditionsTest.test_siem_export_checkpoint_retry_dedupe", "tests.unit.test_additions.AdditionsTest.test_audit_cursor_pagination_and_filters"],
    "MC-071": ["LICENSE-STATUS.md", "THIRD-PARTY-NOTICES.md"],
}

H, X, PA, NA = "OPEN_HUMAN", "OPEN_EXTERNAL", "PARTIAL", "NA_PROPOSED"
OPEN: dict[str, dict[str, tuple[str, str]]] = {
    "MC-001": {"T01": (PA, "upstream series archive not supplied; MASTER.md is derived from CHECKLIST.json and marked informative")},
    "MC-002": {"T08": (H, "architecture/security/SRE approval not recorded; ADR is PROPOSED")},
    "MC-003": {"T02": (H, "no teams/rotations bound"), "T03": (H, "24x7 vs business hours undecided"),
               "T06": (H, "escalation contacts for peer teams UNASSIGNED"), "T07": (PA, "CODEOWNERS/alert routing use UNASSIGNED placeholders")},
    "MC-004": {"T04": (PA, "placement rules stated; not validated against real infrastructure")},
    "MC-005": {},
    "MC-006": {},
    "MC-007": {},
    "MC-008": {"T05": (PA, "supersession defined by per-commit idempotency; in-flight cancellation of superseded GitOps change not implemented")},
    "MC-009": {"T01": (PA, "quota by tenant + global in-flight; per-principal/per-site/per-operation dimensions not implemented"),
               "T04": (PA, "no borrowing or time-bounded overrides; overrides only via new config generation")},
    "MC-010": {"T03": (PA, "no signed offline cache artifacts; offline admission unsupported by design"),
               "T05": (PA, "local-site autonomy unsupported; reconnect = follower refresh + redelivery")},
    "MC-011": {"T06": (PA, "emergency lever is restrictive freeze only; no TTL-bounded emergency exception mechanism")},
    "MC-012": {"T03": (X, "authoritative INV-64 manifest schema not available; local component schema used")},
    "MC-013": {"T04": (PA, "reason + if_revision + request_id on mutations; approver/activation time/expiry for grants not implemented"),
               "T05": (PA, "bulk import/export only via whole config generations (transactional), no per-entry RBAC bulk API")},
    "MC-014": {"T07": (PA, "SIEM exporter contract + checkpoint + dead-letter implemented; no real SIEM integrated")},
    "MC-015": {"T05": (PA, "JWKS rotation via config generation; no live JWKS refresh, token revocation list or CRL/OCSP"),
               "T08": (PA, "revoked-credential and unknown-CA covered for mTLS; token revocation absent")},
    "MC-016": {},
    "MC-017": {"T03": (PA, "cancellation checked between stages; in-flight HTTP calls bounded by timeout, not actively cancelled")},
    "MC-018": {"T01": (PA, "INV-64/GAP-07/wasmCloud/Cosmonic versions not pinned (no integration)"),
               "T04": (PA, "N/N-1 replica rule documented (schema additive-minor); no mixed-version replica test"),
               "T08": (PA, "matrix defined in CI workflow; only py3.11/linux/x86_64 executed")},
    "MC-019": {"T02": (PA, "PK_ECP_DELIVER/1 defined by INV-66; not agreed with INV-63 owners; auth identity via adapter config"),
               "T08": (PA, "protocol-faithful stub, not real INV-63")},
    "MC-020": {"T03": (PA, "stubs serialise over real HTTP; IdP/registry/INV-64/GAP-07 adapters are interfaces only"),
               "T06": (X, "no peer versions to pin"), "T08": (PA, "CI runs stub integrations only")},
    "MC-021": {"T02": (X, "webhook ingestion + authenticated source events not built (waiver W-08)"),
               "T03": (X, "INV-64 application model schema not available"),
               "T05": (PA, "force-push/branch deletion/revert handled only as new revisions; no explicit detection"),
               "T06": (PA, "repo credentials would be secret refs; ingestor reads a local checkout"),
               "T07": (PA, "commit SHA linked via decision source + explain; no GitOps status endpoint"),
               "T08": (PA, "local git fixture; no git server/webhook replay tests")},
    "MC-022": {},
    "MC-023": {},
    "MC-024": {"T05": (PA, "operator rollback implemented; no automatic rollback trigger on activation failure (activation is atomic, so failure leaves previous active)"),
               "T06": (PA, "rollback target is re-validated against the current schema; no semantic-compat/break-glass check for revoked trust")},
    "MC-025": {"T01": (PA, "journal-backed store; HA/backup/encryption as per journal; no separate RBAC database"),
               "T07": (PA, "no caches of privilege beyond in-process projection rebuilt per generation; multi-replica propagation relies on follower refresh")},
    "MC-026": {"T02": (PA, "exact host + scope + digest + signer key id; no namespace prefixes, issuer/cert constraints or version ranges"),
               "T06": (PA, "rotation by overlapping signer ids + revoked flag; no automatic overlap-window enforcement")},
    "MC-027": {"T01": (PA, "provider interface + env/file provider; KMS/Vault providers not built (OPEN_EXTERNAL)"),
               "T03": (X, "per-path secret permissions belong to the secret manager"),
               "T04": (PA, "no caching/TTL/zeroisation layer beyond the provider call"),
               "T05": (PA, "TLS cert reload + keyring rotation without restart; secret-manager lease rotation absent"),
               "T08": (PA, "local fixtures only; no ephemeral secret-manager fixture")},
    "MC-028": {"T02": (PA, "exact pins; hashes pending (PyPI unreachable, W-09)"),
               "T03": (PA, "Dockerfile written, base digest unpinned, image not built here"),
               "T06": (PA, "validate-config + /readyz dependency view; no DNS/KMS reachability probe tool"),
               "T07": (PA, "SBOM + unattested provenance generated; artifact signed with ephemeral key only")},
    "MC-029": {"T01": (PA, "Ed25519 over a defined payload; no certificate chains / Sigstore-style attestation"),
               "T05": (PA, "revocation via config generation; no online revocation/trust service")},
    "MC-030": {"T02": (X, "no authenticated OCI registry client"), "T03": (X, "artifact bytes not fetched; digest pinning only"),
               "T05": (PA, "attestation carries sbom_digest; SBOM presence/freshness policy not enforced"),
               "T06": (PA, "no version-channel policy"), "T07": (PA, "no verified-metadata cache (nothing fetched)"),
               "T08": (PA, "mutable-tag refused by digest requirement; registry-compromise simulation limited to resolver index")},
    "MC-031": {"T01": (X, "no enterprise IdP/SAML integration; EdDSA JWT issuer + static JWKS only"),
               "T04": (PA, "iss/aud/sig/lifetime/groups validated; AMR/auth-strength not checked"),
               "T05": (H, "joiner/mover/leaver and revocation targets are an IAM owner decision"),
               "T07": (PA, "max token lifetime enforced; no refresh/step-up/break-glass accounts"),
               "T08": (PA, "local issuer only; no representative IdP tests")},
    "MC-032": {"T03": (PA, "groups, service/workload principals, delegation, deny implemented; temporary elevation absent")},
    "MC-033": {"T05": (PA, "caches answers (not compiled bundles); no bundle signature verification")},
    "MC-034": {"T02": (H, "certificate identities/rotation cadence are security-owner decisions; reload path implemented"),
               "T03": (PA, "AES-256-GCM sealing of journal bodies; keys local, no managed KMS"),
               "T04": (PA, "keyring per journal; no per-tenant/data-class key separation"),
               "T05": (PA, "rotate/retire implemented; no re-encryption tool (debt D-04)"),
               "T07": (PA, "no certificate/key expiry health signal"),
               "T08": (PA, "mTLS wrong-CA/no-cert tested; expired/revoked cert and encrypted-backup restore not tested")},
    "MC-035": {"T01": (PA, "append-only file journal + flock; no WORM storage"),
               "T02": (PA, "signed anchors to a separate directory; no independent timestamp/transparency service"),
               "T03": (X, "KMS/HSM-protected audit signing key not available")},
    "MC-036": {"T06": (H, "residual risk uses a provisional L/M/H scale; organisation methodology and owners needed"),
               "T08": (H, "review cadence defined; reviews must be performed by people")},
    "MC-037": {"T07": (PA, "ruff/mypy static analysis run; no sanitizers, no persistent crash corpus"),
               "T08": (H, "release gating on zero high findings is wired in the exit gate; waiver approvals needed")},
    "MC-038": {},
    "MC-039": {"T03": (PA, "shared storage replication delegated to the storage layer; no quorum settings in INV-66"),
               "T05": (PA, "followers converge on refresh(); no bounded propagation-delay guarantee"),
               "T07": (PA, "role/epoch exposed in /readyz; no replication-lag metric"),
               "T08": (PA, "multi-process on one host; no multi-node, packet-delay or clock-skew tests")},
    "MC-040": {"T02": (PA, "up/down with last error; no distinction of unauthorized/stale/version-incompatible states"),
               "T05": (PA, "no hysteresis/debounce on readiness")},
    "MC-041": {"T04": (PA, "global + per-tenant in-flight limits; no per-dependency concurrency pools")},
    "MC-042": {"T01": (PA, "freeze global/tenant/lattice implemented; per-artifact/signer/registry revocation via config generation"),
               "T05": (PA, "reason + actor + approvers recorded; no expiry/TTL or structured ticket field")},
    "MC-043": {"T01": (PA, "timeouts, errors, overload, malformed, auth for policy/delivery; not every dependency x every mode"),
               "T02": (PA, "crash points: journal append, between decision and delivery; not every boundary"),
               "T04": (PA, "partition + mTLS failures; DNS/KMS/clock-skew not injected"),
               "T07": (X, "no production-like multi-replica environment")},
    "MC-044": {"T03": (PA, "no scale-out/in or dependency-slowdown scenarios"),
               "T05": (PA, "60 s soak recorded; longer soaks needed"),
               "T06": (PA, "p50/p95/p99/max; no p99.9 or confidence intervals"),
               "T08": (X, "no controlled performance environment")},
    "MC-045": {"T01": (PA, "thresholds for successful admission only"), "T04": (PA, "replay rate only; no failover/propagation objectives"),
               "T07": (PA, "waiver workflow documented; approvals human")},
    "MC-046": {},
    "MC-047": {"T04": (H, "scaling thresholds PROPOSED, need SRE approval"), "T06": (H, "N+1 policy needs approval"),
               "T08": (PA, "dashboard panels exist; no dedicated capacity dashboard")},
    "MC-048": {"T01": (NA, "proposed NOT APPLICABLE; architecture approval missing"), "T02": (NA, "n/a if T01 approved"),
               "T03": (NA, "n/a if T01 approved"), "T04": (NA, "n/a if T01 approved"), "T05": (NA, "n/a if T01 approved"),
               "T06": (NA, "n/a if T01 approved"), "T07": (NA, "n/a if T01 approved"), "T08": (H, "decision must be approved")},
    "MC-049": {"T01": (PA, "/healthz unauthenticated-minimal; /readyz unauthenticated and must be network-restricted")},
    "MC-050": {"T03": (PA, "in-flight, pending, breaker, frozen, idempotency gauges; no policy/config age gauge or cache hit ratio"),
               "T04": (PA, "RSS/threads/FDs; no GC/network/storage metrics"),
               "T08": (PA, "metrics are in-process and cannot block; overhead not isolated in benchmark")},
    "MC-051": {"T06": (PA, "synchronous stream writer; sink routing external")},
    "MC-052": {"T02": (PA, "one span per admission; no per-stage child spans"), "T05": (PA, "delivery linked by trace id + decision id, not span links")},
    "MC-053": {"T04": (PA, "quota and dependency state at decision time not captured in explain")},
    "MC-054": {"T02": (H, "PII classes and residency need privacy-owner decision")},
    "MC-055": {"T05": (PA, "same scenarios in-process and over HTTP, but not the same fixture set")},
    "MC-056": {"T01": (X, "no real IdP/policy engine/registry/provenance verifier/INV-63/lattice"),
               "T06": (PA, "config rotation tested; signer rotation propagation across replicas not tested"),
               "T07": (PA, "two tenants in one org; no two-organisation run")},
    "MC-057": {"T03": (PA, "CI workflow runs the matrix; only one combination executed here"),
               "T04": (X, "ARM64 not run"), "T05": (X, "no cross-platform crypto backend runs"),
               "T06": (PA, "compat fixtures; no N-1 replica run")},
    "MC-058": {"T01": (PA, "multi-process on one host over the real journal/lease; not multi-node"),
               "T07": (PA, "repeated thread/process races; no schedule-perturbation tooling")},
    "MC-059": {"T02": (H, "RTO/RPO values PROPOSED"), "T05": (PA, "policy/deployment outages; DNS/time/KMS/IdP outages not injected"),
               "T07": (H, "runbooks must be executed by a separate operator"),
               "T08": (PA, "machine-readable results in ci_report; not signed separately")},
    "MC-060": {"T05": (X, "pk_core not bundled; lane NOT_RUN (waiver W-01)"),
               "T06": (PA, "bundle covered by the signed release manifest; signature is ephemeral")},
    "MC-061": {"T02": (PA, "reproducible wheel; signed with ephemeral key; no managed signing identity"),
               "T03": (X, "no environments/promotion pipeline available"), "T04": (X, "no orchestrator for canary"),
               "T06": (PA, "config rollback automated; artifact rollback procedural"),
               "T07": (H, "branch protection + release environment must be enabled by owners")},
    "MC-062": {"T02": (X, "pip-audit / advisory DB not reachable; lane NOT_RUN"),
               "T03": (H, "patch SLAs PROPOSED"), "T04": (H, "EOL dates PROPOSED"), "T05": (X, "continuous CVE monitoring service needed"),
               "T07": (PA, "license metadata in SBOM; no license scanner run")},
    "MC-063": {"T02": (H, "backup frequency/retention/location PROPOSED"), "T03": (PA, "backup verifies itself; scheduling/monitoring external"),
               "T07": (PA, "clean-room restore automated in tests; periodic schedule human"), "T08": (H, "operator sign-off")},
    "MC-064": {"T08": (H, "game days need operators")},
    "MC-065": {"T02": (H, "rotations UNASSIGNED"), "T06": (H, "communications roles undecided"), "T08": (H, "tabletop/game day needs people")},
    "MC-066": {"T01": (H, "review owners UNASSIGNED"), "T04": (H, "dispositions are human"), "T06": (PA, "stale review blocks via exit gate reasons; no overdue escalation"),
               "T08": (PA, "extraction checked by tests of its inputs only")},
    "MC-067": {"T06": (PA, "no trend reporting yet (single release)")},
    "MC-068": {"T04": (H, "named approvals missing"), "T08": (X, "no deployment automation to enforce the gate")},
    "MC-069": {"T02": (PA, "desired/admitted + delivery revision; observed runtime state not ingested (debt D-02)"),
               "T03": (X, "no authenticated INV-63/wasmCloud status feed"), "T06": (PA, "no last-observed timestamps for disconnected sites"),
               "T08": (PA, "rebuild-from-events tested; out-of-order/tombstone/drift not tested")},
    "MC-070": {"T01": (PA, "journal scan with filters; no secondary index"), "T03": (PA, "filters on time/tenant/lattice/principal/request/decision; not indexed"),
               "T04": (PA, "cursor pagination + limits; no rate limit or query-cost control on audit reads"),
               "T06": (PA, "exporter implemented; no real SIEM")},
    "MC-071": {"T01": (H, "license selection is an owner/legal decision"), "T02": (H, "depends on T01"),
               "T05": (H, "depends on policy"), "T06": (H, "depends on T01"), "T07": (PA, "license lane present but NOT_RUN")},
}

# Second pass over the specific items (item-by-item review against the tree).
_MORE = {
    "MC-009": {"T02": (PA, "limits for request rate, in-flight, manifest bytes/components; pending forwards/inventory/audit-rate/storage not hard-limited")},
    "MC-010": {"T01": (PA, "identity/policy/registry/signer/deployment/journal/config/clock covered; DNS not specified")},
    "MC-011": {"T07": (PA, "determinism proven in-process under shuffled rule order; not across nodes/versions/engine modes")},
    "MC-013": {"T06": (PA, "list filtered by scope; no pagination on RBAC list")},
    "MC-014": {"T03": (PA, "cursor pagination + authorization; no rate limits on audit reads")},
    "MC-015": {"T06": (PA, "RBAC keys on subject; issuer is not part of the binding key (multi-issuer collision possible)")},
    "MC-018": {"T06": (PA, "deprecation policy written; no telemetry of old-version use")},
    "MC-019": {"T07": (PA, "pending state persisted; last retryable error is not journaled")},
    "MC-020": {"T07": (PA, "malformed/unavailable/version-mismatch covered for policy, unavailable/refusal for delivery; not every dependency x mode")},
    "MC-021": {"T01": (PA, "repo/rev/path/idempotency recorded; branch, author, signature status, change-set id not modelled")},
    "MC-023": {"T05": (PA, "defaults are code-versioned and merged at build_policy; effective config not stored separately"),
               "T06": (PA, "config.history() available in-process; no authorised HTTP query endpoint"),
               "T08": (H, "per-environment production config revisions do not exist yet")},
    "MC-024": {"T08": (PA, "concurrent activation + stale writer tested; crash mid-activation and dependency failure during validation not tested")},
    "MC-025": {"T08": (PA, "backup/restore + replay tested; migration and multi-replica revocation propagation not tested")},
    "MC-026": {"T01": (PA, "registries(host,scope), signers(id,key,scope,revoked,not_after); artifact types/environments/namespaces absent"),
               "T08": (PA, "expired/revoked/scope tested; namespace confusion, overlapping rotations, stale replica not tested")},
    "MC-027": {"T02": (PA, "never logged/journaled/in errors; env-var provider means secrets exist in process environment"),
               "T07": (PA, "secret-ref changes audited via config generations; provider access failures not audited")},
    "MC-031": {"T03": (PA, "subject used as key without issuer (see MC-015-T06)")},
    "MC-032": {"T01": (PA, "org -> tenant -> lattice; environment/site/workload scope levels absent"),
               "T08": (PA, "cross-tenant, scope, delegation tested; no wildcards/group nesting/expiring grants exist to test")},
    "MC-033": {"T01": (PA, "input, allow, reasons, policy_version; no obligations or bundle digest"),
               "T02": (PA, "tenant/lattice/org/digest/components passed; principal, provenance results, quotas not passed"),
               "T08": (PA, "outage/version/malformed tested; no local-vs-remote differential test")},
    "MC-035": {"T04": (PA, "segments + summaries + anchors defined; anchoring cadence is operator-driven (cli anchor), not scheduled")},
    "MC-037": {"T01": (PA, "admission, token and config fuzzers; RBAC/audit-query payloads not fuzzed"),
               "T03": (PA, "tokens, idempotency keys, signatures, policy versions, duplicate acks; webhooks absent"),
               "T05": (PA, "oversized/deep/many components/overload; slow clients and pathological policy sets not tested")},
    "MC-038": {"T08": (PA, "crash points at journal append and decision->delivery; not every persistence boundary")},
    "MC-040": {"T01": (PA, "dependency registry with required flag; endpoint/timeout in config; no protocol-version/health-method per dependency"),
               "T06": (PA, "last error + since; no latency/staleness age per dependency"),
               "T07": (PA, "degraded transitions visible in health; no audit event on enter/leave")},
    "MC-041": {"T01": (PA, "backoff + full jitter + max attempts + deadline; no retry budget"),
               "T07": (PA, "shed, breaker-open, pending exported; retry counts and breaker transitions not counted")},
    "MC-042": {"T02": (PA, "freeze and release share the quarantine capability; release requires 2 distinct holders")},
    "MC-043": {"T03": (PA, "disk full + corruption + restore; read-only volume, latency, lost quorum not injected"),
               "T05": (PA, "expected safe state documented per dependency; data-loss bound/RTO per scenario not tabulated")},
    "MC-044": {"T02": (PA, "end-to-end latency, throughput, heap, FDs, journal bytes; no per-stage breakdown, CPU or network"),
               "T07": (PA, "comparison implemented; no approved baseline recorded yet")},
    "MC-046": {"T05": (PA, "SIEM exporter streams in batches; audit_export returns a whole range in memory")},
    "MC-047": {"T02": (PA, "QPS, components, journal growth, replay modelled; tenant/binding/query-load dimensions not")},
    "MC-050": {"T01": (PA, "outcome/code/rbac/authn/quota/shed/delivery/audit counters; policy/provenance failures not separately labelled"),
               "T02": (PA, "end-to-end histogram only; no per-stage histograms")},
    "MC-051": {"T01": (PA, "ts/level/event/request/trace/span/tenant/lattice/subject/codes; no service/version/site/replica fields per line")},
    "MC-052": {"T06": (PA, "uniform ratio sampling; errors/denials not preferentially retained")},
    "MC-053": {"T05": (PA, "structured explain JSON; no rendered human-readable decision tree"),
               "T08": (PA, "explain tested for admitted decisions; not for every denial class")},
    "MC-055": {"T01": (PA, "tests use the schemas and a reference validator; not generated from them"),
               "T03": (PA, "authorization negatives per operation; not a full principal x operation x scope matrix"),
               "T07": (PA, "non-JSON and deeply nested bodies tested; truncated bodies not")},
    "MC-056": {"T08": (PA, "machine results in ci_report; service logs/traces/audit exports not archived per run")},
    "MC-058": {"T06": (PA, "concurrent appends verified; concurrent query/export during appends not tested")},
    "MC-061": {"T05": (PA, "schema versions pinned; no per-rollout record of config revision (no rollout system)")},
    "MC-062": {"T01": (PA, "application SBOM only; no base-image/OS package SBOM")},
    "MC-064": {"T07": (PA, "alerts link runbooks; owner/escalation routes UNASSIGNED")},
    "MC-066": {"T05": (PA, "review output retained per run; no ticket linkage"),
               "T07": (PA, "review findings not yet surfaced in evidence/dashboards")},
    "MC-067": {"T07": (PA, "no waiver-resolution workflow yet")},
    "MC-068": {"T05": (PA, "artifact digest, source tree, compatibility, evidence digests; no deployment-manifest version or production config revision")},
    "MC-069": {"T01": (PA, "tenant/lattice/app/component/image/manifest digest/state/decision/seq; no site, desired vs observed revision or timestamps")},
    "MC-070": {"T02": (PA, "one retention class + legal holds; no per-event-type/tenant classes or archive tier"),
               "T08": (PA, "tenant access control, export verification, SIEM outage/recovery, restore tested; large-range and archived retrieval not")},
}
for _k, _v in _MORE.items():
    OPEN.setdefault(_k, {}).update(_v)
