"""Per-component disposition for the 71 MC items (single source for RTM, status ledger and exit gate).

status:  closed-local  implemented + automated evidence in this archive; remaining open items are
                       human review / hosted-CI only (D04/D05), tracked by W-002 / W-010
         partial       core implemented + tested; named external parts waived
         n/a           explicitly not applicable, justified + waived
open_tasks: task ids that are NOT done (with reason) — everything else in the component is done.
"""
P = "inv66_enterprise_wasm_control_plane/"
T = P + "tests/"
DISPOSITION = {
 "MC-001": ("partial", ["MASTER.md", "tools/gen_docs.py", "tools/repo_checks.py"], [], ["W-005"],
            {}),
 "MC-002": ("partial", ["docs/ADR-0001-control-plane-architecture.md"], [], ["W-002"], {}),
 "MC-003": ("partial", ["docs/OWNERSHIP.md", "deploy/alerts.yaml"], [], ["W-001"], {}),
 "MC-004": ("closed-local", ["docs/ARCHITECTURE.md#1"], [], [], {}),
 "MC-005": ("closed-local", ["docs/ARCHITECTURE.md#2", P + "store.py", P + "service.py"], [T + "test_durability.py"], [], {}),
 "MC-006": ("closed-local", ["docs/REQUIREMENTS.md", "tools/gen_docs.py"], [], [], {}),
 "MC-007": ("closed-local", ["governance/RTM.json", "tools/gen_docs.py"], [], [], {}),
 "MC-008": ("closed-local", ["docs/ARCHITECTURE.md#3", P + "lifecycle.py"], [T + "test_service.py"], [], {}),
 "MC-009": ("partial", ["docs/ARCHITECTURE.md#4", P + "resilience.py"], [T + "test_service.py", T + "test_integration.py"], ["W-009"], {}),
 "MC-010": ("closed-local", ["docs/ARCHITECTURE.md#5"], [T + "test_service.py", T + "test_durability.py"], [], {}),
 "MC-011": ("closed-local", ["docs/CONSTRAINT_PRECEDENCE.md"], [T + "test_service.py"], [], {}),
 "MC-012": ("closed-local", [P + "schemas/admit_request.v1.json", P + "schemas/admit_response.v1.json", P + "schema.py"], [T + "test_contracts.py"], [], {}),
 "MC-013": ("closed-local", [P + "schemas/rbac_binding.v1.json", P + "rbac.py", P + "http_api.py"], [T + "test_contracts.py", T + "test_security.py"], [], {}),
 "MC-014": ("closed-local", [P + "schemas/audit_event.v1.json", P + "store.py"], [T + "test_contracts.py", T + "test_service.py"], [], {}),
 "MC-015": ("closed-local", [P + "identity.py", P + "http_api.py"], [T + "test_security.py"], [], {}),
 "MC-016": ("closed-local", [P + "errors.py", P + "schemas/error.v1.json"], [T + "test_contracts.py"], [], {}),
 "MC-017": ("closed-local", ["docs/API.md", P + "resilience.py", P + "service.py"], [T + "test_service.py", T + "test_integration.py"], [], {}),
 "MC-018": ("closed-local", ["docs/API.md", T + "fixtures/"], [T + "test_contracts.py"], [], {}),
 "MC-019": ("partial", [P + "adapters.py", P + "service.py"], [T + "test_integration.py", T + "test_durability.py"], ["W-004"], {}),
 "MC-020": ("partial", [P + "adapters.py"], [T + "test_integration.py"], ["W-004"], {}),
 "MC-021": ("closed-local", [P + "gitops.py"], [T + "test_integration.py"], [], {}),
 "MC-022": ("closed-local", [P + "config.py", P + "schemas/config.v1.json", P + "cli.py"], [T + "test_service.py"], [], {}),
 "MC-023": ("closed-local", [P + "config.py", P + "service.py"], [T + "test_service.py"], [], {}),
 "MC-024": ("closed-local", [P + "service.py"], [T + "test_service.py"], [], {}),
 "MC-025": ("closed-local", [P + "rbac.py", P + "service.py", P + "store.py"], [T + "test_service.py", T + "test_durability.py"], [], {}),
 "MC-026": ("closed-local", [P + "config.py", P + "provenance.py"], [T + "test_service.py"], [], {}),
 "MC-027": ("closed-local", [P + "secrets_provider.py", P + "cli.py"], [T + "test_security.py"], [], {}),
 "MC-028": ("partial", ["pyproject.toml", "constraints.txt", "deploy/Dockerfile", "deploy/inv66.service"], [], ["W-010"], {}),
 "MC-029": ("partial", [P + "provenance.py"], [T + "test_service.py", T + "test_security.py"], ["W-015"], {}),
 "MC-030": ("closed-local", [P + "provenance.py"], [T + "test_service.py"], [], {}),
 "MC-031": ("partial", [P + "identity.py"], [T + "test_security.py"], ["W-004"], {}),
 "MC-032": ("closed-local", [P + "rbac.py"], [T + "test_security.py", T + "test_service.py"], [], {}),
 "MC-033": ("partial", [P + "adapters.py", P + "service.py"], [T + "test_integration.py", T + "test_service.py"], ["W-004"], {}),
 "MC-034": ("partial", [P + "cli.py", "docs/THREAT_MODEL.md"], [], ["W-007"], {}),
 "MC-035": ("partial", [P + "store.py", P + "adapters.py"], [T + "test_durability.py"], ["W-007"], {}),
 "MC-036": ("closed-local", ["docs/THREAT_MODEL.md"], [], ["W-002"], {}),
 "MC-037": ("closed-local", [T + "test_security.py"], [T + "test_security.py"], [], {}),
 "MC-038": ("closed-local", [P + "store.py", P + "service.py"], [T + "test_durability.py"], [], {}),
 "MC-039": ("partial", [P + "store.py"], [T + "test_ha.py"], ["W-006"], {}),
 "MC-040": ("closed-local", [P + "service.py", "docs/ARCHITECTURE.md#5"], [T + "test_service.py", T + "test_durability.py"], [], {}),
 "MC-041": ("closed-local", [P + "resilience.py"], [T + "test_integration.py"], [], {}),
 "MC-042": ("closed-local", [P + "service.py"], [T + "test_service.py", T + "test_integration.py"], [], {}),
 "MC-043": ("closed-local", [T + "test_durability.py"], [T + "test_durability.py", T + "test_ha.py"], [], {}),
 "MC-044": ("closed-local", ["tools/bench.py", "perf/results.json"], [], [], {}),
 "MC-045": ("partial", ["perf/thresholds.json", "perf/baseline.json", "tools/bench.py"], [], ["W-011"], {}),
 "MC-046": ("closed-local", [P + "store.py", P + "service.py"], [T + "test_durability.py"], [], {}),
 "MC-047": ("closed-local", ["docs/ARCHITECTURE.md#4", "perf/results.json"], [], [], {}),
 "MC-048": ("n/a", ["docs/ARCHITECTURE.md#6"], [], ["W-012"], {}),
 "MC-049": ("closed-local", [P + "http_api.py", P + "service.py"], [T + "test_integration.py"], [], {}),
 "MC-050": ("closed-local", [P + "observability.py"], [T + "test_service.py", T + "test_integration.py"], [], {}),
 "MC-051": ("closed-local", [P + "observability.py"], [T + "test_service.py"], [], {}),
 "MC-052": ("closed-local", [P + "observability.py", P + "adapters.py"], [T + "test_service.py", T + "test_integration.py"], [], {}),
 "MC-053": ("closed-local", [P + "service.py"], [T + "test_service.py"], [], {}),
 "MC-054": ("closed-local", ["docs/OPERATIONS.md#2", "deploy/alerts.yaml", "deploy/dashboard.json"], [], [], {}),
 "MC-055": ("closed-local", [T + "test_contracts.py"], [T + "test_contracts.py"], [], {}),
 "MC-056": ("partial", [T + "test_integration.py"], [T + "test_integration.py"], ["W-004"], {}),
 "MC-057": ("partial", [".github/workflows/inv66-ci.yml"], [], ["W-010"], {}),
 "MC-058": ("partial", [T + "test_ha.py"], [T + "test_ha.py"], ["W-006"], {}),
 "MC-059": ("partial", [T + "test_durability.py"], [T + "test_durability.py"], ["W-006"], {}),
 "MC-060": ("partial", ["governance/ACCEPTANCE_EVIDENCE.json", "tools/gen_evidence.py"], [], ["W-003"], {}),
 "MC-061": ("partial", [".github/workflows/inv66-ci.yml", "deploy/rollout.yaml"], [], ["W-010"], {}),
 "MC-062": ("partial", ["governance/SBOM.cdx.json", "tools/sbom.py", "docs/SUPPLY_CHAIN.md"], [], ["W-010"], {}),
 "MC-063": ("closed-local", [P + "backup.py", "docs/OPERATIONS.md#6"], [T + "test_durability.py"], [], {}),
 "MC-064": ("partial", ["docs/OPERATIONS.md"], [], ["W-014"], {}),
 "MC-065": ("partial", ["docs/OPERATIONS.md#7"], [], ["W-014"], {}),
 "MC-066": ("closed-local", ["tools/review.py", "governance/reviews/"], [], [], {}),
 "MC-067": ("closed-local", ["governance/WAIVERS.json"], [], [], {}),
 "MC-068": ("closed-local", ["tools/exit_gate.py", "governance/PRODUCTION_EXIT_GATE.json"], [], [], {}),
 "MC-069": ("closed-local", [P + "service.py"], [T + "test_service.py", T + "test_integration.py"], [], {}),
 "MC-070": ("partial", [P + "service.py", P + "store.py"], [T + "test_service.py", T + "test_durability.py"], ["W-013"], {}),
 "MC-071": ("partial", ["LICENSE", "NOTICE", "THIRD-PARTY-NOTICES.md", "tools/sbom.py"], [], ["W-008"], {}),
}


# Task-level exceptions: (status, reason).  Anything not listed is DONE for T-items.
# PARTIAL = implemented in part / verified only locally;  OPEN = not done;  N_A = justified not applicable.
TASKS = {
 "MC-001-T01": ("PARTIAL", "Authoritative Post-Kubernetes master text is not in the archive; MASTER.md pins CHECKLIST.json as the governing frozen source (W-005)"),
 "MC-001-T02": ("PARTIAL", "MASTER.md carries id/version/timestamp/digest of CHECKLIST.json, not of the upstream master prompt (W-005)"),
 "MC-001-T05": ("PARTIAL", "Check implemented in tools/repo_checks.py; not yet run on hosted CI (W-010)"),
 "MC-002-T08": ("OPEN", "Architecture/security/SRE approval not yet given (W-002)"),
 "MC-003-T02": ("OPEN", "Durable teams/rotations and contacts must be named by the organisation (W-001)"),
 "MC-003-T07": ("PARTIAL", "Ownership in runbooks/alerts; no CODEOWNERS until owners named (W-001)"),
 "MC-003-T08": ("PARTIAL", "tools/review.py flags placeholder owners; no HR/rotation source to diff against (W-001)"),
 "MC-004-T03": ("PARTIAL", "Single-site + DR restore documented; multi-site/regional/edge modes stated but not designed in depth (W-006, W-012)"),
 "MC-004-T08": ("PARTIAL", "Topology + flows described in prose/ASCII; no separate sequence diagrams per flow"),
 "MC-005-T07": ("PARTIAL", "Access control, anchoring, backup, retention done; at-rest encryption delegated to volume (W-007)"),
 "MC-008-T05": ("OPEN", "Supersession/cancellation of in-flight GitOps changes not modelled"),
 "MC-008-T06": ("PARTIAL", "Rollback is an authorised lifecycle transition; re-admission of a replacement goes through admit, but 'fresh authorization for rollback' policy is not configurable"),
 "MC-009-T01": ("PARTIAL", "Quotas by tenant/lattice (+ global bulkhead); not by principal/operation/site"),
 "MC-009-T03": ("PARTIAL", "Per-tenant token buckets; no weighted fair queue (W-009)"),
 "MC-009-T04": ("PARTIAL", "Burst = rate; no borrowing or expiring administrative overrides (W-009)"),
 "MC-009-T05": ("PARTIAL", "QUOTA_EXCEEDED is typed + retryable; no Retry-After/quota headers"),
 "MC-009-T08": ("PARTIAL", "Quota + bulkhead + overload shedding tested; no multi-tenant noisy-neighbour load test"),
 "MC-009-T13": ("OPEN", "Human review pending (W-002)"),
 "MC-010-T05": ("PARTIAL", "Single-writer per site; reconnect = outbox drain; no multi-site conflict resolution (W-006)"),
 "MC-010-T08": ("PARTIAL", "Dependency failures tested independently; correlated/partition combinations not tested (W-006)"),
 "MC-011-T06": ("PARTIAL", "Freeze/waiver rules documented; no emergency-exception object with TTL for tiers 3-5 in code"),
 "MC-011-T07": ("PARTIAL", "Determinism via single evaluation order + golden fixtures; no cross-node/cross-engine differential test"),
 "MC-012-T03": ("PARTIAL", "Manifest schema bundled; INV-64 authoritative schema not available to pin by digest (W-004)"),
 "MC-013-T01": ("PARTIAL", "RBAC administered via versioned config revisions (bindings/groups/service principals); no per-binding CRUD endpoint"),
 "MC-013-T04": ("PARTIAL", "Actor, approvers, source revision, expiry recorded; no desired activation time"),
 "MC-013-T05": ("PARTIAL", "Whole-document transactional validation; no per-entry error report"),
 "MC-013-T06": ("PARTIAL", "Audit query is cursor-paginated/bounded; binding listing is via /version + config only"),
 "MC-014-T07": ("OPEN", "No SIEM delivery adapter with ack/retry/dead-letter (W-013)"),
 "MC-015-T02": ("PARTIAL", "JWT (EdDSA/HS256) + mTLS cert binding; SPIFFE/SPIRE not integrated"),
 "MC-015-T05": ("PARTIAL", "Key rotation by kid in config, skew bounds, fail closed; no JWKS fetch/refresh, no revocation list"),
 "MC-017-T03": ("PARTIAL", "Deadlines bound dependency calls; no cooperative cancellation of in-flight calls"),
 "MC-017-T06": ("PARTIAL", "Bounded bulkhead fails fast (no queue); no Retry-After hint"),
 "MC-018-T01": ("PARTIAL", "Matrix covers INV-66 protocols/Python; GAP-13/GAP-07/INV-64/wasmCloud versions unknown here (W-004)"),
 "MC-018-T04": ("PARTIAL", "Single writer per store prevents divergent N/N-1 decisions; no mixed-version test"),
 "MC-018-T06": ("OPEN", "Deprecation lifecycle and old-version telemetry not defined"),
 "MC-018-T08": ("PARTIAL", "Matrix defined in CI workflow; not executed on hosted runners (W-010)"),
 "MC-019-T02": ("PARTIAL", "Schema/auth/timeout/TLS defined; service discovery is static URL"),
 "MC-019-T05": ("PARTIAL", "Ack = accepted-for-reconciliation; observed deployed/healthy not ingested from INV-63"),
 "MC-019-T08": ("PARTIAL", "Protocol-faithful HTTP fake + crash/duplicate tests; no real INV-63 (W-004)"),
 "MC-020-T03": ("PARTIAL", "Live HTTP fakes (real serialization); no real service containers (W-004)"),
 "MC-020-T06": ("PARTIAL", "Policy bundle version pinned; no version-skew tests for other adapters"),
 "MC-020-T07": ("PARTIAL", "Unavailable/malformed/version-mismatch tested for policy + deploy; not for identity/registry"),
 "MC-020-T08": ("OPEN", "No CI job against real adjacent layers (W-004, W-010)"),
 "MC-021-T02": ("PARTIAL", "Ingestion API with commit-scoped idempotency; no authenticated webhook receiver/poller"),
 "MC-021-T05": ("OPEN", "Force-push/branch-deletion/supersession semantics not implemented"),
 "MC-021-T06": ("PARTIAL", "INV-66 never holds repository credentials (operates on a checked-out tree); least-privilege documented only"),
 "MC-021-T07": ("PARTIAL", "Ingest result links commit to decisions; no persistent GitOps status endpoint"),
 "MC-021-T08": ("PARTIAL", "Filesystem change-set fixture; no real Git server/webhook replay test"),
 "MC-024-T01": ("PARTIAL", "validate -> approved (two-person) -> atomic activate; no separate draft/staged objects"),
 "MC-024-T05": ("PARTIAL", "Operator rollback implemented; automatic rollback triggers not implemented"),
 "MC-024-T06": ("OPEN", "Rollback to a revision with revoked signers is not blocked"),
 "MC-024-T08": ("PARTIAL", "Stale-writer (if_match) + invalid-candidate tests; no crash-mid-activation test"),
 "MC-025-T01": ("PARTIAL", "Persistence via journal; no separate HA RBAC datastore (W-006)"),
 "MC-025-T03": ("PARTIAL", "Schema-level validation; no referential integrity for principals/scopes"),
 "MC-025-T05": ("PARTIAL", "Scoped capabilities + escalation guard; no delegated per-tenant admin workflow"),
 "MC-025-T08": ("PARTIAL", "Backup/restore/audit tested; no multi-replica revocation-propagation test (W-006)"),
 "MC-026-T02": ("PARTIAL", "Approval = two-person rule on config revision; no separate registry/signer approval workflow"),
 "MC-026-T03": ("PARTIAL", "Distributed as config revision; no push distribution to other sites"),
 "MC-027-T01": ("PARTIAL", "Secret-reference model + env/file provider; no KMS/Vault client"),
 "MC-027-T05": ("OPEN", "Rotation without restart not supported"),
 "MC-027-T08": ("PARTIAL", "Provider unit behaviour; no ephemeral secret-manager fixture tests"),
 "MC-028-T03": ("PARTIAL", "Non-root Dockerfile provided; base-image digest placeholder, image not built here (W-010)"),
 "MC-028-T04": ("PARTIAL", "Build commands + pins recorded; no artifact digests from a real build"),
 "MC-028-T06": ("OPEN", "No environment bootstrap validator for DNS/cert/KMS reachability"),
 "MC-028-T07": ("PARTIAL", "SBOM generated; signing/provenance only in CI release job (W-010)"),
 "MC-028-T08": ("PARTIAL", "Clean-container install+test run locally; not on hosted CI (W-010)"),
 "MC-029-T01": ("PARTIAL", "Ed25519 over defined payload with key ids; no certificate/Fulcio identity binding"),
 "MC-029-T04": ("PARTIAL", "Signer validity window enforced; signer scope per tenant/repository not modelled"),
 "MC-029-T05": ("PARTIAL", "Expiry via not_after; no revocation service/transparency log (W-015)"),
 "MC-029-T07": ("PARTIAL", "Digest, signer id, errors and config revision recorded; key fingerprint/algorithm not separately recorded"),
 "MC-030-T02": ("OPEN", "No authenticated registry client; digests are verified by signature, not by fetching content"),
 "MC-030-T03": ("PARTIAL", "Immutable digest pinning + signature over digest; content bytes not re-hashed"),
 "MC-030-T04": ("PARTIAL", "Attestation presence + digest binding required; attestation contents (builder/source) not verified"),
 "MC-030-T05": ("PARTIAL", "SBOM/provenance presence enforced; freshness not enforced"),
 "MC-030-T07": ("N_A", "No metadata cache exists (nothing fetched)"),
 "MC-030-T08": ("PARTIAL", "Tags rejected (no TOCTOU window); malformed provenance covered by schema tests"),
 "MC-031-T01": ("PARTIAL", "JWT from OIDC IdPs + service principals; SAML must be bridged by the IdP (W-004)"),
 "MC-031-T02": ("PARTIAL", "Tenant is request data checked by scoped RBAC; no claim-based tenant discovery"),
 "MC-031-T04": ("PARTIAL", "aud/iss/sig/lifetime/groups validated; AMR/authentication strength not enforced"),
 "MC-031-T05": ("OPEN", "Joiner/mover/leaver propagation targets not defined"),
 "MC-031-T07": ("OPEN", "No step-up auth or break-glass accounts"),
 "MC-031-T08": ("PARTIAL", "Negative token fixtures; no representative IdP federation tests (W-004)"),
 "MC-032-T01": ("PARTIAL", "org > tenant > lattice; environment is per-instance; no workload-level scope"),
 "MC-032-T03": ("PARTIAL", "Groups, service principals, expiring grants, explicit deny; no temporary elevation workflow"),
 "MC-033-T05": ("N_A", "No compiled-policy cache (always remote or embedded rules)"),
 "MC-033-T08": ("PARTIAL", "Remote vs rule engine, malformed, version-mismatch, unavailable tested; no differential equivalence test"),
 "MC-034-T02": ("PARTIAL", "TLS/mTLS wiring in CLI; certificate identities/rotation per org PKI, documented only"),
 "MC-034-T03": ("OPEN", "No application-level at-rest encryption (volume encryption required) (W-007)"),
 "MC-034-T04": ("OPEN", "Key separation by tenant/data class not implemented (W-007)"),
 "MC-034-T05": ("PARTIAL", "Rotation procedure documented; no re-encryption (nothing app-encrypted)"),
 "MC-034-T07": ("OPEN", "No certificate/key expiry health signal"),
 "MC-034-T08": ("OPEN", "No automated TLS configuration / expired-cert tests (W-007)"),
 "MC-035-T01": ("PARTIAL", "Append-only journal + read-only sealed segments + external WORM anchor sink; store itself is not WORM"),
 "MC-035-T03": ("PARTIAL", "Dedicated MAC key via secret reference; not KMS/HSM-protected (W-007)"),
 "MC-035-T06": ("PARTIAL", "Periodic anchoring + /healthz chain verification + alerts; anchor verification not scheduled in loop"),
 "MC-036-T06": ("PARTIAL", "Residuals listed; organisational risk-rating method not applied (W-002)"),
 "MC-036-T08": ("OPEN", "Review before exit gate not yet held (W-002)"),
 "MC-037-T01": ("PARTIAL", "Seeded mutation fuzzer for admission; no grammar fuzzers for admin/audit/config payloads"),
 "MC-037-T02": ("PARTIAL", "Invariant checks in fuzz; no property-based framework"),
 "MC-037-T07": ("OPEN", "No static analysis / dependency scanning executed (W-010)"),
 "MC-038-T05": ("PARTIAL", "fsync per append; acknowledged-loss guarantee documented; replicated-volume RPO depends on storage (W-006)"),
 "MC-039-T01": ("DONE", ""),
 "MC-039-T03": ("OPEN", "Replication factor/quorum delegated to storage; not specified or tested (W-006)"),
 "MC-039-T05": ("PARTIAL", "Single writer => immediate consistency within a site; cross-site propagation not defined (W-006)"),
 "MC-039-T07": ("PARTIAL", "Leader/epoch exposed; no replication lag metric (W-006)"),
 "MC-039-T08": ("PARTIAL", "Multi-process lease/fencing/race tests; no multi-node packet delay/partition/clock-skew tests (W-006)"),
 "MC-039-T13": ("PARTIAL", "Multi-process on one host only (W-006)"),
 "MC-040-T05": ("OPEN", "No hysteresis/debounce on readiness"),
 "MC-040-T06": ("PARTIAL", "Breaker state + status per dependency; no last-success timestamps/latency per dependency"),
 "MC-040-T07": ("PARTIAL", "Degraded transitions logged via metrics; not journalled as audit events"),
 "MC-041-T04": ("PARTIAL", "Global bulkhead + per-dependency breaker; no per-dependency concurrency limit"),
 "MC-041-T05": ("PARTIAL", "Stable OVERLOADED error; no retry-after hint"),
 "MC-041-T07": ("PARTIAL", "Shed/outcome/breaker gauges exported; no retry-count metric"),
 "MC-042-T02": ("PARTIAL", "Freeze capability separate from admit; no dual control for global freeze"),
 "MC-042-T03": ("PARTIAL", "Journalled and replayed across restart/failover within a site; cross-site replication (W-006)"),
 "MC-043-T04": ("PARTIAL", "Dependency outages + fencing tested; no DNS/cert-expiry/KMS/clock-skew injection"),
 "MC-043-T07": ("OPEN", "No production-like multi-replica chaos environment (W-006)"),
 "MC-044-T02": ("PARTIAL", "End-to-end latency measured; per-stage timings not broken out"),
 "MC-044-T03": ("PARTIAL", "Steady, burst/overload, restart replay covered; scale-out/in and dependency slowdown not"),
 "MC-044-T04": ("PARTIAL", "Single-component manifests; no size/component distribution sweep"),
 "MC-044-T05": ("PARTIAL", "Soak mode exists; long (hours) soak not run here"),
 "MC-044-T06": ("PARTIAL", "p50/p95/p99/max; no p99.9 or confidence intervals"),
 "MC-044-T08": ("PARTIAL", "Automated in CI workflow; not executed on a controlled perf host (W-010)"),
 "MC-045-T01": ("PARTIAL", "Threshold for successful admission only; denial/admin op thresholds not separate"),
 "MC-045-T02": ("PARTIAL", "Single end-to-end budget; stage budget not derived"),
 "MC-045-T04": ("PARTIAL", "Replay/startup budget set; failover/propagation objectives not set"),
 "MC-045-T06": ("PARTIAL", "Warm-up excluded; sample size 3000; saturation p99 exceeds SLO (W-011)"),
 "MC-045-T10": ("PARTIAL", "Latency/throughput/RSS/journal bytes; no CPU/I/O breakdown"),
 "MC-046-T05": ("PARTIAL", "Audit query paginated; export returns full retained set in one response"),
 "MC-046-T06": ("PARTIAL", "Head sequence, outbox depth, compactions exported; no retained-bytes/oldest-pending-age"),
 "MC-046-T07": ("PARTIAL", "Store failure => fail closed (never drop); archive-sink-full behaviour not separate"),
 "MC-046-T08": ("PARTIAL", "RSS steady-state gate in bench (short run); no multi-hour test"),
 "MC-047-T04": ("PARTIAL", "Thresholds defined; no autoscaler (scale unit is site instance)"),
 "MC-047-T06": ("PARTIAL", "70% headroom rule; N+1 across zones depends on W-006"),
 "MC-048-T02": ("N_A", "C068 not applicable (W-012)"), "MC-048-T03": ("N_A", "C068 not applicable (W-012)"),
 "MC-048-T04": ("N_A", "C068 not applicable (W-012)"), "MC-048-T05": ("N_A", "C068 not applicable (W-012)"),
 "MC-048-T06": ("N_A", "C068 not applicable (W-012)"), "MC-048-T07": ("N_A", "C068 not applicable (W-012)"),
 "MC-049-T01": ("PARTIAL", "Health/ready/version/metrics are unauthenticated-minimal; must be bound to the ops network"),
 "MC-050-T02": ("PARTIAL", "End-to-end histogram; no per-stage histograms"),
 "MC-050-T03": ("PARTIAL", "In-flight, outbox, head, freezes, leader, breakers; no cache hit ratio/config age"),
 "MC-050-T04": ("OPEN", "No process/runtime metrics exporter"),
 "MC-050-T07": ("PARTIAL", "Tests assert required series exist; no dashboard-query CI"),
 "MC-050-T08": ("PARTIAL", "Overhead included in bench; export failure isolation not tested"),
 "MC-051-T05": ("PARTIAL", "Level threshold only; no sampling (so nothing security-relevant is dropped)"),
 "MC-051-T06": ("PARTIAL", "stderr JSON lines to the platform collector; no in-process buffering"),
 "MC-052-T02": ("PARTIAL", "One span per admission logged with trace/span id; no per-stage spans or OTel exporter"),
 "MC-052-T05": ("PARTIAL", "Outbox delivery reuses decision trace id; no explicit span links"),
 "MC-052-T06": ("PARTIAL", "Sampling policy documented; no sampler in code"),
 "MC-052-T08": ("PARTIAL", "Propagation tested to policy/deploy adapters; untrusted-context handling = new span id only"),
 "MC-053-T02": ("PARTIAL", "Config revision/digest + policy version + errors; matched RBAC bindings not captured per decision (access_review gives current chain)"),
 "MC-053-T05": ("PARTIAL", "Machine-readable explain; no human-rendered decision tree UI"),
 "MC-054-T04": ("PARTIAL", "Bounded in-process telemetry; export spooling belongs to the collector"),
 "MC-054-T08": ("OPEN", "No synthetic alert/dashboard tests"),
 "MC-055-T05": ("PARTIAL", "Same fixtures in-process; HTTP endpoint tests use separate cases"),
 "MC-056-T01": ("OPEN", "No E2E environment with real dependencies (W-004)"),
 "MC-056-T02": ("PARTIAL", "GitOps->admission->journal->HTTP deploy fake->ack path tested in-process"),
 "MC-056-T05": ("PARTIAL", "Policy/deploy/store failures injected; not every dependency"),
 "MC-056-T06": ("PARTIAL", "Config/signer rotation via revisions tested; not under concurrent load"),
 "MC-056-T07": ("PARTIAL", "Two tenants isolation tested; not two organisations concurrently"),
 "MC-056-T08": ("PARTIAL", "Machine results retained; no service logs/traces bundle from E2E env"),
 "MC-057-T03": ("OPEN", "Matrix not executed (W-010)"), "MC-057-T04": ("OPEN", "arm64 not executed (W-010)"),
 "MC-057-T05": ("OPEN", "Cross-platform crypto not validated (W-010)"), "MC-057-T06": ("OPEN", "No N/N-1 rolling tests"),
 "MC-057-T07": ("PARTIAL", "Local run versions recorded in evidence"), "MC-057-T08": ("PARTIAL", "CI job fails on skips; not yet running"),
 "MC-058-T01": ("PARTIAL", "Multi-process against real file store; no multi-node"),
 "MC-058-T03": ("PARTIAL", "Stale-writer rejection tested sequentially; not concurrently"),
 "MC-058-T06": ("PARTIAL", "Concurrent appends tested; concurrent query/export not"),
 "MC-058-T07": ("PARTIAL", "Repeated multi-process contention; no randomized scheduler/race tooling"),
 "MC-059-T01": ("PARTIAL", "Process loss, store corruption, restore covered; site/zone/region loss not (W-006)"),
 "MC-059-T02": ("PARTIAL", "RPO/RTO targets stated for restore only"),
 "MC-059-T04": ("OPEN", "No site partition test (W-006)"),
 "MC-059-T05": ("PARTIAL", "Policy outage tested; DNS/time/KMS/identity outages not"),
 "MC-059-T07": ("OPEN", "Runbooks not executed by a separate operator (W-014)"),
 "MC-059-T08": ("PARTIAL", "Machine-readable DR test results; not signed, no achieved RTO/RPO measured"),
 "MC-060-T04": ("PARTIAL", "Generated from local test/bench/doc checks; no security scans/matrix inputs yet (W-010)"),
 "MC-060-T05": ("OPEN", "pk_core not vendored/available (W-003)"),
 "MC-060-T06": ("PARTIAL", "Evidence bundle digested + HMAC-sealed when a release key is provided; not in signed provenance yet"),
 "MC-061-T02": ("OPEN", "No signed build produced (W-010)"),
 "MC-061-T04": ("PARTIAL", "Rollout plan with checks; no automation executing it"),
 "MC-061-T06": ("PARTIAL", "Rollback procedure + config rollback API; not automated"),
 "MC-061-T07": ("OPEN", "Branch protection/CODEOWNERS need named owners (W-001)"),
 "MC-062-T02": ("OPEN", "No vulnerability scanner executed (W-010)"),
 "MC-062-T05": ("OPEN", "No continuous CVE monitoring"),
 "MC-062-T07": ("PARTIAL", "License gate in tools/sbom.py; no provenance verification of dependency updates"),
 "MC-063-T03": ("PARTIAL", "Backup tool + verification; scheduling/monitoring left to ops platform"),
 "MC-063-T05": ("PARTIAL", "Replay-based migration strategy documented; no second format exists yet"),
 "MC-063-T07": ("PARTIAL", "Automated clean-directory restore test; no periodic clean-room drill yet (W-014)"),
 "MC-063-T08": ("PARTIAL", "Test evidence recorded; no operator sign-off or achieved RTO (W-014)"),
 "MC-064-T08": ("OPEN", "No game day held (W-014)"),
 "MC-065-T02": ("PARTIAL", "Ack/escalation timers defined; rotations need names (W-001)"),
 "MC-065-T08": ("OPEN", "No tabletop/game day held (W-014)"),
 "MC-066-T04": ("PARTIAL", "Findings carry severity + remediation hint; reviewer disposition captured manually"),
 "MC-066-T07": ("PARTIAL", "Review status in evidence bundle; no governance dashboard"),
 "MC-066-T08": ("OPEN", "Automation not validated against source systems"),
 "MC-067-T02": ("PARTIAL", "Expiry required and checked; no notification channel"),
 "MC-067-T06": ("OPEN", "No trend reporting"),
 "MC-068-T04": ("OPEN", "Named approvals cannot be recorded until owners are named (W-001, W-002)"),
 "MC-068-T08": ("PARTIAL", "CI release job requires GO; no deployment automation to bind yet"),
 "MC-069-T02": ("PARTIAL", "Admitted/lifecycle state recorded; observed runtime state not ingested"),
 "MC-069-T03": ("OPEN", "No ingestion from INV-63 reconciliation events (W-004)"),
 "MC-069-T04": ("PARTIAL", "Tenant/lattice filters; no artifact/revision filter or pagination"),
 "MC-069-T06": ("PARTIAL", "as_of_sequence given; no per-site last-observed timestamps"),
 "MC-069-T08": ("PARTIAL", "Rollback removal + replay tested; no out-of-order observed-state tests"),
 "MC-070-T01": ("PARTIAL", "Durable journal + query API; linear scan, no secondary index"),
 "MC-070-T02": ("PARTIAL", "Hot journal/archive tiers + legal hold on purge; retention classes by event type not separate"),
 "MC-070-T03": ("PARTIAL", "Filters: sequence, kind, tenant; no time/principal/digest index"),
 "MC-070-T04": ("PARTIAL", "Cursor pagination + limit + authz; no query-cost controls"),
 "MC-070-T06": ("OPEN", "No SIEM connector (W-013)"),
 "MC-070-T08": ("PARTIAL", "Access control, archive retrieval, export, restore tested; SIEM outage not"),
 "MC-071-T01": ("PARTIAL", "Proprietary all-rights-reserved placeholder shipped; owner/legal selection pending (W-008)"),
 "MC-071-T05": ("N_A", "No per-file headers required by the placeholder licence"),
 "MC-071-T07": ("PARTIAL", "tools/sbom.py fails on forbidden/unknown licences; CI not yet running (W-010)"),
}

# Definition-of-Done rules applied to every component.
DOD = {
 "D01": ("DONE", "In repo at documented path and in RELEASE_MANIFEST.sha256"),
 "D02": ("DONE", "Schemas/configs/tests pinned (constraints.txt, versioned $id)"),
 "D03": ("DONE", "RTM row generated in governance/RTM.json"),
 "D04": ("PARTIAL", "Passes in a clean container locally; hosted CI not yet executed (W-010)"),
 "D05": ("OPEN", "Human security/architecture/operations review pending (W-002)"),
 "D06": ("DONE", "governance/ACCEPTANCE_EVIDENCE.json records artifact and test-run digests"),
 "D07": ("DONE", "docs/OPERATIONS.md covers inspect/diagnose/rollback"),
}
