#!/usr/bin/env python3
"""CycloneDX 1.5 SBOM + licence gate + THIRD-PARTY-NOTICES generation (MC-062, MC-071).

Reads constraints.txt (the pinned dependency set), resolves installed distribution metadata,
writes governance/SBOM.cdx.json and THIRD-PARTY-NOTICES.md, and exits 1 if any dependency has
a forbidden (strong copyleft) or unknown licence.
"""
from __future__ import annotations

import hashlib
import json
import pathlib
import sys
from importlib import metadata

ROOT = pathlib.Path(__file__).resolve().parents[1]
ALLOWED = ("Apache", "BSD", "MIT", "PSF", "Python Software Foundation", "ISC", "MPL-2.0")
FORBIDDEN = ("AGPL", "GPL-3", "GPLv3", "SSPL", "GPL-2", "GPLv2")
RUNTIME = {"cryptography", "cffi", "pycparser"}


def licence_of(dist) -> str:
    md = dist.metadata
    lic = md.get("License-Expression") or ""
    if not lic or len(lic) > 80:
        lic = md.get("License") or ""
    if not lic or len(lic) > 80:
        lic = "; ".join(c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if c.startswith("License ::"))
    return lic.strip() or "UNKNOWN"


def main() -> int:
    pins = [l.split("#")[0].strip() for l in (ROOT / "constraints.txt").read_text().splitlines() if "==" in l]
    comps, problems, notices = [], [], []
    for pin in pins:
        name, ver = pin.split("==")
        try:
            d = metadata.distribution(name)
            installed, lic = d.version, licence_of(d)
        except metadata.PackageNotFoundError:
            installed, lic = None, "UNKNOWN"
        scope = "required" if name.lower() in RUNTIME else "optional"
        comps.append({"type": "library", "bom-ref": f"pkg:pypi/{name}@{ver}", "name": name, "version": ver,
                      "purl": f"pkg:pypi/{name.lower()}@{ver}", "scope": scope,
                      "licenses": [{"license": {"name": lic}}],
                      "properties": [{"name": "installed-version", "value": str(installed)}]})
        if any(f in lic for f in FORBIDDEN):
            problems.append(f"{name}: forbidden licence {lic}")
        elif lic == "UNKNOWN" or not any(a.lower() in lic.lower() for a in ALLOWED):
            problems.append(f"{name}: licence not on allow-list ({lic})")
        if installed and installed != ver:
            problems.append(f"{name}: installed {installed} != pinned {ver}")
        notices.append(f"| {name} | {ver} | {lic} | {scope} |")
    bom = {"bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1,
           "metadata": {"component": {"type": "application", "name": "inv66-enterprise-wasm-control-plane",
                                      "version": (ROOT / "inv66_enterprise_wasm_control_plane" / "VERSION").read_text().strip(),
                                      "licenses": [{"license": {"name": "LicenseRef-INV66-Proprietary-Pending"}}]},
                        "tools": [{"name": "tools/sbom.py"}]},
           "components": comps}
    bom["serialNumber"] = "urn:uuid:" + hashlib.sha256(json.dumps(comps, sort_keys=True).encode()).hexdigest()[:32]
    (ROOT / "governance" / "SBOM.cdx.json").write_text(json.dumps(bom, indent=2) + "\n")
    (ROOT / "THIRD-PARTY-NOTICES.md").write_text(
        "# Third-party notices (generated by tools/sbom.py from constraints.txt)\n\n"
        "INV-66 bundles no third-party source code. It depends at runtime on the packages marked *required*; "
        "*optional* packages are used only by the test-suite. Each package's full licence text ships inside its "
        "installed distribution (`<site-packages>/<name>-<version>.dist-info/`).\n\n"
        "| Package | Version | Licence | Scope |\n|---|---|---|---|\n" + "\n".join(notices) + "\n")
    print(json.dumps({"components": len(comps), "problems": problems}))
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
