apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "inv67-controller"
  namespace: "inv67-system"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "inv67"
