"""Source table for governance/RTM.json (regenerate: python tools/rtm.py build).

status: PASS (in-repo executable/durable evidence), BLOCKED (needs an input this
repository cannot supply - approval, pk_core, peer, hardware, signing key),
EXTERNAL (owned by a peer; INV-25 side covered by contract fixture), NOT_APPLICABLE.
"""
T = {
    "model": "tests/test_model.py::DeviceModelTest", "err": "tests/test_errors_limits.py::ErrorContractTest",
    "lim": "tests/test_errors_limits.py::LimitsTest", "authn": "tests/test_authz.py::AuthnTest",
    "authz": "tests/test_authz.py::AuthorizationTest", "act": "tests/test_store.py::ActivationTest",
    "fault": "tests/test_store.py::PersistenceAndFaultTest", "conc": "tests/test_store.py::ConcurrencyTest",
    "aud": "tests/test_store.py::AuditTamperTest", "prov": "tests/test_provenance_compat.py::ProvenanceTest",
    "compat": "tests/test_provenance_compat.py::CompatTest", "fuzz": "tests/test_fuzz.py::FuzzTest",
    "integ": "tests/test_integration_contracts.py::IntegrationContractTest",
    "perf": "tests/test_performance.py::PerformanceTest", "schema": "tests/test_schemas_rtm.py::SchemaTest",
    "rtm": "tests/test_schemas_rtm.py::RtmTest", "comp": "tests/test_component.py::ConformanceTest",
    "gov": "tests/test_schemas_rtm.py::GovernanceTest",
}
PK = "pk_core-driven assessment not executable: pk_core not distributed with this archive (work item 1)"
APPROVAL = "requires named human approval that cannot be minted by tooling (see governance/waivers.json)"
ROWS = {
    1: ("PASS", ["contract.py::build.responsibility", "README.md"], [], ""),
    2: ("PASS", ["contract.py::build.owns", "docs/ownership.md"], [], ""),
    3: ("PASS", ["contract.py::build.dependencies", "docs/ownership.md"], ["integ"], ""),
    4: ("PASS", ["contract.py::build.source_of_truth", "store.py::CatalogueStore.active"], ["act"], ""),
    5: ("PASS", ["contract.py::build.assumptions", "ADR/ADR-0001-virtio-net-block.md"], [], ""),
    6: ("PASS", ["contract.py::build.boundaries", "authz.py::authorize"], ["authz"], ""),
    7: ("PASS", ["contract.py::build.mandatory", "contract.py::build.optional"], [], ""),
    8: ("PASS", ["contract.py::build.non_goals", "README.md"], [], ""),
    9: ("BLOCKED", ["docs/ownership.md", "CODEOWNERS", "docs/incident-response.md"], ["gov"],
        "role-based ownership defined; named team/person assignments " + APPROVAL),
    10: ("BLOCKED", ["ADR/ADR-0001-virtio-net-block.md"], [], "ADR drafted with status Proposed; " + APPROVAL),
    11: ("PASS", ["model.py", "README.md"], ["model", "err"], ""),
    12: ("PASS", ["docs/requirements.md"], ["model"], ""),
    13: ("PASS", ["docs/requirements.md", "conformance/performance/thresholds.json"], ["perf"], ""),
    14: ("PASS", ["docs/error-contract.md", "errors.py::CODES"], ["err"], ""),
    15: ("PASS", ["docs/requirements.md", "store.py::CatalogueStore"], ["act"], ""),
    16: ("PASS", ["docs/compatibility.md", "compat.py::negotiate"], ["compat"], ""),
    17: ("PASS", ["docs/limits.md", "model.py::MAX_DEVICES"], ["lim"], ""),
    18: ("PASS", ["docs/requirements.md", "store.py::CatalogueStore.activate"], ["fault"], ""),
    19: ("PASS", ["docs/requirements.md"], [], ""),
    20: ("PASS", ["governance/RTM.json", "tools/rtm.py"], ["rtm"], ""),
    21: ("PASS", ["docs/interfaces.md"], ["schema"], ""),
    22: ("PASS", ["schemas/"], ["schema"], ""),
    23: ("PASS", ["docs/authn-authz.md", "authz.py::Verifier"], ["authn"], ""),
    24: ("PASS", ["docs/authn-authz.md", "authz.py::authorize"], ["authz", "act"], ""),
    25: ("PASS", ["docs/interfaces.md", "store.py::_Bucket"], ["act"], ""),
    26: ("PASS", ["docs/error-contract.md", "schemas/PK_DEVICE_ERROR_1.schema.json"], ["err"], ""),
    27: ("PASS", ["docs/compatibility.md", "compat.py"], ["compat"], ""),
    28: ("PASS", ["docs/limits.md"], ["lim", "act"], ""),
    29: ("PASS", ["conformance/fixtures/", "conformance/integration/peer_contracts.py"], ["schema", "integ"], ""),
    30: ("EXTERNAL", ["conformance/integration/peer_contracts.py"], ["integ"],
         "INV-25 side proven against version-pinned contract fixtures; real INV-24/35/26/GAP-13 evidence is peer-owned"),
    31: ("BLOCKED", ["ADR/ADR-0001-virtio-net-block.md", "compat.py::MATRIX"], ["compat"],
         "virtio 1.2 proposed; VMM/backend implementation versions not yet pinned by owners"),
    32: ("PASS", ["docs/requirements.md", "store.py::Snapshot"], ["act"], ""),
    33: ("PASS", ["docs/limits.md", "model.py"], ["model"], ""),
    34: ("PASS", ["store.py::CatalogueStore.activate", "model.py::catalogue_from_export"], ["act", "fault"], ""),
    35: ("PASS", ["store.py::CatalogueStore.__init__"], ["authz"], ""),
    36: ("PASS", ["schemas/PK_DEVICE_CONFIG_ACTIVATION_1.schema.json", "store.py::CatalogueStore._record"], ["act"], ""),
    37: ("PASS", ["store.py::CatalogueStore._commit"], ["act", "fault", "conc"], ""),
    38: ("PASS", ["store.py::CatalogueStore.rollback", "docs/rollout.md"], ["act"], ""),
    39: ("PASS", ["errors.py::_redact", "audit.py::_FORBIDDEN_KEYS"], ["err", "aud"], ""),
    40: ("PASS", ["docs/runbooks.md", "pk_bootstrap.py"], ["compat"], ""),
    41: ("PASS", ["docs/threat-model.md"], ["fuzz", "authn"], ""),
    42: ("PASS", ["authz.py::CAPABILITIES"], ["authz"], ""),
    43: ("PASS", ["docs/threat-model.md", "model.py"], ["model"], "package performs no network/device I/O; state file path is explicit"),
    44: ("PASS", ["authz.py::Verifier", "provenance.py::TrustPolicy"], ["authn", "prov"], ""),
    45: ("PASS", ["provenance.py::TrustPolicy.verify", "docs/provenance.md"], ["prov"], ""),
    46: ("EXTERNAL", ["contract.py::build.not_owns"], [], "execution/memory isolation is owned by INV-24/INV-35; INV-25 bounds guest-visible surface only"),
    47: ("EXTERNAL", ["docs/threat-model.md"], [], "catalogue holds no secrets; transport/at-rest encryption owned by control-plane storage and transport"),
    48: ("PASS", ["docs/authn-authz.md"], ["authn", "fault"], ""),
    49: ("PASS", ["audit.py::AuditLog", "schemas/PK_DEVICE_AUDIT_EVENT_1.schema.json"], ["aud", "act"], ""),
    50: ("PASS", ["tests/test_fuzz.py", "tests/test_authz.py"], ["fuzz", "authn", "authz"], ""),
    51: ("PASS", ["docs/failure-model.md"], ["fault"], ""),
    52: ("PASS", ["store.py::CatalogueStore.health", "docs/telemetry-policy.md"], ["act"], ""),
    53: ("PASS", ["docs/error-contract.md"], ["err"], "INV-25 performs no internal retries; retryable flag + guidance for callers"),
    54: ("PASS", ["store.py::_Bucket", "store.py::CatalogueStore.MAX_PENDING"], ["act"], ""),
    55: ("NOT_APPLICABLE", ["docs/failure-model.md"], [], "single-writer reference store; no failover replica in scope (waiver W-0004)"),
    56: ("PASS", ["docs/failure-model.md", "store.py::CatalogueStore.permits"], ["fault"], ""),
    57: ("PASS", ["store.py::CatalogueStore._persist"], ["fault"], ""),
    58: ("PASS", ["store.py::CatalogueStore.activate"], ["conc"], "CAS on expected digest; multi-process deployment requires external CAS store"),
    59: ("PASS", ["store.py::CatalogueStore.emergency_disable"], ["act", "integ"], ""),
    60: ("PASS", ["tests/test_store.py"], ["fault"], ""),
    61: ("PASS", ["conformance/performance/bench.py", "evidence/benchmarks/"], ["perf"], "baseline from one Linux x86_64 host; pinned host profile BLOCKED on owner hardware"),
    62: ("BLOCKED", ["conformance/performance/thresholds.json"], ["perf"], "thresholds proposed; " + APPROVAL),
    63: ("PASS", ["conformance/performance/bench.py"], ["perf", "conc"], "steady/burst/max-catalogue measured; fleet scale-out is peer-owned"),
    64: ("PASS", ["conformance/performance/bench.py"], ["perf"], ""),
    65: ("PASS", ["docs/requirements.md"], [], ""),
    66: ("NOT_APPLICABLE", [], [], "control-plane catalogue; kernel-bypass/zero-copy belong to INV-35 datapath"),
    67: ("PASS", ["docs/limits.md"], ["lim"], ""),
    68: ("NOT_APPLICABLE", [], [], "no edge-node deployment of the catalogue service declared"),
    69: ("PASS", ["docs/limits.md", "store.py::CatalogueStore.signals"], ["act"], ""),
    70: ("BLOCKED", [".github/workflows/ci.yml", "conformance/performance/bench.py"], ["perf"], "enforced in CI once thresholds are approved (item 62)"),
    71: ("PASS", ["store.py::CatalogueStore.health"], ["act"], ""),
    72: ("PASS", ["store.py::CatalogueStore.signals"], ["act"], ""),
    73: ("PASS", ["audit.py::AuditLog.emit", "docs/telemetry-policy.md"], ["aud"], ""),
    74: ("PASS", ["store.py", "conformance/integration/peer_contracts.py"], ["integ"], "correlation_id propagated through store, audit and runtime fixture; W3C trace export owned by host service"),
    75: ("PASS", ["errors.py::_redact"], ["err"], ""),
    76: ("PASS", ["store.py::CatalogueStore._record"], ["act"], ""),
    77: ("PASS", ["store.py::CatalogueStore.explain"], ["act"], ""),
    78: ("PASS", ["schemas/PK_DEVICE_CONFIG_ACTIVATION_1.schema.json"], ["act"], "source_revision/build_id recorded; live infrastructure graph is external"),
    79: ("PASS", ["docs/telemetry-policy.md"], [], ""),
    80: ("BLOCKED", ["docs/telemetry-policy.md"], [], "dashboard/alert definitions provided; deployment to the owner's monitoring stack not possible here"),
    81: ("PASS", ["tests/"], ["model", "act"], ""),
    82: ("PASS", ["schemas/"], ["schema", "err"], ""),
    83: ("EXTERNAL", ["conformance/integration/peer_contracts.py"], ["integ"], "same as C030"),
    84: ("BLOCKED", ["docs/compatibility.md"], ["compat"], "only linux/x86_64 CPython exercised; arm64/hypervisor cells need owner hardware"),
    85: ("PASS", ["tests/test_fuzz.py", "conformance/fuzz/regressions.json"], ["fuzz"], ""),
    86: ("PASS", ["docs/concurrency.md"], ["conc"], ""),
    87: ("PASS", ["docs/threat-model.md"], ["authn", "authz", "prov", "fuzz"], ""),
    88: ("PASS", ["conformance/performance/bench.py"], ["perf"], "soak/fleet-scale runs are scheduled jobs"),
    89: ("PASS", ["tests/test_store.py"], ["fault", "integ"], ""),
    90: ("BLOCKED", ["docs/acceptance-policy.md", "tools/gate.py"], ["rtm"], PK),
    91: ("PASS", ["contract.py::build.slos", "SUPPORT.md"], [], ""),
    92: ("PASS", ["docs/rollout.md", "store.py::CatalogueStore.emergency_disable"], ["act", "integ"], ""),
    93: ("PASS", ["docs/compatibility.md", "compat.py::MATRIX"], ["compat"], ""),
    94: ("PASS", ["SECURITY.md", "docs/vulnerability-eol.md"], ["gov"], ""),
    95: ("PASS", ["docs/runbooks.md", "store.py::CatalogueStore._load"], ["fault"], ""),
    96: ("PASS", ["docs/runbooks.md"], [], ""),
    97: ("BLOCKED", ["docs/incident-response.md"], [], "paging targets/on-call rota " + APPROVAL),
    98: ("BLOCKED", ["governance/reviews.json", "docs/recurring-review.md"], ["gov"], "cadence and register defined; first review must be held and recorded by the owner"),
    99: ("PASS", ["governance/waivers.json"], ["gov"], ""),
    100: ("BLOCKED", ["docs/acceptance-policy.md", "tools/gate.py"], ["rtm"], PK + "; approvals and signing key not available"),
}
