"""Release certification gate and RTM renderer (C020, C070, C090, C100).

    python -m inv52_messaging_abstraction gate [--out FILE] [--skip-tests] [--skip-bench] [--require-go]
    python -m inv52_messaging_abstraction rtm

The gate fails closed: any check that errors, is skipped, or cannot find its
evidence counts as not-PASS.  A production ``GO`` additionally needs every
owner role assigned, every requirement IMPLEMENTED (or covered by an approved,
unexpired waiver with a named owner) and a recorded independent approval.  The
build tooling can never supply that approval for itself.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import pathlib
import re
import subprocess
import sys
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parent
REQS = ROOT / "governance" / "requirements.json"
TEST_DIR = ROOT / "tests"
SELF_IDENTITIES = {"claude", "gate", "builder", "ci", "automation", "unassigned", ""}


def _load(p: pathlib.Path) -> Any:
    return json.loads(p.read_text(encoding="utf-8"))


def _test_index() -> set[str]:
    names = set()
    for f in TEST_DIR.glob("test_*.py"):
        for m in re.finditer(r"def (test_[A-Za-z0-9_]+)", f.read_text(encoding="utf-8")):
            names.add(f"{f.name}::{m.group(1)}")
    return names


def check_rtm() -> dict[str, Any]:
    data = _load(REQS)
    tests = _test_index()
    problems, counts = [], {}
    for r in data["requirements"]:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
        if r["status"] not in data["status_vocabulary"]:
            problems.append(f"{r['id']}: unknown status {r['status']}")
        for p in r.get("artifacts", []):
            if p.startswith("evidence/"):
                continue  # generated by the gate/bench/cleanroom run itself; checked by those checks
            if not (ROOT / p.split("::")[0]).exists():
                problems.append(f"{r['id']}: artifact {p} missing")
        for t in r.get("tests", []):
            if t not in tests:
                problems.append(f"{r['id']}: test {t} not found")
        if r["status"] != "BLOCKED" and not r.get("tests") and not r.get("artifacts"):
            problems.append(f"{r['id']}: no evidence linked")
        if r["status"] == "BLOCKED" and not r.get("blockers"):
            problems.append(f"{r['id']}: BLOCKED without a named blocker")
    return {"check": "rtm", "result": "PASS" if not problems else "FAIL", "problems": problems,
            "status_counts": counts, "total": len(data["requirements"])}


def render_rtm() -> str:
    data = _load(REQS)
    lines = ["# INV-52 Requirements Traceability Matrix", "",
             f"Generated from `governance/requirements.json` ({len(data['requirements'])} rows). Status vocabulary:", ""]
    for k, v in data["status_vocabulary"].items():
        lines.append(f"* **{k}** — {v}")
    lines += ["", "| ID | Was | Status | Artifacts | Tests | Blockers / waivers |", "|---|---|---|---|---|---|"]
    for r in data["requirements"]:
        lines.append("| {id} | {was} | {st} | {a} | {t} | {b} |".format(
            id=r["id"], was=r.get("was", ""), st=r["status"],
            a="<br>".join(f"`{x}`" for x in r.get("artifacts", [])),
            t="<br>".join(f"`{x}`" for x in r.get("tests", [])),
            b="<br>".join(r.get("blockers", []) + [f"waiver {w}" for w in r.get("waivers", [])])))
    return "\n".join(lines) + "\n"


def _run(args: list[str], cwd: pathlib.Path, timeout: int = 900) -> dict[str, Any]:
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
    try:
        p = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=timeout, env=env)
        return {"argv": args, "exit": p.returncode, "stdout_tail": p.stdout[-2000:], "stderr_tail": p.stderr[-4000:]}
    except Exception as exc:  # noqa: BLE001
        return {"argv": args, "exit": None, "error": repr(exc)}


def check_tests() -> dict[str, Any]:
    r = _run([sys.executable, "-B", "-m", "unittest", "discover", "-s", f"{ROOT.name}/tests", "-p", "test_*.py"],
             ROOT.parent)
    m = re.search(r"Ran (\d+) tests", r.get("stderr_tail", ""))
    sk = re.search(r"skipped=(\d+)", r.get("stderr_tail", ""))
    return {"check": "tests", "result": "PASS" if r.get("exit") == 0 else "FAIL",
            "ran": int(m.group(1)) if m else None, "skipped": int(sk.group(1)) if sk else 0, "run": r,
            "note": "skipped tests are the pk_core adapter tests (external dependency) and are reported, not passed"}


def check_integrity() -> dict[str, Any]:
    r = _run([sys.executable, "-B", str(ROOT / "verify_integrity.py")], ROOT)
    return {"check": "integrity", "result": "PASS" if r.get("exit") == 0 else "FAIL", "run": r}


def check_perf() -> dict[str, Any]:
    out = ROOT / "evidence" / "perf_gate.json"
    r = _run([sys.executable, "-B", "-m", f"{ROOT.name}.bench", "--quick", "--out", str(out),
              "--check", str(ROOT / "perf" / "baseline.json")], ROOT.parent)
    baseline = _load(ROOT / "perf" / "baseline.json")
    res = "PASS" if r.get("exit") == 0 else "FAIL"
    return {"check": "performance", "result": res, "thresholds_status": baseline["status"], "run": r,
            "evidence": "evidence/perf_gate.json"}


def check_governance(today: dt.date) -> dict[str, Any]:
    owners = _load(ROOT / "governance" / "owners.json")
    unassigned = sorted(k for k, v in owners["roles"].items() if not v or v.strip().upper() == "UNASSIGNED")
    waivers = _load(ROOT / "governance" / "waivers.json")["waivers"]
    expired = [w["id"] for w in waivers if dt.date.fromisoformat(w["expires"]) < today]
    ownerless = [w["id"] for w in waivers if w["owner"].upper() == "UNASSIGNED"]
    approvals_file = ROOT / "governance" / "approvals.json"
    approvals = _load(approvals_file)["approvals"] if approvals_file.exists() else []
    valid = [a for a in approvals if a.get("approver", "").strip().lower() not in SELF_IDENTITIES
             and a.get("decision") == "APPROVE"]
    problems = []
    if unassigned:
        problems.append("owner roles UNASSIGNED: " + ", ".join(unassigned))
    if expired:
        problems.append("expired waivers: " + ", ".join(expired))
    if ownerless:
        problems.append("waivers without an accountable owner: " + ", ".join(ownerless))
    if not valid:
        problems.append("no independent human approval recorded in governance/approvals.json")
    return {"check": "governance", "result": "PASS" if not problems else "BLOCKED", "problems": problems}


def gate(skip_tests: bool = False, skip_bench: bool = False) -> dict[str, Any]:
    today = dt.date.today()
    checks = [check_rtm()]
    checks.append(check_tests() if not skip_tests else {"check": "tests", "result": "NOT_RUN"})
    checks.append(check_integrity())
    checks.append(check_perf() if not skip_bench else {"check": "performance", "result": "NOT_RUN"})
    checks.append(check_governance(today))
    reqs = _load(REQS)["requirements"]
    not_done = [r["id"] for r in reqs if r["status"] != "IMPLEMENTED"]
    engineering_ok = all(c["result"] == "PASS" for c in checks if c["check"] != "governance")
    production = "GO" if engineering_ok and not not_done and checks[-1]["result"] == "PASS" else "NO_GO"
    why = []
    if not engineering_ok:
        why.append("an engineering check did not PASS (NOT_RUN counts as not-PASS)")
    if not_done:
        why.append(f"{len(not_done)} requirements are not IMPLEMENTED (checklist definition requires owner "
                   "approval and deployed evidence)")
    if checks[-1]["result"] != "PASS":
        why.extend(checks[-1]["problems"])
    version = (ROOT / "VERSION").read_text().strip()
    manifest = (ROOT / "CHECKSUMS.sha256")
    return {
        "schema": "INV52_RELEASE_CERTIFICATION/1",
        "component": "INV-52", "version": version, "generated_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "python": sys.version.split()[0], "platform": sys.platform,
        "manifest_sha256": hashlib.sha256(manifest.read_bytes()).hexdigest() if manifest.exists() else None,
        "checks": checks, "engineering_verdict": "PASS" if engineering_ok else "FAIL",
        "production_verdict": production, "production_blockers": why,
        "requirements_not_implemented": not_done,
    }


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(prog="gate")
    ap.add_argument("--out", default=str(ROOT / "evidence" / "release_certification.json"))
    ap.add_argument("--skip-tests", action="store_true")
    ap.add_argument("--skip-bench", action="store_true")
    ap.add_argument("--require-go", action="store_true")
    a = ap.parse_args(argv)
    res = gate(a.skip_tests, a.skip_bench)
    pathlib.Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(a.out).write_text(json.dumps(res, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({k: res[k] for k in ("engineering_verdict", "production_verdict", "production_blockers")}, indent=2))
    if res["engineering_verdict"] != "PASS":
        return 1
    return 0 if (res["production_verdict"] == "GO" or not a.require_go) else 3


if __name__ == "__main__":
    raise SystemExit(main())
