"""Source of the INV-63 requirement/traceability catalogue (INV-63-C011, C020).

Each entry: C-ID -> (SHALL statement, implementation refs, design docs, external evidence keys).
tools/gen_docs.py renders docs/requirements/REQUIREMENTS.json + REQUIREMENTS.md;
audit.py joins it with test tags and approvals to compute status.
External evidence keys are defined in governance/EXTERNAL_EVIDENCE.json.
"""
A = "docs/architecture/"
R = {
"C001": ("The manager SHALL own desired-state storage, diff computation, spread, convergence and bounded rollouts only.", ["contract.py::build", "service.py::DeploymentService"], [A+"ADR-0001-wadm-deployment-manager.md"], []),
"C002": ("The manager SHALL NOT define manifests, run components, sign artifacts or provision hosts.", ["contract.py::build"], [A+"BOUNDARIES.md"], []),
"C003": ("Upstream INV-64, downstream INV-60/INV-66 and peer GAP-08 dependencies SHALL be declared.", ["contract.py::build", "docs/interfaces/BOUNDARIES.json"], [A+"BOUNDARIES.md"], []),
"C004": ("The journaled desired-state record SHALL be the source of truth; lattice state is observed and corrected.", ["store.py::Journal", "service.py::_observe"], [A+"ADR-0001-wadm-deployment-manager.md"], []),
"C005": ("Every node/runtime/network/storage/control-plane assumption SHALL be catalogued and, where feasible, checked at startup.", ["preflight.py::run", "service.py::status"], [A+"ASSUMPTIONS.md"], ["arch-review"]),
"C006": ("Tenant, environment, site and workload boundaries SHALL be enforced.", ["security.py::namespace", "config.py::load_layers"], [A+"BOUNDARIES.md"], []),
"C007": ("Mandatory vs optional behaviour SHALL be declared.", ["contract.py::build"], ["README.md"], []),
"C008": ("Non-goals SHALL be declared.", ["contract.py::build"], ["README.md"], []),
"C009": ("An accountable owner, on-call rotation, security contact, release approver and escalation path SHALL be recorded and validated.", ["OWNERS.yaml", "CODEOWNERS", "gate.py::check_owners"], ["ops/runbooks/INCIDENT.md"], ["owner-assignment", "arch-review"]),
"C010": ("An approved ADR SHALL record Wadm selection, role, alternatives, boundaries, data ownership, failure model and acceptance criteria.", [A+"ADR-0001-wadm-deployment-manager.md"], [A+"ADR-0001-wadm-deployment-manager.md"], ["arch-review"]),
"C011": ("Desired-state reconciliation SHALL be specified as testable SHALL requirements (this catalogue).", ["docs/requirements/REQUIREMENTS.json"], ["docs/requirements/REQUIREMENTS.md"], []),
"C012": ("Functional behaviour SHALL be defined per tier: cloud, datacenter, near-edge and far-edge (offline autonomy, constrained limits).", ["config.py::validate", "deploy/config/site/edge-site-a.json", "service.py::reconcile_ns"], ["docs/requirements/REQUIREMENTS.md"], []),
"C013": ("Latency, availability, durability, consistency, isolation and determinism SHALL have numeric NFRs verified by tests/benchmarks.", ["perf/thresholds.json", "perf/bench.py", "store.py::Journal.append"], ["docs/requirements/NFR.md"], ["perf-approval"]),
"C014": ("Every response SHALL carry one of SUCCESS, PARTIAL, DEGRADED, RETRYABLE, TERMINAL with defined semantics.", ["errors.py::Outcome", "service.py::handle"], ["docs/requirements/NFR.md"], []),
"C015": ("Lifecycle states and legal transitions SHALL be defined and illegal transitions rejected.", ["lifecycle.py::TRANSITIONS", "lifecycle.py::Lifecycle"], [A+"LIFECYCLE.md"], []),
"C016": ("Contracts SHALL be semver'd by schema major; minors additive; deprecations dated; the legacy Manager API preserved.", ["schema.py::SUPPORTED", "schema.py::DEPRECATED"], ["docs/interfaces/VERSIONING.md"], []),
"C017": ("Per-tenant instance quotas, request-rate fairness and global capacity ceilings SHALL be enforced.", ["resilience.py::Admission", "service.py::op_set_desired"], ["docs/interfaces/LIMITS.md"], []),
"C018": ("With intermittent/absent connectivity the manager SHALL journal intents, report DEGRADED within the autonomy window, fail RETRYABLE beyond it, and resynchronise on reconnect.", ["service.py::reconcile_ns", "service.py::resync"], ["docs/requirements/NFR.md"], []),
"C019": ("Conflicts SHALL resolve in precedence security > residency > consistency > SLO > cost.", ["service.py::PRECEDENCE", "service.py::_eligible"], ["docs/requirements/PRECEDENCE.md"], []),
"C020": ("A traceability matrix requirement->design->implementation->test->evidence->owner SHALL be generated per release.", ["audit.py::write_docs"], ["docs/requirements/TRACEABILITY.md"], []),
"C021": ("Every exposed boundary SHALL be inventoried with contract, authN, authZ, timeout, limits and owner.", ["docs/interfaces/BOUNDARIES.json"], [A+"BOUNDARIES.md"], []),
"C022": ("Every external contract SHALL have a versioned JSON schema validated at the boundary.", ["schema.py::validate", "schemas/"], ["docs/interfaces/VERSIONING.md"], []),
"C023": ("Every inbound boundary SHALL authenticate callers (signed, expiring, replay-protected tokens).", ["security.py::TokenAuthority"], [A+"THREAT_MODEL.md"], []),
"C024": ("Every operation SHALL require an explicit capability, scoped to the caller's tenant.", ["security.py::Authorizer", "security.py::OP_CAPABILITY"], [A+"THREAT_MODEL.md"], []),
"C025": ("Timeouts, cancellation, retries (idempotent only), idempotency keys and backpressure SHALL be defined and enforced.", ["resilience.py::Deadline", "resilience.py::RetryPolicy", "service.py::handle"], ["docs/interfaces/LIMITS.md"], []),
"C026": ("Every failure SHALL be a stable code with retryability and machine-readable details.", ["errors.py::ErrorCode", "errors.py::DeploymentError"], ["docs/interfaces/ERROR_CODES.md"], []),
"C027": ("Peers SHALL negotiate the highest common schema major and fail closed when none exists.", ["schema.py::negotiate"], ["docs/interfaces/VERSIONING.md"], []),
"C028": ("Payload, depth, concurrency, queue, rate and size limits SHALL be documented and enforced.", ["schema.py::MAX_PAYLOAD_BYTES", "resilience.py::Admission"], ["docs/interfaces/LIMITS.md"], []),
"C029": ("Reference examples and digest-bound conformance fixtures SHALL ship with the package.", ["fixtures/FIXTURES.json", "tools/gen_fixtures.py"], ["docs/interfaces/VERSIONING.md"], []),
"C030": ("Automated tests SHALL prove interoperation with INV-64 (desired input), INV-60 (lattice) and INV-66 (controller).", ["adapter.py::InMemoryLattice", "adapter.py::WadmAdapter"], [A+"BOUNDARIES.md"], ["wadm-live"]),
"C031": ("Wadm and all runtime dependencies SHALL be pinned by version and digest and approved.", ["pins.json", "requirements.lock"], [A+"ADR-0001-wadm-deployment-manager.md"], ["wadm-pin"]),
"C032": ("Immutable package, mutable config and mutable state SHALL be physically separate.", ["store.py::Journal", "config.py::load_layers"], [A+"STATE_AND_CONFIG.md"], []),
"C033": ("Configuration SHALL be declarative with secure defaults (prod profile by default).", ["config.py::SECURE_DEFAULTS"], [A+"STATE_AND_CONFIG.md"], []),
"C034": ("Configuration SHALL be validated before activation and fail closed on security-critical errors.", ["config.py::validate"], [A+"STATE_AND_CONFIG.md"], []),
"C035": ("Site/environment overlays SHALL change behaviour without rebuilding the package.", ["config.py::load_layers", "deploy/config/"], [A+"STATE_AND_CONFIG.md"], []),
"C036": ("Each activation SHALL record version, digest, author, time, reason and previous digest.", ["config.py::ConfigStore.activate"], [A+"STATE_AND_CONFIG.md"], []),
"C037": ("Configuration activation SHALL be atomic (all-or-nothing).", ["config.py::ConfigStore.activate"], [A+"STATE_AND_CONFIG.md"], []),
"C038": ("Failed rollouts SHALL auto-rollback; operators SHALL be able to roll back workloads and configuration.", ["service.py::_rollback", "service.py::op_rollback", "config.py::ConfigStore.rollback"], ["ops/runbooks/CANARY_ROLLBACK.md"], []),
"C039": ("Secrets SHALL appear only as refs (env:/file:) and SHALL be redacted from logs, traces and errors.", ["security.py::redact", "config.py::_scan_secrets"], [A+"THREAT_MODEL.md"], []),
"C040": ("Bootstrap from an empty node SHALL be deterministic and gated by preflight.", ["preflight.py::run", "tools/bootstrap.py"], ["ops/runbooks/DAY0_BOOTSTRAP.md"], []),
"C041": ("A STRIDE threat model SHALL cover tenants, workloads, inputs, supply chain, control plane and insiders, each threat mapped to controls and tests.", [A+"THREAT_MODEL.md"], [A+"THREAT_MODEL.md"], ["security-review"]),
"C042": ("Each role SHALL hold the minimum capability set; platform principals SHALL NOT mutate tenant workloads.", ["security.py::ROLES", "security.py::Authorizer"], [A+"THREAT_MODEL.md"], []),
"C043": ("The service SHALL use only injected handles (adapter, journal dir); no ambient FS/network/device/secret authority.", ["service.py::DeploymentService.__init__"], [A+"THREAT_MODEL.md"], []),
"C044": ("Nodes, peers, artifacts, providers and controllers SHALL be authenticated before trust.", ["security.py::TokenAuthority", "security.py::ArtifactVerifier"], [A+"THREAT_MODEL.md"], ["node-attestation"]),
"C045": ("Artifacts SHALL be verified by digest, Ed25519 signature from a trusted key id, approved version and revocation list before deploy or rollout.", ["security.py::ArtifactVerifier"], [A+"THREAT_MODEL.md"], []),
"C046": ("Tenant state, identifiers, quotas and placement SHALL be isolated.", ["security.py::namespace", "security.py::Authorizer"], [A+"THREAT_MODEL.md"], []),
"C047": ("Sensitive state SHALL be encrypted at rest (AES-256-GCM) with key ids and rotation; transit SHALL use the transport's TLS/mTLS.", ["security.py::Sealer", "store.py::Journal"], [A+"THREAT_MODEL.md"], ["kms"]),
"C048": ("When identity, key, verifier or time services are unavailable the manager SHALL fail closed.", ["security.py::_require_crypto", "service.py::op_set_desired", "preflight.py::run"], [A+"FAILURE_MATRIX.md"], []),
"C049": ("Security-sensitive operations SHALL emit hash-chained, fsync'd audit records; tampering SHALL be detected at load.", ["store.py::Journal"], [A+"THREAT_MODEL.md"], ["external-anchor"]),
"C050": ("Adversarial tests SHALL cover escalation, injection, replay, spoofing, escape and exhaustion.", ["tests/test_security.py"], [A+"THREAT_MODEL.md"], []),
"C051": ("Component/process/node/site/network/provider/dependency/control-plane failures SHALL be enumerated with detection and response.", [A+"FAILURE_MATRIX.md"], [A+"FAILURE_MATRIX.md"], []),
"C052": ("Health and stall thresholds SHALL be defined and detected automatically.", ["resilience.py::HealthMonitor", "service.py::tick"], [A+"FAILURE_MATRIX.md"], []),
"C053": ("Retries SHALL be bounded, jittered and limited to idempotent operations and retryable errors.", ["resilience.py::RetryPolicy"], [A+"FAILURE_MATRIX.md"], []),
"C054": ("Admission control, priority shedding and circuit breaking SHALL prevent cascades.", ["resilience.py::Admission", "resilience.py::CircuitBreaker"], [A+"FAILURE_MATRIX.md"], []),
"C055": ("Failover SHALL NOT violate isolation, residency or consistency (fenced leader; residency-constrained placement).", ["store.py::Journal.acquire", "service.py::_eligible"], [A+"FAILURE_MATRIX.md"], []),
"C056": ("Non-critical dependency loss SHALL degrade (not fail) the service.", ["service.py::reconcile_ns"], [A+"FAILURE_MATRIX.md"], []),
"C057": ("State SHALL be crash-consistent; restart SHALL replay the journal and truncate only torn tails.", ["store.py::Journal._load", "service.py::_recover"], [A+"STATE_AND_CONFIG.md"], []),
"C058": ("Stale controllers SHALL be fenced by epoch; concurrent writers SHALL be detected.", ["store.py::Journal.append"], [A+"FAILURE_MATRIX.md"], ["consensus-lease"]),
"C059": ("Operators SHALL be able to freeze, quarantine (workload/tenant/host) and emergency-disable automation.", ["resilience.py::Controls", "service.py::emergency_disable", "service.py::quarantine_host"], ["ops/runbooks/INCIDENT.md"], []),
"C060": ("Fault-injection tests SHALL prove recovery objectives.", ["adapter.py::InMemoryLattice"], [A+"FAILURE_MATRIX.md"], []),
"C061": ("Reproducible baselines SHALL be recorded for latency, throughput, startup, memory and storage.", ["perf/bench.py", "perf/results.json"], ["docs/requirements/NFR.md"], ["perf-approval"]),
"C062": ("p50/p95/p99/max thresholds SHALL be defined.", ["perf/thresholds.json"], ["docs/requirements/NFR.md"], ["perf-approval"]),
"C063": ("Steady, burst, overload, scale-out, scale-in and recovery SHALL be measured.", ["perf/bench.py"], ["docs/requirements/NFR.md"], []),
"C064": ("Per-tenant and per-workload overhead SHALL be measured.", ["perf/bench.py::per_tenant_overhead"], ["docs/requirements/NFR.md"], []),
"C065": ("Avoidable serialization, copies and duplicated state SHALL be identified.", ["docs/requirements/PERF_ANALYSIS.md"], ["docs/requirements/PERF_ANALYSIS.md"], []),
"C066": ("Safe optimizations SHALL be applied with semantic-equivalence proof.", ["manager.py::Manager.diff"], ["docs/requirements/PERF_ANALYSIS.md"], []),
"C067": ("Memory, queues, buffers, concurrency and fan-out SHALL be bounded.", ["observability.py::Metrics", "resilience.py::Admission", "store.py::Journal.max_bytes"], ["docs/interfaces/LIMITS.md"], []),
"C068": ("Power and thermal impact SHALL be measured on constrained edge nodes.", ["perf/EDGE_POWER_PLAN.md"], ["perf/EDGE_POWER_PLAN.md"], ["edge-hardware"]),
"C069": ("A capacity model and saturation signals SHALL predict resource needs.", ["docs/requirements/CAPACITY_MODEL.md", "observability/alerts.json"], ["docs/requirements/CAPACITY_MODEL.md"], []),
"C070": ("Releases SHALL be blocked when performance regresses beyond approved thresholds.", ["perf/bench.py::gate", "gate.py"], ["docs/requirements/NFR.md"], ["perf-approval"]),
"C071": ("Health, readiness, version, config digest, dependency status and capabilities SHALL be exposed.", ["service.py::status"], ["ops/runbooks/DAY2_OPERATIONS.md"], []),
"C072": ("RED/USE metrics SHALL be emitted in Prometheus format.", ["observability.py::Metrics"], ["observability/dashboard.json"], []),
"C073": ("Logs SHALL be structured with node, tenant, workload, component, operation and trace ids.", ["observability.py::Logger"], ["docs/requirements/TELEMETRY_POLICY.md"], []),
"C074": ("W3C trace context SHALL propagate across request, decision and adapter boundaries.", ["observability.py::SpanContext", "observability.py::Tracer"], ["docs/requirements/TELEMETRY_POLICY.md"], []),
"C075": ("Diagnostics SHALL be cardinality-bounded, redacted and tenant-pseudonymised when exported.", ["observability.py::MAX_LABEL_SETS", "observability.py::tenant_hash", "security.py::redact"], ["docs/requirements/TELEMETRY_POLICY.md"], []),
"C076": ("Every automated decision SHALL record its reason, inputs, policies and constraints.", ["observability.py::DecisionLog", "service.py::_decide"], ["docs/requirements/TELEMETRY_POLICY.md"], []),
"C077": ("An explain view SHALL link decisions to inputs, policies, topology and constraints.", ["observability.py::DecisionLog.explain", "service.py::op_explain"], ["ops/runbooks/DAY2_OPERATIONS.md"], []),
"C078": ("Decisions SHALL carry release lineage and a topology digest.", ["service.py::_decide", "observability.py::topology_digest"], ["docs/requirements/TELEMETRY_POLICY.md"], []),
"C079": ("Telemetry retention, sampling, privacy and export SHALL be defined.", ["docs/requirements/TELEMETRY_POLICY.md", "config.py::SECURE_DEFAULTS"], ["docs/requirements/TELEMETRY_POLICY.md"], ["privacy-review"]),
"C080": ("Dashboards and alerts SHALL distinguish load, degradation, policy rejection, dependency failure, security events and stalls.", ["observability/alerts.json", "observability/dashboard.json", "observability.py::classify_alert"], ["observability/alerts.json"], []),
"C081": ("Unit tests SHALL cover core logic.", ["tests/test_manager.py"], ["README.md"], []),
"C082": ("Every public interface SHALL have contract tests.", ["tests/test_contracts.py"], ["docs/interfaces/VERSIONING.md"], []),
"C083": ("Integration tests SHALL exercise every adjacent layer and execution tier.", ["tests/test_service.py"], [A+"BOUNDARIES.md"], ["wadm-live"]),
"C084": ("Compatibility SHALL be tested across CPU architectures, runtimes, providers and protocol versions.", ["tests/test_contracts.py", ".github/workflows/ci.yml"], ["governance/COMPATIBILITY_MATRIX.md"], ["multi-arch-ci", "wadm-live"]),
"C085": ("Parsers, schemas and untrusted inputs SHALL be fuzzed.", ["tests/test_contracts.py::FuzzTest"], [A+"THREAT_MODEL.md"], []),
"C086": ("Concurrency and race tests SHALL cover shared/distributed state.", ["tests/test_platform.py::ConcurrencyTest"], [A+"FAILURE_MATRIX.md"], []),
"C087": ("Security tests SHALL derive directly from the threat model.", ["tests/test_security.py"], [A+"THREAT_MODEL.md"], []),
"C088": ("Benchmark, soak, burst and fleet-scale tests SHALL exist.", ["perf/bench.py"], ["docs/requirements/NFR.md"], ["fleet-scale"]),
"C089": ("Disaster, partition, reconnect and degraded-control-plane tests SHALL exist.", ["tests/test_service.py"], [A+"FAILURE_MATRIX.md"], []),
"C090": ("Machine-readable, signed acceptance evidence SHALL be required before production certification.", ["audit.py", "gate.py"], ["release/GATE_POLICY.json"], ["signing-key", "pk_core"]),
"C091": ("Production SLOs, error budgets and support commitments SHALL be defined.", ["governance/SLO.md", "contract.py::build"], ["governance/SLO.md"], ["owner-assignment"]),
"C092": ("Canary, staged rollout, rollback and emergency-disable procedures SHALL be defined and exercised.", ["service.py::op_rollout", "service.py::emergency_disable"], ["ops/runbooks/CANARY_ROLLBACK.md"], ["game-day"]),
"C093": ("A supported-version compatibility matrix SHALL be maintained.", ["governance/COMPATIBILITY_MATRIX.md"], ["governance/COMPATIBILITY_MATRIX.md"], []),
"C094": ("Patching, vulnerability response and EOL SLAs SHALL be defined.", ["governance/VULN_AND_EOL_POLICY.md"], ["governance/VULN_AND_EOL_POLICY.md"], ["owner-assignment"]),
"C095": ("Backup, restore, migration and reconstruction procedures SHALL exist and be tested.", ["store.py::Journal.backup", "store.py::Journal.restore"], ["ops/runbooks/BACKUP_RESTORE.md"], ["game-day"]),
"C096": ("Day-0/1/2 runbooks SHALL exist.", ["ops/runbooks/DAY0_BOOTSTRAP.md", "ops/runbooks/DAY1_DEPLOY.md", "ops/runbooks/DAY2_OPERATIONS.md"], ["ops/runbooks/"], ["game-day"]),
"C097": ("Incident severity, paging, escalation, containment and recovery SHALL be defined.", ["ops/runbooks/INCIDENT.md"], ["ops/runbooks/INCIDENT.md"], ["owner-assignment", "game-day"]),
"C098": ("Access, policy, dependency, configuration and architecture reviews SHALL recur on a schedule enforced by the gate.", ["governance/REVIEWS.json", "gate.py::check_reviews"], ["governance/REVIEWS.json"], ["review-records"]),
"C099": ("Exceptions, waivers, debt and deprecations SHALL be tracked with owners and expiry, and expired waivers SHALL block release.", ["governance/WAIVERS.json", "gate.py::check_waivers"], ["governance/WAIVERS.json"], []),
"C100": ("A single signed production exit gate SHALL consume all evidence bound to the exact artifact/config/dependencies.", ["gate.py::evaluate"], ["release/GATE_POLICY.json"], ["signing-key", "pk_core", "owner-assignment"]),
}
