"""M42 - validate traceability/rtm.json and render docs/TRACEABILITY.md.

    python tools/rtm.py            # regenerate docs/TRACEABILITY.md
    python tools/rtm.py --check    # CI: fail on drift, unknown controls, missing files, bad status
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
STATUSES = ("PRESENT", "PARTIAL", "BLOCKED")


def load() -> dict:
    return json.loads((ROOT / "traceability" / "rtm.json").read_text(encoding="utf-8"))


def problems(rtm: dict) -> list[str]:
    out = []
    checklist = {i["check_id"] for i in json.loads((ROOT / "CHECKLIST.json").read_text())["items"]}
    ids = [i["id"] for i in rtm["items"]]
    if ids != [f"M{n:02d}" for n in range(1, 49)]:
        out.append("RTM must list M01..M48 exactly once, in order")
    for item in rtm["items"]:
        if not item["controls"] and not item.get("control_note"):
            out.append(f"{item['id']}: no controls")
        if item["status"] not in STATUSES:
            out.append(f"{item['id']}: bad status {item['status']}")
        if item["status"] != "PRESENT" and not item["residual"]:
            out.append(f"{item['id']}: non-PRESENT item needs a residual explanation")
        for c in item["controls"]:
            if c not in checklist:
                out.append(f"{item['id']}: unknown control {c}")
        for f in item["implementation"] + item["tests"]:
            if not (ROOT / f).exists():
                out.append(f"{item['id']}: missing file {f}")
    master = (ROOT / "MASTER.md").read_text(encoding="utf-8")
    for c in re.findall(r"PLN-04-C\d{3}", master):
        if c not in checklist:
            out.append(f"MASTER.md references unknown control {c}")
    return out


def render(rtm: dict) -> str:
    counts = {s: sum(1 for i in rtm["items"] if i["status"] == s) for s in STATUSES}
    lines = ["# PLN-04 4.3.0 — requirements traceability (M01–M48)", "",
             "Generated by `tools/rtm.py` from `traceability/rtm.json`; do not edit by hand.", "",
             f"Owner: **{rtm['owner']}**. Totals: " + ", ".join(f"{k} {v}" for k, v in counts.items()) + ".", ""]
    for k, v in rtm["status_vocabulary"].items():
        lines.append(f"- **{k}**: {v}")
    lines += ["", "| M | Component | Priority | Controls | Status | Implementation | Tests | Residual / blocker |",
              "|---|---|---|---|---|---|---|---|"]
    for i in rtm["items"]:
        lines.append(f"| {i['id']} | {i['title'].replace('|', '/')} | {i['priority']} | {', '.join(c[-4:] for c in i['controls']) or i.get('control_note', '')} | "
                     f"{i['status']} | {', '.join('`'+f+'`' for f in i['implementation'])} | "
                     f"{', '.join('`'+f+'`' for f in i['tests'])} | {i['residual'] or '—'} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    rtm = load()
    errs = problems(rtm)
    target = ROOT / "docs" / "TRACEABILITY.md"
    if "--check" in sys.argv:
        if target.read_text(encoding="utf-8") != render(rtm):
            errs.append("docs/TRACEABILITY.md is stale; run tools/rtm.py")
        print("\n".join(errs) or "RTM OK")
        sys.exit(1 if errs else 0)
    target.write_text(render(rtm), encoding="utf-8")
    print("\n".join(errs) or "RTM OK")
