"""Generate and verify the requirements traceability matrix (MC-004). Exit 1 on any dangling link."""
from __future__ import annotations

import ast
import sys

from _common import PKG, write_json
from inv34_legacy_cpu_expansion_path.production.requirements import REQUIREMENTS


def test_index() -> set[str]:
    ids = set()
    for f in (PKG / "tests").glob("test_*.py"):
        mod = f.stem
        for node in ast.parse(f.read_text()).body:
            if isinstance(node, ast.ClassDef):
                ids.add(f"{mod}.{node.name}")
                for m in node.body:
                    if isinstance(m, ast.FunctionDef) and m.name.startswith("test"):
                        ids.add(f"{mod}.{node.name}.{m.name}")
    return ids


def main() -> int:
    tests, rows, problems = test_index(), [], []
    for rid, text, checks, code, tlist in REQUIREMENTS:
        for c in code:
            if not (PKG / c).exists():
                problems.append(f"{rid}: missing code {c}")
        for t in tlist:
            if t not in tests:
                problems.append(f"{rid}: missing test {t}")
        rows.append({"id": rid, "shall": text, "checklist": [f"INV-34-{c}" for c in checks], "code": code,
                     "tests": tlist, "operations_evidence": "NOT_AVAILABLE (no deployment)",
                     "release_evidence": "governance/CI_RESULT.json (local)"})
    write_json("governance/RTM.json", {"schema": "INV34_RTM/1", "rows": rows, "problems": problems})
    md = ["# INV-34 Requirements Traceability Matrix (generated by tools/rtm.py)", "",
          "| Req | Checklist | Code | Tests |", "|---|---|---|---|"]
    for r in rows:
        md.append(f"| {r['id']} | {', '.join(r['checklist'])} | {'<br>'.join(r['code'])} | {'<br>'.join(r['tests'])} |")
    md += ["", "Operations evidence: not available — no deployment exists for this package."]
    (PKG / "governance/RTM.md").write_text("\n".join(md) + "\n")
    print(f"RTM: {len(rows)} requirements, {len(problems)} problems")
    for p in problems:
        print("  ", p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
