"""C020 / C061 / C070 / C080 / C090 / C099 and doc-presence governance checks.

Removing or corrupting a required artifact makes this suite fail, which makes
the release evidence verdict fail (C090 'fails when removed/invalid/tampered').
"""
import importlib
import json
import pathlib
import unittest

import yaml

import _path
ROOT = _path.ROOT
status = importlib.import_module(_path.PKG + ".tools.remediation_status")
bench = importlib.import_module(_path.PKG + ".tools.bench")
lock = importlib.import_module(_path.PKG + ".tools.check_lock")
svc = importlib.import_module(_path.PKG + ".service")

REQUIRED_DOCS = ["OWNERS.md", "docs/adr/ADR-0001-execution-technology.md", "docs/DEPLOYMENT_MATRIX.md",
                 "docs/PRECEDENCE.md", "docs/INTERFACES.md", "docs/WASM_RUNTIME.md", "docs/CONFIGURATION.md",
                 "docs/PERFORMANCE.md", "docs/OBSERVABILITY.md", "docs/COMPATIBILITY.md", "RUNBOOK.md",
                 "ops/VULNERABILITY_AND_EOL.md", "ops/REVIEWS.md", "ops/alerts.yaml", "ops/dashboard.json",
                 "EXCEPTIONS.yaml", "requirements/RTM.yaml", "requirements/wasm.lock", "perf/baseline.json",
                 "wit/inv70.wit"]


class Docs(unittest.TestCase):
    def test_required_documents_exist_and_are_substantive(self):
        for d in REQUIRED_DOCS:
            p = ROOT / d
            self.assertTrue(p.is_file(), d)
            self.assertGreater(p.stat().st_size, 200, d)

    def test_owner_named_and_escalation_present(self):
        t = (ROOT / "OWNERS.md").read_text()
        self.assertIn("Accountable owner", t)
        self.assertIn("Escalation path", t)

    def test_adr_has_decision_and_approval_block(self):
        t = (ROOT / "docs/adr/ADR-0001-execution-technology.md").read_text()
        for s in ("## Decision", "## Consequences", "## Approval", "**Status:**"):
            self.assertIn(s, t)


class RTM(unittest.TestCase):
    def test_covers_all_100_and_every_remediated_row_is_traceable(self):
        rtm = yaml.safe_load((ROOT / "requirements/RTM.yaml").read_text())
        ids = [r["id"] for r in rtm["rows"]]
        self.assertEqual(len(ids), 100)
        self.assertEqual(len(set(ids)), 100)
        by = {r["id"]: r for r in rtm["rows"]}
        for cid, (st, impl, tests, gap) in status.S.items():
            row = by[cid]
            self.assertEqual(row["status"], st, cid)
            self.assertTrue(row["implementation"], cid)
            self.assertTrue(row["owner"], cid)
            if st == "VERIFIED":
                self.assertTrue(tests, cid)
            else:
                self.assertTrue(gap, f"{cid} non-verified without a stated gap")
        self.assertNotIn("MISSING", {r["status"] for r in rtm["rows"] if r["id"] in status.S})

    def test_referenced_paths_exist(self):
        for cid, (st, impl, tests, gap) in status.S.items():
            for ref in impl + tests:
                path = ref.split("::")[0].split("#")[0].split(" ")[0]
                if path == "RELEASE_EVIDENCE.json":   # generated by tools/release_evidence.py
                    continue
                if "/" in path or path.endswith((".py", ".md", ".yaml", ".json", ".lock")):
                    self.assertTrue((ROOT / path).exists(), f"{cid}: {path}")


class Perf(unittest.TestCase):
    def test_baseline_reproducible_metadata(self):
        b = json.loads((ROOT / "perf/baseline.json").read_text())
        for k in ("inv70_version", "environment", "vm", "service_prod", "burst", "tenants", "warm_vs_cold"):
            self.assertIn(k, b)
        self.assertTrue(b["burst"]["recovered"])
        self.assertLess(b["warm_vs_cold"]["warm_hit"]["p50_us"], b["warm_vs_cold"]["cold_spawn"]["p50_us"])

    def test_gate_blocks_regressions_and_missing_baseline(self):
        b = json.loads((ROOT / "perf/baseline.json").read_text())
        self.assertEqual(bench.gate(b, b), [])
        self.assertEqual(bench.gate(b, None), ["baseline missing"])
        worse = json.loads(json.dumps(b))
        worse["vm"]["arith6"]["p50_us"] *= 2
        self.assertTrue(bench.gate(worse, b))
        other = json.loads(json.dumps(b))
        other["environment"]["machine"] = "riscv"
        self.assertTrue(bench.gate(b, other))


class Ops(unittest.TestCase):
    def test_alerts_reference_real_reason_codes(self):
        text = (ROOT / "ops/alerts.yaml").read_text()
        rules = yaml.safe_load(text)["groups"][0]["rules"]
        self.assertGreaterEqual(len(rules), 5)
        codes = {c for c, _ in svc.REASON_CODES.values()}
        for code in ("FB-C003", "FB-S022", "FB-C001"):
            self.assertIn(code, codes)
            self.assertIn(code, text)
        json.loads((ROOT / "ops/dashboard.json").read_text())

    def test_reason_codes_unique(self):
        codes = [c for c, _ in svc.REASON_CODES.values()]
        self.assertEqual(len(codes), len(set(codes)))


class Exceptions(unittest.TestCase):
    def test_register_well_formed(self):
        reg = yaml.safe_load((ROOT / "EXCEPTIONS.yaml").read_text())
        ids = set()
        for e in reg:
            for k in ("id", "type", "requirement", "reason", "owner", "opened", "expires", "status"):
                self.assertIn(k, e)
            self.assertIn(e["type"], {"waiver", "exception", "tech-debt", "deprecation"})
            self.assertNotIn(e["id"], ids)
            ids.add(e["id"])
            self.assertGreater(str(e["expires"]), str(e["opened"]))

    def test_every_blocked_item_has_register_entry(self):
        reg = yaml.safe_load((ROOT / "EXCEPTIONS.yaml").read_text())
        covered = {e["requirement"] for e in reg}
        for cid, (st, *_rest) in status.S.items():
            if st == "BLOCKED" and cid != "INV-70-C068":
                self.assertIn(cid, covered)


class Evidence(unittest.TestCase):
    def test_lock_checker_rejects_ranges_and_unset_hash(self):
        self.assertTrue(lock.problems("wasmtime>=25"))
        self.assertTrue(lock.problems("wasmtime==25.0.0 --hash=sha256:UNSET"))
        self.assertEqual(lock.problems("wasmtime==25.0.0 --hash=sha256:" + "a" * 64), [])

    def test_evidence_self_digest_detects_tamper(self):
        import hashlib
        ev = importlib.import_module(_path.PKG + ".tools.release_evidence")
        body = {"release": "x", "verdict": "NOT_ACCEPTED"}
        doc = dict(body, self_digest=hashlib.sha256(json.dumps(body, sort_keys=True).encode()).hexdigest())
        self.assertTrue(ev.verify(doc))
        doc["verdict"] = "ACCEPTED"
        self.assertFalse(ev.verify(doc))
        p = ROOT / "RELEASE_EVIDENCE.json"
        if p.exists():
            self.assertTrue(ev.verify(json.loads(p.read_text())), "RELEASE_EVIDENCE.json was modified after generation")

if __name__ == "__main__":
    unittest.main()
