"""Hand-maintained binding of the 100 checklist components to artifacts, tests and blockers.

Statuses (never COMPLETE here - completion needs a human approval the gate verifies):
  IMPLEMENTED  code/artifact present AND at least one executable test named
  DRAFTED      normative document present; needs owner review/approval, no executable behaviour
  PARTIAL      some of the component is implemented+tested; the rest needs an external dependency
  BLOCKED      cannot be produced in this repository; blocker names the missing input
"""
R = "runtime/"
T_UNIT, T_SVC, T_X, T_TOOLS = "tests/test_runtime_units.py", "tests/test_runtime_service.py", "tests/test_runtime_extra.py", "tests/test_tools.py"

M = {
 1: ("DRAFTED", ["docs/governance/OWNERSHIP.md", "CODEOWNERS", "catalog-info.yaml"], [], "no named owners (human input)"),
 2: ("DRAFTED", ["docs/architecture/ADR-0001-vault-provider.md"], [], "ADR status PROPOSED; approvers unassigned"),
 3: ("DRAFTED", ["docs/architecture/DEPLOYMENT_PATTERNS.md"], [], "far-edge unsupported (W-004); needs approval"),
 4: ("IMPLEMENTED", ["docs/requirements/REQUIREMENTS.md"], [f"{T_TOOLS}::Traceability.test_requirement_tests_exist"], None),
 5: ("DRAFTED", ["docs/requirements/NFR.md"], [], "thresholds PROPOSED; availability unmeasurable offline"),
 6: ("IMPLEMENTED", [R + "errors.py"], [f"{T_UNIT}::ErrorModel"], None),
 7: ("IMPLEMENTED", [R + "lifecycle.py"], [f"{T_UNIT}::Lifecycle"], None),
 8: ("IMPLEMENTED", ["docs/requirements/VERSIONING.md", R + "negotiation.py"], [f"{T_UNIT}::WireAndNegotiation.test_negotiation"], None),
 9: ("PARTIAL", [R + "resilience.py::TokenBucketQuota"], [f"{T_SVC}::Adversarial.test_T12_quota_and_overload"], "provider-side quota enforcement needs Vault rate-limit quotas (W-001)"),
 10: ("IMPLEMENTED", [R + "cache.py"], [f"{T_UNIT}::Cache", f"{T_SVC}::Resilience.test_degraded_stale_serving_when_configured"], None),
 11: ("DRAFTED", ["docs/requirements/REQUIREMENTS.md#constraint-precedence-checklist-11"], [], "needs approval"),
 12: ("IMPLEMENTED", ["TRACEABILITY.json", "tools/build_status.py"], [f"{T_TOOLS}::Traceability"], None),
 13: ("BLOCKED", [], [], "series MASTER.md not in upload (W-010); this pass's master prompt lives in the work order"),
 14: ("IMPLEMENTED", [R + "provider.py"], [f"{T_SVC}::HappyPath"], None),
 15: ("PARTIAL", [R + "vault.py"], [f"{T_SVC}::VaultIntegration"], "exercised only against the KV v2 wire double, not real Vault (W-001)"),
 16: ("PARTIAL", ["docs/governance/COMPATIBILITY.md"], [], "no Vault server version certified (W-001)"),
 17: ("IMPLEMENTED", ["schemas/", R + "wire.py", "fixtures/wire/"], [f"{T_UNIT}::WireAndNegotiation"], None),
 18: ("PARTIAL", [R + "identity.py"], [f"{T_UNIT}::Identity", f"{T_SVC}::Adversarial.test_T05_forged_and_expired_tokens"], "external IdP/SPIFFE issuer not bound (W-003)"),
 19: ("PARTIAL", [R + "authz.py"], [f"{T_UNIT}::Authz", f"{T_SVC}::Fuzz.test_property_scope_decision_matches_model"], "INV-59 policy engine not integrated (W-003)"),
 20: ("IMPLEMENTED", [R + "resilience.py", R + "service.py::_rotate"], [f"{T_UNIT}::Resilience", f"{T_SVC}::HappyPath.test_rotate_idempotency"], None),
 21: ("IMPLEMENTED", [R + "errors.py", "schemas/error.schema.json"], [f"{T_UNIT}::ErrorModel"], None),
 22: ("IMPLEMENTED", [R + "negotiation.py"], [f"{T_UNIT}::WireAndNegotiation.test_negotiation", f"{T_SVC}::Adversarial.test_T06_schema_smuggling_and_oversize"], None),
 23: ("IMPLEMENTED", [R + "service.py", R + "config.py"], [f"{T_SVC}::Adversarial.test_T12_quota_and_overload", f"{T_UNIT}::Resilience.test_bulkhead_refuses_when_full"], None),
 24: ("IMPLEMENTED", ["fixtures/wire/"], [f"{T_UNIT}::WireAndNegotiation.test_fixtures_conform"], None),
 25: ("PARTIAL", ["tests/fake_vault.py"], [f"{T_SVC}::VaultIntegration.test_service_over_vault_end_to_end"], "runtime/authz/identity/audit estate layers absent"),
 26: ("IMPLEMENTED", [R + "config.py"], [f"{T_UNIT}::Config"], None),
 27: ("IMPLEMENTED", [R + "config.py::deep_merge", "deploy/config/"], [f"{T_UNIT}::Config.test_overlay_locked_keys", f"{T_X}::Bootstrap.test_site_overlay_and_locked_overlay"], None),
 28: ("IMPLEMENTED", [R + "config.py::ConfigController.provenance"], [f"{T_UNIT}::Config.test_transactional_activation_and_rollback"], None),
 29: ("IMPLEMENTED", [R + "config.py::ConfigController"], [f"{T_UNIT}::Config.test_transactional_activation_and_rollback"], None),
 30: ("IMPLEMENTED", [R + "config.py::ConfigController.rollback"], [f"{T_UNIT}::Config.test_transactional_activation_and_rollback"], None),
 31: ("IMPLEMENTED", ["tools/secret_scan.py"], [f"{T_TOOLS}::Scanner"], None),
 32: ("PARTIAL", ["tools/bootstrap.py"], [f"{T_X}::Bootstrap"], "trust-root provisioning on a real platform not exercised"),
 33: ("IMPLEMENTED", ["pyproject.toml"], [f"{T_TOOLS}::Packaging"], None),
 34: ("IMPLEMENTED", ["tools/sbom.py"], [f"{T_TOOLS}::Packaging.test_sbom_lists_no_third_party"], None),
 35: ("BLOCKED", [], ["tests/test_component.py"], "pk_core not in upload; conformance tests skip (W-010)"),
 36: ("PARTIAL", ["THIRD-PARTY-NOTICES.md"], [], "project licence not chosen (W-011)"),
 37: ("PARTIAL", ["tools/ci.sh", ".github/workflows/ci.yml"], [f"{T_TOOLS}::Gate"], "hosted CI never executed; local ci.sh executed"),
 38: ("IMPLEMENTED", ["docs/security/THREAT_MODEL.md"], [f"{T_SVC}::Adversarial"], None),
 39: ("PARTIAL", [R + "identity.py::ROLES", "deploy/vault/policies/"], [f"{T_SVC}::Adversarial.test_T08_consumer_cannot_rotate_or_rescope"], "Vault policies not applied to any Vault"),
 40: ("PARTIAL", ["docs/security/IDENTITY_AND_POLICY.md"], [], "OS confinement is a platform control (W-005)"),
 41: ("PARTIAL", [R + "vault.py", R + "identity.py"], [f"{T_X}::TLS.test_mtls_client_certificate_required"], "control-plane/peer identity issuer absent (W-003)"),
 42: ("PARTIAL", ["tools/gate.py (SHA256SUMS)"], [f"{T_TOOLS}::Gate"], "no signing identity (W-009)"),
 43: ("IMPLEMENTED", [R + "authz.py", R + "resilience.py::TokenBucketQuota"], [f"{T_SVC}::Adversarial.test_T02_cross_tenant", f"{T_SVC}::Adversarial.test_T12_quota_and_overload"], None),
 44: ("IMPLEMENTED", [R + "vault.py"], [f"{T_X}::TLS", f"{T_SVC}::VaultIntegration.test_transport_policy_fail_closed"], None),
 45: ("BLOCKED", ["docs/security/AT_REST.md"], [], "provider at-rest/KMS not provisioned (W-002)"),
 46: ("IMPLEMENTED", ["docs/security/FAIL_CLOSED_MATRIX.md"], [f"{T_SVC}::Resilience", f"{T_X}::AuditSink"], None),
 47: ("PARTIAL", [R + "audit.py"], [f"{T_UNIT}::Audit"], "no external durable store / head anchoring service"),
 48: ("IMPLEMENTED", [T_SVC], [f"{T_SVC}::Adversarial", f"{T_SVC}::Fuzz"], None),
 49: ("PARTIAL", ["docs/security/MEMORY_AND_PRIVACY.md", "reference.py::_SecretValue"], [f"{T_SVC}::Adversarial.test_T11_no_plaintext_in_any_channel_after_mixed_traffic"], "no zeroization in CPython (W-005)"),
 50: ("IMPLEMENTED", ["docs/security/MEMORY_AND_PRIVACY.md", R + "telemetry.py"], [f"{T_SVC}::Adversarial.test_T01_no_existence_oracle", f"{T_TOOLS}::Privacy"], None),
 51: ("DRAFTED", ["docs/operations/FMEA.md"], [], "needs review"),
 52: ("IMPLEMENTED", [R + "health.py"], [f"{T_SVC}::Resilience.test_breaker_opens_and_health_reports_not_ready", f"{T_TOOLS}::Privacy.test_stall_detector"], None),
 53: ("IMPLEMENTED", [R + "resilience.py::retry"], [f"{T_UNIT}::Resilience"], None),
 54: ("IMPLEMENTED", [R + "resilience.py"], [f"{T_UNIT}::Resilience.test_breaker_open_half_open_close", f"{T_UNIT}::Resilience.test_bulkhead_refuses_when_full"], None),
 55: ("IMPLEMENTED", [R + "failover.py"], [f"{T_X}::Failover"], None),
 56: ("IMPLEMENTED", [R + "cache.py", R + "service.py::_resolve"], [f"{T_SVC}::Resilience.test_degraded_stale_serving_when_configured"], None),
 57: ("IMPLEMENTED", [R + "service.py::state_snapshot"], [f"{T_SVC}::Resilience.test_restart_invalidates_leases_keeps_scopes_and_retirements"], None),
 58: ("PARTIAL", [R + "failover.py", R + "service.py::_rotate"], [f"{T_X}::Failover.test_failover_reads_only"], "idempotency table is per instance; distributed dedupe needs a shared store"),
 59: ("IMPLEMENTED", [R + "quarantine.py"], [f"{T_UNIT}::QuarantineTest", f"{T_SVC}::Adversarial.test_T09_freeze_blocks_resolve_and_use"], None),
 60: ("IMPLEMENTED", [R + "provider.py::InMemoryProvider", "tests/fake_vault.py"], [f"{T_SVC}::Resilience.test_transient_fault_retried", f"{T_SVC}::VaultIntegration.test_timeout_maps_to_deadline"], None),
 61: ("IMPLEMENTED", ["tools/bench.py"], [f"{T_TOOLS}::Bench"], None),
 62: ("DRAFTED", ["docs/operations/SLO_POLICY.md", "tools/bench.py::THRESHOLDS"], [], "thresholds PROPOSED, not approved"),
 63: ("PARTIAL", [T_SVC], [f"{T_SVC}::Concurrency", f"{T_SVC}::Adversarial.test_T12_quota_and_overload"], "soak/scale not run (W-006)"),
 64: ("PARTIAL", ["tools/bench.py"], [f"{T_TOOLS}::Bench"], "per-tenant overhead measured only as state size (W-006)"),
 65: ("BLOCKED", [], [], "profiler/context-switch/network-hop analysis needs the certified environment (W-006)"),
 66: ("IMPLEMENTED", [R + "cache.py"], [f"{T_UNIT}::Cache"], None),
 67: ("IMPLEMENTED", [R + "service.py", R + "resilience.py", R + "telemetry.py"], [f"{T_UNIT}::Cache.test_bounded_lru", f"{T_UNIT}::Telemetry.test_prometheus_export_and_cardinality_cap"], None),
 68: ("BLOCKED", [], [], "no power/thermal instrumentation (W-006)"),
 69: ("PARTIAL", ["docs/operations/CAPACITY.md", "tools/bench.py"], [f"{T_TOOLS}::Bench"], "fleet numbers unmeasured (W-006)"),
 70: ("IMPLEMENTED", ["tools/bench.py::regression"], [f"{T_TOOLS}::Bench.test_regression_gate"], None),
 71: ("IMPLEMENTED", [R + "health.py::status"], [f"{T_SVC}::Resilience.test_health_ready_when_all_good"], None),
 72: ("IMPLEMENTED", [R + "telemetry.py::Metrics"], [f"{T_UNIT}::Telemetry"], None),
 73: ("PARTIAL", [R + "telemetry.py::JsonLogger"], [f"{T_UNIT}::Telemetry.test_logger_scrubs_and_refuses_secret"], "no shipping pipeline (W-008)"),
 74: ("PARTIAL", [R + "telemetry.py::Tracer"], [f"{T_UNIT}::Telemetry.test_trace_spans"], "no exporter/collector (W-008)"),
 75: ("PARTIAL", [R + "telemetry.py"], [f"{T_TOOLS}::Privacy"], "no separate access-controlled diagnostic channel"),
 76: ("IMPLEMENTED", [R + "audit.py", R + "service.py::_audit"], [f"{T_SVC}::HappyPath.test_explain_view"], None),
 77: ("IMPLEMENTED", [R + "service.py::explain"], [f"{T_SVC}::HappyPath.test_explain_view"], None),
 78: ("BLOCKED", [], [], "release-lineage/infrastructure graph is an estate service (W-008)"),
 79: ("DRAFTED", ["docs/operations/TELEMETRY_POLICY.md"], [], "needs approval"),
 80: ("PARTIAL", ["deploy/monitoring/"], [f"{T_TOOLS}::Monitoring"], "not deployed"),
 81: ("IMPLEMENTED", [T_UNIT, T_SVC], [f"{T_UNIT}", f"{T_SVC}::HappyPath"], None),
 82: ("PARTIAL", [T_SVC], [f"{T_SVC}::VaultIntegration"], "real adjacent layers absent (W-001, W-010)"),
 83: ("BLOCKED", ["docs/governance/COMPATIBILITY.md"], [], "only one interpreter and no real Vault versions available"),
 84: ("IMPLEMENTED", [T_SVC], [f"{T_SVC}::Fuzz"], None),
 85: ("IMPLEMENTED", [T_SVC], [f"{T_SVC}::Concurrency"], None),
 86: ("PARTIAL", ["docs/security/THREAT_MODEL.md", T_SVC], [f"{T_SVC}::Adversarial"], "certification needs an independent security reviewer"),
 87: ("BLOCKED", [], [], "soak/fleet-scale certification needs the certified environment (W-006)"),
 88: ("PARTIAL", [T_SVC, T_X], [f"{T_SVC}::Resilience", f"{T_X}::Failover"], "multi-node partition tests need a cluster"),
 89: ("IMPLEMENTED", ["tools/gate.py"], [f"{T_TOOLS}::Gate"], None),
 90: ("DRAFTED", ["docs/operations/SLO_POLICY.md"], [], "needs approval"),
 91: ("BLOCKED", ["docs/operations/ROLLOUT.md"], [], "no deployment platform (W-007)"),
 92: ("DRAFTED", ["docs/governance/COMPATIBILITY.md"], [], "support windows need approval"),
 93: ("DRAFTED", ["SECURITY.md"], [], "security contact unassigned"),
 94: ("PARTIAL", ["docs/operations/BACKUP_RESTORE.md", R + "service.py::state_snapshot"], [f"{T_SVC}::Resilience.test_restart_invalidates_leases_keeps_scopes_and_retirements"], "restore drill not executed"),
 95: ("DRAFTED", ["docs/operations/RUNBOOKS.md"], [], "not exercised in staging"),
 96: ("DRAFTED", ["docs/operations/INCIDENT_RESPONSE.md"], [], "roles unassigned; no drill"),
 97: ("DRAFTED", ["docs/operations/REVIEWS.md"], [], "no review held"),
 98: ("IMPLEMENTED", ["docs/governance/WAIVERS.json", "tools/gate.py::check_waivers"], [f"{T_TOOLS}::Gate.test_expired_or_unapproved_waiver_never_covers"], None),
 99: ("IMPLEMENTED", ["tools/gate.py"], [f"{T_TOOLS}::Gate"], None),
 100: ("DRAFTED", ["SECURITY.md", "CONTRIBUTING.md", "CODEOWNERS"], [], "branch protection and release authority are repository-host settings"),
}
