"""Generate MASTER.md (component 51) and docs/REQUIREMENTS.md (xx.A04) from the
two authoritative inputs shipped in the archive: ``CHECKLIST.json`` (the 100
v4 architecture requirements) and the 54-component professional checklist.

The v4.2.0 README referenced a MASTER.md that was never in the archive.  This
file is a *regeneration* from sources that are present -- it is labelled as
such, and it does not claim to reproduce the lost original.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMP = os.path.dirname(HERE)
PKG = os.path.dirname(COMP)
CHECKLIST_MD = os.path.join(COMP, "checklist", "INV07_GitOps_Transition_Layer_54_Component_Professional_Checklist_v1.0.0.md")
VERSION = "5.0.0"


def parse(path: str = CHECKLIST_MD) -> dict:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    comps = {}
    heads = list(re.finditer(r"^## (\d\d)\. (.+)$", text, re.M))
    for i, m in enumerate(heads):
        body = text[m.end(): heads[i + 1].start() if i + 1 < len(heads) else len(text)]
        pr = re.search(r"\*\*Priority:\*\*\s*(\w+)", body)
        obj = re.search(r"\*\*Component-specific closure objective:\*\*\s*(.+)", body)
        checks = [{"id": f"{c.group(1)}", "label": c.group(2).strip(), "text": c.group(3).strip()}
                  for c in re.finditer(r"^- \[ \] \*\*(\d\d\.[A-Z]+\d\d) — ([^.*]+)\.\*\* (.+)$", body, re.M)]
        checks += [{"id": c.group(1), "label": "Definition of Done", "text": c.group(2).strip()}
                   for c in re.finditer(r"^- \[ \] \*\*(\d\d\.DOD\d\d)\.\*\* (.+)$", body, re.M)]
        comps[m.group(1)] = {"title": m.group(2).strip(), "priority": pr.group(1) if pr else "?",
                             "objective": obj.group(1).strip() if obj else "", "checks": checks}
    return {"sha256": hashlib.sha256(text.encode()).hexdigest(), "components": comps,
            "global_rules": re.findall(r"^- \[ \] (.+)$", text.split("## Master index")[0], re.M)}


def requirements_md(p: dict) -> str:
    out = ["# INV-07 v5.0.0 — SHALL-level requirements", "",
           f"_Generated by `tools/master.py` from the 54-component checklist (sha256 `{p['sha256'][:16]}…`)._", "",
           "Each component contributes one closure requirement (`R01`) and the stable check IDs it must satisfy. "
           "Implementation/test/evidence traceability per check is in `evidence/CHECKLIST_STATUS.json`.", ""]
    for cid, c in p["components"].items():
        obj = c["objective"].rstrip(".")
        out += [f"## INV07-C{cid} — {c['title']} ({c['priority']})", "",
                f"* **INV07-C{cid}-R01** The GitOps transition layer SHALL {obj[0].lower() + obj[1:]}.",
                f"* **INV07-C{cid}-R02** It SHALL fail closed when identity, authorization, trust, provenance, policy "
                "or integrity cannot be established for this component's decisions.",
                f"* **INV07-C{cid}-R03** Its interfaces, configuration and durable formats SHALL be versioned and "
                "validated before use.",
                f"* Checks: {', '.join(x['id'] for x in c['checks'])}", ""]
    return "\n".join(out)


def master_md(p: dict) -> str:
    with open(os.path.join(PKG, "CHECKLIST.json"), encoding="utf-8") as fh:
        v4 = json.load(fh)
    out = [f"# INV-07 GitOps transition layer — MASTER (v{VERSION})", "",
           "> **Provenance of this document.** The v4.2.0 archive referenced a `MASTER.md` that was not shipped. "
           "This file is **regenerated** by `components/tools/master.py` from `CHECKLIST.json` (100 architecture "
           "requirements) and the 54-component professional checklist, both present in the archive. It does not "
           "claim to reproduce the missing original; if the original surfaces it supersedes this file.", "",
           "## Identity", "",
           f"* Element: `INV-07` · Name: GitOps transition layer · Version: `{VERSION}` (VERSION, pyproject, "
           "`__version__` and `controller.VERSION` are checked for consistency by `tools/gates.py docs`).",
           "* Contract: `contract.py` (requires the external `pk_core`); production overlay: `components/`.", "",
           "## External dependencies (disclosure)", "",
           "| Dependency | Needed for | Present in archive |", "|---|---|---|",
           "| `pk_core` | 100-item architecture conformance gate | **no** |",
           "| git ≥ 2.31 | transport | host-provided |",
           "| Git server, Kubernetes, Argo CD/Flux, KMS, OPA, GAP-07 verifier | production acceptance | **no** (BLOCKED items) |",
           "| INV-05 / INV-06 / INV-63 sibling components | adjacent integration | **no** |", "",
           "## Global completion rules (from the 54-component checklist)", ""]
    out += [f"{i + 1}. {r}" for i, r in enumerate(p["global_rules"])]
    out += ["", "## Architecture requirements (CHECKLIST.json, stable IDs)", "",
            "| ID | Dimension | Requirement |", "|---|---|---|"]
    for it in v4["items"]:
        out.append(f"| `{it['check_id']}` | {it['dimension']} | {it['requirement']} |")
    out += ["", "## Production components (54-component checklist)", "",
            "| # | Component | Priority | Checks | Closure objective |", "|---|---|---|---|---|"]
    for cid, c in p["components"].items():
        out.append(f"| {cid} | {c['title']} | {c['priority']} | {len(c['checks'])} | {c['objective']} |")
    out += ["", "## Traceability and evidence", "",
            "* Requirement → design: `components/docs/REQUIREMENTS.md`, `components/docs/ADR-001-v5-production-overlay.md`.",
            "* Design → implementation → test → evidence: `components/checklist/bindings.py` and the engine output "
            "`components/evidence/CHECKLIST_STATUS.json` (2,160 records), hash-chained in `GATE_LEDGER.jsonl`.",
            "* Packaging verification: `MANIFEST.sha256` over every shipped file; `tests/test_overlay_integrity.py`.",
            "* A skipped or NOT_RUN required check is never a pass; PASS additionally requires a named owner and an "
            "independent human reviewer (none assigned — `components/docs/OWNERS.md`).", ""]
    return "\n".join(out)


def main() -> None:
    p = parse()
    with open(os.path.join(COMP, "docs", "REQUIREMENTS.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(requirements_md(p))
    with open(os.path.join(PKG, "MASTER.md"), "w", encoding="utf-8", newline="\n") as fh:
        fh.write(master_md(p))
    return len(p["components"]), sum(len(c["checks"]) for c in p["components"].values())


if __name__ == "__main__":
    print(*main())
