"""WP #47/#100 - render TRACEABILITY.md from TRACEABILITY.json and check consistency."""
from __future__ import annotations

import collections
import json
import pathlib
import sys

PKG = pathlib.Path(__file__).resolve().parents[1]


def load() -> dict:
    return json.loads((PKG / "TRACEABILITY.json").read_text())


def check(doc: dict) -> list[str]:
    problems = []
    checklist = json.loads((PKG / "CHECKLIST.json").read_text())["items"]
    if [r["check_id"] for r in doc["items"]] != [i["check_id"] for i in checklist]:
        problems.append("TRACEABILITY.json does not cover CHECKLIST.json 1:1 in order")
    waivers = {w["id"] for w in json.loads((PKG / "WAIVERS.json").read_text())["entries"]}
    for r in doc["items"]:
        if r["status"] not in ("Implemented", "Partial", "Missing"):
            problems.append(f"{r['check_id']}: bad status")
        if r["status"] != "Implemented" and not r["waivers"]:
            problems.append(f"{r['check_id']}: {r['status']} without waiver")
        for w in r["waivers"]:
            if w not in waivers:
                problems.append(f"{r['check_id']}: unknown waiver {w}")
    return problems


def render(doc: dict) -> str:
    c = collections.Counter(r["status"] for r in doc["items"])
    out = ["# PLN-06 post-implementation traceability matrix\n",
           f"**Audited version:** {doc['version']}  ",
           f"**Audit date:** {doc['audited']}  ",
           "**Source of truth:** `TRACEABILITY.json` (this file is generated by `tools/traceability.py`).  ",
           "**Rule:** *Implemented* only when executable/in-repo evidence exists here; anything depending on people, approvals, "
           "external services or hardware stays *Partial* with a waiver in `WAIVERS.json`.\n",
           f"**Result:** {c['Implemented']} implemented, {c['Partial']} partial, {c['Missing']} missing out of {len(doc['items'])}.\n",
           "| ID | Status | Requirement | Evidence / remaining gap | Waivers | WP |", "|---|---|---|---|---|---|"]
    for r in doc["items"]:
        out.append(f"| {r['check_id']} | **{r['status']}** | {r['requirement']} | {r['evidence']} | "
                   f"{', '.join(r['waivers']) or '—'} | {', '.join(f'#{w}' for w in r['work_packages']) or '—'} |")
    return "\n".join(out) + "\n"


def main() -> int:
    doc = load()
    probs = check(doc)
    for p in probs:
        print("TRACEABILITY:", p)
    (PKG / "TRACEABILITY.md").write_text(render(doc))
    return 1 if probs else 0


if __name__ == "__main__":
    sys.exit(main())
