"""Deterministic binding generator: idl/pk_async.wit -> _generated_bindings.py.

Parses the enum subset of the WIT file (explicit ``// = N`` discriminants) and
emits a Python module. Output is a pure function of the input bytes, so
``--check`` proves the committed bindings are reproducible and unedited.
"""
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
WIT = ROOT / "idl" / "pk_async.wit"
OUT = ROOT / "_generated_bindings.py"


def generate(text: str) -> str:
    enums = {}
    for m in re.finditer(r"enum ([a-z-]+) \{(.*?)\}", text, re.S):
        cases = re.findall(r"^\s*([a-z-]+),\s*// = (\d+)\s*$", m.group(2), re.M)
        if not cases:
            raise SystemExit(f"enum {m.group(1)} has no annotated cases")
        vals = [int(v) for _, v in cases]
        if len(set(vals)) != len(vals):
            raise SystemExit(f"duplicate discriminant in {m.group(1)}")
        enums[m.group(1)] = cases
    digest = hashlib.sha256(text.encode()).hexdigest()
    lines = ['"""GENERATED by tools/bindgen.py from idl/pk_async.wit. DO NOT EDIT."""',
             f'WIT_SHA256 = "{digest}"', ""]
    for name, cases in enums.items():
        const = name.replace("-", "_").upper()
        lines.append(f"{const} = {{")
        for c, v in cases:
            lines.append(f'    "{c.replace("-", "_").upper()}": {v},')
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main():
    src = generate(WIT.read_text())
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == src
        print("BINDINGS_REPRODUCIBLE" if ok else "BINDINGS_DRIFT")
        return 0 if ok else 1
    OUT.write_text(src)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
